### ISSUE TITLE
Revist the meeting times

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1004]
@Trott correctly pointed out in todays meeting that with 3 new people joining and the Daylight savings time change we should update the spreadsheet with time availability and see if we should change the meeting times.

@nodejs/tsc I'll send the link to the spreadsheet through email. Please update your availability and we'll look to see if we should update the times in the next few weeks.

**Comment by ChALkeR** [comment]
I'll go over the dataset today a few hours after the meeting.

**Comment by ronag** [comment]
Maybe a good idea if nominated members are also taken into consideration?

**Comment by mhdawson** [comment]
@ChALkeR I've emailed the nominated members the link, lets give them 1 week to fill in and then go over the dataset. I also asked that they let you know if possible once they have so in that case you could assess the data earlier.

**Comment by Trott** [comment]
For the nominated folks: Note that there are two worksheets (tabs) in the spreadsheet: One for Wednesday (UTC) and one for Thursday (UTC). For a lot of people, it's mostly copy/paste from one to the other. (But of course, not everyone.)

**Comment by ChALkeR** [comment]
There are three rows that are not filled in yet (two for both days, one for Wednesday).
I updated the raw results in the spreadsheet, but those exclude the abovementioned rows for now.
Let's wait for those to get filled in.

Also, perhaps in the meantime we should revisit whether we do want a 3-slot or 2-slot based system.

The advantage of a 3-slot one is that it should ensure that for any two members, there should be a timeslot where they at least _could_ meet. And for the 2-slot one, there would be members whose availability does not intersect at all (i.e. one person can't be present at timeslot 1 and the second person can't be present at timeslot 2).

On the other hand — 2-slot is easier to use. Also, we tend to cancel meetings often, and it might be that the intention for having a 3-timeslot system is defeated.

Thoughts?

**Comment by Trott** [comment]
I prefer 3 slots because it allows us to try to make it such that everyone is likely to attend ~2/3 of the meetings. With 2 slots, the differences get starker. There are people that can attend ~100% of the time and people who can only attend ~50% of the time.

**Comment by ChALkeR** [comment]
Currently, `15, 40, 45` (Wed 15:00, Thu 16:00, Thu 21:00) seems optimal.
But we are still missing data from three people at least.

**Comment by mmarchini** [comment]
I've been sort of away these past three weeks and definitely missed this issue. Will update mine today.

**Comment by mcollina** [comment]
I have updated as well, sorry :(

**Comment by mhdawson** [comment]
@ChALkeR can you get the updated suggestions and then we'll move the meeting times based on that.

**Comment by mhdawson** [comment]
@ChALkeR ping

**Comment by ChALkeR** [comment]
Let's move to `15, 41, 45`, the data hasn't been significantly updated in a while.

That's Wed 15:00, Thu 17:00, Thu 21:00 UTC.

**Comment by mcollina** [comment]
I just realized I had not considered daylight savings :(. My availability at Thu 17:00 is significantly low. Probably does not change things.

**Comment by mhdawson** [comment]
I think one moved by +2 hours, in any case schedule update, closing.

**Comment by ChALkeR** [comment]
With updated data optimal seems to be `15, 40, 45` or `14, 40, 45` (mostly equivalent).

That's  Wed 14 (or 15), Thu 16, Thu 21.
