### ISSUE TITLE
nit: update OpenSSL-Strategy.md

### ISSUE THREAD

**Issue by brodybits** [nodejs/TSC#1008]
`OpenSSL-Strategy.md` seems to have some old info no longer needed. For example, I just raised PR #1007 to fix a statement regarding OpenSSL and Node.js 10.x.

P.S. After raising this issue I discovered that Node.js started using a quictls fork of OpenSSL in <https://github.com/nodejs/node/pull/37601>. I would appreciate if this info would be in `OpenSSL-Strategy.md`.

Thanks to mhdawson for the response to this issue and PR #1007.

**Comment by mhdawson** [comment]
@danbev I know you've been keeping up to date on the OpenSSL 3.X front maybe you can take a look at doing a bigger update on: https://github.com/nodejs/TSC/blob/main/OpenSSL-Strategy.md

**Comment by danbev** [comment]
> I know you've been keeping up to date on the OpenSSL 3.X front maybe you can take a look at doing a bigger update on

Yeah I can take a look at updating it :+1:

**Comment by danbev** [comment]
Fixed by https://github.com/nodejs/TSC/pull/1010
