### ISSUE TITLE
2021 TSC Chair election

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1013]
May is the month for TSC Elections. The proposed schedule is:

April 9 - Call for nominations
April 30 - Close nominations
May 1 - Open balloting
May 15 - Announce Results
May 16-29- Handover
May 30 (or earlier if handover complete) Transition complete

This issue is to open the call for nominations.

Depending on the number of nominations we'll figure out if we need to have people write up something about why they would be a good fit for the position.

**Comment by mhdawson** [comment]
@nodejs/tsc FYI for people who want to nominate/self nominate.

**Comment by mhdawson** [comment]
I'd be happy to continue as the Chair, so I'll kick of nominations by self-nominating :)

**Comment by mmarchini** [comment]
Is the intention to have only one chair? Or should we aim for multiple chairs due to meeting times and timezones?

**Comment by mhdawson** [comment]
We've only had one chair in the past, but I'm open to what we think works best.  Either way it would be great to have additional people who can run meetings.

**Comment by gireeshpunathil** [comment]
> should we aim for multiple chairs

pros: smooth execution of meetings
cons: split / confusing roles and responsibilities between the chairs, probably?

I am in favor of one.

**Comment by Trott** [comment]
Let's not do it abruptly right now, but it might not be a bad idea for there to be a vice-chair that fills the role when the chair is unavailable. Maybe something to talk about after the election?

**Comment by Trott** [comment]
A narrow interpretation of the Charter would make an election a requirement. Yet even an adamant narrowly-interpret-the-charter person like me can't bring myself to argue that we should have a vote. I mean, I guess we could do a roll call vote at the next meeting or something like that? But it seems pretty pointless.

A moderately flexible interpretation of the Charter would be that if an election was mandatory in a situation where there is only one candidate and the outcome is a foregone conclusion, surely the Charter would say so specifically. And it doesn't.

Also: Congratulations, Michael!

**Comment by mhdawson** [comment]
Ok, see no objections, closing issue as complete.
