### ISSUE TITLE
Is email the best space for private discussions and communications?

### ISSUE THREAD

**Issue by mmarchini** [nodejs/TSC#1023]
Related to #1022, the recent vote on yarn made me wonder if email is the right place to have private communication. Maybe we should have a private TSC repo on `node-private` instead? Maybe we should have a private Slack channel in the OpenJSF Slack? Maybe we should have all of those options? I don't have strong preferences either way, but I think it's worth discussing.

**Comment by jasnell** [comment]
Please not another slack! I'd be ok with a private github repo but please please please no more slacks.

**Comment by MylesBorins** [comment]
OpenJS using lists.io for managing mailing lists that also gives a bunch of great options for reviewing historical conversation. Might be worth migrating the list as an option as well.

**Comment by targos** [comment]
I'm +1 to moving off emails, but also -1 on using a new platform... Discussions or issues in a special private repo sounds good but note that all org owners would have access to them.

**Comment by mhdawson** [comment]
Given that we try to limit private discussion I'm not sure how much of an issue it is. We've had only this 1 problem in 5 years from what I remember.

I also think email give us the most confidence that people will see the limited messages we have to share that way, others have a good chance of being drowned with all the other notifications. I know that would be the case at least for me.

**Comment by mhdawson** [comment]
We now have some private slack channels as well as continuing to use email. I think given that the last discussion on this issue was 2 years ago we can close. Please let me know if you think that was not the right thing to do.
