### ISSUE TITLE
Resigning from CPC Voting Member

### ISSUE THREAD

**Issue by mmarchini** [nodejs/TSC#1043]
Hi y'all!

Due to personal reasons and low bandwidth at work at the moment, I'm reducing my time spent on OSS for a few months. I haven't been able to keep up with the responsibilities of CPC Voting Member in the past months, so I'm resigning from the position and am looking for volunteers to take on the work. cc @nodejs/tsc

**Comment by ronag** [comment]
https://github.com/openjs-foundation/cross-project-council

**Comment by ronag** [comment]
One meeting every other week.

**Comment by mhdawson** [comment]
* Rich is only volunteer. Will work with Mary to get up to speed.
