### ISSUE TITLE
Node.js mentorship initiative

### ISSUE THREAD

**Issue by demola07** [nodejs/TSC#1057]
The Node.js mentorship initiative will like to be present at the next node tsc meeting via a representative. We would like to reach out to brief the committee about the work we do and how we can be of more use to the community.
Consequently, We would like to be added to the agenda items for the next meeting.

cc @nodejs/tsc

**Comment by Trott** [comment]
Which GitHub usernames should we add to the meeting?

**Comment by mhdawson** [comment]
The next TSC meeting is Thursday July 22nd at 1 ET.  If the github ids you provide don't include emails that I can send the meeting password to, please have the people email so I can respond with the password need to join the meeting.

**Comment by mhdawson** [comment]
@demola07 can you forward who will be attending so that I can send on the info needed to join the meeting on the 22nd?

**Comment by demola07** [comment]
@mhdawson, David Guttman will be attending the meeting on behalf of the Mentorship initiative, you can send the meeting details here david@js.la

**Comment by mhdawson** [comment]
Email sent to David with meeting details/password.

**Comment by LonelyTree** [comment]
@mhdawson, here with an update: I will be joining this TSC meeting instead of David. I have the meeting details and look forward to meeting with you all soon!

**Comment by mhdawson** [comment]
Closing as done.
