### ISSUE TITLE
Is it make sense for Node.js team to enable codespaces

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/TSC#1071]
Context: https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/enabling-codespaces-for-your-organization#configuring-which-users-in-your-organization-can-use-codespaces

**Comment by mcollina** [comment]
I think this would be a good idea if Github gently donated the cloud resources.

I'm also not sure codespaces can actually build node..
@bnb definitely knows more.

**Comment by targos** [comment]
Codespaces aren't available to the Node.js organization yet, but we can definitely have the conversation before.

@mcollina You can do anything in them, they are ubuntu vms with root access.

**Comment by mcollina** [comment]
I mean I'm unsure how long it would take to build Node.js in there without some kind of compilation cache.

**Comment by devsnek** [comment]
it took 46 minutes the last time i tested it.

**Comment by devsnek** [comment]
That being said i would be 110% for a project sponsored compilation cache. Perhaps we could use electron's.

**Comment by jasnell** [comment]
@mcollina:
> I'm also not sure codespaces can actually build node..

They can. I've done it many times before.

**Comment by bnb** [comment]
hi sorry going through my notifications now and just catching this.

I've built Node.js on every single machine size (I assume this likely surprises nobody). Codespaces can indeed build Node.js, but machine size really matters - you basically want to go as high as you can.

I did a side-by-side comparison back when it was still VS Codespaces (the infra is largely the same from what I understand) on Basic vs. Premium. Basic crashed before the compile completed, after about 2 hours. Premium (8 cores) took about 20-25 minutes. The Normal (4 core) machines that Codespaces defaulted to until they added the ability to switch between sizes took about 40-45 minutes IIRC, which matches the time that @mcollina pointed out.

Pre-building a Docker image would likely help quite a bit, which aligns with https://github.com/nodejs/node/issues/39672 pretty nicely. Dropping in a [`devcontainer.json` file](https://code.visualstudio.com/docs/remote/devcontainerjson-reference) with some additional configuration on top of that would likely make this a pretty good experience.

**Comment by bnb** [comment]
> That being said i would be 110% for a project sponsored compilation cache. Perhaps we could use electron's.

AFAIK this is pretty tied to Azure-based infrastructure. Happy to internally advocate for donating that infrastructure to the project if we do go down this path.

**Comment by mcollina** [comment]
That would be indeed a really good stack/progress.

**Comment by simoneb** [comment]
I posted the same in https://github.com/nodejs/node/issues/39672. https://github.blog/changelog/2022-06-15-prebuilding-codespaces-is-generally-available/ /cc @shogunpanda

**Comment by mhdawson** [comment]
There has been no discussion or work to move this forward for for over 2 years. I'm going to close this. If this was not the right thing to do please let me know or feel free to reopen.
