### ISSUE TITLE
In-person Collaborator Summit in Austin 2022

### ISSUE THREAD

**Issue by mcollina** [nodejs/TSC#1074]
I hope to see you all in Austin next year at OpenJS World (https://events.linuxfoundation.org/openjs-world/). I was wondering if we should slowly start planning for this to happen.
(hoping that travel bans would be lifted by then).

Ref on Openjs Foundation: https://github.com/openjs-foundation/summit/issues/307.

**Comment by jasnell** [comment]
Fingers crossed that we are actually able to meet in person by then. I'm definitely +1 on doing an in-person collab summit.

**Comment by fhinkel** [comment]
+ from me.

**Comment by mhdawson** [comment]
This occured so closing.
