### ISSUE TITLE
Override objection in - display Node.js version at the end of stacktraces [#38332](https://github.com/nodejs/node/pull/38332)

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1078]
We discussed in the TSC meeting this week that:

- No TSC members have objected to the change in [#38332](https://github.com/nodejs/node/pull/38332)
- There remains an object, poster was asked to expand on objection a few weeks ago
- Those in the meeting felt it was time to see if we have TSC consensus to override.

@nodejs/tsc please comment in this issue if you have any objections or +1 to indicate you are in agreement to override.  If we have sufficient +1s by the next TSC meeting and no objections we'll move forward with the override.

**Comment by mhdawson** [comment]
@nodejs/tsc we need 1 more yes or 4 more abstentions.  If we can close on this I'll propose we cancel the in person meeting for this week.

**Comment by Trott** [comment]
> @nodejs/tsc we need 1 more yes or 4 more abstentions. If we can close on this I'll propose we cancel the in person meeting for this week.

Small correction: It needs 2 more yes votes (or 4 abtentions, or 10 no votes).

(If two more people abstain, then it needs only 1 vote or 9 no votes.)

**Comment by Trott** [comment]
> @nodejs/tsc we need 1 more yes or 4 more abstentions. If we can close on this I'll propose we cancel the in person meeting for this week.

Small correction: It needs 2 more yes votes (or 4 abtentions, or 10 no votes).

(If two more people abstain, then it needs only 1 vote or 9 no votes.)

**Comment by danbev** [comment]
I'll abstain.

**Comment by apapirovski** [comment]
+1 to override but will leave some comments on the PR.

**Comment by joyeecheung** [comment]
Yes (and should it cause a widespread regression we can always turn if off by default)

**Comment by ChALkeR** [comment]
I'll abstain.

**Comment by fhinkel** [comment]
I'll abstain.

**Comment by mhdawson** [comment]
As per the update in https://github.com/nodejs/TSC/issues/1078#issuecomment-906769331, the vote has now passed.
