### ISSUE TITLE
Re-charter the Ecosystem Security WG

### ISSUE THREAD

**Issue by Relequestual** [nodejs/TSC#1081]
In relation to "Node.js Foundation technical group"

We should probably re-charter the group with that removed too.

_Originally posted by @Trott in https://github.com/nodejs/TSC/pull/1053#discussion_r665752805_

**Comment by mcollina** [comment]
I think we could think of de-chartering it given the ecosystem program was halted?

**Comment by mhdawson** [comment]
@mcollina @MylesBorins had suggested in this previously and after I mentioned we should talk to @lirantal and @esarafianou first as the most active members. I think @MylesBorins had said he was going to do that.

**Comment by Trott** [comment]
@nodejs/security-wg TSC is trying to figure out if we need to update your charter or simply de-charter you and let you folks continue to work as a GitHub team rather than a chartered working group. I'm not sure that there are relevant advantages to being a working group. Your feedback would be great. I've added the `security-wg-agenda` label to this, but feel free to remove, of course.

**Comment by RafaelGSS** [comment]
@Trott Could you elaborate what are the differences between those charters (if there is a document explaining it would be awesome)? Currently, the group is working pretty similar to any other working group. We have bi-weekly meetings, initiatives...

**Comment by mhdawson** [comment]
A chartered working group is formally delegated responsibility, while a team simply is a group of people working in an area without any formally delegated responsibility. Pratically there is little difference day to day.

**Comment by mhdawson** [comment]
We discussed today in the security-wg team meeting. The consensus was that for the current work we don't need a formally chartered team. Our understanding is that we can continue in the same way we have (with repo, team etc.) if the wg is de-charted. In that context we are ok with decharting the WG.

**Comment by mhdawson** [comment]
@Trott FYI
