### ISSUE TITLE
[Offer]

### ISSUE THREAD

**Issue by vidd-ai** [nodejs/TSC#1093]
As per an exchange with @mhdawson , posting here.  (nb Michael, context added here) 

Not an issue, rather an offer in case of interest.

> We're an AI startup, node.js users here.  We have some cloud credits left and would like to put them to good use before they expire in the next month or so.  If you or any of the node.js OSS committees have any interest, you can use our bot Neo to automatically generate recaps for your public meetings. 
>
> Context: he's been sent to team meetings by folks who can't make it - eg. timezone probs, scheduling conflicts, kids to take care of, etc; he's also been invited to be an embedded team member. NB. he can only attend by being  invited.
> 
> For what it's worth, he can also recap conference sessions, though I don't know if you have any planned soon.
> 
> Hope of help, more power to OSS.  We're fans.

**Comment by mhdawson** [comment]
I think this is long since passed since it mentions credits that were good for a month or so. Sorry we did not get an answer fast enough.
