### ISSUE TITLE
github commit queue feature

### ISSUE THREAD

**Issue by devsnek** [nodejs/TSC#1110]
can we get on the signup for this: https://github.com/features/merge-queue/signup

**Comment by Trott** [comment]
> > Don't tell anyone, but I've successfully used the squash and merge button once or twice by adding all the metadata with node-core-utils, then force-pushing to the PR branch. From there, the squash and merge button is usable for single-commit PRs. (It adds the GitHub PR number to the commit message title, but that can be manually removed and isn't a big deal if you don't remove it.) Doing that is more work than following the usual procedure, though. So, not a big win.
> 
> Kind of off topic, but I wonder if we could use GitHub CLI tool to do that from the commit-queue for one-commit PRs: https://cli.github.com/manual/gh_pr_merge

Step one would be to find a way to get the commit-queue to force-push to the PR branch. That will break for certain PRs. (The npm bot PRs, for example, don't allow us to force push to the branch.) But it can fall back to the current push-to-master-and-close-the-PR process that it does currently. For everyone else, the force-push will give us the nice purple merged PRs and improve some of our ability to gather metrics.

And once you have that working, then there's probably no reason not to do it if you have the commit-queue landing multi-commit PRs. And you can use the GitHub CLI tool to merge with the `--rebase` option.

**Comment by aduh95** [comment]
> Step one would be to find a way to get the commit-queue to force-push to the PR branch. That will break for certain PRs. (The npm bot PRs, for example, don't allow us to force push to the branch.) But it can fall back to the current push-to-master-and-close-the-PR process that it does currently. For everyone else, the force-push will give us the nice purple merged PRs and improve some of our ability to gather metrics.

If we were using the `--squash` option from GitHub CLI tool, we wouldn't need to force push I think. I'll look into that once https://github.com/nodejs/node/pull/40577 has landed (if it lands).

**Comment by ljharb** [comment]
You'd still want to force push tho any time you could, no?

**Comment by aduh95** [comment]
No, I'd prefer not to force push, it makes the GitHub Actions CI run twice.

**Comment by ljharb** [comment]
That's a benefit - it's supposed to run on the final commit that will land on master, _before_ it lands on master. This also gives you the opportunity to freshly rebase it before the force push - otherwise anything that lands on master between the last CI run and the merge could cause master to become broken.

**Comment by aduh95** [comment]
> Either way, CI on GHA on a public repo is free, what's wrong with running it 20 times, let alone twice?

It's free, but limited, it's not uncommon to have macOS jobs queue for hours when there are a lot of PRs (also, global warming, why run needless CIs?).

**Comment by ljharb** [comment]
If that was a concern for Github, they'd provide the ability to only rerun failed jobs instead of only rerunning every job :-) but fair enough.

**Comment by nschonni** [comment]
> No, I'd prefer not to force push, it makes the GitHub Actions CI run twice.

May be worth looking at https://github.com/marketplace/actions/skip-duplicate-actions if you want to trim overlapping runs

**Comment by targos** [comment]
FWIW I signed up the org for the feature. We can still decide not to use it.

**Comment by mex511511mno** [comment]
H

**Comment by Trott** [comment]
User blocked and comment hid.
