### ISSUE TITLE
The `nodejs-github-bot` account is a member of `@nodejs/collaborators`

### ISSUE THREAD

**Issue by targos** [nodejs/TSC#1113]
https://github.com/orgs/nodejs/teams/collaborators/members?query=nodejs-github-bot

I think it shouldn't be, but I don't know if something relies on that.
The commit queue in `nodejs/node` did, but I fixed that by adding the account explicitly to the list of who can push to `master`:

![image](https://user-images.githubusercontent.com/2352663/140617839-6276ffc1-3c5e-4810-9f0b-d7bca60183a1.png)

**Comment by richardlau** [comment]
> 
> I think it shouldn't be, but I don't know if something relies on that.

One possibly reason might have been when the bot was used to start Jenkins CI runs but we're doing that via GitHub Actions now.

**Comment by mmarchini** [comment]
@richardlau but we still use a Jenkins token generated for the nodejs-github-bot user (I think that's how it has always been). And yes, I remember Jenkins being one of the main reasons.

**Comment by targos** [comment]
Is it because it's difficult to maintain access to an additional team (the bot is a member of `@nodejs/bots` too)

**Comment by richardlau** [comment]
Well the security release process involves restricting who can access the CI and unfortunately that's a manual process (https://github.com/nodejs/build/blob/master/doc/jenkins-guide.md#security-releases) -- in particular the groups with permissions taken away have to be individually added back (they disappear completely from the matrix if they have no permissions at all) afterwards. 

We restrict access to the CI for two reasons
1. to restrict potential leakage of the fixes before disclosure.
2. to free up the CI so it's only being used to prepare the security releases.

For the latter point the bot being in collaborators has the nice side effect of preventing CI's being started via labels. In theory we could add nodejs*bots to the security matrix but that's then an extra row that would need to be removed when the CI is locked down and manually reentered when unlocked.

(This is not a hard rejection of moving the bot out of collaborators but I'm not enthusiastic of adding to the above process.)

**Comment by mhdawson** [comment]
> I think it shouldn't be, but I don't know if something relies on that.

Richard I assume that from what you say, the bot being in collaborators is what currently allows it to support starting CI via labels.

**Comment by targos** [comment]
Okay, I'm closing the issue, then.
