### ISSUE TITLE
An alternative strategy to moderation

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#114]
So I've been thinking quite a bit about moderation, and specifically some of the pain points that we have been dealing with. The biggest problems that I currently see are. You will find bold TLDR's throughout this brain dump of the key points.
1. It is impossible to codify code-of-conduct violations without marginalizing a group
   - a good example is the current state of cursing and sexualized language.
   - The discussion around coming up with what is appropriate here results in massive derailment and divide in our internal community
2.  Banning is a big deal, thus we debate quite a bit about banning individuals.
   - While we are busy discussing things people are being harassed
   - When we decide not to act we set a precedent that certain behavior is ok, and this can and has escalated in the past.

TLDR; **we should not be codifying specific acts but rather rely on individual contributors reaction on a case by case basis and we should be more liberal with our banning. The most important thing is to make a safe space for individuals to contribute. The second most important thing is to avoid derailment.**

The project is made up of individuals from all walks of life. We all come with different value systems, philosophies, and agendas. Trying to codify rules or guidelines will only serve to make those differences clearer, it will only divide us. An alternative is to make use of our differences. Does it matter what we have codified if a contributor is offended, marginalized, or feels silenced? With this in mind I would like to propose:

A specific code of conduct violation should be at the discretion of the individual making the moderation request. We are a group of trusted collaborators. If someone from the group feels specific behavior is inappropriate, it is safe to assume that other individuals in the community will feel the same way. If the goal is to create a safe space, then it shouldn't matter if we have check boxes for all the potential violations. Individuals are great at setting a line that shouldn't be crossed for them, and we should empower them to act on it. Spending our time defining that line is counter productive. We inherently trust our collaborators and members to be good actors, and such we should trust them to make the right decision in a situation where they feel the line has been crossed.  If a individual is abusing this privilege it would obviously cross the line of others and be dealt with. It is really easy to argue about a specific hard and fast rule, it is much harder to argue with an individuals experience.

TLDR; **A specific code of conduct violation should be at the discretion of the individual making the moderation request. Individuals are great at setting a line that shouldn't be crossed for them, and we should empower them to act on it**

This now brings up the act of banning. Currently banning has been reserved for repeat offenders or obvious bad actors. Generally if someone is banned it is a very big deal, and they are not very likely to have that ban removed (I can only think of one instance where a ban was lifted). I would like to propose an alternative banning approach closer to the way it is handled on IRC. In many IRC channels if you step over the line or derail the room you are quickly banned (at the discretion of the OP). Generally this is not a permaban... sometimes they are short bans to give someone a chance to calm down, other times there is a repeal process that is documented. Generally pm'ing one of the ops, stating that you understand what you did and won't do it again results in the ban being lifted. This is a fantastic way to set a precedent and stop derailment. A great example where this could have been useful was https://github.com/nodejs/node/pull/5790. Now I think that the way it was handled was fine, but a quick ban followed with an email explaining how to get unbanned would have sent a very clear message regarding derailment. The biggest win for this would be taking banning of of a pedestal. We are all going to make mistakes, taking away the power of a "ban" is a great way to make it way safer to make mistakes without permanent consequences.

TLDR; **We should be very quick to ban individuals for CoC violations or derailment. It should also be very quick to get unbanned by following a clear process. Only repeat offenders will be truly perma banned.**

At this point I want to make it clear that these ideas are still being thought through, and likely have some flaws. The goals I have here are to improve our moderation, make node a safe space, and to decrease derailment (especially internally). The biggest win for me would be if we could find a way to have a moderation policy that does not marginalize our collaborators and members. We spend too much time in fighting about semantics. We draw lines between philosophies and end up creating "others" within our own midst. We all care for node and want to see it succeed. As I can tell those that are investing time have the best intentions for the project. The policies listed above are primarily to help us screen out those who do not have the best intentions for our project / community, not punish those who do.

TLDR; **We all make mistakes. If it isn't such a big deal to be reprimanded for making a mistake, people will feel safer to make them.**

**Comment by williamkapke** [comment]
@TheAlphaNerd nice brain dump.

Related: At NodeConf, I brought up the concept that the github bot could be used to make temp bans maybe even a way to facilitate saying I'm sorry and getting unbanned.

Is this a (partially?) opposing approach to Inclusivity's [project-wide facilitation framework](https://github.com/nodejs/inclusivity/issues/132) and the Run Books?

**Comment by nebrius** [comment]
Some really good thoughts here. I especially like the idea of temp-ban fast and relating it to IRC. We could write a GitHub bot to handle the ban and have it automatically unban when the time has passed.

> Is this a (partially?) opposing approach to Inclusivity's project-wide facilitation framework and the Run Books?

Maybe? I think on the surface they are, but both proposals are still nebulous, and I think can learn a lot from each other. This is a good question to take the time to ponder and think through :)

**Comment by TheAlphaNerd** [comment]
I don't think the two ideas are mutually exclusive. What I am suggesting here is primarily a change in how we treat things, less the process we follow.  For example, a person deciding that a thread or comment should be moderated could prompt a facilitator to come and handle the situation.

The approach we take to banning would obviously change the rulebooks, but not make them necessary. 

I see Bryan's proposal as a way to codify how these things are played out, mine is about how we approach and define it

**Comment by Starefossen** [comment]
+1 for temp bans, too bad that GitHub has such a poor support for it. Maybe the bot can help facilitate with that.

I am very sceptical to have each contributor moderating as they seam fit, in the dark, and without propper guidelines or Code of Conduct. I can not see how that model fits within the spirit of keeping things in the open with a democratic process.

**Comment by bnoordhuis** [comment]
I agree with @Starefossen.  The Code of Conduct is to ensure uniform treatment under a common set of rules.  Leaving it to an individual's discretion makes the process far too arbitrary.

Myles mentions IRC.  That's a great example (although not in the way he intended) because IRC is the poster child for arbitrary enforcement.  It's almost an axiom.

I'm actually quite positive that leaving moderation up to individual contributors would, on average, work well.  But you might as well toss out the Code of Conduct because you're moving from "everyone is equal in the eyes of the law" to something quite different.

> While we are busy discussing things people are being harassed
> When we decide not to act we set a precedent that certain behavior is ok, and this can and has escalated in the past.

Can you provide examples?  I'm not sure what incidents you are referring to.

> safe space

I would avoid that phrase.  It has become much too overloaded and politicized.

**Comment by mikeal** [comment]
>  because IRC is the poster child for arbitrary enforcement. It's almost an axiom.

IRC is also an example of scale that we have not had to deal with yet. The level of arbitration people seem to recommend here simply doesn't scale to the level of enforcement necessary on IRC and, increasingly, even in venues like this (GitHub).

**Comment by jasnell** [comment]
@MylesBorins ... I recommend that we close this issue and move any relevant discussion to the community-committee repository. 

Going to close for now, please reopen if you feel it's necessary to do so.
