### ISSUE TITLE
Nominating Darshan Sen (RaisinTen) to be a TSC member

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#1141]
Per the [Charter](https://github.com/nodejs/TSC/blob/main/TSC-Charter.md#section-3-establishment-of-the-tsc):

> Changes to TSC membership should be posted in the agenda, and may be suggested as any other agenda item.

I'd like to nominate Darshan Sen (RaisinTen). He has been an excellent collaborator and triager.

@nodejs/tsc

**Comment by mhdawson** [comment]
+1 from me

**Comment by richardlau** [comment]
+1

**Comment by mhdawson** [comment]
I see 11 +1s and no objections. 

11 +1s is > thatn 50% of the TSC members and this having been open for 21 days without and on recent TSC meeting agendas.

I believe we can confirm this as fulfilling our governance requirements for a standard TSC motion and vote.

I'll plan to onboard @RaisenTen this week.

**Comment by Trott** [comment]
The charter says: 

> The TSC may add additional members to the TSC by a standard TSC motion and vote. 

I would take that to mean that we need to use our voting process and not merely consensus. So in that spirit, I move to make this a vote.

@nodejs/tsc Can the folks who have not voted either cast a vote or formally abstain?

Yes: 12  (@apapirovski @BethGriggs @danielleadams @gireeshpunathil  @joyeecheung   @mhdawson @MylesBorins @ronag @richardlau @targos @tniessen @Trott)
No: 
Abstain:
Not yet voted/abstained: 8 (@aduh95 @BridgeAR @ChALkeR @cjihrig @fhinkel @jasnell @mcollina @mmarchini)

I'd say let's give folks 72 hours before closing out the voting, since voting can be the difference between retaining TSC membership and being automatically removed.

**Comment by apapirovski** [comment]
@Trott what's the difference between consensus-seeking vs a vote? E.g. other than the +1s being an emoji-reaction vs actual posts, this is basically identical to how Richard Lau's nomination went https://github.com/nodejs/TSC/issues/1096

It was also on the TSC meeting agenda today so all of the TSC would've been alerted about it.

**Comment by Trott** [comment]
> @Trott what's the difference between consensus-seeking vs a vote? E.g. other than the +1s being an emoji-reaction vs actual posts, this is basically identical to how Richard Lau's nomination went #1096
> 
> It was also on the TSC meeting agenda today so all of the TSC would've been alerted about it.

I'm trying to give TSC members every reasonable opportunity to participate since we have now automated the checking-vote-participation part of removing inactive TSC members. I don't want there to be any grounds for someone saying we didn't do the vote properly, they didn't get sufficient notification, etc.

**Comment by mmarchini** [comment]
+1

**Comment by aduh95** [comment]
> Not yet voted/abstained: 6 (@aduh95

I did approve https://github.com/nodejs/node/pull/41419, I thought it was enough. +1 from me!

**Comment by mhdawson** [comment]
@Trott sorry I missed your comment about having to formally call for a vote. I've already on-boarded @RaisinTen, but will make sure reverse if the vote unexpectedly does not align with that.

**Comment by mcollina** [comment]
+1!

**Comment by jasnell** [comment]
+1!!!

**Comment by fhinkel** [comment]
+1

**Comment by jasnell** [comment]
+1 from me!

**Comment by Trott** [comment]
Part of me wants to hold out for a unanimous vote, but I think at 18 in favor and no one opposed, we can close this. Thanks, everyone!

**Comment by RaisinTen** [comment]
Thanks everyone! :D

**Comment by BridgeAR** [comment]
Belated +1
