### ISSUE TITLE
Google Summer of Code

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#1151]
Ref: https://github.com/openjs-foundation/cross-project-council/issues/821

@nodejs/mentorship

**Comment by DerekNonGeneric** [comment]
I would be interested in learning more about this. Depending on the task at hand, I think I would be interested if not taking any classes during summer term. :)

**Comment by Trott** [comment]
> I would be interested in learning more about this. Depending on the task at hand, I think I would be interested if not taking any classes during summer term. :)

We have never participated in Google Summer of Code, and I doubt we'll be participating this year based on the month-plus of silence on this issue. We're not looking for applicants right now. There's likely no shortage of those. What we would need (if it's not already too late!) is people to volunteer to do the work to make it so we can participate, like coming up with (for example) [the ideas list](https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list).

**Comment by Trott** [comment]
I see now that the CPC issue suggested February 7 as a deadline, so I'm going to close this. Maybe next year....
