### ISSUE TITLE
How is a new repo / project added?

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#117]
Recently, the [installer](https://github.com/nodejs/installer) repo popped up- seemingly overnight. I followed [the issue](https://github.com/nodejs/build/issues/440) that @TheAlphaNerd created which seemed to open the discussion. However, I cannot find a conversation that led to the decision that it was something the Foundation officially decided to pursue. I need to extremely emphasize that I have NO objections to the [installer](https://github.com/nodejs/installer) project- it is just a recent example. <br><sup>** Also FTR, I also do not have the personal capacity to assist in that project at this time.</sup>

Perhaps this was discussed in private and I just don't know. I hope this isn't the case because that would make me sad. I don't want to assume this- so I'm asking.

For some contrast here, take the [Github Bot](https://github.com/nodejs-github-bot/github-bot) project for example. [I've been helping](https://github.com/nodejs/build/issues/404#issuecomment-225752703) to get it moved to the Foundation's GitHub account for quite some time now and it is going through process with the Build group- which I think is a good thing.

This process seems significant as [there is proposed language](https://github.com/nodejs/TSC/pull/116) that (paraphrasing:) declares that everything within the GitHub repos are the TSC's responsibility. So it would seem appropriate for there to be a processes for the TSC/CTC/Foundation taking on new responsibilities.

Also note that [NVM (an established project) recently had a bunch of discussion](https://github.com/nodejs/TSC/issues/96) about becoming the Foundation's responsibility and still sits unresolved.

Without being stated- how do outsiders know:
- What problems is the project trying to solve (this can be somewhat deduced from the issue tracker I guess)?
- What is the backstory?
- Who is running it? (commits can tell people- not working groups)
- Who has been granted commit access to it?
- Who are the collaborators?
- What is the contribution policy?
- What is the license when it doesn't have one?
- DCO liabilities?

I hope I do not to seem to promote process that causes impediments to anything (I already feel overwhelmed with them). But I DO want to promote the Foundation's stated goals of openness, increasing collaboration, and community growth.

So, what is the the official pipeline for where & when projects/repos are added?

**Comment by TheAlphaNerd** [comment]
I do not want to speculate but if I recall the github bot needed to be in it's own repo in order to make use of the various hooks / api's of github that can be difficult to set up in the main org. As for a project like NVM there are a variety of complications regarding introducing new projects that already exist (especially when there are various options in the eco system).

The installer project, alternatively, was a new project that didn't require special permissions, nor is it in conflict with community projects.

**Comment by phillipj** [comment]
> I do not want to speculate but if I recall the github bot needed to be in it's own repo in order to make use of the various hooks / api's of github that can be difficult to set up in the main org.

It's true that keeping it outside the main org is easier in regards to enabling some 3rd-party services, such as Travis, but we know how to get around that issue now. The main reason the bot repo was created under the nodejs-github-bot user account, was because it was the simplest option just to get started, and we thought the project would have to prove its worth before putting it under the main org - we're way beyond that point now, so we're pretty much good to go as far as I see it.

**Comment by mikeal** [comment]
I remember writing in a policy somewhere that any org member can create a new repo. We wanted to keep the bar really low for creating sub-groups and sub-projects and being able to break things up into smaller components. Not sure if this is the policy we want going forward but I'm pretty sure it is written down *somewhere* :)

**Comment by nebrius** [comment]
> I do not want to speculate but if I recall the github bot needed to be in it's own repo in order to make use of the various hooks / api's of github that can be difficult to set up in the main org. As for a project like NVM there are a variety of complications regarding introducing new projects that already exist (especially when there are various options in the eco system).

Just to clarify @TheAlphaNerd , when you say "main org," are you referring to the github.com/nodejs/node repo? Or the github.com/nodejs org?

> I remember writing in a policy somewhere that any org member can create a new repo. We wanted to keep the bar really low for creating sub-groups and sub-projects and being able to break things up into smaller components. Not sure if this is the policy we want going forward but I'm pretty sure it is written down somewhere :)

I thought I remembered that from somewhere too.

I tend to be in favor of this approach too, making it so org members can create new repos. They don't const anything financially, and if there isn't any existing code/docs/etc coming in, then there aren't any DCO/licensing/etc issues. Often times, creating a new repo doesn't actually increase the scope of the project. It's more a case that some existing piece was broken off, a new WG is being formed, etc. to handle existing issues/code in the codebase.

That said, there does come a point where a new repo does represent an increase in scope, and perhaps this is a concern that needs to be addressed.

**Comment by williamkapke** [comment]
Related: https://github.com/nodejs/post-mortem/issues/30

**Comment by williamkapke** [comment]
@mhdawson said did a great job summarizing the outcome of the 2016-08-04 TSC meeting in https://github.com/nodejs/post-mortem/issues/30. Quoting a _slighly_ modified version here:
> Discussion in CTC meeting
> 1) Free [to create repos for new projects], just make sure to include boilerplate governance files.
> 2) For [existing projects]:
>   a) add boilerplate governance files to existing project
>   b) open issue in TSC requesting move, once there are a few LGTMs then move to nodejs org.

@Fishrock123 mentioned moving the github-bot to the org under this approach & I volunteered to submit the required documents. Not knowing this, @phillipj moved the bot a few hours ago. lolz. It's good to have it finally moved.

SOoo... I hereby promise to make sure it gets done & will follow up with the TSC ;)
See: https://github.com/nodejs/github-bot/issues/59

These new steps should be documented and I will also add that to my TODO list and then I feel this issue can be closed!

**Comment by williamkapke** [comment]
The bot docs were merged. Closing.
