### ISSUE TITLE
managing dispute with moderation team member

### ISSUE THREAD

**Issue by DerekNonGeneric** [nodejs/TSC#1174]
According to @mmarchini (TSC), the way I framed my objection to a collaborator nomination did not portray them in a positive light, which I hold was due to exceeding the manageable amount of changes expected for core collaborators to review in a reasonable timeframe.

I was soon after requested by @benjamingr (moderation team) to consider self-moderating what I had written and was unable to deliver on that due to such short and unexpected notice. Ultimately, the request was for me to consider it, which I did and found no appropriate replacement. Instead, I chose to censor their comments on the thread, so as to not derail the discussion and which does not seem like the appropriate way to bring this to one's attention.

Because of this, @benjamingr notified me that the matter had been escalated and requested that I make amends to the TSC and moderation team members, both groups of people I have never had previous issues with. This seems like a misunderstanding and @benjamingr likely has much on his plate for this and may have jumped the gun and overreacted.

---

What can we do to resolve the matter?

**Comment by benjamingr** [comment]
Hey,

I am on holiday so sorry for the terse response.

Please reach out to the TSC and moderation teams via email moderation@nodejs.org tsc@nodejs.org

We do not discuss moderation involving individuals publicly.
