### ISSUE TITLE
emails to moderation@nodejs.org bounce

### ISSUE THREAD

**Issue by DerekNonGeneric** [nodejs/TSC#1175]
Hey,

I am on holiday so sorry for the terse response.

Please reach out to the TSC and moderation teams via email moderation@nodejs.org tsc@nodejs.org

We do not discuss moderation involving individuals publicly.

_Originally posted by @benjamingr in https://github.com/nodejs/TSC/issues/1174#issuecomment-1046923597_

**Comment by Trott** [comment]
I've confirmed that moderation@nodejs.org bounces (but moderation@iojs.org seems to work). @nodejs/build Working as expected? Or is that a problem?

**Comment by richardlau** [comment]
I think working as expected. The mailgun instance we have for https://github.com/nodejs/email handles `*@iojs.org` email aliases. See https://github.com/nodejs/email#nodejsorg for `*@nodejs.org` email addresses.

**Comment by Trott** [comment]
In that case, we should modify https://github.com/nodejs/moderation/blob/1ad29ebbf77b0c42a780601bb4fbf6d4371d0771/ONBOARDING.md but that's not urgent. Otherwise, closing. Thanks, Richard.

**Comment by richardlau** [comment]
Or request the alias from the Linux Foundation as documented, but I'll leave that decision up to the moderation team.

**Comment by Trott** [comment]
> Or request the alias from the Linux Foundation as documented, but I'll leave that decision up to the moderation team.

@nodejs/moderation I think we probably want to make that request.
