### ISSUE TITLE
nodejs distributions are not affected the same way by security releases

### ISSUE THREAD

**Issue by kapouer** [nodejs/TSC#1187]
Hi,
as an example, in Debian we have Node.js depending on system-installed OpenSSL,
thus security issues affecting that dependency are, most of the time, dealt with in the corresponding dependency, not in Node.js.

Thus a sentence like "if you're using a Node.js version not distributed by official upstream channel, this security issue might not concern you, please check with their security team", etc...

**Comment by mcollina** [comment]
I'm +1 to add such a disclaimer. It seemed obvious to me but likely it's not for most devs.

**Comment by mhdawson** [comment]
TSC Question:

Any concerns with by default adding 

If you're using a Node.js version which is part of a linux distribution which uses a system installed OpenSSL, this security upated might not concern you, please check with their security team

to any OpenSSL only security releases?

**Comment by richardlau** [comment]
No concerns from me, although I think Homebrew might also be dynamically linking openssl so it's not just Linux distributions.

**Comment by ljharb** [comment]
Considering (i believe) node isn't officially distributed anywhere without openssl, adding such a message seems "fine", but also seems like the sort of thing users sign up for when they choose to use an unofficial installation mechanism.

**Comment by mhdawson** [comment]
Discussion in TSC meeting, might want to say that you may need to update your openssl instead.

**Comment by ChALkeR** [comment]
1. Perhaps the text should be changed to include a reminder to update OpenSSL if needed, as the current one suggests that user might not to have to anything _at all_. And they likely _should_ update OpenSSL for the security update.

2. I have concerns with adding this "by default" as this could lead in accidentally adding it in case where it is not applicable, e.g. could be other changes included. Forgetting it won't cause much damage (as would just keep the current state of things), and accidentally adding it where it's not applicable could significantly break the trust chain and result in rush updates and/or security issues for users. 

So, perhaps we should decide on the wording, and add this as a suggested wording for those cases when we are totally sure there won't be any other changes except for the deps update, but leave it at the releaser judgment on whether to include it or not, without specifically suggesting to do that "by default".

cc @MylesBorins @BethGriggs (as is related to what has been discussed on the meeting) -- does that sound good?

**Comment by mhdawson** [comment]
@ChALkeR so maybe adding the following in the [security release process](https://github.com/nodejs/node/blob/master/doc/contributing/security-release-process.md#announcement-one-week-in-advance-of-the-planned-release) in this section under the [Pre-release announcment to node.js org blog( add the following additional text.

If the security release is planned to only contain an OpenSSL update consider adding the following to the pre-release announcement:

Since this security release will only includes updates for OpenSSL, if you're using a Node.js version which is part of a linux distribution which uses a system installed OpenSSL, this security update might not concern you. You may instead need to update your system OpenSSL libraries, please check the security announcements for the distribution.

**Comment by ChALkeR** [comment]
@mhdawson `s/is planned to/will/` perhaps (and minor fixes):

> If the security release will only contain an OpenSSL update consider adding the following to the pre-release announcement:

> Since this security release will only include updates for OpenSSL, if you're using a Node.js version which is part of a Linux distribution which uses a system installed OpenSSL, this Node.js security update might not concern you. You may instead need to update your system OpenSSL libraries, please check the security announcements for the distribution.

**Comment by mhdawson** [comment]
@ChALkeR looks good to me.

**Comment by mhdawson** [comment]
I'll open a PR to add that and we can have any additional discussion/concerns raised there.
