### ISSUE TITLE
New meeting times

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#1199]
With daylight savings time changes all done and with people having had a decent opportunity to update their availability in the spreadsheet, here are the new meeting times:

* Wednesday UTC 12:00
* Wednesday UTC 20:00
* Wednesday UTC 21:00
* Thursday UTC 14:00

@nodejs/tsc

**Comment by Trott** [comment]
Pacific Daylight Time:

* Wednesday 5am
* Wednesday 1pm
* Wednesday 2pm
* Thursday 7am

Eastern Daylight Time

* Wednesday 8am
* Wednesday 4pm
* Wednesday 5pm
* Thursday 10am

British Summer Time

* Wednesday 1pm
* Wednesday 9pm
* Wednesday 10pm
* Thursday 3pm

Central European Summer Time

* Wednesday 2pm
* Wednesday 10pm
* Wednesday 11pm
* Thursday 4pm

Moscow Standard Time

* Wednesday 3pm
* Wednesday 11pm
* Wednesday 11:59pm/Thursday midnight
* Thursday 5pm

India Standard Time

* Wednesday 5:30pm
* Thursday 1:30am
* Thursday 2:30am
* Thursday 7:30pm

China Standard Time

* Wednesday 8pm
* Thursday 4am
* Thursday 5am
* Thursday 10pm

**Comment by Trott** [comment]
Those times look especially bad for our TSC members from East Asia and South Asia. The Wednesday UTC 12:00 and Thursday UTC 14:00 times are all a 4 or 5 (on a 0-5 scale) time for each of them, so that's good. But those middle two times are indeed awful for those folks. I'm going to run it again with our old 3-meeting rotation and see what comes out.

**Comment by Trott** [comment]
If we want 3 meeting times, those would be all on Wednesday:

* UTC noon
* UTC 3pm
* UTC 9pm

Pacific Daylight Time:

* 5am
* 8am
* 2pm

Eastern Daylight Time:

* 8am
* 11am
* 5pm

British Summer Time:

* 1pm
* 4pm
* 10pm

Central European Summer Time:

* 2pm
* 5pm
* 11pm

Moscow Standard Time:

* 3pm
* 6pm
* Thursday midnight

India Standard Time:

* 5:30pm
* 8:30pm
* Thursday 2:30am

China Standard Time:

* 8pm
* 11pm
* Thursday 5am

**Comment by mhdawson** [comment]
Rich thanks for generating/sharing the options.

I'm good with either the 3 or 4 slot rotation.

I'll move next weeks meeting to 11am on Wednesday as discussed today to avoid the config with the Next-10 mini-summit

**Comment by mcollina** [comment]
I prefer the 3 slots rotation

**Comment by apapirovski** [comment]
4 slot rotation seems painful for a number of timezones. But as someone in PDT, either is fine for me.

**Comment by cjihrig** [comment]
I like the 3 slot rotation more.

**Comment by RaisinTen** [comment]
+1 about the 3 slot rotation.

**Comment by mhdawson** [comment]
I believe I have updated the calendar as per the 3 slot rotation, closing.
