### ISSUE TITLE
DEFER PROPOSAL: Node.js Foundation Technical Steering Committee (TSC) Meeting 2016-07-28

### ISSUE THREAD

**Issue by rvagg** [nodejs/TSC#120]
I'd like to propose that we defer our TSC meeting this week and do it next week instead then return to our normal every-two-weeks cadence the week after that (i.e. have two meetings in a row next week and the week after so we're back on schedule). The majority of us who attend these are at NodeSummit and I think a little busy, at least I am and those who I have floated the idea of deferring this meeting seem to think it's a good idea. Please speak up if you object!

**Comment by jasnell** [comment]
SGTM

**Comment by nebrius** [comment]
SGTM too.

**Comment by misterdjules** [comment]
Sounds good to me!

**Comment by rvagg** [comment]
Will schedule one for next week
