### ISSUE TITLE
Announcement for Collab Summit

### ISSUE THREAD

**Issue by WaleedAshraf** [nodejs/TSC#1204]
OpenJS World Collab Summit has started accepting issues.
https://github.com/openjs-foundation/summit/issues/310

For Node.js Project, we need to
- Make an announcement among all teams/initiatives to submit their session proposal.
- Create an agenda for the sessions.

**Comment by WaleedAshraf** [comment]
The announcement was posted here: https://github.com/orgs/nodejs/teams/members/discussions/18

**Comment by Trott** [comment]
I guess this can be closed? Please re-open and/or comment if I'm mistaken, of course.
