### ISSUE TITLE
request: update OpenSSL-Strategy.md w/ strategy on Node 17/18

### ISSUE THREAD

**Issue by johndevedu** [nodejs/TSC#1207]
Please update https://github.com/nodejs/TSC/blob/main/OpenSSL-Strategy.md with strategy on Node.js version 17.x and 18.x. Since the statically linked OpenSSL has been updated from 1.1.1 to 3.0.0+quic (https://github.com/nodejs/node/issues/40106 https://github.com/nodejs/node/pull/38512), it will be helpful to know what the plans are for supporting dynamically linked 1.1.1 in 17.x and 18.x moving forward. 

Also, there were challenges mentioned in [Node 16 + OpenSSL strategy](https://github.com/nodejs/TSC/blob/main/OpenSSL-Strategy.md#nodejs-version-16x-est-apr-2021-eol-apr-2024) (i.e. algorithms in legacy lib, etc), so it would be helpful to know how these challenges will be/have been overcome. 

TIA!

**Comment by mhdawson** [comment]
@johndevedu the doc's been updated, is that what you were looking for in terms of the strategy for 18.x?

**Comment by mhdawson** [comment]
I'm going to close this since it was updated, and we've not had a response from the op for a few months. Please let us know if that was not the right thing to do.

**Comment by johndevedu** [comment]
I'm sorry for the late reply. Yes, that was exactly what was needed. Thank you!!!
