### ISSUE TITLE
Subscribe TSC email to OpenSSL mailing list

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1215]
I know that @richardlau is subscribed to the OpenSSL mailing list on which security releases are announced.

I think it would be good for all TSC members to be aware when there is a new security release.

Richard tells me it is a low traffic list.

Do people agree that it would make sense to subscribe the TSC email to that list?

**Comment by richardlau** [comment]
> Richard tells me it is a low traffic list.
> 

Specifically this is openssl-announce: https://mta.openssl.org/mailman/listinfo/openssl-announce
Archives: https://mta.openssl.org/pipermail/openssl-announce/

**Comment by tniessen** [comment]
I just unsubscribed from openssl-users a few weeks ago because it was too high volume. If the openssl-announce mailing list is low volume, then no objection.

**Comment by mhdawson** [comment]
@richardlau I forget what you told me but I think you said it was < 1 message a week right?

**Comment by richardlau** [comment]
> @richardlau I forget what you told me but I think you said it was < 1 message a week right?

Completely depends how often OpenSSL release 🙂, but yes it's been that sort of frequency. See https://mta.openssl.org/pipermail/openssl-announce/ for the archives.

**Comment by mhdawson** [comment]
No objections in TSC meeting today, will do it.

**Comment by mhdawson** [comment]
Subscribed today.

**Comment by mhdawson** [comment]
Just leaving this open until we get the email confirmation and confirm that we are subscribed.

**Comment by mhdawson** [comment]
Received confirmation that we are subscribed, closing.
