### ISSUE TITLE
Vote on namespace for args parser 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1224]
There was agreement today in the TSC meeting that we should start a vote on the question of which namespace parseArgs should go under as being discussed in https://github.com/nodejs/node/pull/42675. Vote propsosed by @Trott and seconded by @mhdawson.  

Since we did not have enough people in the meeting, this issue is to give other TSC members an FYI and time to comment/object.

The plan is to start the vote this Friday if there are no objections before then. @aduh95 volunteered to spin up the vote using his great tool. 

The question for the vote is:

Should parseArgs be added under

1) process
1) util

**Comment by mhdawson** [comment]
@nodejs/tsc FYI

**Comment by Jamesernator** [comment]
I personally think `util` makes more sense given `args` is configurable. Like:

```js
const args = process.parseArgs({
   args: ["--some", ...otherArgs],
});
```

Just doesn't seem right for something that has nothing to do with the current `process`. The inversion seems okay, a utility (`util`) that happens to default to the current process.

For something comparable, `path.resolve(...)` uses the current `process.cwd()` as the default root, so it's not new terroritory for Node APIs to default to process-level values when more specific choices aren't given/

**Comment by ljharb** [comment]
If anything, imo `path.resolve` is a good argument for _process_, because it's a solution that lives close to its problem domain, instead of in a "util grab bag because we didn't have a better option" place.

**Comment by aduh95** [comment]
Since it looks like there's consensus on what are the candidates for this vote, I went ahead and opened the voting PR: https://github.com/nodejs/TSC/pull/1225
