### ISSUE TITLE
Recertify moderation team

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1231]
We do this once a year and it's time.

**Comment by mhdawson** [comment]
@mcollina I think we should capture the people recertified as done in the past issue here - https://github.com/nodejs/TSC/issues/1062

**Comment by mhdawson** [comment]
From discussion in the TSC meeting today, Rich said list is:

[aduh95](https://github.com/aduh95) - Antoine du Hamel <[duhamelantoine1995@gmail.com](mailto:duhamelantoine1995@gmail.com)> (he/him)
[benjamingr](https://github.com/benjamingr) - Benjamin Gruenbaum <[benjamingr@gmail.com](mailto:benjamingr@gmail.com)>
[bnb](https://github.com/bnb) - Tierney Cyren <[hello@bnb.im](mailto:hello@bnb.im)>
[codebytere](https://github.com/codebytere) - Shelley Vohr <[shelley.vohr@gmail.com](mailto:shelley.vohr@gmail.com)>
[JohnTitor](https://github.com/JohnTitor) - Yuki Okushi <[huyuumi@neet.club](mailto:huyuumi@neet.club)>
[ljharb](https://github.com/ljharb) - Jordan Harband <[ljharb@gmail.com](mailto:ljharb@gmail.com)>
[othiym23](https://github.com/othiym23) - Forrest L Norvell <[othiym23@gmail.com](mailto:othiym23@gmail.com)>
[ryanmurakami](https://github.com/ryanmurakami) - Ryan Lewis <[ryanharrisonlewis@gmail.com](mailto:ryanharrisonlewis@gmail.com)>
[Trott](https://github.com/Trott) - Rich Trott <[rtrott@gmail.com](mailto:rtrott@gmail.com)>

With that I think we can close the issue again.

**Comment by benjamingr** [comment]
@mhdawson it looks like this needs to happen again?
