### ISSUE TITLE
Onboard @juanarbol as security steward

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1233]
@juanarbol has volunteered to be a security steward. This is his nomination as per  https://github.com/nodejs/node/blob/master/doc/contributing/security-release-process.md#security-release-stewards.  Approval is based on the standard TSC concensus process.

@juanarbol is already a Node.js collaborator and has also recently been onboarded as a releaser.

@nodejs/tsc I'll leave this open for 1 week and tag for the agenda. Please add your +1 unless you have objections in which case please either share them in the issue or privately with me and/or other tsc members.

**Comment by mhdawson** [comment]
+1 from me

**Comment by richardlau** [comment]
+1

**Comment by cjihrig** [comment]
+1

**Comment by mhdawson** [comment]
I think this is now confirmed, will start the onboarding process

**Comment by mhdawson** [comment]
@juanarbol will try to reach out to you this week to get you onboarded.

**Comment by mhdawson** [comment]
He's now onboarded and we'll line up somebody (likely me or @mcollina) to help him when he comes up in the rotation for the first time.
