### ISSUE TITLE
Create GitHub team for reviewing src (C++) changes

### ISSUE THREAD

**Issue by tniessen** [nodejs/TSC#1237]
Refs: https://github.com/nodejs/node/pull/43286#issuecomment-1143946336
Refs: https://github.com/nodejs/node/pull/43202#issuecomment-1144571766

We currently don't have a team that we can ping for C++ changes that don't require familiarity with a particular subsystem. Subsystem teams such as `@nodejs/crypto` have very few active members who frequently review C++ changes, so pinging these teams is not always helpful.

I'm proposing to create a new team under `@nodejs/core`, maybe `@nodejs/cpp-reviewers`, to address this.

To not start with an empty team, I'd like to add a small subset of active collaborators based on some git statistics, e.g., number of authored/reviewed commits that change `src/*` within the last year or so.

(I was going to create this in the core repo but I don't know how to bypass the templates there.)

**Comment by targos** [comment]
+1

> (I was going to create this in the core repo but I don't know how to bypass the templates there.)

https://github.com/nodejs/node/issues/new

**Comment by tniessen** [comment]
This has been open for more than a week with no objections, so I created the team as proposed.

@nodejs/cpp-reviewers You have been added to this team based because at least one of the following is true, based on the commit history from the last 365 days:

1. You reviewed at least 5 commits, and at least 50 % of all commits that you reviewed modified files in `src/`.
   ```bash
   join -t $'\t' -1 2 -2 2 <(git log --format='format:%b' --since '1 year ago' | grep '^Reviewed-By: ' | tr -d '\r' | sort | uniq -c | awk '{ f=$1; $1=""; print f"\t"$0; }') <(git log --format='format:%b' --since '1 year ago' -- src | grep '^Reviewed-By: ' | tr -d '\r' | sort | uniq -c | awk '{ f=$1; $1=""; print f"\t"$0; }') | awk  -F'\t' 'BEGIN {OFS = FS} { r=100*$3/$2 ; if ($2 >= 5 && r > 50) { print $1 } }'
   ```
3. You authored at least 15 commits that modified files in `src/`.
   ```bash
   git log --format='format:%aN' --since '1 year ago' -- src | sort | uniq -c | sort -nr | awk '{ if ($1 >= 15) print $0 }'
   ```
5. You are among the 5 collaborators who reviewed the most commits that modified files in `src/`.
   ```bash
   git log --format='format:%b' --since '1 year ago' -- src | grep '^Reviewed-By: ' | tr -d '\r' | sort | uniq -c | sort -nr | head -5
   ```

Please feel free to remove yourself from the team if you do not wish to be pinged for reviews.

Everyone else, please feel free to add yourself to the team if you do wish to be pinged for reviews.
