### ISSUE TITLE
Grace Hopper Open Source Day (virtual) Sept 16, 2022

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#1238]
@nodejs/tsc Do we possibly want to participate? https://github.com/openjs-foundation/cross-project-council/issues/898

I know Grace Hopper Day has received criticism in the past but I'm also under the impression that they have responded to and corrected for at least some of the criticisms. I haven't formed an opinion one way or the other myself, but maybe some of you feel strongly in favor or against participating?

**Comment by rginn** [comment]
GHC has taken steps to diversity its representation. My only experience is hearing from friends and colleagues who have attended and found it empowering with unparalleled networking opportunities. 

Open Source Day seems like a great way to build a diverse pipeline of Node.js contributors with about 100 participants per project hackathon.

**Comment by danielleadams** [comment]
I've attended GHC and didn't enjoy my experience - that was years ago though, so perhaps the event has improved. I'm still supportive of their mission, and I'm in favor of joining their Open Source Day.

**Comment by Trott** [comment]
> I'm in favor of joining their Open Source Day.

We should all be clear about whether we are merely supportive of participating, or if we are willing to do the work to make it happen. (Danielle, I assume you are in the former category and not the latter, but if I'm wrong, please clarify!)

**Comment by danielleadams** [comment]
@Trott I'm in the latter too (I'd be willing to work to make it happen).

**Comment by fhinkel** [comment]
> @Trott I'm in the latter too (I'd be willing to work to make it happen).

Same here! I can help with creating content/tagging issues or mentoring/leading a workshop during the day.

**Comment by rginn** [comment]
Awesome! Let's hop on a call to brainstorm our ideas, and I'll consolidate into a written submission for the June 20 deadline. We also may be able to leverage our Node.js training content from OpenJS World 2022. Thumbs up please if 8 am Pacific on Friday, June 17, works for you for a planning call. 

I'll also update the Grace Hopper Open Source Day co-chairs that our Node.js project application for participation is on its way.

**Comment by Trott** [comment]
> Awesome! Let's hop on a call to brainstorm our ideas, and I'll consolidate into a written submission for the June 20 deadline. We also may be able to leverage our Node.js training content from OpenJS World 2022. Thumbs up please if 8 am Pacific on Friday, June 17, works for you for a planning call.

I'd be happy to jump on the call too. I can offer perspective from having done the Code+Learn events for so long. And if there are other energized people, I'm likely to get energized too and volunteer to do stuff. Look at me, jumping on the bandwagon!

**Comment by fhinkel** [comment]
Voted on the issue, Friday works for me!

**Comment by PaulaPaul** [comment]
Count me in! Thank you!

**Comment by PaulaPaul** [comment]
Hello! I received a response on the GHC OSD Slack regarding limiting the number of participants for a given project (response copied below)
**_Yes, [the GHC OSD] projects team will work with projects to determine how many people can pre-register for the project._**

Thank you everyone!

**Comment by Trott** [comment]
This event is tomorrow and we are participating. I'm going to close this issue. Thanks, everyone, especially @danielleadams, @fhinkel, and @rginn, for making this happen!

**Comment by tniessen** [comment]
This year's event: https://github.com/nodejs/TSC/issues/1372
