### ISSUE TITLE
Moving to TSC Emeritus

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#1245]
FYI: https://github.com/nodejs/node/pull/43524

> My availability has become smaller and smaller and I think for now the
best thing to do is to move to TSC Emeritus. Perhaps I'll have more
time to focus on Node.js Leadership again in the future, but for now
I think it's best to officially step back a bit.
>
> So long, and thanks for all the modules o/

**Comment by tniessen** [comment]
Thank you for all your amazing work on the TSC!

**Comment by mhdawson** [comment]
Thanks for all of your work over the years.

**Comment by bnb** [comment]
Appreciate your work over the years, Myles. You've been an absolutely incredible mentor to me - knowingly or not. I deeply appreciate you, and the project is better off because of your involvement.

**Comment by mhdawson** [comment]
The PR in the node repo has laned I think this can be closed now.
