### ISSUE TITLE
Adding Geoffrey Booth as a TSC member

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#1252]
@nodejs/tsc Because this will be a yes/no/abstain vote rather than options, I think it's probably OK to just ask TSC members to indicate their vote in a comment here.

**Comment by Trott** [comment]
+1. I'm in favor.

**Comment by Trott** [comment]
(In case there is any confusion, I'm referring to @geoffreybooth and not some other Geoffrey Booth.)

**Comment by gireeshpunathil** [comment]
+1

**Comment by BridgeAR** [comment]
+1

**Comment by RaisinTen** [comment]
+1!

**Comment by targos** [comment]
+1

**Comment by mcollina** [comment]
+1

**Comment by danielleadams** [comment]
+1

**Comment by richardlau** [comment]
+1

**Comment by cjihrig** [comment]
+1

**Comment by BethGriggs** [comment]
+1

**Comment by mhdawson** [comment]
+1 from me he would be a great addition.

**Comment by aduh95** [comment]
+1

**Comment by Trott** [comment]
Welcome, @GeoffreyBooth!

https://github.com/nodejs/TSC/pull/1254

**Comment by GeoffreyBooth** [comment]
Thank you all! I look forward to helping however I can.
