### ISSUE TITLE
TSC Board Director Elections

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#126]
Wow, it's been more than a year now since we started the foundation and merged io.js and Node.js :)

To my surprise, the Bylaws don't spell out the terms of the TSC Board Director position. The TSC is free to elect anyone at any time. We need to figure out what the term limits are and how to proceed with the next election if necessary.

My recommendation would be to have a new election each year for a variety of reasons:

* Gives us the opportunity to share the work load across the project and bring up more project leaders.
* Gives the opportunity for the reps to avoid burnout.
* Sends the right signals to the community that the Board Director is not a defacto-BDFL.
* Educates more members of the TSC with the inner workings of the board.

That said, the role has a lot of responsibilities, of which I'm sure Rod will elaborate on but just off the top of my head:

* Deliver monthly updates to the board on the project as a whole.
* Deliver monthly updates to the TSC on what the board is doing.
* Bi-weekly meetings with a member of the foundation staff (me!) and the Board Chairperson.
* Optional participation in board sub-committees (legal, audit & finance, marketing).

So, that leaves the TSC with a slightly open question about how long you want the terms to be and how you want to conduct the next election. I know that a few people are also on the short list for TSC membership, it would probably be good to start the nominations and elections after they've been on-boarded.

**Comment by jasnell** [comment]
A two year term seems reasonable to me, same as [elected individual member representatives](https://nodejs.org/en/blog/community/individual-membership/#what-are-the-term-lengths).

**Comment by mikeal** [comment]
> A two year term seems reasonable to me, same as elected individual member representatives.

That's actually the *only* two year term. Gold & Silver member reps are one year. Board chair, vice-chair, and secretary are all one year.

The only reason individual reps are two year is so that when new reps come on they have someone who has been on a year to work with in on-boarding them, that doesn't really apply to the TSC seat because the old rep will still be available as a TSC member.

**Comment by mikeal** [comment]
Also, I don't think I made this clear at all, it's up to the TSC if they want to set term limits on any single person running for the seat multiple times. No other seat or chair has that though so I wouldn't recommend it, but looking back at the wording I used I didn't make it clear that the existing rep could run for a new term in each election.

**Comment by jasnell** [comment]
Understood. Still, a two year terms seems reasonable to me, along with the option for the current chair to step down at any time if they are reaching burn out.

**Comment by joshgav** [comment]
@mikeal 

> because the old rep will still be available as a TSC member.

That's not guaranteed as the old rep is more likely to resign as their term ends. Also lack of an official role/title might make it harder for the previous rep to help, depending on their day jobs. Perhaps overlapping two-year terms like for the Individual Member reps makes sense here too.

For those unaware, I believe the arrangement for the Individual Member reps is that one member is elected each year for a two-year term, so that the two members intentionally always overlap for a year.

**Comment by mikeal** [comment]
> That's not guaranteed as the old rep is more likely to resign as their term ends.

Why would it likely that someone would resign from the entirely after handing over the chair?

**Comment by joshgav** [comment]
@mikeal I was heading off the argument that resignation or other unforeseen events could happen during a term too, by arguing that the concern is greater as and after the term ends as people are more likely to resign at or after an official transition point.

> Why would it [be more] likely that someone would resign from the [TSC] entirely after handing over the chair?

No proof and I'm open to alternate views, but this is what I've observed with people holding public offices at all levels: once they've completed terms in a top-level position they're more likely to move on to new domains.

**Comment by mikeal** [comment]
@joshgav I see what you're saying. What I would *hope* to see is a regular rotation of people through all the leadership positions without anyone being "pushed out."

In order for the project to continue to grow and survive long term we need *many* more people in positions of leadership and a broader distribution of responsibilities. This is only one example, but because of its visibility it has a role to play in setting an example for the culture.

If you look at other long running institutions, like Apache, you'll notice a regular rotation of board and committee members, especially in roles with more responsibilities like the chair. 

BTW, I'm not saying we *should* have a new board chair or that even if we settle on year long terms that Rod shouldn't run again, we're still in the early stages of the foundation so some of the longer term considerations may not be relevant yet, but this is something to keep in mind when setting a long term policy.

**Comment by williamkapke** [comment]
I see in the bylaws...
> The TSC Chair shall be elected annually by a majority vote of the Technical Steering Committee members. The TSC Chair may be re-elected for additional terms without limit.

I think it is also important to note that there are 2 elected positions: 
> The TSC shall elect a Chair and a TSC Director. The Chair and TSC Director may be (but are not required to be) the same person. ...
> ...The Technical Steering Committee shall be under the leadership of the TSC
Chair. The TSC Director shall attend meetings of the Board as a member of the Board, and may
vote at such meetings. 
 
There's also quite a bit in the TSC charter that was approved by the board...
> The TSC will elect from amongst voting TSC members a TSC Chairperson to work on building an agenda for TSC meetings and represent the TSC to the Board for a term of one year according to the Node.js Foundation’s By-laws. The TSC shall hold annual elections to select a TSC Chairperson; there are no limits on the number of terms a TSC Chairperson may serve.

...although this appears to conflict with the statement that the Chair and Director can be different people. In my experience with other orgs governing docs, by-laws trump the charter though.

The director election is just past due according to [the Board meeting minutes on 2015-07-27](https://nodejs.org/static/documents/minutes/nodejs-foundation-board-meeting-2015-07-27.pdf):
> RESOLVED: That the Board hereby acknowledges the designation by the Technical
Steering Committee of Rod Vagg as the Technical Steering Committee’s representative
to the Board and the Board hereby acknowledges Rod Vagg as the “TSC Director,” as
defined in the By-laws.

**Comment by mikeal** [comment]
@williamkapke damn, i read those bylaws for an hour today and didn't see this section :)

Looks like we need a TSC election :)

**Comment by jasnell** [comment]
Ha! Good grief. It really does help to read the manual!

**Comment by mikeal** [comment]
Thank god for @williamkapke :)

**Comment by jasnell** [comment]
Putting this on the TSC agenda.

**Comment by jasnell** [comment]
Ok, [discussion](https://github.com/nodejs/TSC/issues/128) and [nomination](https://github.com/nodejs/TSC/issues/129) threads are open. Going to close this issue and untag it from tsc-agenda.
