### ISSUE TITLE
Re-adding Franziska Hinkelmann as a TSC member

### ISSUE THREAD

**Issue by tniessen** [nodejs/TSC#1275]
Ref: https://github.com/nodejs/node/pull/44447#issuecomment-1231750733

The charter says that TSC members must be added by a vote. I propose that we open the voting now and plan to close it at the halfway point of tomorrow's meeting, which would mean voting ends at UTC 3:30 PM on Wednesday, August 31. (That's 8:30 AM Pacific, 5:30 PM Central European, 9:00 PM India, etc. )

Assuming no objections to my vote proposal, please indicate your vote (+1, -1, or 0 to abstain) in a comment. (Votes can get lost in emoji reactions if there are too many. I don't mind a bit of noise for something like this.)

@nodejs/tsc

_(Adapted from https://github.com/nodejs/TSC/issues/1274.)_

**Comment by mcollina** [comment]
+1

**Comment by tniessen** [comment]
+1

**Comment by aduh95** [comment]
+1

**Comment by targos** [comment]
+1

**Comment by Trott** [comment]
+1

**Comment by ChALkeR** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by RaisinTen** [comment]
+1

**Comment by apapirovski** [comment]
+1

**Comment by gireeshpunathil** [comment]
+1

**Comment by GeoffreyBooth** [comment]
+1

**Comment by BethGriggs** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by BridgeAR** [comment]
+1

**Comment by Trott** [comment]
PR to add vote results: https://github.com/nodejs/TSC/pull/1277
