### ISSUE TITLE
Re-adding Franziska Hinkelmann as a TSC member

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#1276]
Ref: https://github.com/nodejs/node/pull/44447

The charter says that TSC members must be added by a vote. I propose that we open the voting now and plan to close it at the halfway point of tomorrow's meeting, which would mean voting ends at UTC 3:30 PM on Wednesday, August 31. (That's 8:30 AM Pacific, 5:30 PM Central European, 9:00 PM India, etc. )

Assuming no objections to my vote proposal, please indicate your vote (+1, -1, or 0 to abstain) in a comment. (Votes can get lost in emoji reactions if there are too many. I don't mind a bit of noise for something like this.)

@nodejs/tsc

**Comment by Trott** [comment]
+1

**Comment by Trott** [comment]
Oops, closing. Please refer to #1275 instead.

**Comment by tniessen** [comment]
Sorry Rich, I copied your text from #1274 and created #1275.

**Comment by Trott** [comment]
> Sorry Rich, I copied your text from #1274 and created #1275.

No problem. Thanks for doing it faster than I did. :-D
