### ISSUE TITLE
Nominating Chengzhong Wu (@legendecas) to the TSC

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1282]
I'd like to nominate Chengzhong Wu (@legendecas)[https://github.com/legendecas].

He has contributed over a number of years and has [83 commits](https://github.com/nodejs/node/commits?author=legendecas) to Node.js core, has been involved in [440 issues](https://github.com/nodejs/node/issues?q=involves%3Alegendecas) in node.js core  and is a significant contributor to Node-api and the work of the Node-api team. He has also been contributing to diagnostic efforts and is leading the [ShadowRealm](https://github.com/nodejs/node/issues/42528) initiative.  

He's been very collaborative, contributes in a thoughtful and respectful way, and works to help move the work of the project forward in a scope greater than individual commits/issues. I've enjoyed my interactions with him and I think he'd be a good addition to the TSC.

**Comment by aduh95** [comment]
+1 assuming is up for it :)

**Comment by mhdawson** [comment]
I should have mentioned I have talked to Chengzhong and he is interested.

**Comment by richardlau** [comment]
+1

**Comment by Trott** [comment]
+1

**Comment by apapirovski** [comment]
+1

**Comment by gireeshpunathil** [comment]
+1

**Comment by RaisinTen** [comment]
+1 for sure!

**Comment by targos** [comment]
+1

**Comment by BethGriggs** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by mhdawson** [comment]
By my count we have 14/20 +1s so far and no objections.

I will wait until after the TSC meeting this week and then close the vote (The goverance says `The TSC may add additional members to the TSC by a standard TSC motion and vote.`) and the +1's emoji's in this issue will be tallied to get the vote results after the TSC meeting. 

I'll volunteer to onboard @legendecas assuming the vote is positive. Anybody else want to join us?

**Comment by mhdawson** [comment]
Ok, TSC meeting passed, and no objections so considering vote complete with a yes. PR to add vote data - https://github.com/nodejs/TSC/pull/1284

**Comment by mhdawson** [comment]
@legendecas can you confirm:
> Confirm that the new member has read, understands, and agrees to uphold the
[Code of Conduct](https://github.com/nodejs/admin/blob/main/CODE_OF_CONDUCT.md).

**Comment by mhdawson** [comment]
PR to add Chengzhong to invited list for TSC meetings - https://github.com/nodejs/create-node-meeting-artifacts/pull/118/files

**Comment by mhdawson** [comment]
PR to add to mailing lists - https://github.com/nodejs/email/pull/197

**Comment by legendecas** [comment]
> Confirm that the new member has read, understands, and agrees to uphold the
[Code of Conduct](https://github.com/nodejs/admin/blob/main/CODE_OF_CONDUCT.md).

I confirm I understand and agree to uphold the code of conduct.

**Comment by mhdawson** [comment]
Working through the list, only a few more items that I should get to tomorrow. @legendecas maybe we can talk after the Node-API  team meeting tomorrow and I can give you some context and answer any questions you have?

**Comment by Trott** [comment]
I think the only thing left to do is to add @legendecas to HackerOne (and maybe to the Google Group--I didn't check that one).

@mhdawson Let me know if you want me to handle HackerOne or find someone to handle the Google Group. Otherwise, I'll assume you're waiting to talk to @legendecas about something first or something like that.

**Comment by mhdawson** [comment]
Ok all done.
