### ISSUE TITLE
Issues regarding the behavior of certain members

### ISSUE THREAD

**Issue by tmathmeyer** [nodejs/TSC#13]
Let me preface this by first stating that I'm not here to troll. If you look at my profile it is plainly obvious that I have been involved with open source (though sadly mostly my own projects... thanks schoolwork) for a few years. 

As a student mentor for the webware class at my school taught in nodeJS, I sometimes read the comments on the repositories here. Today, I had the misfortune of reading many of the comments the thread about banning some specific user. It was especially the comments by a user named emilyrose that i found to be demeaning and overly emotional and harsh. 

While I'm personally very against having codes of conduct as I believe they promote censorship and "circlejerking" for lack of a better term, I will respect that you as project owners want one. However, I don't think it's out of line for me to say that  you should apply it equally to all members of the community, whether they be fresh accounts wanting to make silly and disruptive comments, or more active members of the community who attack others opinions on the basis of personal feelings. This is a technical project after all.

**Comment by roboman2444** [comment]
I agree. Banning someone for posting an eggplant emoji is very childish. However, it is up to the project owner to decide.

**Comment by mikeal** [comment]
The sole intention of the comment was to offend people, it served no other
purpose. The degree to which is was offensive or to whom isn't relevant
because the intention was not to contribute in any way other than to
offend. The
result was moderation and a ban so that it wasn't followed by additonal
comments.

**Comment by roboman2444** [comment]
"The sole intention of the comment was to offend people" - please elaborate.
I do not have enough experience in the web dev community to understand why an aubergine would be offensive. Are emojis not allowed in the project?

**Comment by tmathmeyer** [comment]
All I would ask is that users who seek to upset and piss off others, whether it be thrones who make dick jokes, or Emilyrose arguing for punishment for those with whom she disagrees, be treated equally under your global rules.

Allowing special treatment for "old guard" users, or users with specific political opinions is just as detrimental to inclusovity as a penis joke. Please treat them both seriously.

**Comment by mikeal** [comment]
Emily was arguing that we enforce a project policy that is already in
place, which we gad a hard time doing because we hadnt had to enforce it
yet and didnt have a process in place. Given the flood of trolls we have
now moderation has become less controversial and responses faster.

**Comment by HandsomeMatt** [comment]
:eggplant:

**Comment by HandsomeMatt** [comment]
:eggplant:

**Comment by HandsomeMatt** [comment]
HOW IS AN EGGPLANT OFFENSIVE THO

**Comment by Naarkie** [comment]
:eggplant:
