### ISSUE TITLE
adding bmeck to security-external

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#1300]
Proposing that we add bmeck to the security-external team.

@nodejs/tsc 

From our [Security Team doc](https://github.com/nodejs/TSC/blob/db67321d4f7b6ecba563d3e73c6aeab3e2638581/Security-Team.md):

> 3. On a case-by-case basis, individuals outside the Technical Steering
>    Committee are invited by the TSC to have access to private security reports
>    or private patches so that their expertise can be applied to an issue or
>    patch. This access may be temporary or permanent, as decided by the TSC.
>
>  Membership on the security teams can be requested via an issue in the TSC repo.

**Comment by aduh95** [comment]
+💯

**Comment by mhdawson** [comment]
+1

**Comment by Trott** [comment]
Added.
