### ISSUE TITLE
New meeting times

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#1306]
The (tentative until early next week) schedule of TSC meeting times:

UTC 09:00 16:00 21:00
Pacific Time 1am 8am 1pm
Eastern Time 4am 11am 4pm
Central European Time 10am 5pm 10pm
Armenia Time 1pm 8pm 1am
India Time 2:30pm 9:30pm 2:30am
China Time 5pm midnight 5am

<details>

These are the times that are viable and have the lowest standard deviation in their total scores for folks (which is stated unclearly, but just know that I mean "schedule that is the mos fair") is:

Hi, @nodejs/tsc. We have 19 of 21 of us who have updated the availability spreadsheet or confirmed that their availability hasn't changed. I think that's probably the highest participation percentage we've ever gotten, so kudos!

@apapirovski and @richardlau still have to update theirs. I know Richard is on holiday until (I think) next week, so this is a tentative proposal at least until Richard has  a decent chance to update his entries (and that gives Anatoli a little extra time too), but honestly, it's unlikely to change significantly.

</details>

**Comment by mhdawson** [comment]
@Trott should I move the meeting time for next week in the calendar? It is currently 8 AM ET, but new schedule would move that to 4 AM ET. 

Either way I'm assuming @mcollina (mentioned as an FYI) will chair as I won't make it.

**Comment by mcollina** [comment]
I won't be able to chair next week as I'm in london. Maybe start with a different slot?

**Comment by Trott** [comment]
As of today, all TSC members have updated the spreadsheet. I think we can start with this new schedule next week. @nodejs/tsc

**Comment by mhdawson** [comment]
ok, I'm going to update the calendar starting next week
