### ISSUE TITLE
Remove nodejs gitter

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#1328]
Hi, @nodejs/tsc. There is a nodejs gitter that has all the appearances of an officially-supported support channel, but we don't watch it, we don't moderate it, etc. etc.

I propose that we delete it, but that will require contacting Gitter HQ.

Before taking such action, I want to make sure there is TSC consensus. Can I get a 👍 for "+1", a 👀 for "no opinion", or a comment explaining why you think we should do it if you are "-1"? Thanks!

**Comment by Trott** [comment]
Here's the URL: https://gitter.im/nodejs/node

And here's a post from not too long ago....

![image](https://user-images.githubusercontent.com/718899/211937317-93bb220d-fc61-4b62-8c9c-46bac9ae7e06.png)

**Comment by ljharb** [comment]
fwiw I watch it, and have moderated it since long before (and after) I've been on the Moderation team.

**Comment by Trott** [comment]
> fwiw I watch it, and have moderated it since long before (and after) I've been on the Moderation team.

Yes, the "we" in my statements meant the TSC.

I think you're the only person who moderates/watches in there, so thank you for that.

Between having a bus factor of 1, the fact that most people probably didn't even know it existed until I opened this issue, and my general belief that we should have a small number of robust and well-defined official channels and not a wide variety of less-than-robust ones, I'm still very much a +1 on deleting it.

**Comment by joyeecheung** [comment]
+1, but this also reminds me...do we want to delete the `libera.chat` IRC channels from the documentation at this point?

**Comment by ljharb** [comment]
I'd hope not; that one's *very* active and well moderated.

**Comment by Trott** [comment]
Gitter room removed.
