### ISSUE TITLE
javascript try-block can't work properly 
try {
  let a = 24 = 2002;
  console.log("a is " , a)
} catch (e) {
  console.log(e);
  console.log(e.name);
  console.log(e.message);
  console.log(e.stack);
}


### ISSUE THREAD

**Issue by rohiTippe24** [nodejs/TSC#1329]
try {
  let a = 24 = 2002;
  console.log("a is " , a)
} catch (e) {
  console.log(e);
  console.log(e.name);
  console.log(e.message);
  console.log(e.stack);
}

javascript can't handle the try block in this code . without catching the catch block it throws an error

**Comment by ljharb** [comment]
That's because you can't assign to `24`. This repo isn't the place to be asking JS questions, though, so this should be closed.

**Comment by aduh95** [comment]
The JavaScript language is following the ECMAScript spec, which is authored by TC39, not the Node.js TSC. This is not the correct forum to discuss the limitations of the JS language. If you have a specific question, I suggest asking StackOverflow.

**Comment by nschonni** [comment]
Normally this would just get transferred over to nodejs/help for triage
