### ISSUE TITLE
Request to migrate Inclusivity Working Group responsibilities to the Node.js Foundation and TSC

### ISSUE THREAD

**Issue by nebrius** [nodejs/TSC#133]
After recent events and discussions, we feel that a working group is not the best structure for achieving many of the Inclusivity WG's goals. The Inclusivity WG requests that the TSC ask the Node.js Foundation to investigate transferring some or all of the Inclusivity WG's responsibilities to the Node.js Foundation and TSC.

## Reasoning for this change

The Inclusivity WG is tasked with improving the inclusivity and diversity of the Node.js project. To date, the Inclusivity WG has largely failed to make progress in achieving these goals. We think that the primary reasons the WG has failed to make progress are:

- Structural Problems
    - The WG is chartered by the TSC, and is more or less an extension of the TSC
    - Oversight/fairness was difficult to achieve correctly ("who watches the watchers")
    - Getting buy-in using the consensus model could be unnecessarily difficult on contentious topics.
- Lack of Resources
    - The WG was entirely made up of volunteers
    - Getting larger initiatives implemented proved to be impractical given the limited time and motivations of volunteers
- Fear (This is not a judgement on the validity of these fears)
    - Many people were afraid to move forward on initiatives, regardless of which "side" of the debate people were on.
    - This fear manifested in disengaging, actively pushing back against initiatives, and other ways.

## What is being requested

The Inclusivity WG is requesting that the TSC ask the Node.js Foundation to investigate migrating some or all of the responsibilities of the Inclusivity WG to more appropriate venues. The full list of responsibilities can be found in the [Inclusivity WG's charter](https://github.com/nodejs/inclusivity/#list-of-responsibilities).

Please note that this is a request for _investigation_ into transferring responsibilities. Most likely, we should transfer some responsibilities to the Node.js Foundation and  some to the TSC. It _may_ make sense to keep some responsibilities in the Inclusivity WG.

This request is intentionally light on details. There will likely be a lot of questions and concerns with this migration, and we think it is very important that we take our time to address these concerns and to do this right.

We realize there some contentious topics the Inclusivity WG has been involved in, and that there has been some unpleasant history involving the WG. For the sake of making progress, any discussion relating to this history should be considered off topic and derailing in this thread, which is against the Code of Conduct and may be subject to moderation.

**Comment by jasnell** [comment]
+1 on this, absolutely. I know that @hackygolucky has already been putting in a ton of work investigating what can be done at the Foundation level.

**Comment by hackygolucky** [comment]
+1, looking forward to creating a comprehensive approach that addresses needs at every level of the project.

**Comment by rvagg** [comment]
+1 to investigation, the tricky bits of course will be in the details.

Given the division of responsibility between the Technical Team and the Executive/Board, if there are going to be parts of this that require crossing those boundaries then we'll have to come up with wording that satisfies the goals here while preserving the independence which has been so important to the technical operation to date.

One concern I have is simply regarding the robustness of whatever new structures are put in place and ensuring that they don't simply rely on existing personalities but will serve us well into the future as we have turnover in personnel. While in theory the Executive will have the resources to be able to do this in a professional manner and engage professional expertise, the possibility of future capture by narrow interest groups should not be ignored and I'd like to see any proposal here demonstrate how this might be mitigated. I imagine one way to achieve this would be via accountability mechanisms of some kind.

**Comment by hackygolucky** [comment]
Totally agree here @rvagg. Accountability is something that will be looked
into on many fronts in order to make this a change that is sustainable and
effective.

**Comment by rvagg** [comment]
Moved this to https://docs.google.com/document/d/1rl4ZBFiTzUBy81eGz_srcJj2wSaTOES95qbC4w7I8wM and edited a bit so it can be done in a form that can be presented to the Board. The meeting is in ~6 hours from now and I'll be asleep but am passing on the link to the Board prior to the meeting. @jasnell & @nebrius you have edit access if you see anything that could be improved.

**Comment by rvagg** [comment]
This has been shipped and approved by the Board, it now moves into the executive's hands to come up with a proposal, they will keep various stakeholders in the loop in order to ensure broadly acceptable outcomes. We'll likely end up with a proposal of some kind of the TSC to consider as well as one for the Board to consider for the rest of the org.

**Comment by Trott** [comment]
I imagine at some point, the TSC will need to formally revoke the charter of the Inclusivity WG, although I imagine there's no rush on that until it has an alternative Inclusivity proposal to consider...

**Comment by mikeal** [comment]
BTW, request made it to the board and was passed, the foundation is now working on some proposals for the next meeting.
