### ISSUE TITLE
Moving away from Team Discussions

### ISSUE THREAD

**Issue by anonrig** [nodejs/TSC#1340]
**I don't know if this is the correct place to write this, but if not, please move this issue to the correct repository.**

Today, Github announced that they are deprecating team discussions, this means that we'll no longer have the private area to nominate each other. There is a button called `Transfer` in https://github.com/orgs/nodejs/teams/collaborators page that I think somebody who is eager to take risks should press, and I thought what about the TSC team?

```
Team Discussions will be deprecated on May 8th, 2023. We encourage you to transfer these posts to GitHub Discussions. Read more about this deprecation in our [changelog](https://github.co/AAjbqar).
Transfer
```

**Comment by mhdawson** [comment]
@anonrig do you know if the transfer will change anything with respect to public visibility. ie more/less public than before?

**Comment by anonrig** [comment]
I don't know. I couldn't find any information about this @mhdawson

**Comment by cjihrig** [comment]
Maybe @MylesBorins knows, or could find out?

**Comment by jasnell** [comment]
We might just look at creating a private repo just for collaborator discussions

**Comment by MylesBorins** [comment]
Internally we've moved to discussions for this.

So a private repo with discussions enabled seems like the best bet for this. It's also a better interface tbh

https://docs.github.com/en/organizations/managing-organization-settings/enabling-or-disabling-github-discussions-for-an-organization

**Comment by mcollina** [comment]
I've added it to the tsc-agenda for visibility.

**Comment by targos** [comment]
I think we should create a private repository called `nodejs/collaborators`, disable everything we can on it except discussions (issues, wiki), and transfer the team discussions to it.

This is what shows up when you click on "Transfer":

![CleanShot 2023-02-14 at 11 50 41](https://user-images.githubusercontent.com/2352663/218714411-60db1ff3-9af5-4da3-93e2-d3ba7f4768a7.png)

**Comment by mhdawson** [comment]
We discussed in TSC meeting today, the 8 people we had in the meeting were ok with the suggestion.

**Comment by mhdawson** [comment]
Mentioned in TSC meeting today, been open 2 weeks, everbody at the meeting agreed @targos should move forward.

**Comment by targos** [comment]
Done: https://github.com/nodejs/collaborators/discussions

I created two initial categories:
- Announcements for PSA like CI lockdowns
- Collaborator nominations
GitHub migrated all previous discussions to the "Team Posts" category.

![CleanShot 2023-03-16 at 14 34 43](https://user-images.githubusercontent.com/2352663/225633520-9c3ab458-7982-42e5-9e89-794cdfe18042.png)
