### ISSUE TITLE
Node.js Truck Factor

### ISSUE THREAD

**Issue by 2mferreira** [nodejs/TSC#136]
Dear **Node.js** contributors,

I am Master's student investigating the importance of the idea of truck factors in Software Engineering.

As you know, [truck factor](https://en.wikipedia.org/wiki/Bus_factor) (aka bus factor) is defined as “the number of people on your team who have to be hit by a truck before the project is in serious trouble”.  By "serious trouble", we mean that it will very difficult to maintain the project (e.g., bugs will take more time to be fixed, new features will be delayed etc).

I would appreciate your contribution by answering two questions:

1) According to your experience, what number best represents the truck factor of **Node.js**?

2) Who are the developers responsible for this truck factor (i.e., the name of the developers who are responsible for the TF result answered in the previous question)?

Mívian Ferreira
Master's Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by cjihrig** [comment]
I'm going to close this, as there is nothing actionable from the TSC here. Anyone can feel free to chime in here though.

**Comment by williamkapke** [comment]
Hm. I don't agree with closing it without addressing the visitor directly. I don't think it portray us positively.

So, @2mferreira - My thought is that we probably wouldn't want to put out a hit list of people (heh... no.. really not funny). Having met many of the contributors, my observation is that many would not want to be listed out like this.

Node has MANY contributors. I cannot think of a number to offer you- just to say it would be significant. I feel it is very resilient to the loss of a member. Some folks along the way have moved on and Node has continued to progress forward.

I hope your investigation with all the other projects you've contacted yields some interesting data. Best of luck!

**Comment by addaleax** [comment]
I’m not sure the question is applicable to Node.js in the way in which it is asked – there are quite a few subareas of the codebase, each with its own TF and overlapping with other areas, and with different levels of criticality.

> Node has MANY contributors. I cannot think of a number to offer you- just to say it would be significant. I feel it is very resilient to the loss of a member. Some folks along the way have moved on and Node has continued to progress forward.

:+1:

(I think Colin closed this because this is not really the ideal place to ask this kind of question?)

**Comment by cjihrig** [comment]
> (I think Colin closed this because this is not really the ideal place to ask this kind of question?)

Yes, sorry if that came across wrong.
