### ISSUE TITLE
Limits on sharing content on social media based on benefits to a corporation

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#1362]
The TSC delegated management of our social media to the foundation. Our old tweet repo had this guideline:

> We do not amplify or share content that could unduly promote or benefit one corporation that does work in the space of Node.js over another.

The Twitter handle seems to be deviating from that principle lately, at least in one case (https://twitter.com/nodejs/status/1156624318790623232). 

I think @nodejs/tsc should choose one of the following regarding that guideline and communicate that decision to the foundation:

1. Reaffirm the guideline.
2. Revoke the guideline.
3. Defer to the foundation. They can choose to adopt that guideline or not and the TSC does not have a formal opinion on it one way or the other.

I personally think 3 is the way to go. (If not 3, then 1. 2 is my last choice.) I'm happy to give the foundation as much freedom as we can to manage the Twitter handle responsibly. We can always pull it back if we are unhappy with anything at some point.

Can some other @nodejs/tsc members chime in so we can see if we have consensus?

**Comment by bnb** [comment]
Some context: when at NodeSource, I asked Zibby Keaton to share some of our content.

She shared that the foundation explicitly didn't share content from member companies for anti-competitive reasons - if they shared something from Company A, and Company B competed with Company A, it could cause issues. The logical conclusion of that is sharing content from _both_. Multiply that by companies who are members, and the signal vs. noise ratio from the Node.js account dramatically goes up. And that doesn't even get into external companies. 

A simpler to implement, and overall fairer, approach is to avoid that problem entirely by simply not sharing content from corporate sites or that points to/advertises corporate tools.

My personal opinion - as someone whose career literally started _here_ doing social media and content, which got me a job in the industry at the intersection of engineering, marketing, and communications _including_ running and advising on multiple large-scale project and corporate social media accounts - is that whatever policy is chosen needs to be fair and equitable to the ecosystem.

If we're letting everything through or letting the Foundation choose, that information shouldn't be held by a few insiders who are a part of an in circle. That's an excellent way to only promote a few people who are already in a privileged position. Further, the decision criteria shouldn't be arbitrary - they should be well documented and achievable. Again, without that it would be extremely easy for bias towards a few to be the default.

**Comment by Trott** [comment]
When I opened this issue, I made the assumption that the Snyk tweet you (@bnb) shared as an example was recent, but it was from 2019.  I don't see any recent tweets promoting corporate content. So I don't think anything has changed. Especially if this is a foundation guideline, I would expect it to continue to be enforced. I'm not sure there's anything here for the TSC to do after all (although we *could* choose to be explicit here, certainly).

**Comment by bnb** [comment]
Just surfaced in my timeline, and I too didn't check the timestamp before sharing in the Slack with the question about sharing policies - didn't expect a question would result in a TSC issue proposing changes, normally I'd ask more people about something like that before proposing something like this 😅

**Comment by mcollina** [comment]
I don't think there is anything to do on a tweet of 2019, minus removing it. I don't remember who was handling in 2019 and I think everything is respecting the guideline right now.

**Comment by Trott** [comment]
I'm going to close this, but if someone thinks it warrants further discussion or a decision, feel free to re-open. Thanks.
