### ISSUE TITLE
Nominating @MoLow to the TSC

### ISSUE THREAD

**Issue by cjihrig** [nodejs/TSC#1364]
I would like to nominate @MoLow to the @nodejs/tsc.

Moshe authored Node's watch mode, has made significant contributions to the test runner in core and on npm, and has recently joined the Build WG.

- [@MoLow's nomination as a collaborator](https://github.com/nodejs/collaborators/discussions/147), which includes many links to his activity around the org.
- I have raised this to the TSC in private and there were no objections.
- I have contacted @MoLow in private and verified interest.

**Comment by mhdawson** [comment]
+1 from me

**Comment by cjihrig** [comment]
This has been open for a week with plenty of positive reactions and I have not received any objections publicly or privately. I think we can move forward with this.

**Comment by cjihrig** [comment]
(Technically this is on the TSC agenda for this week. We did briefly discuss it last week though and we may be cancelling the meeting tomorrow.)

**Comment by cjihrig** [comment]
## Onboarding of voting members

- [x] Confirm that the new member has read, understands, and agrees to uphold the
  [Code of Conduct](https://github.com/nodejs/admin/blob/main/CODE_OF_CONDUCT.md).
- [ ] Add the new member to the `@nodejs/tsc` and `@nodejs/security-tsc` teams.
- [ ] Change the new member's role in the GitHub `nodejs` organization to `Owner`.
- [ ] Add them to the `@nodejs-private` org and with an `Owner` role.
- [ ] Add them to the `@nodejs-private/security-tsc` team.
- [ ] Add them to the `@pkgjs` org and with an `Owner` role.
- [ ] Add them to the `@pkgjs/node-tsc` team.
- [ ] Invite them to the HackerOne [Node.js team](https://hackerone.com/nodejs/team_members).
  Have them turn on two-factor authentication after they have joined.
- [ ] Add them to the `tsc` and `crypto-export` mailing lists.
- [ ] Add them to the [nodejs-tsc](https://groups.google.com/g/nodejs-tsc) Google Group as owners, so they receive Calendar invites for TSC meetings.
- [x] Update the `@nodejs/node` repository README to reflect membership in the TSC.
- [ ] Update <https://github.com/nodejs/create-node-meeting-artifacts/blob/main/templates/invited_tsc> to reflect membership in the TSC.
- [ ] Ask them what is their handle on OpenJS Slack – and ask them to create one if they haven't one already. Add that handle to the `#nodejs-tsc` channel.
