### ISSUE TITLE
Update meeting times

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#1367]
New meeting times. All times are Wednesday except for the for the UTC 19:00 meeting in India Standard Time and China Standard Time which are early morning Thursday.

* UTC: 13:00 15:00 19:00
* British Summer Time: 14:00 16:00 20:00
* Central European Summer Time: 15:00 17:00 21:00
* India Standard Time: 18:30 20:30 00:30 
* China Standard Time: 21:00 23:00 03:00
* Pacific Daylight Time: 06:00 08:00 12:00
* Eastern Daylight Time: 09:00 11:00 15:00
* Brasilia Standard Time: 10:00 12:00 16:00

@nodejs/tsc

**Comment by Trott** [comment]
We have a majority of the TSC voting members (me + 10 👍  = 11 TSC voting members out of 20) endorsing this. @mhdawson Can you make it happen?

**Comment by mhdawson** [comment]
@Trott done, let me know if I somehow translated the times wrong.
