### ISSUE TITLE
Live TSC/CTC meetings in Austin?

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#137]
The Dec 1st TSC meeting falls on day 1 of the Collaboration summit. I think it would be neato if the meeting could be done live! ... I mean, more than the usual YouTube Live; Like "live studio audience!"
<sup>Obviously no private business.
...and obviously, this requires at least some TSC members be present and willing.</sup>

The CTC meeting falls on the last day of the conference (Nov 31st)- which might be really cool for attendees to see.
<sup>Same caveats</sup>

**Comment by nebrius** [comment]
If we can get enough people this sounds interesting! I'll be there, fwiw.

**Comment by mhdawson** [comment]
I'll be there and it sounds good to me as long as it does not overlap with anything else.

**Comment by evanlucas** [comment]
I'll be there. Sounds good to me too!

**Comment by mikeal** [comment]
What kind of technology do we need?

**Comment by williamkapke** [comment]
@mikeal The concept is just so attendees could see the magic and make them feel like they were a part of it. Really, it is marketing the development/contribution side of Node. If the Foundation finds that valuable (aka worth it?), then I'd suggest asking the AV crew if they could set something up. But, that costs money... probably too much money.

I always thought it was cool how Microsoft did live booths like this at their conferences:
https://channel9.msdn.com/Events/Build/2016/C906


But, as I said- members would need to be cool with being live... which I assumed was going to be a problem. This thread has a surprising amount of positive reaction that I didn't respect. That's really cool.

So- if you're not so positive on the idea.. speak up! It's ok!

Also: It sounds like the CTC meeting might get canceled that week.

**Comment by joshgav** [comment]
To offer a counter-perspective, we've always emphasized the centrality of discussion in GitHub as our main decision-making process and downplayed the importance of "meetings." Making a big deal about the weekly meeting might imply the opposite.

But the desire to interact with CTC members in particular I think is there, what other ways might we facilitate that? It's called Node _Interactive_ after all :)

Idea 💡 : An interactive session or several to demo common activities in core with actual examples from the past few months, e.g.:

* walkthrough of putting together a release
* trace the evolution of a somewhat complex PR - comments and fixes, CI, CTC discussion, merge, rollback and more fixes, semver considerations, cut into release, etc.
* process of adding a significant new features, like:
  * async_hooks
  * HTTP/2
  * V8 inspector

**Comment by williamkapke** [comment]
Ping... if it is going to happen, we would need to start planning since NI Austin is approaching fast. It seems some are in favor- and other are not.

Should we add an agenda label?

/cc @hackygolucky

**Comment by mikeal** [comment]
So, the logistics of doing this **during** the conference content is too much. However, we could do this during the Collaboration Summit where the setup is more informal and there are less people.

**Comment by williamkapke** [comment]
I ran out of time and wasn't able to arrange something to make this possible :( sry

I think the CTC meeting was canceled and I suspect the TSC meeting may only have a private session with so many people here in-person in Austin.

Maybe next time ;)
