### ISSUE TITLE
Adding the OpenJS Foundation staff as a billing manager for nodejs-private

### ISSUE THREAD

**Issue by mcollina** [nodejs/TSC#1376]
In https://github.com/openjs-foundation/cross-project-council/issues/1009#issuecomment-1496227217, @bensternthal offered to set up a virtual credit card to pay for GitHub Actions minutes in nodejs-private.

I think this would allow us to have continuity of service for the security releases.

On a similar note, @abbycabs has offered to bump up nodejs-private up into the waitlist to the large runners for private builds.

Should we move forward?

**Comment by richardlau** [comment]
I'm +1 but I have no idea what our budget ask would need to be -- the amount of minutes we'd need is wholly dependent on how often we push to nodejs-private -- every commit triggers the workflows (although subsequent pushes to the same branch does cancel any inflight/queued runs).

**Comment by mcollina** [comment]
We'll start with 100$ and adjust

**Comment by targos** [comment]
Can't we ask GitHub for the same free coupon that we have on the `nodejs` org?

**Comment by mcollina** [comment]
Unfortunately, that's not available for private repositories.
We already have the maximum allotment they give away for free: we are burning through them too quickly.

**Comment by targos** [comment]
Another option is to disable the most costly GitHub actions on the private repo (test-asan for example). TBH I'm not sure they are really useful to prepare security releases.

I have no objections to adding some money on the account, though. We'll see how much is needed in practice.

**Comment by aduh95** [comment]
I agree that disabling workflows seems like a more reasonable approach. We can use https://github.com/pricing/calculator to estimate how much money would be actually needed.

Here's what I get if I calculate for a daily run of Coverage Linux + Coverage Windows + test macOS: 
![screenshot of the GitHub Calculator showing a bill of $339.12](https://user-images.githubusercontent.com/14309773/233359811-b1f3cc4f-baae-425d-839d-ebc641479d5f.png)

**Comment by abbycabs** [comment]
> Can't we ask GitHub for the same free coupon that we have on the `nodejs` org?

`nodejs-private` already has the highest level of coupon we offer (free [Enterprise plan](https://docs.github.com/en/get-started/learning-about-github/githubs-products#github-enterprise)) , same as `nodejs`. This includes 50,000 private minutes / month, which doesn't seem to be sufficient. 

I definitely recommend optimizing your actions usage if you can!

There are a couple larger runners betas you can join. They have separate pricing than the standard runners. These are all more powerful machines, so hopefully you would need fewer minutes to complete the build!

* Linux larger runners: https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners
* MacOS XL: https://github.blog/2023-03-01-github-actions-introducing-faster-github-hosted-x64-macos-runners/

Try trimming your actions first, but if you'd like to join either beta let me know when you're on the waitlist & I can flag you in.

**Comment by tniessen** [comment]
Related to reducing build times: https://github.com/nodejs/build/issues/2949 (I was going to work on that but didn't find enough time yet)

**Comment by mcollina** [comment]
I've disabled both Windows and Mac OS X workflows in nodejs-private. Let's see how it goes and reasses.

**Comment by mcollina** [comment]
DUring the meeting we agreed to add the billing manager with a small budget, ideally 100$. @bensternthal what are the next steps?

**Comment by bensternthal** [comment]
Let me seek budget approval for this monthly spend. Once I have approval I can detail next steps here.

**Comment by rginn** [comment]
Approved!

**Comment by bensternthal** [comment]
@mcollina can you add me as a billing manager on the right project?

**Comment by tniessen** [comment]
@bensternthal Done.

**Comment by bensternthal** [comment]
Alrighty, a virtual credit card with a $100 monthly limit has been added.

**Comment by mcollina** [comment]
Awesome, thanks!
