### ISSUE TITLE
Node.js TSC Charter defines how the foundation operates

### ISSUE THREAD

**Issue by Relequestual** [nodejs/TSC#1379]
Hello! In the process of JSON Schema forming its charter, we ran into feedback which said the JSON Schema draft charter was trying to define what the OpenJS Foundation operates. This was not our intent, and we were rather stating facts, we thought.

I pointed out, the JSON Schema draft charter was mostly copying the Node.js TSC charter!

> The Node.js project is part of the OpenJS Foundation which operates transparently, openly, collaboratively, and ethically. Project proposals, timelines, and status must not merely be open, but also easily visible to outsiders. - https://github.com/nodejs/TSC/blob/HEAD/TSC-Charter.md#section-1-guiding-principle

Here's a link to the feedback: https://github.com/json-schema-org/community/pull/325#discussion_r1172383625

> The JSON Schema charter should focus on the project itself and not accidentally start defining how the foundation operates. - @tobie 

I'm guessing this would require just a small change, although I don't know if a more holistic "This isn't a foundation" review might be more appropriate or already underway. So, although I won't be submitting a PR, here's the issue being logged/relayed. 🙏

**Comment by tobie** [comment]
FWIW, this is preamble text and I don't think it is worth spending anytime fixing it (unless as part of a bigger change).

**Comment by Relequestual** [comment]
I somewhat agree, however the CPC template points to this as an example. If it includes stuff that others shouldn't, that's a problem IMHO.

**Comment by tobie** [comment]
> I somewhat agree, however the CPC template points to this as an example. If it includes stuff that others shouldn't, that's a problem IMHO.

I suggest fixing this with the CPC and closing here, then.

**Comment by Relequestual** [comment]
> > I somewhat agree, however the CPC template points to this as an example. If it includes stuff that others shouldn't, that's a problem IMHO.
> 
> I suggest fixing this with the CPC and closing here, then.

I've opened an [issue](https://github.com/openjs-foundation/cross-project-council/issues/1069), but I'm **not** in favour of closing this one in favour.

It either IS a problem, or it isn't. @tobie you have indicated you believe it IS a problem.
Maybe this issue can be collected as part of some form of regular charter review schedule/project by the Node.js team.

**Comment by RaisinTen** [comment]
IIUC, the ask here is that if anyone makes a change to the [TSC-Charter.md](https://github.com/nodejs/TSC/blob/main/TSC-Charter.md) file in this repo, we should remember to update the text in https://github.com/nodejs/TSC/blob/918a9c9502a94e0ef017eeaceb0f54fc6beeb2ff/TSC-Charter.md?plain=1#L5-L6
with:
```md
The Node.js project is part of the OpenJS Foundation.
```
right?
