### ISSUE TITLE
What License(s) needed?

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#138]
Moving from https://github.com/nodejs/TSC/issues/135#issuecomment-245455843

When a project is brought in to the Node.js GitHub org, what license is desired/required?

**Comment by jasnell** [comment]
MIT is our default license but I don't believe we require that specifically.

**Comment by jasnell** [comment]
See: https://github.com/nodejs/TSC/issues/139

**Comment by williamkapke** [comment]
Closing in favor of #139
