### ISSUE TITLE
2023 TSC Elections 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1382]
May is the month for TSC Elections.

Last year we elected a **Chair** and a **Vice-chair** and I assume we'd do the same this year.

The proposed schedule is:

May 8 - Call for nominations
May 15 - Open Balloting
May 22 - Announce Results
May 22-31- Handover

This gives us a bit of time to discuss if there are any changes in the election process that we'd like to make.  Please chime in on the issue as to whether this sounds good or you have alternate suggestions.

**Comment by jasnell** [comment]
SGTM

**Comment by BridgeAR** [comment]
SGTM

**Comment by mhdawson** [comment]
I'll self-nominate for Chair.

**Comment by mcollina** [comment]
I self-nominate for Vice-Chair.
