### ISSUE TITLE
Nominating @ruyadorno to TSC

### ISSUE THREAD

**Issue by danielleadams** [nodejs/TSC#1388]
I'd like to nominate @ruyadorno to the TSC. He's an active member of the Release WG and has been running the monthly meetings. He has also helped release major Node versions, and he has been a liaison between the Node release team and the NPM team.

Here are his GitHub contributions around the org: https://github.com/search?q=author%3Aruyadorno+org%3Anodejs&type=pullrequests.

I've spoken with Ruy, and he is interested in moving forward with his nomination.

**Comment by RafaelGSS** [comment]
+1

**Comment by mhdawson** [comment]
+1 from me

**Comment by mhdawson** [comment]
There have been no objections and may TSC +1s and its been open for over a week. I think we can conclude there is consensus.

Welcome @ruyadorno. I'll start the onboarding process tomorrow when I have time.

**Comment by mhdawson** [comment]
- [ ] Confirm that the new member has read, understands, and agrees to uphold the [Code of Conduct](https://github.com/nodejs/admin/blob/main/CODE_OF_CONDUCT.md).
Add the new member to the @nodejs/tsc and @nodejs/security-tsc teams.
Change the new member's role in the GitHub nodejs organization to Owner.
Add them to the @nodejs-private org and with an Owner role.
Add them to the @nodejs-private/security-tsc team.
Add them to the @pkgjs org and with an Owner role.
Add them to the @pkgjs/node-tsc team.
Invite them to the HackerOne [Node.js team](https://hackerone.com/nodejs/team_members). Have them turn on two-factor authentication after they have joined.
Add them to the tsc and crypto-export mailing lists.
Add them to the [nodejs-tsc](https://groups.google.com/g/nodejs-tsc) Google Group as owners, so they receive Calendar invites for TSC meetings.
Update the @nodejs/node repository README to reflect membership in the TSC.
Update https://github.com/nodejs/create-node-meeting-artifacts/blob/main/templates/invited_tsc to reflect membership in the TSC.
Inform them of the TSC meeting password.
Ask them what is their handle on OpenJS Slack – and ask them to create one if they haven't one already. Add that handle to the #nodejs-tsc channel.

**Comment by mhdawson** [comment]
Onboarding checklist complete. Have setup time with @ruyadorno on Monday to chat and answer any questions about being a TSC member. 

Will just leave this open until all the related PRs have landed.
