### ISSUE TITLE
Switching the default license from MIT to Apache v2

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#139]
@nodejs/tsc: Currently, the default license for new Node.js Foundation projects is MIT. Due to a number of factors, including patent protection, the recommendation is to change the default license for _new_ projects to the Apache v2 license.

**Comment by addaleax** [comment]
I’m not sure, but is the question of whether code from another project might be pulled into Node core or one of the other MIT-licensed projects here relevant? Like, afaik, code licensed under Apache v2 wouldn’t be eligible for inclusion in MIT-licensed code.

**Comment by jasnell** [comment]
Relevant section from Foundation bylaws: https://nodejs.org/static/documents/node-foundation-by-laws.pdf, Section 2.15

**Comment by jasnell** [comment]
We'd need a lawyer to verify, but I do believe Apache v2 and MIT are compatible. At the very least, I've never had a lawyer balk at Apache v2 code and MIT code being used together.

The question is primarily about new projects either coming into to foundation from outside (that is, we'd ask them to change the license if possible), or new projects emerging within the foundation that currently have no license.

**Comment by trevnorris** [comment]
But node won't be required to switch? Not against it, but seems frivolous if only a tiny subset of projects are different.

**Comment by jasnell** [comment]
Eventually it's likely that Node.js will need to switch. I believe the Board is still working through the details on that because it would definitely be non-trivial.

**Comment by mikeal** [comment]
Changing the license for existing code is quite a process if there are a lot of contributors. We *may* do that for the project but that's not what this thread is about, this is just about *new* repositories defaulting to a different license.

**Comment by mikeal** [comment]
Apache v2 and MIT are "compatible" licenses but it's important to understand what that means. It **does not** mean that you can just re-license code from license to another without the consent of the authors. All "compatible" means is that you can use MIT and Apache v2 code together and that code written in one does not violate the other's license.

**Comment by joshgav** [comment]
@jasnell 

> the recommendation is to change the default license

Could you clarify who this recommendation is from? Thanks!

I am not a lawyer of course, but it seems Apache will better protect our users from patent trolls but could also make it harder for orgs with a lot of patents to contribute, since they'd need to do more careful patent review. Perhaps a reasonable tradeoff, but a tradeoff nonetheless that we should keep in mind.

**Comment by williamkapke** [comment]
I heard this was, indeed, brought to the board at their meeting yesterday. The meeting was not broadcast list this time unfortunately so I don't know the details. Hopefully @rvagg or maybe @mikeal can fill us in.

**Comment by rvagg** [comment]
Handed over to the Legal Committee to come back with guidance. The board isn't in a position to give guidance without legal backing (i.e. the board members are unwilling to take responsibility for such a recommendation—which is perfectly reasonable). Will have to wait patiently to hear back.

**Comment by jasnell** [comment]
Closing due to lack of forward progress on this. We can revisit this later if/when the legal committee is able to get back to us.
