### ISSUE TITLE
nodei.co EOL strategy needed

### ISSUE THREAD

**Issue by rvagg** [nodejs/TSC#1393]
https://nodei.co serves npm package badges for READMEs. It used to be extremely popular, but not so much now because I haven't given it much love. It goes down pretty regularly, the nice download counts and histogram badges stopped working years ago when npm changed their API and I didn't keep up. HiDPI never quite got support (there's svg support that I never got _quite_ right).

Here's the problem though: I don't want to manage it anymore, I pay for the domain, and keep the server up (mostly), but it's overhead I don't really want. Unfortunately, these badges are on thousands (possibly millions?) of current and historical READMEs, all of which will render on both GitHub and npm—even if I somehow convinced everyone to remove it today, the historical versions don't go away. So, anyone picking up the domain when I drop it gets a pretty decent audience to serve whatever will render with markdown image tags (and btw, usage isn't just limited to READMEs and markdown, they're _everywhere_).

I don't want to care about this problem, but I also don't want to be responsible for the fallout, so I'm a little stuck. A similar recent attempt of mine to disentangle myself a tiny bit from the ecosystem resulted in an expired resource takeover attack: https://github.com/justmoon/node-bignum/security/advisories/GHSA-7cgc-fjv4-52x6

I've approached npm/github/microsoft but there's no capacity to take on something like that.

I've had a couple of offers from interested individuals in taking it over, which would be great, but I without knowing the person or being able to vet them in some way. This may be a better option than letting it expire, but not much better I fear, and the person taking it also bears the weight of it.

The remaining option I can think of is letting the OpenJS Foundation take the domain, and either park it, or put it in to service—perhaps letting some of those interested parties take over maintaining and improving the site (likely rewriting it, the code is all on my github btw), but with the domain ultimately in Foundation hands lest something goes awry. This is probably up to the TSC.

Next domain renewal is due in mid July.

**Comment by mcollina** [comment]
A couple of questions:

1. is there just one server? will you transfer that too or it would be up to the receiver to re-deploy the code?
2. can you link the code?

Unless somebody would volunteer to run the server, my 2 cents is that asking the foundation to host the domain would allow a graceful sunsetting. Everything would break, but there would be no hostile takeover.

**Comment by rvagg** [comment]
3 separate mini services running on a single server:

* https://github.com/rvagg/nodei.co (www)
* https://github.com/rvagg/nodei.co-pkginfo-api (talk to npm for packages)
* https://github.com/rvagg/nodei.co-npm-dl-api (no longer running, download api not working)

Not stateful, the code can be deployed fresh on a new host and it should just work. Not a high workload since GitHub put CDN rewriting in front of all image fetches from READMEs. The only catch might be an ancient node-canvas build that may need a custom addon compile transferred but I could tar that all up.

Server can't be transferred, but I could rsync the existing installation somewhere else and give someone pointers. It's just a bit brittle, I never got around to spending much time making this smooth and stable. Logs fill up too quick with the download API endpoint busted so I have a symlink to /dev/null at the moment to deal with that.

**Comment by mhdawson** [comment]
>Unless somebody would volunteer to run the server, my 2 cents is that asking the foundation to host the domain would allow a graceful sunsetting. Everything would break, but there would be no hostile takeover.

+1 from me as well. Asking the foundation to own the domain handles the concern over a hostile takeover, and probably makes sense even if somebody shows interest in keeping it going.

**Comment by ljharb** [comment]
It definitely seems viable for the foundation to also continue running it, at least for historical images if not for new ones.

**Comment by Trott** [comment]
I think it makes sense for the Foundation to take it on as a proactive measure to protect the Node.js ecosystem, even if all they do is return a 404 for every request.

@rginn Is this the kind of thing that would be brought to you, the CPC, the board, someone else....?

**Comment by rginn** [comment]
The CPC is responsible for approving new projects. Once it clears that process, our foundation team can work on its transition. 

@rvagg, you've covered a lot of the "New Project Application" https://github.com/openjs-foundation/cross-project-council/blob/main/NEW_PROJECT_APPLICATION.md in this issue. Can you please take a look and email the info to @joesepi and me and we'll get it in front of the CPC?

Cc: @bensternthal

**Comment by mhdawson** [comment]
@rginn I'm not quite following the request to apply as a new project. In the past we've not considered projects that don't come with maintainers that are willing to actively support the project going forward.

I think the main ask is that the foundation take over the domain name, pay for it each year and park it in some way. I don't think we need all of the in a "New Project Application" for that. For example, none of the questions about governance, etc. make any sense in this context.

We may want a new type of application which would be something like take over any assets that involve takeover risks.

**Comment by ljharb** [comment]
This issue seems to cover two parts (@rvagg please correct me if i'm mischaracterizing):
1. the domain name, ie @mhdawson's prior comment, which i agree shouldn't need a new project application - it's just donating IP to the Foundation.
1. the project itself, which would need a new project application, and typically would need to come with maintainers.

@rvagg i'd be happy to hop on a call with you to go over the infra and codebase - if it seems like something i can take on, i'd be happy to help you maintain it, which should serve to ensure the project is maintained such that it can qualify for OpenJS membership.

**Comment by rvagg** [comment]
> it's just donating IP to the Foundation

It's also a liability since the domain needs constant renewal, although that's only in the range of ~$30USD (tho I bet the LF has access to sweet bulk deals). Someone has to agree to take that on. Maybe @rginn can squeeze that out of a discretionary funds bucket?

Re actually running it—@ljharb I'd be happy to help transition maintenance of current infra but I need to move it off infra I own unfortunately. I could stick it onto one of the existing Build WG resources, but there's not an obvious fit for pairing with an existing service (unofficial-builds may be the closest conceptually), and Build would have to want yet another liability to remember about (although we do have an [interesting list of potentially forgotten liabilities that may need cleaning up](https://github.com/nodejs/build/blob/main/ansible/inventory.yml#L12-L32)). There is a grey area within Build already, where miscellaneous items don't clearly fall within the wider group's responsibilities and they have much lower expected SOAs, like nodejs/unofficial-builds which is mostly me still, and nodejs/snap which is still exclusively me (even though it was another item I was trying to extract myself from by moving it into Build!). This could potentially fit in that space, but what wouldn't be ideal is to have a repo/project within the nodejs scope of responsibility that has people trying to fix, or report problems with, and nobody even watching or responding.

**Comment by ljharb** [comment]
nvm came with a domain name, and LF IT took it over and renews it for me, I no longer have to manage it, so that seems easy.

I'm sure I could help migrate the infra once I understood the current stuff :-)

**Comment by mhdawson** [comment]
My personal take it's not something the Node.js build WG should take on as another ongoing maintainance effort.

I could see the Foundation taking it on as it could even make sense to expand what is shown in the badge in support of the efforts to help packages implement best practices, but that would require a longer term commitment of resources to keep it going.

Either way the Foundation helping by taking on/renewing the domain name for the forseable future to project the JavaScript ecosystem makse sense.

**Comment by rvagg** [comment]
OK, so the most pressing thing is domain ownership; it's not super urgent that I offload the server resources, it can keep humming for a while. What would be the next steps for the domain bit @rginn, both in terms of getting sign-off that it's something the foundation wants, and making the actual transfer?

**Comment by mhdawson** [comment]
I've sent an email to the CPC requesting concensus on:

The Foundation
1) take ownership of the nodei.co domain name and pay to renew this domain until it no longer makes sense (which will likely be a long time)
2) configure the DNS entries for nodei.co to Rod's infrastructure for as long as Rod keeps it working. 
3) consider updating the DNS entries to point to new/ported infrastructure if a trusted entity/group (trusted in the opinion of the CPC) sets up a new/ported infrastructure and commits to maintain it.
4) In absence of 2) or 3) configure the DNS entries such that all http queries to nodei.co will return a 404.

**Comment by mhdawson** [comment]
There are 8 +1s from CPC members and no objections so I believe concensus has been reached.

@rginn, how do we move forward?

**Comment by bensternthal** [comment]
@mhdawson this is something I can handle from here. 

@rvagg I will reach out to you over email to discuss DNS transfer codes.

**Comment by mhdawson** [comment]
@bensternthal I assume you'll let us know when its complete and we can close this issue.

**Comment by bensternthal** [comment]
The domain has been transferred to LF.

**Comment by mhdawson** [comment]
@bensternthal, @rvagg thanks for the work on this.  Are there more steps or should we close the isue now?

**Comment by ljharb** [comment]
@rvagg whether the issue remains open or not, I’d love to pair with you some time and learn how to help manage the codebase and infra.

**Comment by rvagg** [comment]
I guess the critical piece is done. The rest is just figuring out a transition strategy for the hosting to get off a personal server of mine.
