### ISSUE TITLE
Rebranding OpenJS Collaborator Summits as Node.js Collaborator Summits

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1399]
The OpenJS Collaborator Summits were an expansion of the Node.js Collaborators Summits that the project has held over many years.

The reality turns out to be that most of the sessions and partipants at recent Collaborator Summits have been from the Node.js project and Ecosystem.  

The suggestion from the program committee is that going forward that the summits be branded as Node.js Collaborator Summits. This will help clarify for attendees that most of the discussion/content will focus on Node.js and give us flexibility in how when/they are scheduled since they will not be branded as OpenJS.  I've also confired that it will not affect the level of support we get from the Foundation in terms of running the events.

I'm opening this issue as I was asked to get feedback from the TSC in terms of this proposal.  I personally think it makes a lot of sense and there were no concerns from the TSC member in the last TSC meeting but it was a small subset (~7). 

@nodejs/tsc any thoughts/concerns about doing this?

**Comment by mcollina** [comment]
Would the organization of the summit move back to the Node.js project then?

**Comment by rginn** [comment]
Note that this is for the OpenJS Collab Summit hosted adjacent to OpenJS World. 

Other projects and Collab Spaces continue to host their own with our support, such as the upcoming Open Visualization Collaborator Summit https://www.eventbrite.com/e/2023-open-visualization-collaborator-summit-tickets-641499340797?utm_content=251952017&utm_medium=social&utm_source=twitter&hss_channel=tw-14538601

The previous OpenJS Collab Summits have always been organized by the community with our foundation and LF event team support. https://github.com/openjs-foundation/summit @ovflowd is leading planning again for the summit at OpenJS World Europe.

**Comment by mhdawson** [comment]
> Would the organization of the summit move back to the Node.js project then?

**Comment by mhdawson** [comment]
I don't see any concerns raised and a number of thumbs up. @rginn I think we can confirm that the feedback from the TSC is positive on the suggestion to rebrand.  Let us know if you need anything more from the TSC, otherwise I'll close this in a few days.

**Comment by ovflowd** [comment]
> @mcollina I think moving the repo in which they are organized back to the Node.js organization could make sense if we agree to the rebrand.

TBH I'm fine with `/openjs-foundation/summit` as the central place for sharing all the summits that are happening under the OpenJS umbrella. Having a centralised place feels like good for people from different projects to easily know what sort of summits are being organised.

Also easier to streamline templates and announcements.

What do you all think?

**Comment by mhdawson** [comment]
I'm ok with them living in either place.

**Comment by mhdawson** [comment]
Closing as metioned before.
