### ISSUE TITLE
adding joaocgreis to security-external

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/TSC#1403]
Proposing that we add @joaocgreis to the security-external team. We have a specific Windows report with a fix ready where his review would be much appreciated. Of course, if he's interested in reviewing it.

@nodejs/tsc @tniessen

From our [Security Team doc](https://github.com/nodejs/TSC/blob/db67321d4f7b6ecba563d3e73c6aeab3e2638581/Security-Team.md):

> 3. On a case-by-case basis, individuals outside the Technical Steering
>    Committee are invited by the TSC to have access to private security reports
>    or private patches so that their expertise can be applied to an issue or
>    patch. This access may be temporary or permanent, as decided by the TSC.
>
>  Membership on the security teams can be requested via an issue in the TSC repo.

**Comment by Trott** [comment]
+100 on this. They were (are?) on Build and had access to all this stuff for a very long time and are definitely well-known and trusted.

While you're in there, you can probably remove yourself from security-external since you are now on security-tsc.

**Comment by mhdawson** [comment]
+1

**Comment by RafaelGSS** [comment]
Invited.
