### ISSUE TITLE
Add bmeck to HackerOne

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#1409]
@nodejs/tsc See recent discussion in private Slack channel. Unless he doesn't want to be added, Rafael (and I!) would like to add @bmeck to general HackerOne access. If you have concerns or questions, please surface them privately or publicly before the next TSC meeting (on Wednesday, July 5). If no one has any concerns, we'll add Bradley after that meeting.

**Comment by Trott** [comment]
tsc-agenda label added for visibility and so that we can have one final call for consensus at the meeting

**Comment by GeoffreyBooth** [comment]
Strong +1

**Comment by mcollina** [comment]
+1

**Comment by mhdawson** [comment]
+1
