### ISSUE TITLE
Request for Foundation funds to get @Fishrock123 to SF for ES Modules meetings

### ISSUE THREAD

**Issue by rvagg** [nodejs/TSC#141]
I'm told that if we want to dip into Foundation funds then we have to do it formally through the TSC, so let's give that a spin!

TC39 is meeting in Los Gatos on 27-29th of September, i.e. next week. There is also a meeting being planned for the 26th with key ES Modules people in attendance, including Dave Herman, Yehuda Katz and of course @bmeck. A few other Node folks will be attending this meeting, including, I believe, @mikeal, @jasnell and @dshaw. My proposal is that we request Foundation funds to get @Fishrock123 there as well, for at least the meeting on the 26th but also potentially the TC39 meeting if we can somehow secure an invite for him to that (no luck on that front so far). @Fishrock123 has been the CTC (& TSC) member most closely keeping up with the discussion and has the most amount of technical depth on the issues facing Node, aside from @bmeck.

@Fishrock123 would be coming in from Canada and we estimate that flights and accommodation should come in under $1800 so that is the maximum ask here.

I'd also be interested to know if @chrisdickinson would like to attend and if this proposal could be extended to cover his travel & accom.

**Comment by nebrius** [comment]
Can you expand on what "formally through the TSC" means? To get funds, do we need to make a formal request to the board? Vote on it in a meeting? Something else?

**Comment by jasnell** [comment]
If NodeSource is unable to sponsor his travel then +1 on this.

**Comment by mhdawson** [comment]
+1 from me as well.

**Comment by rvagg** [comment]
@nebrius I think we just need to have a vote in a TSC meeting and we can dip in to funds already set aside for the TSC. I believe the "travel fund" that we set up some time ago is still in existence although there's talk of taking it away due to non-use. We just need to say, as a TSC, that we want to dip in to it.

And yes, I'm having a little bit of trouble getting this sponsored internally @ NodeSource, all due to timing.

**Comment by Fishrock123** [comment]
*sigh*

**Comment by jasnell** [comment]
sigh? As far as I could tell there were no objections to this during the TSC call last week. Just not sure what the process is for actually making it happen, especially on such short notice. I think we likely need to make sure the process is better documented and that there's plenty of time to make sure things like this can happen.

**Comment by Fishrock123** [comment]
Oh I guess I should note that was approved but I didn't attend for other reasons including timing.

**Comment by mikeal** [comment]
As I noted in another thread, this is the process for approving these kinds of requests. Once approved expense reports should be sent to ap@linuxfoundation.org and you can use this template https://drive.google.com/previewtemplate?id=0Ak7JTr_5ZgQBdHVEOG5rX0FYdTNzak5IQnh6cnp0dXc&mode=public&ddrp=1#
