### ISSUE TITLE
nominating @benjamingr to the TSC

### ISSUE THREAD

**Issue by gireeshpunathil** [nodejs/TSC#1410]
Benjamin has made significant contributions to Node.js. Some of the noteworthy items include:

- abortsignal / eventtarget
- design review and code contributions to major features like worker_threads
- stream: iterator workers, map operator
- promises
- moderation

Benjamin's exemplary skills on navigating and facilitating on issues (technical and social) will add great value to the project leadership.

It is my privilege to nominate Benjamin to the Node.js TSC.

**Comment by mhdawson** [comment]
+1 from me

**Comment by benjamingr** [comment]
Happy to help <3

**Comment by Trott** [comment]
@nodejs/tsc

**Comment by Trott** [comment]
Added to TSC agenda so that we can get resolution and move forward. Hopefully we get resolution and move forward before the meeting.

**Comment by mhdawson** [comment]
Starting on the onboarding 

 - [ ] Confirm that the new member has read, understands, and agrees to uphold the
  [Code of Conduct](https://github.com/nodejs/admin/blob/main/CODE_OF_CONDUCT.md).
- [ ] Add the new member to the `@nodejs/tsc` and `@nodejs/security-tsc` teams.
- [ ] Change the new member's role in the GitHub `nodejs` organization to `Owner`.
- [ ] Add them to the `@nodejs-private` org and with an `Owner` role.
- [ ] Add them to the `@nodejs-private/security-tsc` team.
- [ ] Add them to the `@pkgjs` org and with an `Owner` role.
- [ ] Add them to the `@pkgjs/node-tsc` team.
- [ ] Invite them to the HackerOne [Node.js team](https://hackerone.com/nodejs/team_members).
  Have them turn on two- factor authentication after they have joined.
- [ ] Add them to the `tsc` and `crypto-export` mailing lists.
- [ ] Add them to the [nodejs-tsc](https://groups.google.com/g/nodejs-tsc) Google Group as owners, so they receive Calendar invites for TSC meetings.
- [ ] Update the `@nodejs/node` repository README to reflect membership in the TSC.
- [ ] Update <https://github.com/nodejs/create-node-meeting-artifacts/blob/main/templates/invited_tsc> to reflect membership in the TSC.
- [ ] Inform them of the TSC meeting password.
- [ ] Ask them what is their handle on OpenJS Slack – and ask them to create one if they haven't one already. Add that handle to the `#nodejs-tsc` channel.


@benjamingr  can you confirm that the new member has read, understands, and agrees to uphold the [Code of Conduct](https://github.com/nodejs/admin/blob/main/CODE_OF_CONDUCT.md).

**Comment by mhdawson** [comment]
@benjamingr  let me know once you have accepted the HackerOne invitation and have turned on 2FA

**Comment by benjamingr** [comment]
I confirm I've read and understood the Code of Conduct and agree to uphold it.

I've accepted the HackerOne invite and turned on 2FA thanks.

**Comment by mhdawson** [comment]
Onboarding complete @benjamingr welcome!
