### ISSUE TITLE
Need Chair for TSC meeting Aug 9 at 3 ET.  

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1424]
Are there any volunteers to chair. @mcollina cannot make that time. An alternative is to change the time.

@nodejs/tsc

**Comment by mcollina** [comment]
I'm can take a 17:00 CEST or 18:00 CEST meeting, but not a 21:00 one.

**Comment by ruyadorno** [comment]
I have a conflicting meeting at that time, that said I'm a +1 to changing the time.

**Comment by mhdawson** [comment]
Not sure if this occured since I failed to follow up before I went on PTO. Closing.
