### ISSUE TITLE
Add generated ical file to TSC meeting agenda issues

### ISSUE THREAD

**Issue by jsumners** [nodejs/TSC#1432]
A quick search of the issues indicates this hasn't been suggested before. I'm not sure if GitHub even allows attaching such files, but it would be really cool if whatever is generating the TSC agenda issues, e.g. https://github.com/nodejs/TSC/issues/1431, also attached an ical file with all pertinent details (particularly the public YouTube URL) for the meeting. This would allow people to easily add it to their calendar if they are interested in a specific meeting.

**Comment by anonrig** [comment]
I've been thinking about implementing this. I'm extremely interested in this since it helps me a lot.

**Comment by tniessen** [comment]
Just in case you haven't come across it yet, the [Node.js calendar](https://nodejs.org/calendar) lists all meetings, including TSC meetings. For me, personally, this works well enough.

**Comment by anonrig** [comment]
> Just in case you haven't come across it yet, the [Node.js calendar](https://nodejs.org/calendar) lists all meetings, including TSC meetings. For me, personally, this works well enough.

For people who want to subscribe to specific working group meetings, I couldn't find a good solution for this. It's either all-in or none.

**Comment by mhdawson** [comment]
PRs welcome to https://github.com/nodejs/create-node-meeting-artifacts

**Comment by anonrig** [comment]
So, I've looked into this. Github issues does not support `.ics` file extension. It seems the website we use to link for the datetime (example: https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Technical%20Steering%20Committee%20(TSC)+Meeting+2023-08-30&iso=20230830T1900), has a `Add to calendar` button. We can add a new link to the issue to add it to calendar that directly opens this page. The code implementation exists in: https://github.com/nodejs/make-node-meeting/blob/main/make-node-meeting.sh#L89

**Comment by jsumners** [comment]
How about a zip that extract to `.ics`?

**Comment by anonrig** [comment]
> How about a zip that extract to `.ics`?

People might be against downloading a zip for variety of reasons. Directly adding a link from `timeanddate.com` might be a lot faster to implement.

**Comment by jsumners** [comment]
But that link will not include all of the details for attending, correct? That's just the time and date, yest?

**Comment by iambary44** [comment]
> A quick search of the issues indicates this hasn't been suggested before. I'm not sure if GitHub even allows attaching such files, but it would be really cool if whatever is generating the TSC agenda issues, e.g. https://github.com/nodejs/TSC/issues/1431, also attached an ical file with all pertinent details (particularly the public YouTube URL) for the meeting. This would allow people to easily add it to their calendar if they are interested in a specific meeting.

**Comment by iambary44** [comment]
> So, I've looked into this. Github issues does not support `.ics` file extension. It seems the website we use to link for the datetime (example: https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Technical%20Steering%20Committee%20(TSC)+Meeting+2023-08-30&iso=20230830T1900), has a `Add to calendar` button. We can add a new link to the issue to add it to calendar that directly opens this page. The code implementation exists in: https://github.com/nodejs/make-node-meeting/blob/main/make-node-meeting.sh#L89

**Comment by mhdawson** [comment]
There has not been any discussion or volunteers to move this forward for over a year.  Are there any objections to me closing this issue?

**Comment by jsumners** [comment]
I wish it could be solved. But it seems like some level of support from @GitHub would be needed, and I don't think that'll happen 😢

**Comment by mhdawson** [comment]
k, I'll close and please re-open if there is a path/volunteers to move forward at some point.
