### ISSUE TITLE
Need volunteer to Chair TSC meeting Nov 8 and Nov 1st

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1456]
Both @mcollina and myself will be away on these two dates.  

- Nov 8 is in the middle of NodeConf.eu so others might also be there.

I'm looking for volunteers to chair each of these two days. @nodejs/tsc can you comment in the issue if you can volunteer to chair one or both of the days?

**Comment by gireeshpunathil** [comment]
I can chair nov 8th instance.

**Comment by mhdawson** [comment]
@gireeshpunathil thanks. If I don't hear from anybody before the end of this week about nov 1st I'll cancel that one.

**Comment by mhdawson** [comment]
Ok cancelling for nov 1, @gireeshpunathil thanks for chairing on the 8th.
