### ISSUE TITLE
Add Paolo Insogna to HackerOne

### ISSUE THREAD

**Issue by mcollina** [nodejs/TSC#1466]
@shogunpanda has been maintaining llhttp and our HTTP/1.1 implementation. I think we should add him to HackerOne.

Any objections?

**Comment by tniessen** [comment]
Are there any rules for [who we grant access to](https://github.com/nodejs/TSC/blob/main/Security-Team.md#team-with-access-to-private-security-reports-against-nodejs) besides TSC voting members? The [triaging team](https://github.com/nodejs/TSC/blob/main/Security-Team.md#team-responsible-for-triaging-security-reports) makes sense to me.

FWIW, it's just a few clicks to add non-org members to individual reports. On the other hand, org members on HackerOne have far more permissions than just interacting with reports.

**Comment by jasnell** [comment]
No objections to adding @ShogunPanda to hackerone

**Comment by mcollina** [comment]
Invited.
