### ISSUE TITLE
Utilize travel fund for all CTC / TSC members who want to come to Node Interactive

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#147]
We have [45k in un allocated funds.](https://github.com/nodejs/TSC/issues/145#issuecomment-249633456)

This should be MORE than enough to get all of the CTC members to Node Interactive US. I would like to propose that we offer a travel stipend to all CTC members whose companies cannot afford to send them.

If there are remaining funds after this I would be interested in seeing some of the funds allocated as a scholarship for collaborators from under represented groups

**Comment by TheAlphaNerd** [comment]
@mikeal I would also be interested in finding out if the Foundation would be willing to give free tickets to CTC members and discounted tickets to collaborators. This could make more of the funds available for travel as opposed to conference tickets

**Comment by mikeal** [comment]
I think you meant "US" not "EU" :)

**Comment by TheAlphaNerd** [comment]
updated

**Comment by mikeal** [comment]
> free tickets.

Code and Learn mentors receive "speaker" tickets for their help, is there anyone that wouldn't fall into that category?

**Comment by TheAlphaNerd** [comment]
@mikeal I was unaware of this. Broadcasting

**Comment by mikeal** [comment]
Keep in mind that it costs the conference money to have each attendee there so we shouldn't abuse this. Obviously anyone on the CTC and anyone that is a regular contributor is eligible for this but let's not extend it broader than that.

**Comment by TheAlphaNerd** [comment]
@mikeal I don't think it would make sense to allow a someone to mentor code and learn who doesn't fall into that category.

**Comment by Fishrock123** [comment]
Nit: the travel funs are _allocated_ to us, aren't they?

**Comment by jasnell** [comment]
I would very much like to see us get as many contributors there as possible but we need to make sure this is not abused. If the employer is a member of the foundation already, then I think it is reasonable to expect the company to fund it's own participants travel. The bias needs to be towards helping the individual developers who otherwise have no ability to pay for the travel out of pocket.

**Comment by TheAlphaNerd** [comment]
Is this still something we can do? How can we get people onboarded?

**Comment by nebrius** [comment]
> Is this still something we can do? How can we get people onboarded?

For the time being, people who want to utilize funds should open an issue here asking for funds, similar to #150.

**Comment by TheAlphaNerd** [comment]
Should we limit this to CTC / TSC? Would it make sense to include collaborators?

**Comment by mhdawson** [comment]
As per TSC meeting I agreed to put a draft of an announcement to be sent out letting people know they can as for funding. We'll need to send it out soon if its going to help: @nodejs/tsc please comment:

The Foundation would like to ensure that as many active collaborators attend the collaborator summit at Node Interactive in Austin at the end of November.  We expect that for collaborators working for one of the corporate members, that their company will cover the required travel costs.  However, for collaborators not employed by one of these companies, travel funding may be provided by the Foundation provided that the collaborator has been active over the last 3 months as seen through involvement in issues and PRs, working groups or other day to day activities of the community.  If you are an active collaborator and would like to request travel funding please make your request in this issue: https://github.com/nodejs/TSC/issues/147.

**Comment by Trott** [comment]
> The Foundation would like to ensure that as many active collaborators attend the collaborator summit at Node Interactive in Austin at the end of November.

This is not a complete sentence. ("As many" as what?)

Nit: The _de facto_ standard practice in the repo is to use `Collaborator` rather than `collaborator`.

`collaborator summit` -> `Collaborator Summit`

I think the Collaborator Summit actually takes place on the first and second day of December rather than the end of November, doesn't it?

**Comment by Trott** [comment]
> for one of the corporate members

I imagine this means corporate members _of the Foundation_. I suspect it's not going to be clear to people what that means without that clarifying bit. Maybe include a link to the list of corporate members. Or just simplify and take out this sentence, and in the next sentence:

* remove the `However` at the start
* change `one of these companies` to `corporate members of the Node.js Foundation` (and perhaps include a link to a list of these companies)

**Comment by Trott** [comment]
Nit: `working groups or other day to day activities of the community.` -> `working groups, or other [Collaborator activities](https://github.com/nodejs/node/blob/master/GOVERNANCE.md#collaborator-activities).`

**Comment by Trott** [comment]
Nit: add a comma after `funding` in the last sentence

**Comment by mhdawson** [comment]
Updated version to address comments:

**Comment by mhdawson** [comment]
Note that I left it as end of November as Node Interactive does start in November.

**Comment by rvagg** [comment]
perhaps a bit more broad on the corporate bit:

"We expect that Collaborators working on Node.js as part of their employment arrangements, particularly for one of the [corporate members of the foundation](https://nodejs.org/en/foundation/members/), that their employer will cover the required travel costs. For Collaborators unable to secure employer funding and who have been active ..."

It's not as obvious as it might seem that people could secure funding for this kind of thing from their employer even if that employer is a member company, budgets are pretty tight outside of the Platinum member list and we need to be open to the possibility that money isn't available.

**Comment by mhdawson** [comment]
Ok updated to :

The Foundation would like to ensure that as many active Collaborators as possible attend the Collaborator summit at Node Interactive in Austin at the end of November. We expect that Collaborators working on Node.js as part of their employment arrangements, particularly for one of the [corporate members of the foundation](https://nodejs.org/en/foundation/members/), that their employer will cover the required travel costs. For Collaborators unable to secure employer funding,  travel funding may be provided by the Foundation provided that the Collaborator has been active over the last 3 months as seen through involvement in issues and PRs, working groups, or other [Collaborator activities](https://github.com/nodejs/node/blob/master/GOVERNANCE.md#collaborator-activities). If you are an active Collaborator and would like to request travel funding, please make your request in the TSC repo (https://github.com/nodejs/TSC) with an issue similar to #150

**Comment by mhdawson** [comment]
I think the text is pretty close. In terms of getting it out to collaborators once we all agree would an issue in this repo with an @ copy to the node js collaborators be enough or are there other channels we should use as well ?

**Comment by nebrius** [comment]
I think it would be better to be specific with the dates, just to make sure there isn't any confusion, e.g. "...as possible attend the Collaborator summit at Node Interactive in Austin on December 1st and 2nd."

Grammar nit: I think it should be "We expect that Collaborators working on Node.js as part of their employment arrangements, particularly for one of the corporate members of the foundation, will ask their employer to cover the required travel costs."

**Comment by mhdawson** [comment]
Ok. updated as follows:

The Foundation would like to ensure that as many active Collaborators as possible attend the Collaborator summit at Node Interactive in Austin on December 1st and 2nd. We expect that Collaborators working on Node.js as part of their employment arrangements, particularly for one of the corporate members of the foundation, will ask their employer to cover the required travel costs. For Collaborators unable to secure employer funding, travel funding may be provided by the Foundation provided that the Collaborator has been active over the last 3 months as seen through involvement in issues and PRs, working groups, or other Collaborator activities. If you are an active Collaborator and would like to request travel funding, please make your request in the TSC repo (https://github.com/nodejs/TSC) with an issue similar to #150

I really think we need to get this out a soon as possible or it will just be too late.  @node/tsc can I get a few LTGMs for the ok to send this out tomorrow.

**Comment by bnoordhuis** [comment]
LGTM

**Comment by indutny** [comment]
LGTM
