### ISSUE TITLE
Node.js Collaborator Spotlight Proposal

### ISSUE THREAD

**Issue by kyliewd** [nodejs/TSC#1474]
To better showcase some of the Node.js folks doing good work across our community, I'd like to propose a bi-monthly collaborator spotlight.

Here are some early thoughts on how to approach:

- Create a form for folks to nominate a Node.js collaborator who has done something important or meaningful. This form will always be open.
- On a cadence (monthly or bi-monthly), post about nominating collaborators for spotlight.
- Let's start bi-monthly for choosing a collaborator to highlight (so 6 for 2024).
- This person will be highlighted on the Node.js social channels.
- If it feels warranted, we can look into doing a blog post on [openjsf.org](http://openjsf.org/).

Any other ideas are welcome for how we can highlight some of our amazing collaborators here! 💚

**Comment by RafaelGSS** [comment]
> Create a form for folks to nominate a Node.js collaborator

I'm a bit confused. What does "Folks" in this sentence mean?

1. TSC members
2. All Node.js collaborators
3. Open to public

**Comment by kyliewd** [comment]
> > Create a form for folks to nominate a Node.js collaborator
> 
> I'm a bit confused. What does "Folks" in this sentence mean?
> 
> 1. TSC members
> 2. All Node.js collaborators
> 3. Open to public

Open to public!

**Comment by RafaelGSS** [comment]
Wouldn't it create a situation where popularity will be more important than the contribution itself? I have a feeling that it might create "unfair" situations where the ones with more recognition by the community will always win. Just my 2 cents.

**Comment by kyliewd** [comment]
@RafaelGSS you mean like the same person getting it every time? We could make it so you can only be spotlighted once. 

Do you think it would be better if the nomination was only by TSC? I’d just like to make sure we are keeping it open and fair!

**Comment by joyeecheung** [comment]
My 2 cents: personally I prefer not to be highlighted as a person. This is the reason why I avoid interview, podcast, or panels in general, with the exception of doing tech talks because I think communicating/spreading ideas with slides/diagrams/voice is effective. But making my work personal is something I like to avoid. That might be just me, but I also see that some of our collaborators choose to hide their real names and real identities online. I think making it too much about people is not great for those who want to keep their identity less obvious online. Making it more about the work, and, give credit to the people behind it if they want to, would be a good idea though.

**Comment by mcollina** [comment]
I think quite a few people feel major OSS project are "personified", so "Node.js" does XYZ. This initiative is meant to show that Node.js is built by developers, and everybody can contribute.

I think nominations should be:

* done by the individual (to avoid the issues @joyeecheung mentioned)
* showing/explaning one or more meaningful contributions (can be a bug or a new feature)

We should highlight XYZ done by Bob.

**Comment by mhdawson** [comment]
I think it's important to recognize people for the work they do in the project as I believe it is one of the ways that we can grow and retain our collaborator base. I think it helps by:

1) Ensuring people know that the project appreciates their work
2) Encouraging people to repeat/grow their contributions
3) Helping people demonstrate to their managers the value of the contributions they are making, which in terms helps their manager support their employer investing in the project (unfortunately this is something that matters)
4) Highlighting the new features in Node.js and showing that they are being added by individuals like those mentioned. This should encourage other people to get involved and make similar contributions.
5) Highlighting those leading efforts/initiatives and they are being done by individual like those mentioned. This should encourage other people to get involved and make similar contributions

**Comment by mhdawson** [comment]
In terms of the original proposal, I think I'd add that nominations are approved by the TSC.

**Comment by mhdawson** [comment]
I'd also add that a spotlight would not always need to be an individual, it would be for example a team that is doing a great job and we would mentioned the members of that team.

**Comment by RafaelGSS** [comment]
I'm definitely +1 to spotlight the group effort, I concur with all the above affirmations. I'm just raising the concern that open-to-public voting to define who to spotlight might lead to _unfair_ results. Perhaps, restricting it to nodejs collaborators could avoid that.

Overall, I love this initiative.

**Comment by kyliewd** [comment]
Thanks everyone! Your feedback is greatly appreciated. Let me put this together in a more formal plan + get the form ready.

We'll aim to launch this in the new year 🚀 💚

**Comment by kyliewd** [comment]
Hi all - here is a peek at the form I created for the spotlight nominations. I'd love to hear if you have any other question ideas or thoughts: https://forms.gle/piDkMfKfumUy6H4m6

**Comment by mhdawson** [comment]
@kyliewd I tried to access the form but I did not have enough permissions.

**Comment by mcollina** [comment]
same

**Comment by kyliewd** [comment]
apologies - please try now: https://docs.google.com/forms/d/e/1FAIpQLSfvXjLq_YaC2BrhefEhi-xQpmpF02x3B7r9oEvI6LfjxHfs3w/viewform?usp=sharing

@mcollina @mhdawson

**Comment by mhdawson** [comment]
I still get

You need permission
This form can only be viewed by users in the owner's organization.

Try contacting the owner of the form if you think this is a mistake. [Learn More.](https://support.google.com/docs/?p=forms_settings)

**Comment by kyliewd** [comment]
chatted with ben and there were permission issues but they have now been removed: https://forms.gle/dXBXZn8yu83HLJ57A

**Comment by mhdawson** [comment]
That form looks good to me. I don't think we need more than that.

**Comment by mcollina** [comment]
sgtm

**Comment by mhdawson** [comment]
@kyliewd what's the next step on this?

**Comment by kyliewd** [comment]
@mhdawson waiting for submissions! if there is a slack channel you'd like me to promote in, let me know. or, it would be good to discuss this in the next TSC meeting. Let me know.

**Comment by mhdawson** [comment]
@kyliewd thanks, added to the TSC agenda so I can raise awareness there and then we can see what else se might do.

**Comment by mcollina** [comment]
@mhdawson can anybody be nominated, right? Is there a process we should follow?

**Comment by mhdawson** [comment]
@mcollina nominations can be made through https://forms.gle/dXBXZn8yu83HLJ57A, and then I think the TSC should weigh in on confirming the nomination and which order they should be processed in. It is something that I think would be good to document.  I'll take a first cut at that.

**Comment by mhdawson** [comment]
@mcollina @kyliewd PR to document here. I tried it address any discussion/concerns etc from this issue into what's documented - https://github.com/nodejs/node/pull/52598

**Comment by BridgeAR** [comment]
I like the idea and the form is LGTM.

What we might want to do in addition is to highlight all new contributors a bit stronger.

**Comment by mhdawson** [comment]
@BridgeAR I think that is a good idea but a bit different than this specific proposal. Could you open a new issue with what you are suggesting? In this case its going to be once every two months and possibly only through social versus a blog post so don't think we can squeeze in promotion of new collaborators

**Comment by kyliewd** [comment]
@mhdawson we are getting some entries! what do you think about me leaving it open for the next month, and then I will send over the nominees to the TSC and y'all can vote on who we should spotlight for the month. thoughts?

**Comment by kyliewd** [comment]
great! i'll follow up on this in a few weeks.

**Comment by mhdawson** [comment]
The program has been documented and we've had the first spotlight completed and nominations for the second are being discussed. I think this issue which was to propose/get the program going can be closed.

Going to close, please let me know if that was not the right thing to do.
