### ISSUE TITLE
Offboard cjihrig

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1477]
We need to complete the offboarding steps in https://github.com/nodejs/TSC/blob/main/ONBOARDING.md#offboarding-of-voting-members

Refs: https://github.com/nodejs/node/pull/50816#event-11057436271

@nodejs/tsc any volunteers to do that?

**Comment by mhdawson** [comment]
@aduh95 I think you did a few of the steps?

**Comment by aduh95** [comment]
Correct, I've been through the list, unless I've forgotten something this is already completed.

**Comment by mhdawson** [comment]
@aduh95 many thanks!
