### ISSUE TITLE
New structure of security releases

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/TSC#1494]
While discussing with @marco-ippolito about approaches for the task https://github.com/nodejs/security-wg/issues/860#issuecomment-1636464514 I rapidly thought about a new strategy.
A new private repository `node-private/security-release` will hold all information on previous and upcoming security releases. Currently, the automation of security release is based on a "Next Security Release" issue, which makes the process unnecessarily complicated and flaky in terms of automation since we will need to deal with markdown/strings.

My suggestion will be this repository (`node-private/security-release`) holding all metadata of an upcoming security release such as:

* reports
* affected versions
* CVEs
* ...

Therefore, the automation won't need to parse strings/markdown, it just needs to read a JSON file. For instance, consider this structure:

```
security-release/
  2023-10-13/
    vulnerabilities.json
  next-security-release/   <---- This will be updated to the security release date once it lands
    vulnerabilities.json
```

Using this approach should be much easier to request CVEs and generate blog posts. It also makes possible the automation of uploading vulnerabilities to our security-db.

EDIT: I forgot to mention the review will be easier too since a PR will be opened targeting `main` -- assuming all the upcoming security release will be handled in a fixed branch: `next-security-release`

**Comment by mcollina** [comment]
sgtm

**Comment by tniessen** [comment]
SGTM assuming we have a well-defined SSOT for all the data so that we won't run into conflicts or inconsistencies.

**Comment by aduh95** [comment]
Maybe we could get away with opening that PR on `node-private` – so without the need to create a new repo. In any case, SGTM.

**Comment by mhdawson** [comment]
I think trying it out and seeing what it looks like makes sense.

**Comment by RafaelGSS** [comment]
Repo created https://github.com/nodejs-private/security-release.
