### ISSUE TITLE
Code & Learn NI NA lead teacher travel fund request: Anna Henningsen

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/TSC#150]
**Travel fund request for Anna Henningsen**  

**Event:** Node Interactive NA
**Location:** Austin, TX, United States

**Code & Learn**--Anna will lead and organize event for welcoming folks to contribute to Node.js by walking through setup, supporting session time with mentors, and providing tasks that are beginner-friendly

**Stipend request size:** *** It was noted that $1500 is the cap for travel funds, but it is clear that this is not enough to cover flight and lodging from Anna's current location.
Stipend would cover flight and lodging for the duration of NI NA, which includes the Code & Learn.

I have opened this as part of discussions that occurred after the NI EU Code & Learn where it was realized that this is a really awesome effort that needs solid support and more preparation. I will be assisting with organizing(@hackygolucky) but I believe that by having both @Trott and @addaleax leading this event, we are setting it up for success.

**Comment by nebrius** [comment]
I'm in favor of this request.

**Comment by jasnell** [comment]
+1 from me as well.

**Comment by mikeal** [comment]
There's no cap on this fund (TSC Community Travel Fund), the $1500 cap is only relevant to the "speaker stipend" fund that lives in side the event budget (which is maxxed out).

Also note that this doesn't have to be a stipend, it can more easily be used as a direct re-imbursement.

**Comment by mikeal** [comment]
My bad, there's a cap set in the TSC policy https://github.com/nodejs/TSC/blob/master/Member-Travel-Fund.md

The TSC can change the policy though, they own it and the board didn't set a cap on per-person expenses when they allocated the fund. The TSC just needs to land a PR to adjust the policy before approving a larger expense.

**Comment by addaleax** [comment]
> Also note that this doesn't have to be a stipend, it can more easily be used as a direct re-imbursement.

That assumes (all of this assumes?) that I’m in the financial position to cover flight costs for myself beforehand, right?

**Comment by mikeal** [comment]
A stipend can be a fixed amount of money ahead of time.

**Comment by rvagg** [comment]
approved
