### ISSUE TITLE
Spend from Node.js Bug Bounty/Security Fund (LFX crowdfunding account) to have collaborator fix urgent vulnerability

### ISSUE THREAD

**Issue by tniessen** [nodejs/TSC#1506]
Due to a rather unique situation, we are seeking approval for using up to $2000 of the [security fund](https://github.com/nodejs/TSC/blob/main/Nodejs-Bug-Bounty-Security-Fund.md) for contracting a collaborator to fix a security vulnerability. Details are available through the private TSC mailing list. Please let us know if there are any concerns or objections by the end of 2024-02-21, and please +1 the issue if you don't have any concerns.

cc @nodejs/tsc

**Comment by mcollina** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by aduh95** [comment]
+1

**Comment by gireeshpunathil** [comment]
+1

**Comment by MoLow** [comment]
+1

בתאריך יום א׳, 18 בפבר׳ 2024, 17:01, מאת Gireesh Punathil ‏<
***@***.***>:

**Comment by anonrig** [comment]
+1

**Comment by tniessen** [comment]
Consensus has been reached.

**Comment by mhdawson** [comment]
Based on the pre-approval here, and the fix which was published in the recent security release, I'm approving payment for this on behalf of the TSC as per the process in https://github.com/nodejs/TSC/blob/main/Nodejs-Bug-Bounty-Security-Fund.md#disbursements.
