### ISSUE TITLE
Member Status

### ISSUE THREAD

**Issue by refack** [nodejs/TSC#1509]
For some reason, my Org-Member status was revoked.
Please restore.

**Comment by refack** [comment]
I don't have any context about why or under what policy I violated. If you consider me worthy of kicking out, please provide context.

**Comment by mcollina** [comment]
As a security measure, we remove inactive people from the organization. You were moved to the emeritus status in https://github.com/nodejs/node/pull/40115.

In order to have this restored, you might want to start contributing again.

**Comment by aduh95** [comment]
Looking in the logs, I can't find any trace of that, which means the removal happened more than 6 months ago.
Is there any specific reason you would need that membership for? AFAIK org membership should not have any impact in the things you can access or the actions you can take.

**Comment by benjamingr** [comment]
Hey Refael, hope you're doing well.

Like Matteo explained Node.js routinely removes org members who are not in any teams. If there is anything specific you'd gain from org membership - the project might be able to assist (e.g. a note signed by the TSC acknowledging your many contributions in the past). As there is nothing actionable to do regarding membership - I'm going to go ahead and close this.
