### ISSUE TITLE
Community Travel Fund in 2017

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#151]
Heya,

It's nice to finally see that the community travel fund is being used.

I'd like to know how much money the TSC would like to see allocated into this fund in 2017 and if there are any scope or process changes to be considered. I'm working on the budget now, so feedback would be greatly appreciated.

**Comment by rvagg** [comment]
Going to drop this in here for reference, the template for expense reimbursement https://drive.google.com/previewtemplate?id=0Ak7JTr_5ZgQBdHVEOG5rX0FYdTNzak5IQnh6cnp0dXc

**Comment by williamkapke** [comment]
I have a few questions about this. I don't expect answers- I guess they really serve to provoke though. So here is my brain dump:
- How many events does the foundation have lined up for next year? (Live, Interactive, ....?)
  - Locations of them? I mean- NYC is far more expensive than many low cost cities.
- Do we anticipate.. or want to pad for Summits that pop up? e.g.: VM Summit did not happen in a budget friendly way. (but we should allow for these agile events)
- How many do we predict will need assistance?
- Will this only be "assistance"? (only helping when your company denies you)
- Meals allowance?
- Will people now __plan__ for this benefit and we will see an increase in use?

**Comment by mikeal** [comment]
> How many events does the foundation have lined up for next year? (Live, Interactive, ....?)

We felt pretty over-extended this year so the only we've committed to so far in next year is a single, large, Node.js Interactive in North America. Not sure which city yet but it will be a relatively low cost city for budgetary reasons.

Keep in mind that the event budget includes money to bring in some selected speakers so it's not entirely on this budget to get people there if they are speaking. Also, if we want to bring in a bunch of people *just* for that event we could get the board to dedicate specific funds in addition to the regular Community Travel Fund.

> Do we anticipate.. or want to pad for Summits that pop up? e.g.: VM Summit did not happen in a budget friendly way. (but we should allow for these agile events)

No, we shouldn't. If we want to have one of these next year we'll just pass a new budget allocation for the whole event (including venue, food, travel, etc).

**Comment by jasnell** [comment]
@mikeal ... does this need to remain open?

**Comment by mikeal** [comment]
This does not need to remain open but you may want to request an allocation for additional funds since the TSC has already spent more than 50% of this year's allocation.

**Comment by jasnell** [comment]
@mikeal ... let's include a discussion of this during the private section of this week's TSC call.
