### ISSUE TITLE
Owner permissions to the github-bot repo?

### ISSUE THREAD

**Issue by phillipj** [nodejs/TSC#153]
I've asked 3-4 times the last month or so on IRC freenode/#node-dev, if an org admin could help me add a webhook to the [github-bot repo](https://github.com/nodejs/github-bot) needed for auto deployment, without luck :/

Therefore I'm wondering if I could be added as an owner of that repo, so I won't have to bug others about issues like this.

FYI for those that wasn't aware, the @nodejs-github-bot is governed by the TSC which has delegated the responsibility to members of the @nodejs/github-bot team.

**Comment by phillipj** [comment]
ping @nodejs/tsc -- *any* response would be much appreciated.

**Comment by rvagg** [comment]
Sorry @phillipj, I hadn't seen this yet! I've switched everyone to Admin over there, let me know if that helps, otherwise please ping me on IRC some time, PM rather than in the channel and remember that I'm in Australia.

**Comment by phillipj** [comment]
Awesome, thanks!
