### ISSUE TITLE
Coordinating nodejs security audit report finalization and publication

### ISSUE THREAD

**Issue by Amir-Montazery** [nodejs/TSC#1546]
The objective is to collaborate with the nodejs TSC to close out the report finalization and publication per: https://github.com/nodejs/security-wg/issues/1159. We will review the report and discuss anything needed.

**Comment by mhdawson** [comment]
Plan is to covery this in the private section of the TSC meeting on May 8

**Comment by Amir-Montazery** [comment]
Hello Michael and node TSC. I am terribly sorry for missing this meeting. The reason is I made a mistake and got my time zones mixed up (I'm on the west coast for the next few days and the calendar didn't update). 

Is it possible to participate in next week's TSC meeting? 

Sorry about that again! I know the group's time is valuable and didn't mean to keep you waiting.

**Comment by mhdawson** [comment]
We'll plan to have you in next weeks TSC meeting. See you then.

**Comment by mhdawson** [comment]
Removing from the agenda until we get the report.

**Comment by mhdawson** [comment]
The report has been shared through email, and discussed a few times in the TSC meeting. I'm going to go ahead and close this issue.  Please let me know if that was not the right thing to do.
