### ISSUE TITLE
Remove screen capture CTC meeting from YouTube

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#156]
I just watched the last CTC Meeting video on YouTube which appears to be a screen capture of ... @mikeal's screen? The UberConference url is listed there (which only has security by obscurity). That is probably why an unknown person joined midway through the meeting. There may have been something else displayed that we don't want seen.

I downloaded the video and would be happy to redo it with the NodeJS logo replacing the screen capture.

See: https://www.youtube.com/watch?v=zFdhHrdPiKE

/cc @Trott

**Comment by mikeal** [comment]
+1

**Comment by mikeal** [comment]
BTW, I specifically set the capture lower than the URL bar in OBS. For some reason the preview in OBS does not match what actually gets captured.

Also, the uberconf url is the most easily guessable url ever :)

**Comment by williamkapke** [comment]
heh so not "security by obscurity" but rather "security by good faith" ;)

@mikeal Can you send me that static Node.js image that is usually used for the videos?

**Comment by mikeal** [comment]
@williamkapke i don't have it, if i did i probably would have used it, my guess is that @Fishrock123 has it though :)

**Comment by Fishrock123** [comment]
![nodejs_new_pantone](https://cloud.githubusercontent.com/assets/1093990/19705881/edd7b55a-9b06-11e6-8b6e-156f9e98d7f2.png)

@williamkapke here, hopefully this uploaded in full 720p size.

**Comment by Fishrock123** [comment]
@williamkapke / @mikeal was this ever completed?

**Comment by williamkapke** [comment]
I have the video done- can I get YouTube account access so I can upload it?
Otherwise, I need to (somehow) get it to one of you to upload it.

**Comment by mikeal** [comment]
Aren't you on the Google Plus account? It's the same account, it's connected.

**Comment by williamkapke** [comment]
No- I haven't been added.

**Comment by williamkapke** [comment]
Re-uploaded, original removed.
