### ISSUE TITLE
Enable LFX Insights On The Node.js Project

### ISSUE THREAD

**Issue by bensternthal** [nodejs/TSC#1572]
This issue tracks a request to enable LFX insights on the Node.js project. We've piloted this on Express.js and jQuery and would like to onboard Node.js next.

**What Is LFX Insights**
Insights provides projects with more visibility into their community dynamics, particularly around contributors, organizations, issues, and pull request metrics. It does this through an app (similar to the DCO bot) installed at the organization level. This is then enabled for one or more repos under the organization. Insights uses [crowd.dev](http://crowd.dev/) under the hood to gather read-only data about specified public repositories in a GitHub organization.

**What Information Is Collected (only public information from Github)**

- Stars/Un-stars
- Forks
- Issues
- Pull requests
- Discussions
- Comments on issues/pull requests/discussions
- Closing of issues/pull requests/discussions

**Future Ideas**
We’d like to use insights to display security metrics for OpenJS projects including those being currently developed as part of the Sovereign Tech Fund initiative/score cards/ best practices etc. Use this data to help inform which if any projects should be Emeritus. 

**What I Need From The Project**
I’d like a) A thumbs up from the TSC if we are OK to proceed b) Any questions or concerns C) Who from Node.js should have access to the data (community managers)

**How Do We Turn This On**
I need to be made an admin (this can be temporary) on the Node.js org, this will allow me to install the read only Linux Foundation app. Once I install the app my privileges can be revoked.

**More Info**
You can find [Insights documentation here](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current).

**Express.js Links & Insights Examples**
* https://github.com/expressjs/discussions/issues/205
* https://insights.lfx.linuxfoundation.org/foundation/ojsf/overview/github?project=ojsf-express

@mhdawson

**Comment by richardlau** [comment]
+1 from me -- I thought we were already on it? (Perhaps an earlier iteration?)

**Comment by richardlau** [comment]
> I thought we were already on it? (Perhaps an earlier iteration?)

https://openjs-foundation.slack.com/archives/CPE10404W/p1683663452497269:
> https://insights-v2.lfx.linuxfoundation.org/ojsf-nodejs/technical-contributors/contributor-acquisition

(Link appears dead now, so probably it was an earlier version of the tool.)

**Comment by mhdawson** [comment]
@richardlau I think it was an earlier iteration.

+1 from me as well. I think there were some questions about contribution stats based on email so we might need to take some data with a grain of salt, but overall having more data is good.

**Comment by mcollina** [comment]
+1

**Comment by anonrig** [comment]
+1

**Comment by bensternthal** [comment]
It think we have consensus to proceed. If someone can grant me admin access to the Node org repo, I can enable it. My access can be revoked once it's set up.

**Comment by mhdawson** [comment]
@bensternthal how hard is it to enable, if it's easy I might just do it versus adding/removing you afterwards.

**Comment by bensternthal** [comment]
It's not hard, but as far as I know, it has to be enabled via LFX.

**Comment by mhdawson** [comment]
Opened - https://github.com/nodejs/admin/issues/886 so we have a record of giving admin access. Will do enable monday so that people have a chance to see the issue before I do that and I don't think there is any urgency in terms of enabling the LFX insights.

**Comment by bensternthal** [comment]
Thanks Michael, Monday works for me.

**Comment by bensternthal** [comment]
Looks like metrics are coming in, you can view here https://insights.lfx.linuxfoundation.org/foundation/ojsf/overview/github?project=ojsf-nodejs&repository=&routedFrom=Github

**Comment by mcollina** [comment]
Thanks @bensternthal, closing for now!
