### ISSUE TITLE
Node.js Foundation Survey 2016: need questions/input!

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/TSC#158]
In January of this year the Node.js Foundation ran its first Node.js User Survey. As a refresher, you can find the results here: https://nodejs.org/en/blog/announcements/nodejs-foundation-survey/

With Node growing as quickly as it has been, we have decided to launch a second survey at Node.js Interactive in Austin. The purpose of this survey is to understand *who* is writing/consuming Node.js, *how* they are participating in the space, *why* they are writing/consuming Node.js, and *what* they'd like to see improve(we ask a little about *where* as well without having required questions such as real names). It's difficult for us to know all of this to set goals for improvement and a roadmap if we don't have data to back it up!

You will recall from the first survey that a major interest area of the TSC was to understand whether users were upgrading to the new LTS release and if not, why not. What are the current areas of feedback the TSC would like to get from users?

All input is required no later than **November 12** in order for us to be able to launch the survey at Node.js Interactive.

cc @nodejs/evangelism @nodejs/ctc  (and any other working groups you think would like to offer questions)

**Comment by ljharb** [comment]
It might be nice to get a picture of people's usage of node version managers - do they use one (or more), which one(s) do they use, etc

**Comment by hackygolucky** [comment]
Thanks @ljharb 

Closing this for deadline's sake. There's always next year!

**Comment by ljharb** [comment]
@hackygolucky will there be version management questions on the survey? I commented well before November 12th.

**Comment by hackygolucky** [comment]
@ljharb oh, yes definitely!  Sorry, my comment made it sound like the opposite of that. The "Thanks" was for you and the "there's always next year!" was for everyone else who might comment later. I just didn't want anyone else commenting because we wouldn't be able to include their input, as we're working on finalizing it this week.
