### ISSUE TITLE
Give @williamkapke access to YouTube account

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#161]
RE: https://github.com/nodejs/TSC/issues/156

I'd love to be able to help with YouTube related things. There isn't a defined protocol for who & how people are added to non-Github services like this- so I'd thought I'd try this route. ;)

**Comment by mikeal** [comment]
I promoted a bunch of people to be owners of the G+ account including @Fishrock123 and @rvagg, I'd like to confirm they can now add people to it.

**Comment by Fishrock123** [comment]
@williamkapke I think I did this correctly, could you confirm?

**Comment by williamkapke** [comment]
Yup! I'm fixing #156 now.
