### ISSUE TITLE
Node.js CPC reps

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1627]
It's the yearly elections/nominations on the CPC side.

We currently have @mcollina and @joesepi as our reps.

https://github.com/openjs-foundation/cross-project-council/issues/1370

creating as an FYI to @nodejs/tsc members. @mcollina, @joesepi just confirming that you two are still happy to continue as the reps?

**Comment by joesepi** [comment]
I'm happy to continue and feel like I could improve in my representation of Node.js at the foundation and forge a better connection back to the project. Something I think about and am working on. Better attendance at the TSC meetings is one way (it's been crazy busy lately) but also being more tuned into the projects needs. All that is to say: I'm happy to continue and interested in improving. 🙌

**Comment by mcollina** [comment]
Happy to continue but my time for meetings at around that time is getting lower by the time passes. I read minutes and engage in issues/decisions when they came through.

**Comment by mhdawson** [comment]
Confirmed with @mcollina that while he is happy to continue if somebody else would like to volunteer he'd also be happy with that.  

I'll leave this open for another week to see if there are any other volunteers otherwise we'll assume that Matteo and Joe will continue.

**Comment by mhdawson** [comment]
Looks like we are settled on Matteo and Joe continuing. Closing.
