### ISSUE TITLE
Features to highlight in what's new in Node.js 23

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1628]
I have a talk at NodeConf.eu where I'll be talking about some of the recent features in Node.js

So far my list includes:

- Experimental TypeScript Support
- Experimental Web Storage API
- Progress on ESM compatitility
  - support requiring synchronous ESM graphs
  - module syntax detection
- Continued progress on performance
  - NODE_COMPILE_CACHE
  - Buffer performance improvements

Opening to ask if there are any other highlights the people think I should cover?

**Comment by mhdawson** [comment]
@nodejs/tsc if you have chance your input on this would be appreciated.

**Comment by anonrig** [comment]
node --run is stable now.

**Comment by targos** [comment]
Maybe `node:sqlite` ? I personally find that more interesting than Web Storage for Node.js use cases.

**Comment by mhdawson** [comment]
@targos thanks, I had assumed that under Experimental Web Storage API, but it might be worth covering separately.

**Comment by mhdawson** [comment]
Thanks for the comments/suggestions. Closing as its been a week.
