### ISSUE TITLE
Chair for TSC meeting Oct 30.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1640]
I have a conflict I can't move on Oct 30.

@mcollina can you chair?

**Comment by mcollina** [comment]
Yes I can. I might be 5 minutes late, so if somebody else can start the zoom call, it would be better.

**Comment by mhdawson** [comment]
@mcollina thanks for chairing, @nodejs/tsc can somebody else start the zoom call?

**Comment by RafaelGSS** [comment]
I can start the zoom call.

**Comment by mhdawson** [comment]
I'm going to close this issue as we've confirmed that @mcollina will chair and @RafaelGSS can start the zoom call. Thanks to both of you!

**Comment by ruyadorno** [comment]
thanks for the ping @mhdawson I thought I had a free scheduled tomorrow but turns out not to be the case! thanks @RafaelGSS for jumping in!
