### ISSUE TITLE
Requesting access to https://github.com/nodejs-private/security-release

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/TSC#1644]
I have access to https://github.com/nodejs-private/node-private but not https://github.com/nodejs-private/security-release, leaving me somewhat in the dark on _when_ exactly a security release is supposed to happen.

I also don't seem to have access to h1 anymore. Not that I really missed it but I am probably missing out on things.

**Comment by RafaelGSS** [comment]
Can you check if you have access?

**Comment by bnoordhuis** [comment]
Thanks @RafaelGSS, works.
