### ISSUE TITLE
TSC meeting for the week of Nov 6th - Chair needed

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#1647]
I'm going to be at NodeConf.eu the week of the 6th and won't be able to chair. @mcollina will be as well.

Is there anybody available who can chair, alternatively we could cancel for next week.

**Comment by richardlau** [comment]
Looking at [tsc-agenda labelled issues](https://github.com/search?q=org%3Anodejs+label%3Atsc-agenda+state%3Aopen+&type=issues) it looks like we could skip?

https://github.com/nodejs/Release/issues/1054 is newly added compared to the last agenda but I don't think it's time-sensitive and would need to be discussed this week.

I also think that the other items on the agenda were put there by people most likely to be attending the conf.

**Comment by RafaelGSS** [comment]
https://github.com/nodejs/Release/issues/1054 should be first discussed by the releasers. I've added the TSC label just for awareness.
