### ISSUE TITLE
Reduce the single point of failure for livestreaming meetings.

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/TSC#165]
Similar to https://github.com/nodejs/CTC/issues/24

I know @mikeal is also capable of doing these but he is not always around either so backup in case would be nice.

I am still capable of streaming most meeting, and my setup is well suited for it.

**Comment by jasnell** [comment]
@Fishrock123 ... what is the status on this?

**Comment by Trott** [comment]
Closing at it seems to be simultaneously less of an issue and a stalled issue. Feel free to comment or re-open if I'm misguided on closing it.
