### ISSUE TITLE
Travel fund request: Stephen Belanger

### ISSUE THREAD

**Issue by Qard** [nodejs/TSC#170]
**Event**: Collaborator Summit at Node Interactive NA
**Location**: Austin, TX, United States

I'd like to take part in the Diagnostics WG face-to-face and the VM Summit, if at all possible. I'd like to help more with LTS stuff too. Sadly, I have no current employer to pay my way.

Stipend request size: $800 USD should cover it.

**Comment by rvagg** [comment]
@nodejs/tsc let's see if we can get this approved here with enough votes. Please add an explicit +1 if you're on the TSC and approve this. We need to move fast, though.

+1 from me, and @Qard go ahead and make the bookings if you have enough cash laying around to cover it, I'll make sure you get reimbursed in some way even if it's from my own pocket.

**Comment by indutny** [comment]
👍

**Comment by cjihrig** [comment]
+1

**Comment by Qard** [comment]
Actually I'm a bit unclear on distinction between Collaboration Summit and Node Interactive NA. I see a statement in https://github.com/nodejs/summit/issues/35 that registration has closed. Is that just for the Code and Learn part? I specifically just want to attend the Diagnostics and VM meetings.

Do I need a Node Interactive NA ticket for this? Would I just attend Thursday and Friday?

**Comment by rvagg** [comment]
@hackygolucky can you clarify how this is all working out?

**Comment by mikeal** [comment]
@rvagg we had more people sign up that we have room to fit :)

We expect some people not to show who initially signed up. We will make affordances for any committers and WG members to get in even after we're full up on RSVP.

**Comment by Qard** [comment]
I've booked a flight and hotel for the whole event (including NI NA itself) and whatever I can get back would be much appreciated! Flight and hotel ended up being about $850. I can share receipts with the appropriate people. With the conf tickets being another $800, it's certainly a pricy trip. 😅

**Comment by TheAlphaNerd** [comment]
@stephenbelanger if you volunteer for code and learn you can get a free
ticket

**Comment by Qard** [comment]
Oh yeah, I'm definitely into that. Free ticket or otherwise! 😸

**Comment by yasinaydin** [comment]
@TheAlphaNerd free ticket for what? Conference ticket or plane ticket?

**Comment by TheAlphaNerd** [comment]
conference

**Comment by yasinaydin** [comment]
Ok, thanks. I asked because I woud be so happy to attend the conference but I don't think my company would support the travel cost.

**Comment by Fishrock123** [comment]
+1 for getting @Qard there if possible

**Comment by nebrius** [comment]
+1

**Comment by bnoordhuis** [comment]
Here, have another +1.

**Comment by jasnell** [comment]
+1

**Comment by jasnell** [comment]
I assume this can be closed now? If not, please re-open
