### ISSUE TITLE
Travel fund request: Italo A. Casas

### ISSUE THREAD

**Issue by italoacasas** [nodejs/TSC#171]
Event: Collaborator Summit at Node Interactive NA
Location: Austin, TX, United States

I'd like to take part of the Collaborator Summit in Austin. Because the short notice time my current employer is not able to fund me. 

I would like to ask if is possible, since I'm pretty new in the Core (last week was my onboarding session with Trott) but my first PR in core was in May.

I live in Florida, the amount should be something close to ~$800

**Comment by rvagg** [comment]
+1 from me for our newest collaborator

@nodejs/tsc can we get some +1's on this please?

**Comment by cjihrig** [comment]
+1

**Comment by jasnell** [comment]
+1

**Comment by Fishrock123** [comment]
+1

**Comment by indutny** [comment]
+1

**Comment by nebrius** [comment]
+1

**Comment by italoacasas** [comment]
@rvagg should I go ahead and buy the ticket or should I wait ?

**Comment by rvagg** [comment]
doh! sorry @italoacasas! yes you should get to Austin if you can! sorry for the late response

**Comment by italoacasas** [comment]
👌🏻

**Comment by yasinaydin** [comment]
+1

**Comment by jasnell** [comment]
I assume this can be closed now? If not, please re-open
