### ISSUE TITLE
Permission to edit Board Meeting video

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#172]
The Board Meeting was posted to YouTube yesterday:
https://www.youtube.com/watch?v=hYNJBuB8B60

It has 10:15 at the beginning of people eating food, chatting, and some cat herding. The video is only 36 min long.

I'd like to trim that first 10:15 from the video- this can be done with the YouTube editor and is very simple.

...BUT I didn't want to modify it without making sure it is ok. @rvagg - as the board rep: can you give me the OK?

**Comment by rvagg** [comment]
Yes, do it. It was a bit of a shambles getting the technology sorted out tbh. Nothing material was covered before we launched into the real meeting.

**Comment by williamkapke** [comment]
Done!... but YouTube is being really slow to complete the edit.
