### ISSUE TITLE
Node.js Foundation Technical Steering Committee (TSC) Meeting 2016-12-01 (private only)

### ISSUE THREAD

**Issue by rvagg** [nodejs/TSC#173]
Folks, instead of doing a normal public TSC meeting, I'd like to hold a private in-person meeting for those of us at Austin for Node.js Interactive and hopefully with a connection to Uberconference for anyone not here on the TSC that wants to join in. Mainly to debrief from the board meeting. While I'd prefer to not have to do this all privately we're bound by the same rules that push a lot of content from the board meetings into private (primarily legal and financial).

Same timeslot as usual, 2pm in Austin (just a proposal for now, if anyone is more in tune with the agenda tomorrow thinks this will be a problem please speak up!). I'm trying to line up a space to do this, I'm hoping for the room labelled Boardroom on level 4 of the JW but I'll update this thread with details when I can pin everything down.

## Time

**UTC Thu 01-Dec-2016 20:00**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Thu 01-Dec-2016 12:00 |
| US / Mountain | Thu 01-Dec-2016 13:00 |
| US / Central  | Thu 01-Dec-2016 14:00 |
| US / Eastern  | Thu 01-Dec-2016 15:00 |
| Amsterdam     | Thu 01-Dec-2016 21:00 |
| Moscow        | Thu 01-Dec-2016 23:00 |
| Chennai       | Fri 02-Dec-2016 01:30 |
| Tokyo         | Fri 02-Dec-2016 05:00 |
| Sydney        | Fri 02-Dec-2016 07:00 |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Technical%20Steering%20Committee%20(TSC)+Meeting+2016-12-01&iso=20161201T20
* or http://www.wolframalpha.com/input/?i=8pm+UTC%2C+Dec+01%2C+2016+in+local+time

## Invited

* Ben Noordhuis @bnoordhuis (TSC)
* Bryan Hughes @nebrius (TSC)
* Chris Dickinson @chrisdickinson (TSC)
* Colin Ihrig @cjihrig (TSC)
* Jeremiah Senkpiel @Fishrock123 (TSC)
* Fedor Indutny @indutny (TSC)
* James M Snell @jasnell (TSC)
* Josh Gavant @joshgav (observer/Microsoft)
* Mikeal Rogers @mikeal (observer/Node.js Foundation)
* Brian White @mscdex (TSC)
* Bert Belder @piscisaureus (TSC)
* Rod Vagg @rvagg (TSC)
* Shigeki Ohtsu @shigeki (TSC)
* Trevor Norris @trevnorris (TSC)
* William Kapke @williamkapke (observer)
* Jenn Turner @renrutnnej (observer)
* Tracy Hinds @hackygolucky (observer/Node.js Foundation)
* Anna Henningson (observer/CTC)
* Michael Dawson (observer/CTC)

**Comment by jasnell** [comment]
2pm could bump up against some of the WG breakouts that are planned. I'll be helping to lead the vm neutrality breakout, for instance. I definitely think we should make sure there is time for the TSC/CTC members who are here to meet but we may need to be flexible on the times.

**Comment by rvagg** [comment]
I've spoken to a couple of people this morning and they've agreed that moving this to lunch time, 12-1pm would be best so we don't conflict so much.

So, grab some lunch and head in to the Boardroom at the end of the hall at 12:00. Remote participants can hop on Uberconference and we'll try and let you hear what's going on.

**Comment by nebrius** [comment]
Just to clarify, is lunch provided today, or do we need to grab it on our own?

**Comment by nebrius** [comment]
Just confirmed that lunch is _not_ provided as part of the summit (it was uncertain in the summit thread AFAICT). FYI I'll probably be about 5 minutes late

**Comment by addaleax** [comment]
I think @joshgav took notes here, are they going to be shared somewhere?

**Comment by joshgav** [comment]
I took down a list of key points I could share privately. Generally, we talked about a) regular F2F's and b) how we could continue building and learning from the community.
