### ISSUE TITLE
Travel fund request for Anna Henningsen for TC39 in January

### ISSUE THREAD

**Issue by addaleax** [nodejs/TSC#176]
**Event**: TC39 meeting January 24–26, 2017
**Location**: San Jose, CA, US

Hi everyone! I’ve been invited to take part in the TC39 meeting in January as a guest, as members of the committee seek to broaden the range of backgrounds that the participants have. While TC39 itself is apparently making plans for being able to make travel funding available, that won’t be implemented until after the next meeting, so I’d like to formally ask the TSC for financial support in this. I hope that is okay, since if I take part in representing anybody’s stance on things there in the future, it would obviously be Node’s.

Stipend request size: I don’t think there is any reason why this should be more expensive than NINA, so I guess $3,000 is a good maximum. (Since the Foundation paid directly for travel & lodging there, I don’t know how much that actually was.)

**Comment by addaleax** [comment]
Also maybe just fyi @nodejs/tc39 ^^^^

**Comment by indutny** [comment]
LGTM

**Comment by ljharb** [comment]
I'm happy to help you prepare for your first meeting in any way I can!

**Comment by mikeal** [comment]
This is great. I'm just curious, which TC39 member invited you this time around?

**Comment by addaleax** [comment]
@mikeal I was approached by James Kyle and will be a guest on Google’s side there :)

**Comment by mikeal** [comment]
@addaleax great! thanks :)

**Comment by bnoordhuis** [comment]
What are you hoping to accomplish or participate in?  Most of the TC39 discussions aren't directly relevant to node.js.

Consider the environmental impact as well.  One mainland Europe -> California return trip puts out more CO2 than my four person household does in four months.  It's much friendlier to the environment to send someone local.

**Comment by ljharb** [comment]
@bnoordhuis modules, which are directly relevant to node.js, have been discussed in at least 3 of the last 4 meetings I can recall, and will certainly continue to be discussed in January.

It's also worth noting that the plane will be flying whether or not @addaleax has a ticket on it, so the differential environmental impact is negligible.

**Comment by rvagg** [comment]
+1 from me, great news

**Comment by addaleax** [comment]
I know that so far I have been rather passive as far as the modules discussion was concerned, but yes, that would obviously be something I’ll want to catch up on.

> It's also worth noting that the plane will be flying whether or not @addaleax has a ticket on it, so the differential environmental impact is negligible.

I can’t say the vegetarian in me doesn’t cringe a little over this reasoning ;)

**Comment by bnoordhuis** [comment]
> modules, which are directly relevant to node.js, have been discussed in at least 3 of the last 4 meetings I can recall, and will certainly continue to be discussed in January.

Don't we already have several people to represent the node viewpoint?  @bmeck, @piscisaureus, @jasnell, you?

> It's also worth noting that the plane will be flying whether or not @addaleax has a ticket on it

That's both defeatist and logically flawed.  Air travel is purely demand-based: if enough people don't buy a ticket, that plane is staying in its hangar.  We are a big and well-known project, we can set a good example.

**Comment by TheAlphaNerd** [comment]
Looking at the TC39 [meeting schedule[(http://www.ecma-international.org/memento/TC39-M.htm) it would not appear that there is a meeting in Europe next year. There isn't even anything on the west coast until May.

While we may have more representation from the project than we have had in the past I don't think we should be underestimating the value of working with individuals in person. While I do not have a vote here I want to push that I do not feel focusing on the carbon footprint is thinking about the long term benefits of this experience.

As for setting a good example, I think it is an amazing example to show that as a project we are supporting an individual who has worked with us for just over a year at the time of the meetings has been able to have enough success and respect in the organization that we are going to sponsor them to the TC39.

Congrats on the invite @addaleax

**Comment by jasnell** [comment]
The two goals of having more Node.js representation in the room and broadening the range of backgrounds of individuals participating in TC-39 are excellent reasons on their own to support this. @addaleax would be a fantastic representative here. I do worry about the sustainability of it over time given the ECMA pay-for-play membership and participation rules but hopefully TC-39 is wanting to make a real effort here and hopefully the invitation is not just a one time thing. I'm not quite sure how carbon footprint enters into the discussion. +1 to the stipend request.

**Comment by nebrius** [comment]
+1 to the stipend request, for the reasons @jasnell mentioned

**Comment by mikeal** [comment]
After my first TC39 meeting I was surprised at how many of these specs do directly impact us. There's a lot of work happening there that isn't controversial and as a result is not debated on Twitter endlessly so most people don't know about it, but it is good work and is highly relevant to us.

Also, the number of people representing a particular user community is important. There's a lot of "in the room" discussion and, for lack of a better term, politics. It's not something anyone can do alone and the more people we have the more political capital we have. As it stands we have roughly the same number of people representing Node.js users in TC39 are there are "people that really loved scheme" in TC39.

I'm working on a long term solution that will send me there on a regular basis as well.

**Comment by Fishrock123** [comment]
+1, Sounds good to me. So many people are effected by the decisions made there (including us) that it's be great to send more perspective(s) there.

**Comment by piscisaureus** [comment]
I'm generally in favor of having more node.js people at TC39. 
The next step of course would be that we come there with a bit of an agenda, maybe "node.js" needs a TC39 workgroup to identify topics that impact us and decide what our position is?

That said, I think you (@addaleax) you might find it taxing to make the transatlantic trip an additional 6 times a year. That's not a reason to reject travel funding though.

+1 on the stipend request

**Comment by cjihrig** [comment]
+1 from me.

**Comment by addaleax** [comment]
If I’m counting correctly this has passed. (Sorry for being a bit late to catch up, it’s all a bit holidays-y right now… :smile:)

@mikeal Could you set me up with the Foundation people who book flights etc. again? This is not the kind of money for which reimbursements would work, again…
