### ISSUE TITLE
Node.js Foundation Technical Steering Committee (TSC) Meeting 2016-12-29 — Casual sync

### ISSUE THREAD

**Issue by rvagg** [nodejs/TSC#182]
I'm proposing a slightly different meeting this week. Experience from CTC participation over the last couple of weeks suggests it will be harder than usual to get a focused group together so let's just have a casual sync rather than a formal meeting. If there's anything pressing that anyone has to discuss then please bring it, I'm not seeing anything urgent that has made any progress since our last meeting.

The only thing I'd like to put on notice for discussion is #179 and the proposal for a new top-level community-focused group. There is an outstanding question there about where this group will be housed and how it will relate to the technical group. Being another top-level group it wouldn't come under the TSC like everything else in github/nodejs but does it make sense to push its locus to somewhere else on GitHub or even off GitHub all together? @hackygolucky has some thoughts and questions in this area but really needs broad input from us, so please come prepared to at least contribute to the initial discussion.

## Time

**UTC Thu 29-Dec-2016 20:00**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Thu 29-Dec-2016 12:00 |
| US / Mountain | Thu 29-Dec-2016 13:00 |
| US / Central  | Thu 29-Dec-2016 14:00 |
| US / Eastern  | Thu 29-Dec-2016 15:00 |
| Amsterdam     | Thu 29-Dec-2016 21:00 |
| Moscow        | Thu 29-Dec-2016 23:00 |
| Chennai       | Fri 30-Dec-2016 01:30 |
| Tokyo         | Fri 30-Dec-2016 05:00 |
| Sydney        | Fri 30-Dec-2016 07:00 |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Technical%20Steering%20Committee%20(TSC)+Meeting+2016-12-29&iso=20161229T20
* or http://www.wolframalpha.com/input/?i=8pm+UTC%2C+Dec+29%2C+2016+in+local+time

## Invited

* Ben Noordhuis @bnoordhuis (TSC)
* Bryan Hughes @nebrius (TSC)
* Chris Dickinson @chrisdickinson (TSC)
* Colin Ihrig @cjihrig (TSC)
* Jeremiah Senkpiel @Fishrock123 (TSC)
* Fedor Indutny @indutny (TSC)
* James M Snell @jasnell (TSC)
* Josh Gavant @joshgav (observer/Microsoft)
* Mikeal Rogers @mikeal (observer/Node.js Foundation)
* Brian White @mscdex (TSC)
* Bert Belder @piscisaureus (TSC)
* Rod Vagg @rvagg (TSC)
* Shigeki Ohtsu @shigeki (TSC)
* Trevor Norris @trevnorris (TSC)
* William Kapke @williamkapke (observer)
* Jenn Turner @renrutnnej (observer)
* Tracy Hinds @hackygolucky (observer/Node.js Foundation)
* Anna Henningson (observer/CTC)
* Michael Dawson (observer/CTC)

## Joining the meeting

Uberconference; participants should have the link & numbers, contact me if you don't.

A standing invitation exists for all @nodejs/CTC members who are not also TSC members to attend in observer capacity.

**Comment by bnoordhuis** [comment]
I'm on holiday until mid-January and won't be participating.  I scanned #179 and I'm not sure what it is concretely proposing so I'm going to abstain for now.
