### ISSUE TITLE
Which repos should we pin?

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#189]
I noticed that we have some repositories pinned now but I'm not sure how we decided which ones to highlight or possibly if it just happened automatically.

We should have a discussion about which six repositories we would like to highlight on the front page.

**Comment by MylesBorins** [comment]
The current 6 make a lot of sense to me

**Comment by williamkapke** [comment]
Maybe https://github.com/nodejs/help should be pinned 🤔

**Comment by mikeal** [comment]
I don't think that most people care about the CTC repo :/

**Comment by Fishrock123** [comment]
> I noticed that we have some repositories pinned now but I'm not sure how we decided which ones to highlight or possibly if it just happened automatically.

I just put up the 6 I figured were most important.

**Comment by mikeal** [comment]
Do we have stats on which are the most viewed?

**Comment by Trott** [comment]
> Do we have stats on which are the most viewed?

You can go to the Traffic stats in individual repositories.

Views in the last two weeks:

nodejs/node: 129014 
nodejs/CTC: 939
nodejs/help: 6554

Seems consistent with the suggestion that nodejs/help is likely more relevant/useful to users than nodejs/CTC.

**Comment by Trott** [comment]
(TSC had even fewer views: 877.)

**Comment by Trott** [comment]
Aw, heck, might as well round out the other pinned ones:

LTS: 10293
nodejs.org: 1888
node-eps: 891

**Comment by Trott** [comment]
docker-node: 12377

😮

**Comment by Trott** [comment]
Easier metric to gather without having to write a screen-scraper might be stars and/or forks.

**Comment by targos** [comment]
I made a little script to gather the stats for public repos: https://github.com/targos/nodejs-stats/blob/master/stats.md

Top of the list (sorted by unique view count):

| Repo | Stars | Watchers | Forks | Unique views | Total views |
| ---- | ----: | -------: | ----: | -----------: | ----------: |
| node | 30339 | 30339 | 5469 | 141094 | 47442 |
| node-v0.x-archive | 36752 | 36752 | 8262 | 41058 | 29268 |
| node-gyp | 2779 | 2779 | 510 | 35547 | 16809 |
| LTS | 633 | 633 | 66 | 11170 | 8450 |
| help | 123 | 123 | 30 | 7116 | 4946 |
| docker-node | 914 | 914 | 207 | 13600 | 4513 |
| nan | 1612 | 1612 | 250 | 7626 | 1665 |
| http-parser | 3013 | 3013 | 848 | 2854 | 1040 |
| node-chakracore | 908 | 908 | 71 | 1991 | 793 |
| nodejs.org | 530 | 530 | 843 | 2098 | 656 |
| NG | 96 | 96 | 2 | 827 | 635 |
| node-addon-examples | 681 | 681 | 216 | 4642 | 574 |
| readable-stream | 477 | 477 | 93 | 1523 | 537 |
| promises | 93 | 93 | 3 | 680 | 509 |
| node-eps | 208 | 208 | 31 | 958 | 492 |
| CTC | 27 | 27 | 7 | 1018 | 437 |
| build | 131 | 131 | 49 | 1078 | 345 |
| education | 156 | 156 | 12 | 608 | 323 |
| TSC | 51 | 51 | 27 | 961 | 253 |
| http2 | 115 | 115 | 15 | 584 | 193 |
| roadmap | 133 | 133 | 40 | 192 | 119 |
| benchmarking | 50 | 50 | 18 | 348 | 113 |
| evangelism | 188 | 188 | 34 | 345 | 113 |
| nodejs-ko | 154 | 154 | 44 | 783 | 98 |
| abi-stable-node | 26 | 26 | 7 | 263 | 89 |

**Comment by Fishrock123** [comment]
I don't think we should put up what is necessarily already most viewed - we should be putting up what is most important to surface and otherwise lost in the ocean.

**Comment by Trott** [comment]
> I don't think we should put up what is necessarily already most viewed

I don't think anyone is advocating blindly putting up what is most viewed. The point is that we shouldn't use data to inform our decisions.

**Comment by Trott** [comment]
If I had my druthers: 

Pin node, nodejs.org, and help.

Let the other three slots rotate through via whatever mechanism GitHub uses to display/rotate repos. (I think it uses the most recently updated repositories.)

Totally open to other ideas (including just leaving it as is). I'm sure we could bikeshed on this for years if we wanted to.

**Comment by mikeal** [comment]
I'm a big fan of @Trott's plan.

I'd like to avoid linking people to "process" repos (LTS, CTC, TSC) because it's really hard to confuse what they are for and log issues there that should be in the code repo they are associated with.

**Comment by MylesBorins** [comment]
I would like to suggest that LTS should be included in that list. It is the only place to find the schedule and information about releases

**Comment by evanlucas** [comment]
I like @Trott's suggestion. I think having `node-gyp` and `nan` as well would be valuable since they are repos for packages used by lots of people in the ecosystem as well. I find readable-stream to be a bit different since it gets vendor'd from core.

**Comment by Fishrock123** [comment]
> Let the other three slots rotate through via whatever mechanism GitHub uses to display/rotate repos. (I think it uses the most recently updated repositories.)

IIRC it does nothing.

**Comment by MylesBorins** [comment]
Perhaps then we can do

* node
* nodejs.org
* help
* lts
* node-gyp
* nan

???

**Comment by Fishrock123** [comment]
I will note that I do actually use these links a bit, specifically for the LTS, TSC, and CTC repos. I suppose I could just type it in the address bar, but...

I'd totally drop the EP repo for the help repo tho.

**Comment by evanlucas** [comment]
@Fishrock123 yea I use them too. 

IMO, help should the top one. I would much rather have a core issue opened on help first over a help issue opened in core

**Comment by Fishrock123** [comment]
Updated them like so for now:

<img width="998" alt="screen shot 2017-01-04 at 3 13 18 pm" src="https://cloud.githubusercontent.com/assets/1093990/21657459/5d572cc4-d290-11e6-8712-7ff18ac894b8.png">

I do think we should improve the descriptions of the Website, LTS, CTC, and TSC repos though.

**Comment by mikeal** [comment]
I just want to point out that the most active contributors in the org are not very representative of the "average" person hitting the org page.

That's why I would like to bury the process repos, although Myles has a really good point about the LTS repo including release scheduling info a lot of people care about, that's probably one of the reasons the views are so high.

**Comment by Trott** [comment]
> I just want to point out that the most active contributors in the org are not very representative of the "average" person hitting the org page.

Yes, please, let's not use pinned repositories as bookmarks for our power users. We can use it as a "you might be looking for..." for new users or any of a number of other things instead.

I think TSC and CTC should go because even people who are actually ON those committees have different ideas about what the differences are. Presenting it concisely in a way users will understand will be challenging. And the average user will have no need to ever look at those repos or open issues there.

That said, the current state of help, node, and nodejs.org across the top is a big improvement and I'm happy enough with that, so I might even stop talking now. Maybe.

**Comment by mikeal** [comment]
Maybe we should use the top row as "things people are probably looking for" and use the bottom row for "things we're trying to get more people to pay attention to."

Maybe we should stick build, benchmarking, citgm, and other repos that are super important and doing a ton of work but possibly not as well known as others. I'm also assuming those repos all have good READMEs.

**Comment by nebrius** [comment]
> Maybe we should stick build, benchmarking, citgm, and other repos that are super important and doing a ton of work but possibly not as well known as others. I'm also assuming those repos all have good READMEs.

That brings up a really good point. Not having a README, even if the repo is important, might be worse than not linking to the repo.

Ideally, I think all repos that involve code (e.g. not nodejs/help) should have at minimum:

- Purpose/scope of the repo
- How to use the thing in the repo (build instructions, etc)
- How to file an issue when you have a problem
- How to submit a PR
- How to join the group, if it's a working group or other member based group

Here is my personal opinion of the README's and how they match those points, I'd like to hear what others think

- nodejs/help: it's functional but sparse.
  - We include a link in the README for opening a new issue, but provide no guidance for what goes in the issue. Ideally we'd also have an issue template in the repo.
- nodejs/node: well documented
- nodejs/nodejs.org: well documented
- nodejs/LTS: Has a lot of great information about the LTS schedule and purpose of the repo, but lacks contributing information currently.

I agree that TSC and CTC aren't good candidates for pinned repos. I'd put node-eps on there because we do see some people come in to comment on issues being talked about much more broadly (e.g. promises and modules). It's probably not that high profile in the grand scheme of things, especially compared to nodejs/help and nodejs/node, but I think it has value and could be nice to see more traffic going to it.

**Comment by williamkapke** [comment]
@nebrius Thanks for bringing that up- can we move it to a new issue? I think it's a good discussion to have.

**Comment by nebrius** [comment]
> @nebrius Thanks for bringing that up- can we move it to a new issue? I think it's a good discussion to have. It's on the same topic that was mentioned in the last meeting about repo "minimum requirements"

Good call: https://github.com/nodejs/TSC/issues/191

**Comment by richardlau** [comment]
At some point in the ladt week(?) the pinned repositories changed and the help repository is no longer pinned -- Was this intentional?

**Comment by bnoordhuis** [comment]
I noticed that too.  I don't know who did that but unless anyone objects in the next day or so, I'll replace LTS or TSC with help.

**Comment by Trott** [comment]
> I noticed that too. I don't know who did that but unless anyone objects in the next day or so, I'll replace LTS or TSC with help.

+💯 on replacing TSC with help.

**Comment by nebrius** [comment]
Agreed, let's replace TSC with help. I think LTS will be more important for most people than TSC.

**Comment by ChALkeR** [comment]
After replacing TSC with help, perhaps it's worth to replace citgm (which is more an internal tool that collaborators generally know about) with something where new collaborators could start. E.g. if a person wants to contribute to Node.js (not necessary the core repo), but is not sure where to start — where should they look?

**Comment by bnoordhuis** [comment]
@ChALkeR makes a good suggestion but we currently don't have a 'getting started' repo.  Someone would have to volunteer to put some resources together.

I've removed TSC and pinned help, by the way.

**Comment by mikeal** [comment]
pulling @hackygolucky into this conversation as she's been putting together some "getting started" resources for the website.

**Comment by ChALkeR** [comment]
@bnoordhuis I changed the order a bit so that `node`, `LTS`, `help` are now on the first line, and `node-gyp`, `nan`, `citgm` are on the second line.

**Comment by jasnell** [comment]
Does this need to remain open?

**Comment by bnoordhuis** [comment]
No, I'll close.
