### ISSUE TITLE
Meeting December 3rd

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#19]
We should have a TSC meeting this Thursday to discuss libuv and any other pending business prior to the board meeting next week.

Let's use the same timeslot we do the CTC meetings in.

-Mikeal

**Comment by Fishrock123** [comment]
Regarding libuv, I'd like to discuss top-level projects in general as I missed the last meeting.

**Comment by mikeal** [comment]
@nodejs/tsc

**Comment by jasnell** [comment]
+1

**Comment by bnoordhuis** [comment]
I don't know if I can attend, I have social obligations tomorrow.

**Comment by jasnell** [comment]
@mikeal ... is this happening? 12pm pacific time correct?

**Comment by mikeal** [comment]
yes, same dialin as the CTC meeting. this week has been crazy so sorry for the lack of formality but we need to get a few resolutions knocked out :)
