### ISSUE TITLE
Bring 'node-inspect' (CLI Debugger) under the Foundation

### ISSUE THREAD

**Issue by joshgav** [nodejs/TSC#190]
As summarized in https://github.com/nodejs/diagnostics/issues/67, work is underway to replace Node's current built-in CLI debugger (`node debug`) with a new one compatible with the new Inspector Protocol. @jkrems has an implementation at https://github.com/buggerjs/node-inspect and work has begun in https://github.com/nodejs/node/pull/10187 to include this as a third-party dependency under "deps" in nodejs/node.

We'll likely also further integrate it into the standard Node binary so that `node debug` or `node inspect` work out-of-the-box as in the past, see https://github.com/nodejs/node/pull/10187 for discussion.

Since the CLI debugger is a significant component of Node core, and because we'd like to facilitate broader and deeper work on this basic diagnostic tool, the @nodejs/diagnostics WG recommends that the TSC:

1. Bring [node-inspect](https://github.com/buggerjs/node-inspect) under the governance of the Node Foundation.
2. Bring the [node-inspect](https://github.com/buggerjs/node-inspect) repo into the nodejs GitHub org.

I believe all necessary prerequisites as described in [TSC/Project-Lifecycle.md](https://github.com/nodejs/TSC/blob/master/Project-Lifecycle.md#applying-to-join) have been completed.

Thanks!

**Comment by mhdawson** [comment]
I'm +1 on moving forward on this.

**Comment by joshgav** [comment]
The TSC concluded in yesterday's meeting to bring in node-inspect as proposed, pending agreement from the CTC. I think the next step would be to ask @nodejs/ctc to chime in here or in https://github.com/nodejs/CTC/issues/40 to finalize.

@jasnell or @mhdawson can you please label with `ctc-agenda` or `ctc-review` to get people's attention? Thanks!

**Comment by MylesBorins** [comment]
Should we open a new issue for voting or just vote in the already open issue?

**Comment by joshgav** [comment]
@MylesBorins seems +1's here or in the CTC issue should be sufficient, there are a lot of issues open already :)

If we have enough votes in favor in the issues I'll collect them before the next TSC meeting and we can move forward, if not we can bring it up again in the Jan-25 CTC meeting to finalize.

Thanks!

**Comment by Trott** [comment]
Not sure if these are CTC votes or TSC votes. If CTC: I'm +1. (I'm not TSC.)

**Comment by Trott** [comment]
At today's CTC meeting, this received additional "yes" votes from @Fishrock123 @addaleax @mscdex @rvagg @bnoordhuis @thefourtheye @jasnell @ChALkeR and an implicit yes vote from @trevnorris. So that's 11 or 12 (depending on whether you count @trevnorris) yes votes, which is a majority of the CTC. This passes. 

I'll remove the `ctc-agenda` label. Hopefully someone knowledgable can indicate what the next step is now that this has passed. (CC @williamkapke I guess.)

**Comment by williamkapke** [comment]
It looks like all of the documents are in place -- awesome work @nodejs/diagnostics !

It just needs to be transferred and @rvagg needs to add it to the TSC's scope doc PR: https://github.com/nodejs/TSC/pull/144

**Comment by joshgav** [comment]
Thanks everyone, especially @jkrems for this donation! @nodejs/evangelism can you perhaps give him a shout-out in the next newsletter?

Repo is now available at https://github.com/nodejs/node-inspect 🎉

**Comment by jkrems** [comment]
If there's a shout-out in the newsletter, it would be good to also mention @groupon since they sponsored some of my work on node-inspect. :)

**Comment by Trott** [comment]
Ping @renrutnnej on the "shout-out in the newsletter" request. (Aside: Should @renrutnnej be added to @nodejs/evangelism?)

**Comment by renrutnnej** [comment]
Thanks for the heads up!
