### ISSUE TITLE
Ensure pinned repos have well documented READMEs

### ISSUE THREAD

**Issue by nebrius** [nodejs/TSC#191]
Bringing the conversation over from https://github.com/nodejs/TSC/issues/189#issuecomment-270529623, I think it's really important that these repos have well documented READMEs.

Ideally, I think all repos that involve code (e.g. not nodejs/help) should have at minimum:

- Purpose/scope of the repo
- How to use the thing in the repo (build instructions, etc)
- How to file an issue when you have a problem
- How to submit a PR
- How to join the group, if it's a working group or other member based group

Here is my personal opinion of the proposed pinned repo's README's and how they match the above points, I'd like to hear what others think:

- nodejs/help: it's functional but sparse.
  - We include a link in the README for opening a new issue, but provide no guidance for what goes in the issue. Ideally we'd also have an issue template in the repo.
- nodejs/node: well documented
- nodejs/nodejs.org: well documented
- nodejs/LTS: Has a lot of great information about the LTS schedule and purpose of the repo, but lacks contributing information currently.

**Comment by williamkapke** [comment]
I think this should apply to *all* repos.

This is where someone often jumps in and says: "Groups are autonomous! We can't make them do it!" We can **strongly recommend** it if nothing else. My experience is that _everyone_ wants to adhere to a cohesive GitHub community. I have not seen 1 example of this NOT being the case. 

One thing I would add: It should list who the members are- or reference to the group that is in charge.

There will be odd scenarios. For example, node-chakracore gets it's docs from upstream
....and all the i18n groups.

**Comment by williamkapke** [comment]
Issue template for nodejs/help: https://github.com/nodejs/help/pull/437

**Comment by nebrius** [comment]
> I think this should apply to all repos...

Totally agree with everything you mentioned! I was thinking that starting with the pinned repos could be a way to start with a more manageable chunk of work.

**Comment by jasnell** [comment]
Does this need to remain open?

**Comment by jasnell** [comment]
Closing because of lack of any further activity
