### ISSUE TITLE
Publishing WG meetings into the nodejs youtube account

### ISSUE THREAD

**Issue by mcollina** [nodejs/TSC#192]
Following up @Fishrock123 advice, may I get credentials (and maybe instructions) for publishing wg recording and HOA, on the nodejs account?

I created the whole setup for the streams-wg last time (here is the video https://www.youtube.com/watch?v=GVcZu6zgyMo).

We have a meeting tomorrow https://github.com/nodejs/readable-stream/issues/252, and I would like to do the same for https://github.com/nodejs/http2/issues/26 as well.

**Comment by williamkapke** [comment]
+1 !!

**Comment by Fishrock123** [comment]
Yep, sent you an invite as a Manager to the google... business page or whatever it is.

99% sure that gives you the ability to set up HOA. You should also be able to export / import that previous video to the Nodejs youtube I think.

The account can be switched to as shown here: https://github.com/nodejs/TSC/blob/master/Streaming/Streaming-To-Youtube.md#switch-account-to-nodejs

**Comment by Fishrock123** [comment]
(Note: _I_ do not know how to set up a HOA **from** the nodejs account.)

**Comment by mcollina** [comment]
I think I have set it all up correctly. I've scheduled them as I would have done in my profile.

**Comment by williamkapke** [comment]
Great work @mcollina 😄
