### ISSUE TITLE
Rotating meeting times

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/TSC#198]
Proposal: rotate meeting times like we do for CTC meetings.  The current time almost never works for me and I can't be the only one.

The CTC currently uses UTC 16:00, 20:00 and 05:00.  I can't get the table with local times to render properly so I'll just link to it: https://github.com/nodejs/CTC/blob/master/README.md#meeting-schedule

**Comment by joshgav** [comment]
I don't love the multiple times anymore than I bet most anyone else does, but it seems fair and appropriate for an international organization. So +1.

**Comment by nebrius** [comment]
I'm a +1 as well. Maybe we can coopt the CTC schedule, but 24 hours later, to keep things simpler?

**Comment by mhdawson** [comment]
Agree we need to find a solution that works for all those who want to attend.

**Comment by williamkapke** [comment]
For planning the CTC's schedule, @Trott created a spreadsheet that everyone filled out.

@rvagg created an additional TSC section for @nebrius and myself... since we are not in the CTC section. @piscisaureus was the only people not listed... so I added a line for him.

If you need the link to the spreadsheet again- email me for it, or ask me in IRC.

**Comment by williamkapke** [comment]
In our meeting, yesterday, we decided to try to just look for a new time that accommodates more/all TSC folks rather than having it rotate.

**Comment by Trott** [comment]
> For planning the CTC's schedule, @Trott created a spreadsheet that everyone filled out.

Small correction: @ChALkeR created the spreadsheet and it was his idea. Credit where its due and all that.

**Comment by piscisaureus** [comment]
@williamkapke Can you e-mail me the sheet link? bertbelder@nodejs.org

**Comment by williamkapke** [comment]
Looks like someone already sent it to you 👍

**Comment by piscisaureus** [comment]
Yeah @Chalker beat you to it!

**Comment by nebrius** [comment]
@williamkapke can you also email the the sheet link? It's possible I had it before but lost it? bryan@nebri.us

**Comment by jasnell** [comment]
hmm... I must have misplaced the link also, if someone can please send it my way again I'd be grateful.

**Comment by williamkapke** [comment]
Sent to @nebrius & @jasnell

**Comment by joshgav** [comment]
Tip for next time: If you've ever opened the spreadsheet before it'll show up in the list at https://docs.google.com/spreadsheets.

**Comment by bnoordhuis** [comment]
> In our meeting, yesterday, we decided to try to just look for a new time that accommodates more/all TSC folks rather than having it rotate.

This didn't happen and for that matter, I don't see a time slot that could possibly work for all TSC members.  Rotating times need to happen, I don't think there is a way around that.

**Comment by mikeal** [comment]
@bnoordhuis I think you're the primary person we need to accommodate, could you give us a breakdown of a good range of times that are better for you?

**Comment by Trott** [comment]
FWIW, I wrote a program to take calendar data from the spreadsheet and come up with fair times that aren't "fair" by being completely awful for everyone and also aren't "fair" by being the best times for "most" people which will just mean the best times for people in the Americas. If the spreadsheet data is up-to-date, I can run share the code and/or run it on that data and give you some ideas of times that might work well for the TSC.

**Comment by bnoordhuis** [comment]
I just realized that Fedor and Shigeki aren't active, that uncomplicates things (although that might be a cause and reaction thing - it's in the middle of the night for them.)

6 hours earlier or 12+ hours later would be ideal for me.  Failing that, Tuesday instead of Thursday one or two hours earlier.

**Comment by jasnell** [comment]
@nodejs/tsc @mikeal @williamkapke @ashleygwilliams @renrutnnej (observer) @hackygolucky @MylesBorins ... I have added a tab to https://docs.google.com/spreadsheets/d/1_CD_XRlVyXlu5RILUMhgTnIYVChUInv6exNO0xXvqi0/edit#gid=425904776 to collect availability for bi-weekly Thursday TSC meetings. As done with the CTC meeting times, please fill in your row in the table so that we can select rotating meeting times that work best internationally. If you do not yet have access to the table, please request access.
/cc @Trott

**Comment by williamkapke** [comment]
@nebrius @piscisaureus I copied your data along with mine to the new tab.

**Comment by nebrius** [comment]
> I copied your data along with mine to the new tab. You might want to make sure it is still valid though.

Thanks @williamkapke! I did have some edits to make. Turns out, I forgot to update this when I switched roles at Microsoft, and thus regular work meeting times.

**Comment by nebrius** [comment]
> although that might be a cause and reaction thing - it's in the middle of the night for them.

I suspect you're right @bnoordhuis.

My opinion is that, even though we could make this work with a fixed meeting time, I still think we should move to rotating meeting times because a) I would really like to see Fedor and Shigeki active again (if they want to be active again of course), which this could enable and b) this is an issue that will arise again when we want to onboard someone else from those timezones and I think it would be better to prepare in advance instead of having to scramble.

**Comment by mikeal** [comment]
> I would really like to see Fedor and Shigeki active again

Meetings should not be the primary mode of collaboration for any group in the project.

I'm all for adjusting meeting times to ensure everyone that is active can participate but if they aren't active in the discussions happening in the repo then I don't think we should be adjusting the meetings for them. *Nobody* should be staying silent on the repo and then popping into the meetings and we definitely shouldn't be trying to accommodate that.

That said, @bnoordhuis is quite active in the repo and not accommodated by the current meeting time so lets adjust.

**Comment by bnoordhuis** [comment]
> Meetings should not be the primary mode of collaboration for any group in the project.

I strongly agree, but... we did commit to a 25% meeting attendance rate last month.

**Comment by jasnell** [comment]
Not quite. We agreed to a minimal participation rule that included meetings, votes *or* discussions. Ideally someone would make as many meetings as possible but participating in other ways is good too.

**Comment by mikeal** [comment]
Honestly, we've been doing this so long at such a bad time for Ben that we should ask what the absolute best time is for Ben and then make everyone else deal with it for at least one meeting :stuck_out_tongue_closed_eyes:

**Comment by jasnell** [comment]
I'm pretty commited to adjusting the times at this point. If everyone can please take a moment to update the table with their Thursday availability I will likely select a time that works best for European participants.

**Comment by mikeal** [comment]
@jasnell currently, the table shows UTC 16 as a good time for everyone.

**Comment by jasnell** [comment]
@mikeal ... not that I'm seeing. On the `CTC Data` page, both @addaleax and @rvagg have marked UTC 16 as `0` (Impossible) for Wednesdays, and the `TSC Data` page has not been filled out completely for Thursdays. Assuming the availability for Thursdays is the same as Wednesdays, UTC 19 looks like the only time that would definitely work for all TSC members (albeit quite inconvenient for @rvagg and @shigeki).

**Comment by mikeal** [comment]
I'm seeing @addaleax as a 5 for UTC-16 but Rod hasn't filled it out yet.

**Comment by ChALkeR** [comment]
@Trott 
> FWIW, I wrote a program to take calendar data from the spreadsheet and come up with fair times that aren't "fair" by being completely awful for everyone and also aren't "fair" by being the best times for "most" people which will just mean the best times for people in the Americas.

You probably already handled that, but just in case: there are times that are strictly not better than other ones, e.g. for the CTC meeting, 21:00 UTC isn't better than 20:00 for anyone and 23:00 isn't better than 22:00 for anyone. Your program handles that correctly, right?

**Comment by Trott** [comment]
> You probably already handled that, but just in case: there are timeslots that are strictly not better than other ones, e.g. for the CTC meeting, 21:00 UTC isn't better than 20:00 for anyone and 23:00 isn't better than 22:00 for anyone. Your program handles that correctly, right?

It usually does almost by accident, but not always. Time to add more logic....

**Comment by jasnell** [comment]
This shouldn't need to remain open
