### ISSUE TITLE
Request regarding Node.js Foundation sponsored events in US

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#200]
@nodejs/tsc @hackygolucky @mikeal I request that, to the extent possible, no Node.js Foundation sponsored or hosted in-person events be planned or hosted within the borders of the United States for the foreseeable future. Exception to this given solely to provide meeting venues for legal permanent residents currently residing within the United States for whom International travel would currently be considered unsafe.

**Comment by mikeal** [comment]
I thought about something like this but quickly realized that there are many VISA holders in the United States that now cannot leave if they ever want to return.

Regardless, NINA 2017 is planned for Vancouver, BC already, so we have quite a bit of time before the 2018 planning to see what the long term ramifications of the EO are.

**Comment by jasnell** [comment]
As I said, exception should only be given to those currently within the United States for whom international travel would be dangerous or not recommended. If necessary, we can put funds towards remote participation options such as video conferencing tie-ins.

**Comment by nebrius** [comment]
Is NINA 2017 the next event being sponsored?

I think that our first responsibility as part of the Node.js Foundation leadership is to protect members of the Node.js community to the largest extent possible. Sadly, I must agree that this has now become a lot more difficult with recent moves by the US government.

I like @jasnell's idea of possibly investing in remote access for events. As @mikeal also pointed out, it's just as difficult or dangerous for a lot of folks within the US to leave, as it is for folks outside the US to get in :(

**Comment by jasnell** [comment]
Closing. This is still very much an issue, but I trust that the foundation has it well under control
