### ISSUE TITLE
GitHub Repo Topics

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/TSC#201]
GitHub introduced these today: https://github.com/blog/2309-introducing-topics

I've gone ahead and given nodejs/node an initial set of topics:

<img width="649" alt="screen shot 2017-01-31 at 4 48 49 pm" src="https://cloud.githubusercontent.com/assets/1093990/22485860/3b355efe-e7d5-11e6-833e-b0c9dc766191.png">

These were partially just my own thinking, and partially inspiration taken from the atom / electron repos.

**Comment by joshgav** [comment]
I think these are intended to help with searches and correlating related projects, so let's choose terms from the perspective of what best succinctly describes Node.

some suggestions: `streams`, `events`, `backend`, `fullstack`

I understand why we might list OS's to reflect on the multi-platform compatibility, but each term individually doesn't capture that well. What's a good short term for "multi-platform compatibility"?

**Comment by jasnell** [comment]
`asyncio`, `libuv`, `http`, `server`, etc also come to mind

**Comment by addaleax** [comment]
> What's a good short term for "multi-platform compatibility"?

`cross-platform` is kind of the standard term, no?

**Comment by joshgav** [comment]
@addaleax 

> cross-platform is kind of the standard term, no?

Well I wasn't sure if that was a Microsoft-ism 😉 , but yeah that's the term I use too, sometimes abbreviated as `xplat`.

**Comment by jasnell** [comment]
We've got a number of topics there. This likely doesn't need to be open still.
