### ISSUE TITLE
nominating @joshgav to the TSC

### ISSUE THREAD

**Issue by joshgav** [nodejs/TSC#205]
If I can be so forward, I'd like to nominate myself (@joshgav) for TSC membership. My qualifications include that I coordinate Node's Diagnostics WG and support technical and business decision making in the CTC and TSC. I'm also a Collaborator in core and make frequent doc and process contributions and occasional code contributions across the Node.js projects. I already attend and help run TSC meetings too.

I'm by nature a collaborator and consensus-builder who believes in [raising the tide and all boats](https://en.wikipedia.org/wiki/A_rising_tide_lifts_all_boats) together. I believe a great, reliable Node.js platform is good for all of us as individuals, as well as good for companies and products we may work for and support. That belief is reflected in what I try to do in the Diagnostics WG, i.e. drive capabilities for Node which can be built upon and enhanced by any and all.

From the [TSC README](https://github.com/nodejs/tsc#tsc-members):

> Candidates for membership tend to be people who have a competency for community management and a high tolerance and patience for process minutiae.

I'm quite passionate and sometimes perhaps a bit *im*patient :) but know how to keep that in check so that we can all make gradual progress together. In fact I think a combination of patience and passion is helpful in collaborative projects - patience to achieve gradual, continuous improvement; and passion to help through the inevitable occasional rough patches ;).

Thank you for your consideration!

**Comment by jasnell** [comment]
Seconded. We'll need to get you invited as an observer.... oh wait nevermind ;-) This is overdue, let's do it.

**Comment by Fishrock123** [comment]
I wasn't able to find it right now but while I don't think you can technically nominate yourself you can certainly ask to be nominated! (Or maybe that is the collaborator rules? bah, I forget.)

Second(?)-ing. @joshgav has been helping to represent Microsoft as an observer to the TSC for quite some time and has spent countless meetings recording excellent notes.

**Comment by williamkapke** [comment]
The docs are messy on this. With the yet-to-be-approved PR #142; They say... Folks can be added via a standard `TSC motion`... which is done by a Collaborator who adds the `tsc-agenda` label to an issue.

A Collaborator is someone that has been promoted up from a Committer.

This was obviously written when there wasn't the TSC/CTC split-- so, we now have an odd mess since the TSC doesn't have Collaborators directly and just saying "use the CTC Collaborators" excludes some folks. `//TODO: fix this!`

So, I would conclude that self nomination is not allowed. In this scenario- let's just use @Fishrock123's statement as the nomination and we'll move along from this hubbub. ;)

**Comment by joshgav** [comment]
Thanks @williamkapke and @Fishrock123 for getting this straight!

To be honest I started this thread cause I think I'll be able to contribute more as an official TSC member 😸

**Comment by rvagg** [comment]
Calling for a vote from @nodejs/TSC members please. So far, +1's from @jasnell, @bnoordhuis and @rvagg. For the rest, please indicate your vote here.

**Comment by nebrius** [comment]
+1 from me

**Comment by cjihrig** [comment]
Already 👍'ed it a while back, but that may not count. +1

**Comment by mscdex** [comment]
+1

**Comment by piscisaureus** [comment]
+1

**Comment by joshgav** [comment]
Passed in [last TSC meeting][], PR in #225.

[last TSC meeting]: https://github.com/nodejs/TSC/blob/master/meetings/2017-03-09.md#nominating-joshgav-to-the-tsc-205

Thank you all! Looking forward to continuing to work together to advance Node.js and JavaScript!
