### ISSUE TITLE
nominating Michael Dawson to the TSC

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#206]
It actually has not been clear whether or not @mhdawson is a voting member of the TSC or just an observer. If he is not currently a member, it would be good to make him a full member.

**Comment by cjihrig** [comment]
Does the TSC have the same rules about the number of representatives from a single company? If it's within the rules, +1 from me.

**Comment by mikeal** [comment]
The TSC definitely has those rules, they are defined in the TSC Charter the board passed.

["No more than one-fourth of the TSC members may be affiliated with the same employer."](https://github.com/nodejs/TSC/blob/master/TSC-Charter.md#section-4-establishment-of-the-tsc)

**Comment by addaleax** [comment]
There are 12 current TSC members and, iirc, 3 of them (Ben, Bert & James) are already affiliated with IBM, so that might be a problem? :/

**Comment by jasnell** [comment]
Good point. TBH I forgot that Bert was still on TSC.

**Comment by piscisaureus** [comment]
I think Michael Dawson absolutely deserves a TSC spot and he'll be much more useful than yours truly.
I would happily cede my TSC seat if that would make it possible.

cc @mhdawson @jasnell

**Comment by cjihrig** [comment]
With @jasnell leaving IBM, I'm +1 to getting @mhdawson on the TSC.

**Comment by jasnell** [comment]
@nodejs/tsc ... revisiting this. I've put it on the tsc-agenda. Now that I am officially started with nearForm, IBM is no longer at it's limit.

**Comment by rvagg** [comment]
@nodejs/tsc time for vote on this one. Best do it here because we're going to have trouble getting many people to a meeting this week so it'd be best if we can get the votes here then whoever is at the meeting this week can formalise it. 

+1 from me!

**Comment by bnoordhuis** [comment]
+1

**Comment by shigeki** [comment]
+1

**Comment by mscdex** [comment]
+1

**Comment by indutny** [comment]
👍

**Comment by jasnell** [comment]
+1

**Comment by cjihrig** [comment]
Still +1

**Comment by nebrius** [comment]
+1

**Comment by joshgav** [comment]
+1

**Comment by Fishrock123** [comment]
+1

**Comment by mhdawson** [comment]
PR to add landed, closing.
