### ISSUE TITLE
npm package management for node.js foundation modules

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#211]
We have a number of modules under the node.js foundation including:

```
https://github.com/nodejs/node-report
https://github.com/nodejs/node-inspect
```
and there may be others in the future.

I've looked at a few options of how we might manage the publishing of these modules which are listed below.  My recommendation is Option 1:

* Option 1 - create a user called something like "node-foundation" who we always add as one of the collaborators with admin rights and for which the password is maintained by the build workgroup.  We would then add individuals as collaborators who can also publish.  Generally, a module push could be done by the additional collaborators.  In the cases were collaborators other than "node-foundation" cease to be active, the build workgroup would provide continuity by using the node-foundation user to add additional collaborators who would have the ability to push the module.  The node-foundation user could also be used to remove collaborators if that was ever necessary.

* Option 2 - use the organization feature in npm.  This gives use better management of a team to manage the modules but means the module would be scoped.  I don't think we'd necessarily want the scope in the name, and I was told that it also prevents shrinkwrap from working,  which sounds like a deal-breaker.  Organizations are also a paid feature so we'd either need to budget modest funds or ask for the feature for free.

* Option 3 - Create a user called something like "node-foundation" and ensure it is used for all publishes.  We'd only publish through CI jobs so that access to the password would be limited.

* Option 4 - Create a user called something like "node-foundation" and ensure it is used for all publishes.  In this option we'd share the password so that the people who need to do publishes can do them directly.

An addition to Options 1, 2 and 4 would be to work on CI jobs so that publishes could be done more easily and consistently.  I believe we should plan this in regardless of the option chosen.

In searches on npm.js, the collaborator who last pushed the module shows up. In the case of Option 3 and 4 (or for any of them if we consistently use a CI job for publishes) that would always be the node-foundation user.  All collaborators are listed in alphabetical order on the main page for the module.

**Comment by ljharb** [comment]
Scopes should work fine with shrinkwrap on npm3+, as far as I know.

Option 2 would be the cleanest, Option 1 is next, Option 4 is last. Option 3 would remove the human component from publishing, so I'd discourage it.

**Comment by jasnell** [comment]
Option 2 is likely the best option moving forward but does not necessarily help with things that are already published and used without that scope (e.g. `readable-streams`). A hybrid of Options 1 and 2 are likely the best choices.

**Comment by sam-github** [comment]
We use npm2 in 4.x, which is LTS, I don't think we should use a strategy that causes pain to LTS users, which means avoiding scopes until all LTS releases support them.

**Comment by rvagg** [comment]
TSC discussion today: I'm advocating for option 1, we do something like that @ NodeSource, and Michael has feedback that the StrongLoop team does something similar. i.e. publish packages as normal, under normal user accounts but always _add_ an official NF user account for publish access so that if we need to, we can use the NF user to get access to it.

**Comment by jasnell** [comment]
+1 for option 1

**Comment by bnoordhuis** [comment]
I have a mild if possibly irrational preference for option 3: one NF account coupled with CI.

A single NF publisher looks official (less confusion about whether it's a NF package or not) and the CI would be a backstop for accidental or bad publishes, hopefully.

**Comment by ljharb** [comment]
For an anecdotal data point, at Airbnb we go with option 1 (https://www.npmjs.com/~airbnb) and I've not heard any complaints or commentary about the "officialness" of any of our packages.

Separately, we stick with the philosophy that publishes must always be manually initiated by a human as a backstop against mis-labeling semver ranges, since publishes are irrevocable.

**Comment by mhdawson** [comment]
Ok from what I see we have +1 for option 1 from myself, jasnell, rvagg along with agreement through comments or thumbs up from ljharb and sam-github.  

@bnoordhuis your preference was mildly for 3, but I think given the rest of the input unless you want to object to 1 instead, I'll move forward with option 1 as a start.  I still think we should also look at supporting publish with the CI but don't want to make it a blocker to moving forward for now.  If an when we get the CI jobs in place we can move to 3 if we think that makes sense at the time.

I'll look to create the npm user mid next week and co-ordinate with @jbergstroem to get the password added to the secrets rep.  Once thats done we'll move on to having that user added to the modules in npm.

**Comment by mhdawson** [comment]
Ok, created user ```nodejs-foundation```, next step is to get password into secrets repo.

**Comment by mhdawson** [comment]
Would also be good to figure out how to set avatar to be the node logo.

**Comment by gibfahn** [comment]
@mhdawson https://www.npmjs.com/~nodejs-foundation seems to have `build@iojs.org` as an email address. Is there a `nodejs.org` equivalent we could use?

**Comment by mhdawson** [comment]
@gibfahn I had looked for that and did not find any nodejs.org emails in the alias list. I thought I'd go with what was there and then update when I figured out if we had any nodejs.org equivalents.  @rvagg do we have nodejs.org emails as well ? I thought I'd go with what was there and then update

**Comment by jasnell** [comment]
@mikeal ... What's the current status on being able to use `@nodejs.org` email aliases?

**Comment by gdams** [comment]
@mhdawson setting the avatar on npm should just a case of creating an account on gravatar with the same email address and it should pull it in. I believe that's how I changed mine

**Comment by Fishrock123** [comment]
Wait, why `nodejs-foundation`? @chrisdickinson has `nodejs` iirc, we should just be able to get that.

**Comment by MylesBorins** [comment]
Added citgm to `nodejs-foundation`

**Comment by gibfahn** [comment]
>setting the avatar on npm should just a case of creating an account on gravatar with the same email address and it should pull it in. I believe that's how I changed mine

@mhdawson I'm pretty sure @gdams is correct about how you set the avatar. Would be really good to do this, having the right logo makes the account look more official.

**Comment by mhdawson** [comment]
I'll be getting back to this this week

**Comment by mhdawson** [comment]
Added userid/password info to build secrets

**Comment by mhdawson** [comment]
Ok, have added gravitar and it shows up for citgm in npmjs :)

**Comment by mhdawson** [comment]
Next step is to make sure all relevant modules have the user added to the npms.

I'm aware of 
  citgm - Myles added earlier
  node-report - I just added.
  node-inspect - created issue 

@rvagg, @jbergstroem I think you had mentioned there are some other npm modules as well.  Can you provide the list and if you have access add the nodejs-foundation user.

**Comment by mhdawson** [comment]
next going to make pr to add doc to build repo to capture how we are managing.

**Comment by mhdawson** [comment]
PR for adding doc into build repo to capture what we agreed to: https://github.com/mhdawson/build/blob/31601d1c4d0bcb0fe3cca54fcdcc179f5cf12975/doc/process/npm_management.md

**Comment by gibfahn** [comment]
>Wait, why nodejs-foundation? @chrisdickinson has nodejs iirc, we should just be able to get that.
 
@Fishrock123 any update on this? I think `nodejs` would be good if we can get it.

**Comment by mhdawson** [comment]
I went ahead with nodejs-foundation as I missed the earlier comment.  But if we do get nodejs, it will be simple to swap it in.  @Fishrock123 are you going to see if you can get the login creds from @chrisdickinson. If so just forward to me once you have them and we can do the swap.

**Comment by jasnell** [comment]
@mhdawson ... what's the current status on this? Should we leave this open?

**Comment by mhdawson** [comment]
The one thing I'd like us to do before we close is to get the nodejs-foundation user added to the rest of the modules.  @rvagg and @jbergstrom had mentioned there were are few others. I'll try to bring it up on the build WG meeting today,

**Comment by jbergstroem** [comment]
@mhdawson there's a few build related ones we have as part of the build repo. They're currently not packaged at npm.

**Comment by gibfahn** [comment]
@jbergstroem would it be worth pushing them to npm? If not then this is done.

Except for trying to find out if @chrisdickinson is willing to give us `@nodejs`.

**Comment by joaocgreis** [comment]
Should https://github.com/nodejs/node-gyp add the user as well? (cc @nodejs/node-gyp)

**Comment by bnoordhuis** [comment]
I'd take care of that but it looks like the npm registry is broken again, I get a 500 trying to add or remove owners.

**Comment by mhdawson** [comment]
Still need to get nodejs-foundation user added to node-gyp, nodejs-dist-indexer, nodejs-nightly-builder

**Comment by mhdawson** [comment]
Checked and there is still some discussion on how to manage the password in the secrets repo as well.

**Comment by bnoordhuis** [comment]
nodejs-foundation is now a proud (co-)owner of node-gyp.

**Comment by gibfahn** [comment]
https://twitter.com/isntitvacant/status/856194444248326145 from @chrisdickinson 

>2 weeks ago I turned that into an org and gave @Fishrock123 ownership.

@Fishrock123 and @mhdawson any chance you two could get together and convert `@nodejs-foundation` to `@nodejs`?

**Comment by Fishrock123** [comment]
If that is the favored path then sure.

**Comment by mhdawson** [comment]
I'm fine with any name so if you can give me enough access so that I can set a master password, I'll do that, store that in build secrets repo and then go through and add the new user (I guess org will need to look to see if that affects anything) to the relevant modules.

**Comment by jasnell** [comment]
Does this issue need to remain open?
@mhdawson ... what may be helpful is a write up added to the repository about how to use the foundation npm account.

**Comment by mhdawson** [comment]
@jasnell this is what I was waiting to land and is the doc: https://github.com/nodejs/build/pull/670

**Comment by jasnell** [comment]
oh nice... sorry I had missed that PR. Once that lands we can close this issue.

**Comment by mhdawson** [comment]
Just landed https://github.com/nodejs/build/pull/670, closing.
