### ISSUE TITLE
Figure out who's an admin on the old Google Groups

### ISSUE THREAD

**Issue by ThisIsMissEm** [nodejs/TSC#212]
I've asked around as I'm currently subscribed and can't unsubscribe, and will need an admin on the google groups to remove me from the group.

Backstory: google groups got messed up when my email changed from `deadname@` to `em@`, and there's no way for me to fix this.

**Comment by sam-github** [comment]
@mikeal maybe?

**Comment by bnoordhuis** [comment]
I believe it's @othiym23.

**Comment by othiym23** [comment]
Yes, I and @aredridel are the two administrators on the Google Group. Thanks for the mention, @bnoordhuis. @ThisIsMissEm, hit me up at othiym23@gmail.com with the address you want removed, and I'll get to it within the next day or so. Thanks, and sorry for the trouble!

**Comment by aredridel** [comment]
\o

**Comment by othiym23** [comment]
This has been done!
