### ISSUE TITLE
Nominating Anna Henningsen to the TSC

### ISSUE THREAD

**Issue by rvagg** [nodejs/TSC#214]
@addaleax is not an official member of the TSC but actively participates in meetings and the decision-making process that happens there as well as activity within this repository and across the breadth of Node Foundation!

**Comment by cjihrig** [comment]
+1

**Comment by jasnell** [comment]
Seconded... She's been attending the meetings regularly and would make an excellent full member. Big +1

**Comment by Fishrock123** [comment]
+1

**Comment by nebrius** [comment]
Big +1 from me too

**Comment by mhdawson** [comment]
Don't have a formal vote but +1 from me anyway.

**Comment by mhdawson** [comment]
What do we need to do to close on the vote ?

**Comment by addaleax** [comment]
@mhdawson Somebody needs to put it on the agenda, and we’ll finalize it in a meeting then (assuming we meet quorum, I guess).

**Comment by rvagg** [comment]
@nodejs/tsc time for vote on this one. Best do it here because we're going to have trouble getting many people to a meeting this week so it'd be best if we can get the votes here then whoever is at the meeting this week can formalise it. 

+1 from me!

**Comment by bnoordhuis** [comment]
+1

**Comment by shigeki** [comment]
+1

**Comment by mscdex** [comment]
+1

**Comment by jasnell** [comment]
+1

**Comment by cjihrig** [comment]
Still +1

**Comment by nebrius** [comment]
+1

**Comment by joshgav** [comment]
+1

**Comment by mhdawson** [comment]
PR to add landed, closing.
