### ISSUE TITLE
Travel Fund Request: Rich Trott, May 2017 Collaborators Summit

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#221]
Event: Collaborator Summit adjacent to JSConf EU
Location: Berlin, Germany

I'd like to take part in the (proposed?) Collaborator Summit in Berlin. I am not attending JSConf EU and my employer will not fund travel to the Collaborators Summit.

I live on the west coast of the United States. Round trip airfare will likely be around USD 900. Lodging will probably be around USD 400.

Even though details for the Collaborators Summit are not yet finalized, I'm asking about this now because travel costs are likely to go up at some point before too long. The summit is currently about 2 months away.

**Comment by cjihrig** [comment]
+1 from me, assuming the summit actually happens.

**Comment by nebrius** [comment]
+1 from me too.

**Comment by mikeal** [comment]
Are we still planning on doing a Code & Learn in Berlin?

**Comment by Trott** [comment]
> Are we still planning on doing a Code & Learn in Berlin?

¯\\_(ツ)_/¯

**Comment by mikeal** [comment]
@Trott the only reason I ask is because that has a separate, already approved, budget allocation to send and lodge you ;)

**Comment by Trott** [comment]
> @Trott the only reason I ask is because that has a separate, already approved, budget allocation to send and lodge you ;)

As I understand it, that budget request did not include JSConf EU. (It included NodeConf EU which might be what you're thinking of?)

**Comment by mikeal** [comment]
@Trott my mistake, ETOOMANYCONFERENCES.

**Comment by indutny** [comment]
👍

**Comment by Trott** [comment]
No idea if this ever made it to an agenda or a spreadsheet or anything, but I'm going to close it and withdraw the request. I wish I could make it work, but I don't think I can make it this time.
