### ISSUE TITLE
Add tdtsh to nodejs-ja

### ISSUE THREAD

**Issue by watilde** [nodejs/TSC#226]
From https://github.com/nodejs/Intl/issues/42. He is working for some translation works related to workshoppers in NodeSchool, and we've decided to welcome him to the `nodejs-ja` WG.

e.g.
+ https://github.com/evanlucas/learnyoumongo/pull/42
+ https://github.com/stevekane/promise-it-wont-hurt/pull/115

Could someone add him to org?

**Comment by bnoordhuis** [comment]
@tdtsh Invite should be in your inbox.

**Comment by tdtsh** [comment]
Thank you. I participated. :-)

**Comment by addaleax** [comment]
Looks like this can be closed now. :)

**Comment by watilde** [comment]
Yes it does. Thanks!
