### ISSUE TITLE
Travel Fund Request: Calvin Metcalf, May 2017 Collaborators Summit

### ISSUE THREAD

**Issue by calvinmetcalf** [nodejs/TSC#234]
Event: Collaborator Summit adjacent to JSConf EU
Location: Berlin, Germany

I'd like to take part in the Collaborator Summit in Berlin. I am not attending JSConf EU and my employer will not fund all the travel costs to the Collaborators Summit.

I live on the east coast of the United States. Round trip airfare will likely be around USD 400. Lodging will probably be around USD 200.

The @nodejs/streams wg face to face to hammer out some of the longer term issues with streams is the primary reason I'd like to be able to go.  I work for a small company and while they couldn't cover all of this, they may be able to cover the difference if I only get partial funding.

**Comment by cjihrig** [comment]
@calvinmetcalf I think you probably want to open this as a PR similar to https://github.com/nodejs/TSC/pull/230.

**Comment by calvinmetcalf** [comment]
ah woops ok thanks

**Comment by cjihrig** [comment]
Closing in favor of #235
