### ISSUE TITLE
Add fhinkel as owner

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#240]
when @fhinkel was added to CTC they were not given owner permissions on the org. I do know that ownership is currently being discussed, but we should give those permissions until a decision has been made

**Comment by addaleax** [comment]
Agreed, I added her as an owner.

**Comment by targos** [comment]
BTW she should also be added to the mailing list in https://github.com/nodejs/email/blob/master/iojs.org/aliases.json

**Comment by addaleax** [comment]
Thanks for the reminder, mhdawson and me also need to be added to the TSC mailing list. I’ll just do that in one batch.

**Comment by fhinkel** [comment]
Thanks!
