### ISSUE TITLE
New Executive Director

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#241]
It has been two years since we started the Node.js Foundation.

When I first took on the task of leading the foundation it was in order to support a project under very new and untested organizing principals. 

We had not yet shown that these principals could handle the challenges of stability and long term support our ecosystem demands. We did not yet know if these ideas could handle the number of contributors doubling, then doubling again, and then once again. I believed they would, as did others, but we were still learning as we grew, just as we continue to learn today. 

But the project, and the foundation, have very different needs today than they did back then. 

Today, most of our project leaders are not those that created these policies but those that began contributing under them. In just a few years the new faces outnumber the old. As the project has become healthy and sustainable the need for my direct involvement has dwindled and I've turned more and more to the institutional needs of the Node.js Foundation. I have always been less adept as a salesman than I am as a community organizer and for some time now I've been looking for the right person to lead the foundation as the role has changed.

Node.js has a strong project, an even stronger community, and it deserves a strong institution ensuring its longevity. We have never had funding commensurate with our adoption and in order to achieve it we need a great Executive Director to lead the Node.js Foundation.

Mark Hinkle has been the VP of Marketing for the Linux Foundation for almost the entire time I’ve been with the Linux Foundation so I’ve had plenty of time to get to know him. After hearing so much about how great our community is Mark decided he had to see it for himself and attended Node.js Interactive in Austin of last year. I’ve rarely seen someone with so much experience in Open Source so excited by our community, we truly have something amazing and unique.

I couldn't be happier to let you all know that Mark Hinkle is now, officially, the Executive Director of the Node.js Foundation.

Over the next few months I'll be shifting the administrative responsibilities over to Mark. Eventually I'll be stepping away even further and Mark will be working more directly with the CTC/TSC.

[More info about Mark is up on Medium.](https://medium.com/@nodejs/hello-im-mark-hinkle-the-new-executive-director-of-the-node-js-foundation-ask-me-anything-86a5f5417619)

**Comment by jasnell** [comment]
@mikeal @rvagg ... please extend an invitation to Mark to join either this or the next TSC call. I would very much like everyone to have a chance to get to know him and hear about his vision for the Foundation.

**Comment by jasnell** [comment]
This can be closed now.
