### ISSUE TITLE
TSC Election Scheduling

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#244]
First, some backstory.

In 2015, shortly after we started the merge of io.js and Node.js we had an election for a Board Director. The first election was kind of rocky because we weren't entirely sure what the responsibilities were but we also wanted to place someone on the board before the board did its officer elections.

Last year we actually forgot to hold another election at the same time and were a few months late. If we do this year's election a full year later it will be *after* the board's officer elections.

Additionally, the TSC might want to think strategically about the *best* time to do these elections now that the timing has become difficult.

For reference, the budget and goals for a new year usually get worked out towards the end of the year and ratified before January 1st (keeping in mind that we do other allocations throughout the year). December everyone pretty much takes off.

Board work tends to ramp up as the year goes along. A new Individual director comes on in January, new elected Gold/Silver directors in June and a board officer election in July.

June is not the *best* time to ramp up a new TSC board director and so the TSC may want to think about doing yearly elections earlier. That said, it's April already :)

Also, I know the TSC has been considering electing the Board Chair and TSC Chair separately, effectively splitting a role that is currently all on one person.

Let's kick off a good discussion about what best to do and try to get to a decision by the end of the month.

**Comment by jasnell** [comment]
May works for me.

**Comment by nebrius** [comment]
May works for me as well. I think it would be prudent to hold elections for board rep and TSC chair independently, however I suspect that in practice candidates will run for both simultaneously. If that's not the case, that's fine too!

**Comment by bnoordhuis** [comment]
Whatever is most pragmatic.  If that's May, +1 to May.

**Comment by mikeal** [comment]
Closing for  #256
