### ISSUE TITLE
Nominating @MylesBorins to the TSC

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#247]
@nodejs/tsc ... I would like to nominate @MylesBorins to the TSC. The contributions to LTS, CITGM and just general overall ecosystem stability, not to mention the relatively new connections on the V8 side make it a fairly obvious choice, in my opinion. Following the normal procedure, the first step would be to invite @MylesBorins as an observer in the regular TSC calls.

**Comment by cjihrig** [comment]
+1 from me.

**Comment by addaleax** [comment]
+1 from me, too.

**Comment by nebrius** [comment]
+1 from me too

**Comment by mhdawson** [comment]
+1 from me, makes sense to bring people on who are willing to help out.

**Comment by joshgav** [comment]
+1. Somewhat relatedly I think, perhaps @MylesBorins can help us identify areas where the TSC can more deeply support Node's technical projects and perhaps reduce the burden on the CTC.

**Comment by Fishrock123** [comment]
+1

**Comment by joshgav** [comment]
We have 8 yes's out of 14 TSC members at the moment. Until #142 lands we need a 2/3 vote to add someone (after that PR we'll just need a majority), which means we need at least 2 more yes votes.

@rvagg @bnoordhuis @piscisaureus @mscdex @shigeki @trevnorris can you please vote? Thanks!

**Comment by mhdawson** [comment]
Since #142 has landed and there are no objections I believe we can declare this as approved.

**Comment by MylesBorins** [comment]
can I put this on my linkedIn yet??

**Comment by shigeki** [comment]
Sorry for my late vote. Of course +1.

**Comment by mhdawson** [comment]
@MylesBorins I think we just need a PR to add you to the readme.md do you want to do that or would you like me to ?

**Comment by MylesBorins** [comment]
@mhdawson opened in https://github.com/nodejs/TSC/pull/293
