### ISSUE TITLE
Request: Additional 2017 Travel Fund Allocation

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#250]
@nodejs/tsc @mikeal @hackygolucky @ashleygwilliams ...

Per @mikeal, we need to consider asking for a new TSC Travel Fund allocation for the remainder of 2017 given that we have already used 50% of our allocation. Opening the issue so we remember to discuss -- most likely during the private session of an upcoming TSC meeting.

**Comment by hackygolucky** [comment]
@jasnell After further discussions at Collab Summit, I looked at last year's numbers to what's already been requested for this year, the anticipated attendance numbers for the Vancouver Collab Summit. I'd recommend the TSC consider requesting an additional 

We would like to encourage as many collaborators to attend, and part of that is making sure it is known that everyone meeting in one place is awesome(and valued)! Calculating for 50% of the count that attended last year to request travel funding with a North America to non-NA ratio at 60/40, and estimated at a $500 domestic/$1000 international flight rate, I expect at 2 nights' hotel:

| Whereabouts | Count  |  Flight Cost | Lodging  | 
|:-:|---|---|---|
| North America | 30 |  $500 | $210 |
| Everywhere Else | 20 | $1000  |  $210 |
| Total | 50 | $35,000  |  $21000 |

Total need: $46,000

As I've dug, I'm only seeing $2000 of the current $10000 allocated so far for the year. So **unless y'all will need other travel requests met for the year**(please take this into account!), the additional request to the Board would be **$38,000**.

**Comment by jasnell** [comment]
Excellent, thank you. 

Questions: Is the allocation for calendar year or fiscal year? I assume the funds are folded back into the general fund at the end of the allocation period?

**Comment by jasnell** [comment]
@nodejs/tsc ... If there are no objections, I will bring this request to the Foundation Board at the next meeting. I will work with @hackygolucky and Mark Hinkel to refine the actual numbers for the request.

**Comment by jasnell** [comment]
@nodejs/tsc @nodejs/community-committee ... FYI, the board has approved an additional travel fund allocation of $67,000 (USD) for the remainder of this year, with the primary intent of enabling collaborators to attend the upcoming Node.js Interactive Collaborator Summit in Vancouver.
