### ISSUE TITLE
Define Travel Fund approval requirements

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#254]
The Travel Fund process seems to be working well so far:
https://github.com/nodejs/TSC/blob/master/Member-Travel-Fund.md

The approval (voting?) requirements are not defined however. I think the TSC has been working on a "majority" approval required.. but that is not included in [the document](https://github.com/nodejs/TSC/blob/master/Member-Travel-Fund.md).

It does say:
> The TSC will consider each proposal in its next regular meeting.

I don't _think_ this is happening. It seems that it is currently just working off getting a majority TSC PR approvals..?  Maybe my memory is off on this.

Please document what it takes to achieve the official approval.

**Comment by mikeal** [comment]
> The TSC will consider each proposal in its next regular meeting.

Good catch, this should probably be changed so that approvals can be completed via issue votes and only bubble up to the meeting if untended or controversial.

**Comment by jasnell** [comment]
> this should probably be changed so that approvals can be completed via issue votes...

Which is in line with actual practice so +1

**Comment by bnoordhuis** [comment]
The current online process works well so +1 to updating the document.  I can file a pull request if no one is already working on it.

**Comment by jasnell** [comment]
The one thing that we definitely need, however, is greater visibility into exactly how much money is left in the fund. It would be good if we can have a periodic review on that from either @mikeal or @rvagg

**Comment by Fishrock123** [comment]
yeah let's update that

**Comment by mhdawson** [comment]
+ 1 from me as well.

**Comment by addaleax** [comment]
@jasnell Maybe we should just insert the amount available into the document when something is allocated, that seems easiest

**Comment by jasnell** [comment]
Easiest yes, but I'm not certain if the allocated amount is public info.

**Comment by mikeal** [comment]
The board has assumed that it would be public being that the TSC would have to manage it. In future allocations that can be made more explicit.

**Comment by ChALkeR** [comment]
@jasnell That's public here: https://github.com/nodejs/TSC/issues/250#issuecomment-299440566

**Comment by Fishrock123** [comment]
seems to me this just needs a PR

I'll try to get around to it soon(tm)

**Comment by jasnell** [comment]
Closing due to lack of any further activity
