### ISSUE TITLE
TSC meeting - 2017-05-04 - skip?

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#258]
The TSC meeting overlaps with collaborator summit this week. I propose that we skip the meeting this week. If there are critical items we need to discuss, we can defer to email or the issue tracker.

One very important item we have is the TSC election. I will post a separate issue on that later today.

**Comment by joshgav** [comment]
All upvotes and it's dinner time now in Berlin so assuming we're skipping this week. Thanks @jasnell!

**Comment by joshgav** [comment]
Our next meeting is scheduled for Thursday 5/22.
