### ISSUE TITLE
bring string_decoder into the Foundation

### ISSUE THREAD

**Issue by mcollina** [nodejs/TSC#260]
Requesting approval to move https://github.com/rvagg/string_decoder to https://github.com/nodejs/string_decoder. This code has already the Node.js copyright, the only thing that is from @rvagg is the build step. This has been recently updated by myself to use the same machinery of readable-stream.

The responsibility for this module will fall under @nodejs/streams. 

On approval we'd add in the Node.js governance and then transfer over.

**Comment by joshgav** [comment]
Makes sense, but could we clarify what the relationship will be between the proposed repo and [lib/string_decoder.js](https://github.com/nodejs/node/blob/master/lib/string_decoder.js)? I think this is important so the two files don't diverge unexpectedly. Perhaps the built-in file can be vendored out and we can reference the new repo in deps, as we do for node-inspect. 

Also, building this module seems to require babel and I'm a bit negative about depending on babel in core. Could it be built without babel? Thanks!

**Comment by ljharb** [comment]
It's published to npm; without babel it can't support older nodes.

**Comment by addaleax** [comment]
@joshgav I think it’s okay for the npm copy of string_decoder to support exactly what streams needs, even if they diverge (as long as the API is still the same).

(In case it’s relevant, my PR at https://github.com/nodejs/node/pull/11613 would make `string_decoder` in core come to rely on Buffer internals that aren’t available in any currently published Node version.)

**Comment by calvinmetcalf** [comment]
@joshgav currently string decoder is built from the internal one like readable-stream does. It could probably be vendered out in a way that makes it work in current node without using babel, babel only being used to build the browserify/old node version that is put onto npm.

Currently it's created via this process

1. download it from git hub
2. run a bunch of regexes on it to get rid of node specific stuff
3. run babel with the bare minimum of rules needed for it to run in browsers/old node.

if we vendored it would could likely do away with steps 1 and 2 and just have a build process

**Comment by jasnell** [comment]
+1

**Comment by mcollina** [comment]
@joshgav in the build step, we are also importing the `string_decoder` tests, so any breakages would be detected.

**Comment by rvagg** [comment]
+1 obviously, since Matteo and I have had this discussion prior to raising this issue

**Comment by calvinmetcalf** [comment]
I'm +1 on this as a member of @nodejs/streams

**Comment by mhdawson** [comment]
+1 from me.

**Comment by nebrius** [comment]
I'm abstaining. I don't feel like I have enough background on this topic to give an informed vote (which is fine, it's not my wheelhouse).

**Comment by Fishrock123** [comment]
+1 based on discussion in the last CTC meeting.

**Comment by joshgav** [comment]
Thank you @addaleax and @calvinmetcalf for your explanations! I'm going to abstain cause I don't know streams well enough currently to understand the uses of this inside and outside of core; will defer to those more knowledgeable.

If no one objects I'll ask one of the transpilation experts on our TypeScript team to see if we can remove babel easily, on the assumption that we all agree fewer dependencies is better.

Thanks!

**Comment by joshgav** [comment]
@mcollina - I changed the title to make this issue easier to discover, hope you don't mind!

**Comment by ljharb** [comment]
Why is fewer dependencies, especially devDependencies, better?

**Comment by mcollina** [comment]
@joshgav the problem is that `string_decoder` is extracted from core. It also support node down to 0.8, and very old browsers, as `readable-stream`  does. We need babel to transpile during the extraction process, because the JS code that we have in core does not run on node 0.8, 0.10, etc.

**Comment by jasnell** [comment]
@nodejs/tsc ... last call for objections on this.
@nodejs/streams ... if there are no objections by monday, I would recommend proceeding. There are a couple of todo's that would be necessary:

1. Add a note to the readme that clearly indicates that the module is maintained by the streams wg similar to [what's in readable-stream](https://github.com/nodejs/readable-stream#streams-working-group).
2. Add the governance and contributing documentation to the repo.

**Comment by mcollina** [comment]
I would do those when moving.

May I refer to the `readable-stream` repo for governance? It's the same wg.

**Comment by joshgav** [comment]
@mcollina 

> Why is fewer dependencies, especially devDependencies, better?

If there are problems or needs in string_decoder which a later generation of Node contributors has to address, they will also have to understand Babel, which takes time and energy. That is, fewer dependencies make it easier to maintain the code by definition.

IMHO the TSC's job in evaluating new projects is to ensure they are core to Node and justify the resource investment required, that's the only basis of both points I raised :).

**Comment by ljharb** [comment]
@joshgav (i assume your reply was directed at me) That's a fair point, but I'd counter that more dependencies outsources maintenance of the code to more developers, making it easier to maintain by definition ;-).

In this case, i'd say both that understanding Babel is a reasonable assumption to make of modern web developers, since a good number of major projects use it - and, that if it's set up with the proper prepublish scripts, the developers wouldn't ever have to know it exists - the point is that they'd just write normal JavaScript, and Babel would take care of transpiling it to an older target automatically. The burden on maintenance is reduced, because they don't have to remember what edition of the JavaScript spec the target platforms support when coding.

**Comment by mcollina** [comment]
> If there are problems or needs in string_decoder which a later generation of Node contributors has to address, they will also have to understand Babel, which takes time and energy. That is, fewer dependencies make it easier to maintain the code by definition.

There is very little code that we need to maintain, https://github.com/rvagg/string_decoder/blob/master/build/build.js and https://github.com/nodejs/readable-stream/blob/master/build/build.js are almost identical. `string_decoder` is pulled from core, which are already maintaining.

**Comment by joshgav** [comment]
@mcollina 

> There is very little code that we need to maintain

Agreed. If the codebase was bigger I'd be more concerned :).

@ljharb those are good arguments for using Babel, I agree. But to help illustrate the counterpoint, what if Babel isn't available in a couple years or what if a significant refactor is required to stay in sync with Babel updates?

To be clear, I'm not opposed to bringing string_decoder in, particularly cause its small and is similar to lib/string_decoder.js, and I agree with other sentiments expressed here. My goal is to do my due diligence as a stakeholder in the Node project and help us evolve our thinking about bringing in new projects. Thank you!!

**Comment by mhdawson** [comment]
Unless there are objections from TSC members by June 5th this will be considered approved.

**Comment by mcollina** [comment]
This is approved! 

@rvagg can you move the repo to `nodejs/string_decoder`? I'll send a PR against the Stream WG https://github.com/nodejs/readable-stream/blob/master/GOVERNANCE.md and our README.

**Comment by rvagg** [comment]
This is done now, not a straight move but a create and copy to sever the confusing 'forked from substack/string_decoder' message that comes with it. I'll update the old repo documentation to point to this new one. @nodejs/streams have been given admin on the repo, I _think_ that's appropriate.
