### ISSUE TITLE
Adopting Contributor Covenant as CoC

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#261]
The [Contributor Covenant](http://contributor-covenant.org/) has emerged as a standard Code of Conduct used by a [large number](http://contributor-covenant.org/adopters/) of open source projects within the larger Node.js ecosystem and other ecosystems. The [CoC](http://contributor-covenant.org/version/1/4/) text itself is both comprehensive and extremely well thought out.

I am proposing that the TSC adopt the Contributor Covenant CoC as the new Code of Conduct for the entire Node.js project, replacing the existing one.

*Update*: @nodejs/collaborators @nodejs/members ... So far there have not yet been any objections raised from the @nodejs/tsc, but given the impact on the entire project, I'd like to solicit input from the broader base of contributors. If you agree with the change you needn't weigh in except maybe with a simple thumbs up emoji. If you object to the change, please add a comment explaining your objection. Please keep comments focused and on topic. Thank you!

**Comment by ChALkeR** [comment]
While using a standard and maintained by someone else version looks like a good idea, there are some details that should be somehow taken care of, and for that we need to understand the actual changes being done by such replacement.

_Probablably_ an incomplete list:

### Pledge

> or other similar characteristic

Is being removed. 

### Contact

Current CoC states:
> Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by:
> 
> * Emailing [report@nodejs.org](mailto:report@nodejs.org) (this will email all TSC members)
> * Contacting [individual TSC members](https://nodejs.org/en/foundation/tsc/#current-members-of-the-technical-steering-committee).

The Contributor Covenant states:

> Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the project team at [INSERT EMAIL ADDRESS].

Either the Contributor Covenant has to be changed in that specific part somehow, or it should be agreed that the second way of geting in touch should be removed. Ref: #45.

### Moderation

Current CoC has a link to the moderation policy.
> See the TSC's [moderation policy](https://github.com/nodejs/TSC/blob/master/Moderation-Policy.md) for details about moderation.

This change would remove that.

### Profanity

https://github.com/nodejs/node/pull/3827 is being reverted. The new CoC does not mention the profanity at all.

**Comment by mikeal** [comment]
@ChALkeR I'd expect the contacts to be updated. Our moderation policy is written as a separate document so I don't think we'll be dropping it with the new CoC.

Good catch on the profanity addition that isn't paired.

**Comment by jasnell** [comment]
Regarding the profanity addition, we can potentially take that up with the Contributor Covenant project itself. There is language there about "professional" conduct, but with regards to profanity there is far too much room for interpretation there. We'd definitely have to address that one.

Note that for the rest, the Contributor Covenant website includes specific directions on modifying the Covenant to adapt for specific projects, specifically:

> Important! You must add a contact method to the placeholder in the document so that people know how to report violations.
> The Contributor Covenant is released under the Creative Commons Attribution 4.0 International Public License, which requires that attribution be included.

We are free to add additional clauses to the Covenant if we so desire so long as we follow the CC-AT requirements.

**Comment by mikeal** [comment]
Could we maybe just add a note to our moderation guidelines that calls out "profanity" as an example of professional conduct?

**Comment by jasnell** [comment]
Yes, that's entirely possible.

**Comment by nebrius** [comment]
> Either the Contributor Covenant has to be changed in that specific part somehow, or it should be agreed that the second way of geting in touch should be removed. Ref: #45.

TBH I'd like to change this anyways. I get the motivation behind saying that you can contact an individual TSC member, but that really only works if you personally know one of the TSC members. This change would be heavily impacted by https://github.com/nodejs/TSC/pull/263 as well.

I guess what I'm saying is that I think it's fine to drop the "or reach out to individual TSC members" clause to make it simpler to adopt this change.

**Comment by nebrius** [comment]
I'm a huge +1 on this change. The Contributor Covenant has been widely adopted, which means it has been battle tested. It's more mature and has a better track record than ours does simply by virtue of being used so much more widely. It's also one less thing for us to maintain :)

**Comment by mikeal** [comment]
Another important thing to note about the Contributor Covenant is that it is translated into many languages. This makes it easier for non-native english speakers and it also means the language in the reference english version has had time to iterate on terms that are not easily translatable or understandable in other languages and cultures.

**Comment by mhdawson** [comment]
Sounds like there are a number of good reasons for using the "Contributor Covenant" as the gold standard. I'm +1.

**Comment by cjihrig** [comment]
+1 from me

**Comment by jasnell** [comment]
@nodejs/tsc @nodejs/ctc @nodejs/collaborators ... one more call for objections on this.

From what I see, there are two actions necessary for this:

1. Updating the text of the CoC
2. Updates to the Moderation Policy to cover the pieces (like profanity) that are not covered by the Contributor Covenant.

I will open a PR that addresses both items.

**Comment by Frijol** [comment]
@nebrius re dropping "reach out to individual TSC members", I'd push back on removing that. If someone experiences an issue with a TSC member, they are unlikely to want to report the incident to a broad email address that goes to all of the TSC (including the one they're experiencing issues with).

Personally, I would reach out to a TSC member I didn't know (not so hard to find people on Twitter/npm emails/etc) if I felt it was important to report an issue. Separately, I might feel less good about sending a sensitive issue to a large-group mailing list regardless of the incident– it would feel more confidential to look up TSC members and seek out one I felt would understand the issue.

**Comment by ChALkeR** [comment]
@jasnell Note that I am generally in favor of this, and the issues I mentioned are not objections.
I just tried to compare the two and note the actual differences that we might need to take care of somehow.

**Comment by nebrius** [comment]
@Frijol I've been thinking about this a lot lately, and you're definitely right. There needs to be a way to escalate that doesn't involve sending an email to the entire group. I do think that there is a better way than "email a TSC member," but I no longer thing we should drop this part until we have something better to replace it.

FYI @jasnell opened a PR for the CoC change at https://github.com/nodejs/TSC/pull/276, and it still includes this escalation language.

**Comment by refack** [comment]
> @Frijol I've been thinking about this a lot lately, and you're definitely right. There needs to be a way to escalate that doesn't involve sending an email to the entire group. I do think that there is a better way than "email a TSC member," but I no longer thing we should drop this part until we have something better to replace it.
> 
> FYI @jasnell opened a PR for the CoC change at #276, and it still includes this escalation language.

May charter an official ombudsman that is not a TSC member (although all the natural candidates __are__ TSC members).
