### ISSUE TITLE
TSC Meeting Schedule

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#265]
@nodejs/tsc 

Previously we adjusted the TSC Meeting schedule to every two weeks because we did not have enough items to justify meeting every week. Looking at the agenda items, and with the goal in mind of using asynchronous discussion as much as possible to resolve issues, I want to propose having only one TSC meeting per month, which would consist solely of a public portion. There's just are not enough issues or updates on existing issues to justify the current schedule.

In addition to altering the schedule:

* The TSC Chair would post the agenda a week in advance of the meeting (with updates as necessary)
* Rather than an individual standup, there would be a review of working group activities.
* In addition to the existing TSC voting members, any Node.js contributor (to any working group) would be permitted to attend as an observer.

**Comment by rvagg** [comment]
I'd like to see the the review of WG activities as a report presented by WGs, simple, just text. Ask each WG to deliver each month, suggest they assign someone to put together some notes for us.

+1 to this

**Comment by rvagg** [comment]
Does this mean we're not on this week btw @jasnell? My alarm is set but I'd be pretty happy not to have to do another 6am this week.

**Comment by jasnell** [comment]
Doh! I need to get the agenda together to see if we have anything for today. I suspect that we have nothing pressing for the public agenda. If there is only private business we can likely handle it async via email.

**Comment by Fishrock123** [comment]
I assume there is no agenda?

Besides https://github.com/nodejs/TSC/pull/263 that is, but we seem to be well on discussing that in-issue for now.

**Comment by mikeal** [comment]
There's a big thread about structural changes that could benefit from a short public discussion by the TSC members. Not saying anything could/should be resolved or concluded but it's a very detailed issue and it would be nice to have a less formal discussion with some of the stakeholders about it.

**Comment by jasnell** [comment]
Yeah, I'd like everyone to have a few more days to digest the thread before we talk about it tho.

**Comment by mikeal** [comment]
@jasnell cool, sounds good, less meetings today ;)

**Comment by mhdawson** [comment]
I'm +1 to the suggested adjustments to the agenda with the suggestion that we don't limit it to coverage WG areas (but its a good starting point).  I think we should identify any other key areas and try to cover those as well.  For example reviewing the status of dependencies might makes sense.  A concrete case is openssl.  Things are progressing to get an upgrade due to the EOL of 1.0.2 but it might be better if we were proactive on these kinds issues depending on them being addressed organically.

**Comment by Trott** [comment]
This seems long dormant, so I'm going to close it. Feel free to re-open.
