### ISSUE TITLE
TSC Meeting - 2017-05-18 - Canceled

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#266]
@nodejs/tsc ... I am cancelling today's scheduled TSC meeting due to lack of new public agenda items and lack of progress on existing agenda items. 

The items currently tagged as `tsc-agenda` include:

### nodejs/readable-stream

* Bring string_decoder into the foundation [#272](https://github.com/nodejs/readable-stream/issues/272)

Issue #272 is being actively discussed in GitHub and no objections have been raised so far. This is likely going to happen.

### nodejs/TSC

* Request: Additional 2017 Travel Fund Allocation [#250](https://github.com/nodejs/TSC/issues/250)

I will work with @rvagg and @mikeal on an allocation proposal for this.

* Board Request: Input on employer restrictions of TSC Director [#231](https://github.com/nodejs/TSC/issues/231)

There has been nothing further on this matter. I recommend removing the `tsc-agenda` label.

* Copyright Date [#195](https://github.com/nodejs/TSC/issues/195)

There has been nothing further on this matter.

* charter: revised membership rules [#142](https://github.com/nodejs/TSC/pull/142)

The revised participation rules have been accepted by the Board and we just need to get this PR landed. I will do so today. The rules go into affect as of the day they were accepted by the board. @mikeal: can you drop a comment in here letting us know what day that was?

* Clarify which people should be org owners [#125](https://github.com/nodejs/TSC/issues/125)
* Regular roll-up reporting for active working groups [#109](https://github.com/nodejs/TSC/issues/109)

There has been nothing further on these matters.

### nodejs/community-committee

* 1 Code of Conduct for everything? [#7](https://github.com/nodejs/community-committee/issues/7)

I believe the `tsc-agenda` label can be removed from this now.

There is some private business for the TSC that I will send out an email later today on.

**Comment by joshgav** [comment]
Thank you for the report @jasnell, great idea.
