### ISSUE TITLE
TSC Meeting June 15 - Postpone 1 week

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#281]
I'm travelling the week of the 15th so I won't be able to facilitate.  I suggest we either move out one week or somebody volunteer to facilitate.   Which do you prefer ?

**Comment by joshgav** [comment]
I'll also be away next week so am +1 for bumping :)

**Comment by jasnell** [comment]
I had previously proposed moving to having only 1 TSC meeting per month. There was good support for the idea. Is that something we're still looking at?

**Comment by nebrius** [comment]
> I had previously proposed moving to having only 1 TSC meeting per month. There was good support for the idea. Is that something we're still looking at?

I'm +1 on skipping this one and starting the monthly cadence.

FYI I'll be out the week of this meeting too for DinosaurJS.

**Comment by mhdawson** [comment]
I'll let other people chime on the thought of reducing to 1 meeting per month.  I had hoped that we could spend some time trying to see if we are comfortable that everything is in place for the areas in: https://github.com/nodejs/TSC/issues/278 but not sure if it is the right venue, just think its important that we do on a regular basis.

**Comment by mhdawson** [comment]
As for the meeting  this week I don't see any opposition to postponing to I'll consider it postponed and will see if there is any more input here when I get back and then schedule the replacement accordingly.

**Comment by rvagg** [comment]
I'm mostly indifferent to skipping, though not having a 6am is always good and with so many key folks away it doesn't seem like it'd add much value having a meeting.

**Comment by Fishrock123** [comment]
ok let's consider this skipped then

**Comment by mhdawson** [comment]
I'm going to close this and we can discuss the meeting interval in the next regularly scheduled meeting.
