### ISSUE TITLE
Org owners of GitHub

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/TSC#285]
Trying to add folks to our members list for CommComm, and we've run into the fun problem that since we don't have org owner access, we can't actually do this ourselves. 

Who manages the org owners list? (I'm clearly ignorant to this and I feel quite silly for not knowing this very clearly)

Is there a way this can be opened up in some context to some folks in CommComm(I understand certainly that we don't want all members to have that ability) in order for us to be able to operate without asking permission to do some stuff in our repos?

**Comment by nebrius** [comment]
As many of you know, I have historically resisted being given org owner permissions for a variety of reasons, but maybe now is the time since I'm CommComm chair.

**Comment by Trott** [comment]
At the current time, the org owners consist of the 22 members of the CTC + Mikeal Rogers.

Of the 9 people on @nodejs/commcomm-members, @MylesBorins and @mhdawson have the Owner role.

**Comment by jasnell** [comment]
@nodejs/tsc ... I'm +1 on @nebrius have org owner status. Any objections before I elevate his permissions?

**Comment by Trott** [comment]
Ref: https://github.com/nodejs/TSC/issues/125

**Comment by Trott** [comment]
Ref: https://github.com/nodejs/CTC/issues/97

**Comment by mhdawson** [comment]
I'm + 1 as well.  Seems like it should be ok for the commcomm chair to have that.

**Comment by rvagg** [comment]
+1 for @nebrius as owner. As far as I've been concerned that option has been in the table since he was added to the TSC and he's only needed to ask for it.

**Comment by gr2m** [comment]
Hey just wondering, would you be open to setup a GitHub app for this? Similar to https://github.com/probot/settings#usage, but for GitHub Organization teams and members? That way we could use the pull-request process to add / remove people and teams, and it would be transparent. I’ve build several of such bots before, I’d be happy to put some time towards it over the weekend. Only if it would be of help. Happy to make a separate issue for it, just let me know, still finding my ways around here :)
