### ISSUE TITLE
TSC Meeting frequency discusion

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#286]
It was suggested in the issue for the last meeting by @jasnell that we reduce the meeting frequency to 
once a month.

This issue is to discuss and come to an agreement on what we want the meeting frequency to be going forward.

**Comment by nebrius** [comment]
I like the idea of a month to start. We can trial this frequency for a while and in, say, six months check in with everyone to see how it's working. I also like once a month because it lines up with our previous schedule, i.e. there are no _new_ times introduced, only times removed.

Related, we should figure something out for https://github.com/nodejs/TSC/issues/198 though.

**Comment by jasnell** [comment]
I definitely prefer a monthly schedule

**Comment by mhdawson** [comment]
In terms of #198, looking at the meeting time options rated by the CTC members, the current time,  2 hours later is worse for some and better for others. 0 UTC is also better for a number of people but also not possible for a number of people.

Two options would be. Please suggest others if you think there is another one we should consider based on the CTC availability spreadsheet.

1) alternate between 20 and 22 UTC
2) alternate between 20 and 0 UTC

**Comment by nebrius** [comment]
Both options work well for me, I'm fine with whichever is easier for everyone else.

**Comment by mhdawson** [comment]
Based on discussion in last TSC meeting unless we hear objections in the next week, we are going to move to monthly.

@nodejs/tsc can you those of you for which the current time is a challenge please comment ? We'd like to consider if we need to move but we need to know if its going to make a difference before do that as it will affect attendance of some of the existing regular attendees.

**Comment by joshgav** [comment]
Monthly makes sense based on recent experience. Of the two options above I prefer the 20/22 UTC slots slightly. Thanks!

**Comment by mhdawson** [comment]
We agreed on monthly, closing.
