### ISSUE TITLE
Adding members to electron-installer team

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#288]
Hey All,

To get movement on electron installer going I've added a couple members to the team

This includes myself, @gibfahn, @felixrieseberg, and @MarshallOfSound

A good chunk of prior work had been done by @delvedor, who we hope will still be involved in maintaining / developing the project

**Comment by delvedor** [comment]
I'll be super happy to continue working on this, even more now with other people :)

**Comment by jasnell** [comment]
SGTM. There's likely not reason to keep this issue open, however. Definitely hope there's continued momentum on this!
