### ISSUE TITLE
TSC meeting July 13

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#291]
We had agreed on monthly, but unfortunately the next meeting would then conflict with Node Summit.

I would move 1 week back/forth but that would conflict with the CommComm meeting and there are some overlapping members.

I've therefore updated the Node.js calendar to show the next meeting Thursday the 13th, and then every 4 weeks after that.

## Time

**UTC Thu 13-Jul-Apr-2017 20:00 (08:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Thu 13-Jul-2017 13:00 (01:00 PM) |
| US / Mountain |Thu 13-Jul-2017 14:00 (02:00 PM) |
| US / Central  | Thu 13-Jul-2017 15:00 (03:00 PM) |
| US / Eastern  |Thu 13-Jul-2017 16:00 (04:00 PM) |
| Amsterdam     |Thu 13-Jul-2017 22:00 (10:00 PM) |
| Moscow        | Thu 13-Jul-2017 23:00 (11:00 PM) |
| Chennai       | Thu 13-Jul-2017 01:30 (01:30 AM) |
| Tokyo         | Thu 13-Jul-2017 05:00 (05:00 AM) |
| Sydney        | Thu 13-Jul-2017 06:00 (06:00 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Technical%20Steering%20Committee%20(TSC)+Meeting+Thu 13-Jul&iso=20170601T20
* or http://www.wolframalpha.com/input/?i=8pm+UTC%2C+Jun+1%2C+2017+in+local+time

## Links

* **Minutes Google Doc**: 
* Previous Minutes Google Doc: https://docs.google.com/document/d/1LtgN6guOgqD8PcG8uTeO-tOZKfv9WQniAZHXJeJL8is/edit?usp=sharing

## Agenda

Extracted from **tsc-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/TSC

* Candidate "areas" for TSC and Community Committee  [#278](https://github.com/nodejs/TSC/issues/278)
* Request: Additional 2017 Travel Fund Allocation [#250](https://github.com/nodejs/TSC/issues/250)
* Copyright Date [#195](https://github.com/nodejs/TSC/issues/195)
* Regular roll-up reporting for active working groups [#109](https://github.com/nodejs/TSC/issues/109)

## tsc-review

For awareness, please review comment on these issues marked tsc-review:

### nodejs/TSC

* Candidate "areas" for TSC and Community Committee  [#278](https://github.com/nodejs/TSC/issues/278)
* Approval to move node-heapdump into foundation [#257](https://github.com/nodejs/TSC/issues/257)
* Define Travel Fund approval requirements [#254](https://github.com/nodejs/TSC/issues/254)
* Add quorum rules [#253](https://github.com/nodejs/TSC/issues/253)
* Request: Asset audit report [#249](https://github.com/nodejs/TSC/issues/249)
* Nominating @MylesBorins to the TSC [#247](https://github.com/nodejs/TSC/issues/247)
* create public nodejs/collaborators repo [#243](https://github.com/nodejs/TSC/issues/243)
* Rotating meeting times [#198](https://github.com/nodejs/TSC/issues/198)

## Invited

* Bryan Hughes @nebrius (TSC)
* Colin Ihrig @cjihrig (TSC)
* Jeremiah Senkpiel @Fishrock123 (TSC)
* Fedor Indutny @indutny (TSC)
* James M Snell @jasnell (TSC)
* Josh Gavant @joshgav (TSC)
* Brian White @mscdex (TSC)
* Bert Belder @piscisaureus (TSC)
* Rod Vagg @rvagg (TSC)
* Shigeki Ohtsu @shigeki (TSC)
* Trevor Norris @trevnorris (TSC)
* Anna Henningson @addaleax (TSC)
* Michael Dawson @mhdawson (TSC)
* William Kapke @williamkapke (observer/Individual Member Director)
* Ashley Williams @ashleygwilliams (observer/Individual Member Director)
* Kaitlyn Barnard @kbarnard10  (observer)
* Tracy Hinds @hackygolucky (observer/Node.js Foundation)
* Myles Borins @MylesBorins (observer/TSC nominee)

## Notes

The agenda comes from issues labelled with `tsc-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

**NOTE** As agreed in the last meeting with be help using hangouts this week:

For those who want to watch: 
Link for participants: 
Events link: https://www.youtube.com/my_live_events

**Comment by addaleax** [comment]
Just a single data point, but I’ll be on my way to JSConf.CN one week from now, so I won’t be there.

**Comment by mhdawson** [comment]
Looking at the items on the agenda and the later notice I might suggest that we just cancel and do it 4 weeks from now, but I believe  @hackygolucky might have a high priority one to add related to the travel fund ?

**Comment by renrutnnej** [comment]
You can drop me from the invite list and future ones @mhdawson. 
@kbarnard10 is taking over the newsletter duties. ☺️

**Comment by jasnell** [comment]
Unfortunately I'll be on a flight from NYC back to Fresno during this scheduled time so, if it's not cancelled, I won't be able to attend.

**Comment by mhdawson** [comment]
@renrutnnej thanks for the FYI, updated.

**Comment by mhdawson** [comment]
Just waiting to hear from @hackygolucky.  If we don't hear by tomorrow my plan would be to cancel.

**Comment by mhdawson** [comment]
This is the issue https://github.com/nodejs/TSC/pull/294#pullrequestreview-49643170

@nodejs/TSC if people can comment review/there by tomorrow morning we can likely cancel the meeting.

**Comment by mhdawson** [comment]
@nodejs/TSC for those who can make the meeting can you 

1) comment here if you can make it or not.
2) Indicate if you have questions about #294 that we might be able to move quickly resolve on a call versus continued discussion in github.

**Comment by MylesBorins** [comment]
I'm planning to attend, will be at a dinner that may run late. I've approved #294 with a tiny nit.

**Comment by nebrius** [comment]
I'm available and can attend

**Comment by mhdawson** [comment]
So I think that the only people who have responded that they can make it have already approved #294 so I think we should cancel, push #294 forward in the github issue and then meet at the next regular scheduled time where we can get more attendees.
