### ISSUE TITLE
Repo for TSC + CommComm coordination

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/TSC#295]
There are a few efforts getting under way that are going to require a very tight coordination of communication and agreement with the TSC and CommComm members. The Chairs can do some of this work through the existing channels, but the most immediate task that comes to mind is the Board ask for a joint travel fund via the June Node.js Foundation Board meeting. [This PR](https://github.com/nodejs/TSC/pull/294) has relevant context. 

Would repurposing the Collaboration repo, or creating a new repo such as Administration, make sense?

cc @nodejs/commcomm-members

**Comment by nebrius** [comment]
This dovetails into https://github.com/nodejs/TSC/issues/269, which I admit I ended up slacking on pushing through. I wonder if it would be worth it to close #269 in favor of this one?

I kinda like the idea of creating a new repo called "administration" or something because I feel the name is more informative.

**Comment by jasnell** [comment]
hmm... if at all possible I'd rather avoid creating yet another administrative repo (we have so many already!)... but this is definitely important. If a repo we must have, then a repo it is :-) perhaps simply renaming the existing defunct `collaboration` repo to `administration` would work?

**Comment by hackygolucky** [comment]
+1 !

**Comment by hackygolucky** [comment]
Okay, we now have two repos that I -think- need to fall under both TSC AND CommComm joint ownership
- this new admin/collaboration hub repo
- https://github.com/nodejs/getting-started

**Comment by mhdawson** [comment]
No objects so renamed admin repo as agreed and set so that all of TSC, and CommComm have Admin access.  The agreement was to rename as the repo was not being used and we wanted to avoid creating yet another repo.
