### ISSUE TITLE
Security Disclosure Policy

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#296]
@nodejs/tsc @nodejs/ctc ...

One need we have had for quite some time is a formal early disclosure policy for core and ecosystem vulnerabilities. Currently, our process is rather undefined, including the process for who gets admitted to the @nodejs/security group. What is especially undefined are any of the policies around how and to whom we issue early disclosures for security related issues.

One concern that has been brought to my attention by several members of the community is that under our current processes, some commercial organizations have privileged access to security vulnerability information based solely on the fact that their employees are part of the @nodejs/security team, but other organizations who have employees who actively contribute to core do not have an equal opportunity. We've never really been clear on what the expectations are for members of the @nodejs/security team to keep security details embargoed. This ends up creating a bit of an unfair advantage for certain organizations.

It's past time that we need a documented and enforceable ethical disclosure policy. I would argue that we also should have a reasonable early disclosure process that commercial entities may apply for. Obviously there are details to work out here, but I wanted to get the conversation started.

**Comment by jasnell** [comment]
Ping @nodejs/tsc ... thoughts on this?

(I accidentally closed this)

**Comment by thefourtheye** [comment]
@jasnell Can the title be renamed, as we already have https://nodejs.org/en/security/#disclosure-policy as our security disclosure policy.

**Comment by MylesBorins** [comment]
to the concern raised by community members, AFAIK members of security are not supposed to disclose information under embargo to their employers, that is at least the rules I've been following.

I'd be very interested in how other projects handle ethical disclosure, and potentially early disclosure to companies.

**Comment by mhdawson** [comment]
I think we just need a PR for the text of the policy.

**Comment by mhdawson** [comment]
The text in this PR probably addressed the original issue: https://github.com/nodejs/security-wg/pull/56

**Comment by mhdawson** [comment]
Believe this docs the expectations https://github.com/nodejs/security-wg/blob/master/processes/security_team_members.md.  @jasnell can this issue be closed ?

**Comment by jasnell** [comment]
No, I'd prefer to keep this open until https://github.com/nodejs/security-wg/issues/58 is resolved.

**Comment by jasnell** [comment]
This is being picked up by security-wg. Closing.
