### ISSUE TITLE
directing report@nodejs.org messages to the education/community manager

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#298]
Currently, all email sent to the `report@nodejs.org` email aliases for the purposes of reporting moderation issues is copied to the full TSC. I would like to suggest having the alias forward messages to @hackygolucky or someone else in a Foundation role who can then forward the reports on, as appropriate, to either the TSC Chair or CommComm Chair .

**Comment by addaleax** [comment]
SGTM as long as Tracy is comfortable with that?

**Comment by Trott** [comment]
Probably a good idea to have more than one person getting them. I have to imagine sometimes things require a rapid response, and it would be unfortunate if that corresponded to a time when Tracy was on vacation or out sick or whatever.

If it's not too much to ask, it might even be good to have a person designated as the on-call person at all times (so, person A is on-call this weekend, and person B is on call next weekend, or whatever).

**Comment by mhdawson** [comment]
I agree having at least 2 people be on the list.

**Comment by jasnell** [comment]
I definitely agree with that also. It just shouldn't be the whole tsc... Nor should it necessarily be the tsc at all.

**Comment by Fishrock123** [comment]
I'm not sure how I feel about this... I'd rather have an appointed moderation team of non-committee people and direct it there, though this may work as a stopgap...

**Comment by nebrius** [comment]
Agree with @Fishrock123. It's imperfect for the reasons cited above, and long term I think this should be sent to the moderation team, but this is a good solution in the interim (also assuming Tracy is ok with it).
