### ISSUE TITLE
Tracking Issue: Improved conferencing options

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#303]
@nodejs/tsc @nodejs/ctc ... FYI ... I have asked the Foundation to explore options for providing us with more reliable, and easier to use conferencing and live broadcasting service options. I know that @MylesBorins is exploring the use of Google Meet, but having multiple options available to us to evaluate is a good thing. The options being looked at by the Foundation currently are commercial services that the Foundation would foot the bill for. @Hackygolucky will be the contact on this effort. I will update this tracking issue as progress is made.

@MylesBorins ... feel free to use this issue to update on the Google Meet experimentation status as well.

**Comment by Fishrock123** [comment]
as for live broadcasting, I'm pretty sure I've brought up in the past that we may be able to host the encoder on a cloud box somewhere, but it'd need decent CPU power and initial setup may be pretty complex.

**Comment by Fishrock123** [comment]
As an added "if possible" request - it'd be nice to use a service that easily displays who is talking in a way which can safely be captured (hiding phone #'s), similar to gotomeeting. That way we could broadcast who is talking and would probably make recordings more watchable.
