### ISSUE TITLE
Travel fund request: Gregor Martynus – Collaborator Summit at Node Interactive NA

### ISSUE THREAD

**Issue by gr2m** [nodejs/TSC#305]
**Event**: Collaborator Summit at Node Interactive NA
**Location**: Vancouver, Canada

I’m new member of CommComm and would appreciate a reimburse for travel & lodging for the Collaborators Summit. I live on the west coast and booked flights and lodging already, but it was not yet deducted from my German account, I don’t know what the final sum will be yet, but i expect around $600. Ping @nebrius

**Comment by nebrius** [comment]
@gr2m would you mind opening a PR against https://github.com/nodejs/TSC/blob/master/Member-Travel-Fund.md that adds your info to the table? That's how we normally handle the approval process for travel requests.
