### ISSUE TITLE
meta: vote regarding Rod's status on the TSC

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#310]
A few weeks ago, concerns were raised by several TSC and CTC members regarding issues they had with @rvagg's interactions in the Github tracker and Twitter.

The specific issues that were reported include:

[Note: the specific list of issues has been removed at the request of several core collaborators who felt that listing the issues was not fair to Rod. This post was made with an effort at full transparency and with no ill intent towards anyone. No additional harm was intended by listing the issues - jasnell]

In light of the complaints, the TSC discussed these issues and discussed whether to take action against Rod regarding these issues. A specific question was raised whether Rod should be removed from the TSC.

Per the [Charter](https://github.com/nodejs/TSC/blob/master/TSC-Charter.md#section-4-establishment-of-the-tsc), an individual TSC member may be removed only "by voluntary resignation, by a standard TSC motion, or in accordance to the participation rules".

The TSC members were not able to reach a natural consensus on the steps forward so a vote was called on two specific questions:

(A) Should Rod be removed from the TSC: Yes or No
(B) Should Rod be asked to voluntarily resign from the TSC: Yes or No

There are 13 members of the TSC. 10 members voted, two abstained, and Rod did not participate.

The vote came down 60% *against* removing Rod from the TSC and 60% *against* asking Rod to voluntarily resign.

A follow up from this is that the TSC and CommComm will be working jointly with the Node.js Foundation to develop clear guidelines around accountability expectations for all members of the TSC, CTC, and CommComm over an above our existing [Code of Conduct](https://github.com/nodejs/TSC/blob/master/CODE_OF_CONDUCT.md).

*Note 1*: This post includes links to the private Node.js moderation repository. These are included in this post solely to allow Node.js project collaborators to see the original context of the issues. The [Moderation Guidelines](https://github.com/nodejs/TSC/blob/master/Moderation-Policy.md) are still in effect and no discussion of those Moderation issues is to occur outside of the private Moderation repository.

*Note 2*: This issue is being locked. Please direct any feedback you may have to either myself or @mhdawson.

**Comment by jasnell** [comment]
Addendum: Following ongoing discussions with members of the collaborator community, the Node.js Board of Directors, and members of ecosystem, I have decided to post the specific list of complaints as they were provided to me to the private internal moderation repository in accordance with the Moderation Policy. These details are accessible to anyone who is a member of the Node.js GitHub Organization. Prior to posting those issues here, the list of issues was *already* discoverable via the moderation repo by any Node.js collaborator therefore providing the list there does not reveal any additional detail that collaborators did not already have access to. 

Node.js Collaborators are reminded that the details of Moderation repository threads are considered confidential per the [Moderation Guidelines](https://github.com/nodejs/TSC/blob/master/Moderation-Policy.md).

**Comment by rvagg** [comment]
I have now posted a lengthy response to this, and the recent call for my removal from the CTC and today's call for my suspension over at https://github.com/nodejs/CTC/issues/165#issuecomment-324798494

**Comment by jasnell** [comment]
Closing now.
