### ISSUE TITLE
Form an Admin team / subcommittee

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/TSC#328]
As previously discussed in multiple places regarding merging, I think we should form an admin "team" that has explicit granted authority to make _certain_ admin decisions on behalf of the TSC for the sake of not involving everything in a large vote.

Fundamentally, it would be designed to insulate the TSC from certain routine duties in order to streamline administration.

The admin responsibilities would, I think, be:
- explicitly not moderation (should be its own thing)
- be able to make regular budget allocations on behalf of the rest of the TSC
- oversee non-moderation github admin (creating repos, adding members, etc)
- coordinate with the TSC director for communications with the board
- probably be more in contact with the CommComm than the whole TSC

I think that having this as a side group under the TSC with explicit permissions is appropriate at the current time.

I think having 1-2 week on/off-boardings to or from the TSC at any time is acceptable. Perhaps the TSC would be able to separately appoint people to the admin team also.
However, ensuring that it is empowered to make decisions is important to ensure that otherwise not involved people do not hold things up piecemeal.

Please discuss - I may be able to write up a full thing for this but not at the current time.

**Comment by Fishrock123** [comment]
As a note I think this is crutially different from the TSC because the authority structure, goals, and onboarding path are able to be clear.

Also, I think that _at the very least_ this should exist for budget purposes.

**Comment by jasnell** [comment]
-1 ... I do not believe this is necessary at this point and puts us right back in the same position as before merging the committees back.

1. The modifications to the moderation policy that landed today establishes a moderation team
2. The budget allocations are the responsibility of the TSC Director and can, as they have been for some time, be handled async via GitHub.
3. The non-moderation github admin is addressed in https://github.com/nodejs/TSC/pull/219
4. Coordinating with the TSC directory for communications with the board can also happen async via Github without the overhead of spinning up a team
5. Probably be more in contact with the CommComm than the whole TSC... this can be viewed as one of the responsibilities of both the TSC Chair and TSC Director, without the need for spinning up a whole team.

We should only spin up an administrative team if it becomes absolutely necessary that we need to do so. Let's not prematurely optimize and give it some time before we head down this path.

PR https://github.com/nodejs/TSC/pull/219 has been open for quite some time and deals with many aspects of this. Any comments or feedback you may have for that PR would be helpful
