### ISSUE TITLE
meta: Establishing the Moderation Team

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#329]
@nodejs/community-committee, @nodejs/tsc, @nodejs/collaborators 

PR https://github.com/nodejs/TSC/pull/276 landed earlier today after long discussion. 

Among other updates, the PR establishes a Moderation Team staffed by Collaborators approved by *both* the TSC and CommComm. The rules are spelled out fairly explicitly in the updated guidelines.

1. Moderators must be Collaborators, which means they must have write permissions in at least one Node.js GitHub repository.
2. Moderators self-nominate and are either automatically approved after 1 week, or if there are objections from anyone on TSC or CommComm, there must be a vote to approve. The vote requires a simple majority of the CommComm *and* a simple majority of the TSC to approve.
3. Moderators must be recertified annually with a simple majority vote of each committee (just like above).

The Moderation Team is delegated authority for nearly all moderation actions. Both the CommComm and TSC has oversight over those actions.

I invite any Collaborator interested in helping with moderation as an official member of the Moderation Team to respond and leave a comment here self nominating.

**Comment by hackygolucky** [comment]
@jasnell Can we move this issue to the Moderation repo? Since it is a jointly-owned repo, I think it makes more sense for it to exist there.

**Comment by jasnell** [comment]
Yeah that works too

**Comment by hackygolucky** [comment]
Can keep this here to send people to that repo for discussion from the TSC membership!

**Comment by mhdawson** [comment]
Posted in moderation repo here: https://github.com/nodejs/moderation/issues/132

**Comment by mhdawson** [comment]
Issue in moderation repo: https://github.com/nodejs/moderation/issues/128

**Comment by jasnell** [comment]
Closing as the initial moderation team has been bootstrapped.
