### ISSUE TITLE
Proposal: Board issues a joint non-discrimination statement

### ISSUE THREAD

**Issue by DelanoJ84** [nodejs/TSC#330]
The board should issue a statement assuring the community that it will fairly investigate reported [Code of Conduct](https://github.com/nodejs/TSC/blob/master/CODE_OF_CONDUCT.md) violations regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation. No allowances will be made due to the aforementioned characteristics of the person making the report, the person being reported, or any people or groups mentioned in a report.

Additionally, project maintainers who do not follow or enforce the Code of Conduct in good faith will also face temporary or permanent repercussions which will not be biased by any of these immutable traits.

**Comment by Trott** [comment]
Taking @benjamingr's [response elsewhere](https://github.com/ayojs/ayo/issues/41#issuecomment-326759482) almost word-for-word:

The code of conduct for Node.js already states:

> In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation.

I don't think that making a statement about enforcing it would matter that much. I think people will definitely judge Node.js based on how that policy is enforced.

**Comment by DelanoJ84** [comment]
@Trott In writing, yes, the Contributor Covenant Code of Conduct will be enforced just as fairly if someone makes a hateful statement against women as if they make that same statement with the genders flipped. My experience with this CoC, however, has not suggested this is the case. I will not name anyone publicly but I will note that some statements condoning politically-motivated violence have been made by people involved in its promulgation. Such statements are, of course, very different from what is advertised in the document which would suggest that many of the people involved in promoting and adopting the CoC are not actually aware of what it actually contains or what terms like "political attacks" actually mean.

**Comment by TimothyGu** [comment]
> My experience with this CoC, however, has not suggested this is the case.

I'm sorry about that. Node.js is a different project however, and it's unfair judge how *we* will enforce the CoC by looking at other projects.

In any case, whether Contributor Covenant is an appropriate CoC has been decided already, and is out of topic here. :+1: on @Trott and @benjamingr said.
