### ISSUE TITLE
Chair + Director still a single role based on bylaws

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#332]
> The TSC will elect from amongst voting TSC members a TSC Chairperson to work on building an agenda for TSC meetings and represent the TSC to the Board for a term of one year according to the Node.js Foundation’s By-laws. The TSC shall hold annual elections to select a TSC Chairperson; there are no limits on the number of terms a TSC Chairperson may serve.

https://github.com/nodejs/TSC/blob/master/TSC-Charter.md#section-7-elections

Is there language somewhere else that specifies there are two distinct roles?

**Comment by jasnell** [comment]
https://github.com/nodejs/board/blob/master/by-laws.md#section-54-committees-of-the-members

> The TSC shall elect a Chair and a TSC Director (as defined in Section 4.3(e)). The Chair and TSC Director may be (but are not required to be) the same person.
