### ISSUE TITLE
Update nodejs.org website

### ISSUE THREAD

**Issue by fhemberger** [nodejs/TSC#334]
Ref: https://github.com/nodejs/TSC/issues/312#issuecomment-323994897

Please update the foundation pages of nodejs.org with the recent changes:

- Merger of CTC/TSC (foundation bodies, current members, etc.)
- Are meeting minutes still published somewhere? (Same for board meetings)
- …

**Comment by fhinkel** [comment]
@fhemberger you've updated the memberhsip list. Should we update anything else?

**Comment by fhemberger** [comment]
@fhinkel Sorry, I lost a bit track of all the changes. Is there anything else which happened in the Foundation lately that should be reflected on the website? If not, please feel free to close this issue.

I'd still love to have the member list for TSC, Board, etc. in a separate `MEMBERS.md` file in each repository, which we could simply include during all website builds. This way we don't have to direct people away from the website to various GitHub repositories.

**Comment by fhinkel** [comment]
I don't have anything to add top of my head. But I'll think about it. Thanks!
