### ISSUE TITLE
Mothballing and archiving the node-eps process

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#335]
@nodejs/tsc: For those who are not familiar with the term: `mothballing` == to `stop using (a piece of equipment or a building) but keep it in good condition so that it can readily be used again.`

Essentially, the `nodejs/node-eps` process has not been an overly successful process. The conversations there tend to get lost in the weeds, fail to progress, and attract trolling and bad behavior. The process of just setting up a working fork or working via a PR has been extremely successful in comparison (see `URL`, `http2`, `n-api`, `node-chakracore`, @bmeck's ESM PR, all for good examples).

The `nodejs/node-eps` approach never really got the love it needed from the TSC/CTC to be successful. I'm proposing that we archive the repo and no longer push it as a recommended process.

**Comment by Trott** [comment]
SGTM

**Comment by MylesBorins** [comment]
SGTM

**Comment by thefourtheye** [comment]
SGTM

**Comment by mhdawson** [comment]
I wish we had an alternative but seeing how little love it has received SGTM for now.

**Comment by jasnell** [comment]
@nodejs/tsc ... we need more tsc members to weigh in.

**Comment by bnoordhuis** [comment]
One more SGTM for the collection.

**Comment by targos** [comment]
SGTM

**Comment by evanlucas** [comment]
I like that idea

**Comment by Trott** [comment]
> @nodejs/tsc ... we need more tsc members to weigh in.

No one objected. 5 members besides you gave it the thumbs up. It was open for 5 days and TSC was @-notified immediately when the issue was opened.

**That's consensus.** Someone who hasn't spoken up by now can be considered a "no objection" and/or "no opinion". 

(And now you have three more approvals! Four more if you include Joyee's thumbs up reaction.)

**Comment by jasnell** [comment]
Indeed, I'm happy to call it in favor of the proposal. It would just be helpful if all 22 TSC members would generally be more proactive about weighing in on such issues. As it is, assuming we're moving forward with this, I will open a PR against the nodejs/node-eps repo updating the README to say that it is archived and will open an issue there communicating the same.

**Comment by jasnell** [comment]
Closing as the issue appears to be resolved.

**Comment by Fishrock123** [comment]
... I am not for this. I think it is useful and it should be used _more_.

**Comment by ofrobots** [comment]
I thought I had commented on this already. Here's post-closing +1 on this proposal.

**Comment by SamB** [comment]
Um ... shouldn't you have left a note about where to go instead at <https://github.com/nodejs/node-eps#readme>?
