### ISSUE TITLE
TSC Meeting Schedule

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#336]
There's a CTC meeting that had been scheduled for Wed. Sep 13 at UTC 20:00 this Wednesday (1 PM San Francisco, 4 PM New York, 10 PM Germany, 11 PM Moscow, Thu 1:30 AM India, Thu 4 AM China, Thu 5 AM Japan, Thu 6 AM Sydney). 

***I propose that we use that time for our meeting on that date.***

At that meeting, I'd like this to be on the agenda (unless we can get consensus before the meeting, which would be awesome):

***I propose that after that meeting, we have a meeting scheduled every week rotating between UTC 12:00, UTC 17:00, and UTC 22:00.***

Those times were selected algorithmically based on the contents of the private spreadsheet of everyone's availability. If you think those times are terrible, consider updating your row in the spreadsheet!

**Comment by mcollina** [comment]
I am +1 with that.

**Comment by MylesBorins** [comment]
Considering that the majority of TSC meetings had been skipped lately and
that CTC meeting were moved to every third week, do you think it might make
sense to stick with every two weeks?

**Comment by Trott** [comment]
> Considering that the majority of TSC meetings had been skipped lately and
that CTC meeting were moved to every third week, do you think it might make
sense to stick with every two weeks?

CTC was every other week, not every third week.

My opinion only: I think given the current status of things, every week makes sense. We should have had a meeting this week.

I look at it this way: At this point in time, I'd rather have a meeting schedule every week and have half of them canceled rather than have a meeting scheduled every other week and wish we had them more often.

**Comment by ChALkeR** [comment]
Yes, what @Trott said is the same what I had in mind. +1 to every week by default, cancelling on case-by-case basis would be better.

**Comment by mhdawson** [comment]
+1 from me as well

**Comment by MylesBorins** [comment]
Sgtm.

I was definitely mixing up the schedule

**Comment by Trott** [comment]
This was ratified at today's TSC meeting. The Node.js calendar has been updated too.
