### ISSUE TITLE
Expanding WG representation in TSC

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#351]
We currently do not have adequate representation from either the Website or Docker WG's in the TSC. I would like to invite Frederic Hemberger (@fhemberger) from the Website WG, and Christopher Horrell (@chorrell) from the Docker WG as regular Observers to the TSC meetings.

**Comment by mhdawson** [comment]
+1 for inviting them as observers.  It would be great to have them present.

**Comment by chorrell** [comment]
+1 from me :)

**Comment by fhinkel** [comment]
SGTM. @jasnell , since you proposed this, do you want to take initiative and invite them to the next meeting?

**Comment by mhdawson** [comment]
There was a recent request that we don't have standing observers, but instead invite on a per meeting basis.

@jasnell what's your view on how that fits with that approach.

@nodejs/tsc can we get more input on this case.

I'd be ok with inviting them as regular observers, but given the pushback on regular observers I think we need more discussion.

**Comment by jasnell** [comment]
My preference would be to invite @fhemberger and @chorrell in as TSC members.

**Comment by jasnell** [comment]
Closing as there does not appear to be support for this proposal.
