### ISSUE TITLE
Decharter Intl WG

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#353]
I would like to propose dechartering the Intl WG in favor of it being a more informal Team. I'm not convinced that we ever really had much benefit of it being a formally chartered working group. A team would still be just as effective without having any of the additional overhead of a chartered working group.

ping @srl295

**Comment by fhinkel** [comment]
ping @srl295

**Comment by mhdawson** [comment]
@srl295 unless you object I'd agree that Intl could be a team.

**Comment by srl295** [comment]
sure— sounds OK off the top of my head (and I'll go change my slides…)

**Comment by srl295** [comment]
^ I could not find a lot of details on team vs. WG. I filed the above issue nodejs/Intl#45 over any changes that should happen to the Intl repo. In particular, does the Intl _repo_ need to close, because there are some valuable issues there— but, they could move to issues in other repos but with appropriate tags.

**Comment by Trott** [comment]
@srl295 Team = GitHub team, so @nodejs/intl would be the team. Yeah, not a lot of documentation on how that differs from a chartered WG. We could definitely improve there. The repo does not need to close. (Testing WG was de-chartered but the repo remains, for example.)

**Comment by srl295** [comment]
What's the next step here?

**Comment by MylesBorins** [comment]
Ping @nodejs/tsc

**Comment by Trott** [comment]
> Ping @nodejs/tsc

https://github.com/nodejs/nodejs.org/pull/1513
https://github.com/nodejs/TSC/pull/437

**Comment by Trott** [comment]
Going through remaining open issues in https://github.com/nodejs/Intl/issues right now. Planning on archiving the repo (basically making it read-only) sooner or later.

**Comment by mhdawson** [comment]
@srl295 earlier discussion was that the repo did not necessarily need to close if the WG became a team.  Is the repo still useful for the team ?

**Comment by Trott** [comment]
@mhdawson @srl295 OK, I won't archive the repo for now and I'll stop my march through all the issues to close them that I started a few minutes ago. It does seem that the Intl repo is a bit of a graveyard though. I think the issues in that repo would probably get more activity/visibility elsewhere.

**Comment by jasnell** [comment]
The discussion appears to have stalled. What is the next step here?

**Comment by srl295** [comment]
@jasnell did it? What's left to do? I have a PR https://github.com/nodejs/Intl/pull/47 to redirect to i18n, and I'm going to go over the rest of the Intl issues and refile…

**Comment by jasnell** [comment]
The conversation in this thread did at least :-) Since there is actively happening elsewhere in the org, does this specific issue need to stay open?

**Comment by srl295** [comment]
Aha.

 #353 can close

**Comment by cjihrig** [comment]
Thanks @srl295, I'll close this.
