### ISSUE TITLE
Using github projects to manage tasks for the TSC

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#357]
There are a non trivial number of things in various states of completion being tracked by the TSC at any one time. Speaking for myself I find it somewhat overwhelming and it is easy to let things slip through the cracks.

Would individuals be open to using [projects](https://github.com/nodejs/TSC/projects) to help manage what is going on and track their current state?

**Comment by jasnell** [comment]
Assuming we have a critical mass of such things to warrant it actually being useful, and people willing to keep the projects pruned and organized, then sounds fine for individuals to do that. I don't think we need to have any kind of formal policy around it.

**Comment by mcollina** [comment]
Definitely 👍 , but something we should not really regulate.
We are using them in core to track certain things.

**Comment by mhdawson** [comment]
+1 from me.
