### ISSUE TITLE
Rename "Top Level Project" in TSC and Incubator

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#36]
So, here's the problem. We have two totally different definitions of "Top Level Project" in the foundation bylaws and in the Project Lifecycle.

The foundation bylaws establish the TSC as a "Top Level Project" and actually leave the door open for other TLPs at the same level as the TSC (something we aren't doing yet but could potentially do in the future if the board chooses to).

Then we have the definition in this repo which is a "project under the TSC." Because the foundation bylaws are way more difficult to change we're going to need to find new language here.

Can we get away with just renaming to "Project" ???

**Comment by TheAlphaNerd** [comment]
"Community Sponsored Project"?

I personally really like including the term "community" in here if possible, I think it will quell some fears about the intentions of the TSC. There was a comment in the express thread about trusting the foundation today, I will avoid linking as to not send traffic here.

**Comment by mikeal** [comment]
"Sponsored" goes a little bit in the wrong direction considering our current worries about being viewed as "endorsing" or "picking a winner" when we admit projects.

**Comment by TheAlphaNerd** [comment]
Community Supported Projects?
Community Owned Projects?
Community Projects

**Comment by mikeal** [comment]
What do you think about dropping "project" and calling them a "Community?"

**Comment by TheAlphaNerd** [comment]
can you use that in a sentence (not teasing, curious how it would sound)

**Comment by rvagg** [comment]
Just catching up on this, sorry for being out of sync. Can you point us to the bylaws somewhere please @mikeal so we can understand the conflict better?

**Comment by mikeal** [comment]
Section 4.3(e)

> (e)  At the time of any election of Directors  where the number of Platinum Directors is two or greater, the Technical Steering Committee shall designate a representative to the Board of Directors in accordance with Section 5.4(b) below, which representative shall automatically be a member of the Board (the “TSC Director”).  Initially the Node.js Foundation will start with one top level project, however, the Board of Directors may in the future approve the creation of one or more additional top level projects relevant to the Node.js community. As additional top level projects are approved, the Board shall determine an appropriate model for representing the additional top level project technical steering committees on the Board.

Essentially, the board may admit additional top level projects in parallel of what is currently under the TSC and *could* even have another board seat representing them.

This is distinctly different from top level projects *under* the TSC which is what we've been approving and I would like to rename to avoid a conflict.

**Comment by rvagg** [comment]
My vote would be to ignore this apparent disconnect and deal with it ever legitimately comes up. Making it easy for the Board to adopt parallel but completely disconnected projects would have some pretty bad consequences and I for one will work hard to avoid such a situation. Our efforts should be united under the same goal, if a project can't fit under what we are doing _here_ then it doesn't belong.

**Comment by Fishrock123** [comment]
@mikeal Is the marketing board a foundation TLP?

**Comment by jasnell** [comment]
>Essentially, the board may admit additional top level projects in parallel of what is currently under the TSC and could even have another board seat representing them.

This is actually the key issue I'm concerned with. I don't think this is what was *intended* when this was all put together. The Board and TSC should be working together on TLP's as opposed to having parallel tracks. This is why we split the TSC and CTC after all, isn't it?

The relationship should be:

```
Board --- TSC 
    \     /
      TLP 
```

Not, 

```
Board --- TSC 
  |       |
 TLP     TLP  
```

This would help to ensure that there is alignment between the Board and TSC around the community vision moving forward. There has already been concern and criticism that the Board comes across as out of touch with the larger Node.js community, I'm afraid that if we continue along this "parallel TLPs" approach that will become even more pronounced.

**Comment by mikeal** [comment]
@Fishrock123 nope, the marketing committee is a "member committee." The legal committee is a "board committee." The only Top Level Project right now is the "Node.js TSC."

@jasnell I'm not entirely sure what the graphs mean. *Technically* the TSC is under the Board as the TSC charter was passed by the board. However, the TSC charter grants an incredibly high degree of autonomy so you could see them as parallel. A future TLP from the board would also have charter passed by the board, similar to the TSC Charter we have from the board, but it's possible that it could be structured differently from the TSC as it won't have the same charter.

**Comment by jasnell** [comment]
sigh, my ascii art skills are lacking, my friend. The idea I'm trying to convey is that I don't believe the Board should be chartering new TLP's that are *independent* of the the TSC. Top level projects would have their own CTC's, but would still fall under the existing TSC. I *believe* this is the model that most of us were expecting.

**Comment by Fishrock123** [comment]
It seems to me, that by adding another node TLP, we'll have the same core<->other community split that existed when Node was under Joyent. Isn't this what we've been trying to avoid with the foundation?

**Comment by mikeal** [comment]
@jasnell it may be necessary in the future to do this. This does not mean that the TSC won't be the home of multiple TC's but, for a variety of reasons, it may be necessary to bring in another project project chartered by the board with differing governance and constraints than the TSC. This is mostly a tool for risk mitigation, if the board thinks the foundation needs to take on a new technical effort but the risk is high it's best not to jeopardize the work the TSC is doing and it may be important to add constraints the TSC does not have.

@Fishrock123 these shouldn't be in competition with each other and we would expect collaboration between the groups, just as the TSC collaborates with community members and projects outside of the foundation. However, I don't think the board would want to charter another group with the ability to bring in *additional* projects underneath it the way the TSC does, so there is unlikely to be any kind of "competition" for where a project would enter the foundation.

**Comment by jasnell** [comment]
It *may* become necessary at some point but I would much rather it not be one of the default options out of the box. In other words, if and only if the board thinks it necessary for the foundation to take on a new technical effort that would risk jeopardizing the work the TSC is doing, then it *might* be an option to bring on a new fully independent TLP with it's own TSC, however, the first choice should be having projects come in as TSC top level projects, working within the incubation process.

**Comment by mikeal** [comment]
> It may become necessary at some point but I would much rather it not be one of the default options out of the box.

Just to be clear, the bylaws *already* state this. The board *already* has the ability to do this if necessary.

We can discuss this a bit more in the meeting today but I think your notion of what another TLP would look like is a little off. It's also significantly more work for the board to pass a charter for a new TLP than it is for the TSC to admit a project so that is always going to be the *"default"* approach.

**Comment by jasnell** [comment]
> I think your notion of what another TLP would look like is a little off

entirely possible ;-) I think we just need to make sure there's clarity.

**Comment by williamkapke** [comment]
Such an old topic ;)
Revisiting this after all this time; here's how I see things today:

There is only 1 type if TLP. It is approved by the board. That is because a TLP contains tangible goods (software) that is licensed and owned by the Foundation.

We create new projects from time-to-time that all fall under the Core TLP (thus why we've spent the better part of the year "Defining Node Core"). Some sometimes things don't fall under Core TLP and so they would go under a new TLP.

Express is an example.
The Node Security Project MIGHT be another example.

A new TLP doesn't absolutely mean it gets a new Board Committee (or Member Committee). The language in the By-Laws ("shall determine an appropriate model for representing") just allows the board **the option** to create a new TSC if they want. We **hope** they continue to delegate most of the technical work to the TSC.

When the TSC is given the reigns of a new TLP, [it's policy is to create a TC that is in change of it](https://github.com/nodejs/TSC/blob/master/Project-Lifecycle.md).

**Comment by jasnell** [comment]
Do we need to keep this open? If there are concrete changes to be made in the documents, a PR would likely be better than an open ended issue.

**Comment by jasnell** [comment]
Closing due to lack of forward progress on this. We can reopen if necessary
