### ISSUE TITLE
Being an organization for Google Summer of Code 2018

### ISSUE THREAD

**Issue by mcollina** [nodejs/TSC#366]
Here are some details: https://developers.google.com/open-source/gsoc/

We can apply as an organization from the 4th to the 28th of January. We might want to decide if we want to do it before then. My experience in being a mentor has been great, and then student was extremely successful.

This might also fall under @nodejs/community-committee.

**Comment by bnb** [comment]
Huge +1 on this - I've seen other orgs succeed with it, and I'd very much like to see Node.js participate as well. 

What are the expectations of commitment from the Node.js organization and contributors for it?

**Comment by gr2m** [comment]
I all +1, but I’ve also heard several people having bad experiences, but that’s a few years ago. What usually helps is set clear expectations and set a higher bar for students from GSoC to apply for your project. I’d be happy to advice if we decide to move forward

**Comment by fhinkel** [comment]
Not against gsoc, but I would much prefer a project that draws from a more inclusive applicant base.

**Comment by mcollina** [comment]
@fhinkel are any other similar projects that meets your criteria? I only know about GSoC.

**Comment by fhinkel** [comment]
There's Outreachy. @hackygolucky has a better overview I think.

**Comment by gr2m** [comment]
https://railsgirlssummerofcode.org/ is amazing.

**Comment by mcollina** [comment]
https://www.outreachy.org/ seems fantastic.

@gr2m are you suggesting we run our own initiative? Or we should have http://foundation.travis-ci.org/ run it?

**Comment by fhinkel** [comment]
@gr2m it's not limited to Rails/Ruby projects, right? That might be a good fit!

**Comment by Qantas94Heavy** [comment]
@fhinkel I don't think so. For example, Babel mentored two students this year from Rails Girls SoC and they don't exactly seem like a Rails/Ruby project to me 👍

**Comment by tniessen** [comment]
Outreachy, GSOC and RGSoC are not really mutually exclusive, right?

**Comment by MylesBorins** [comment]
They are not... although they all require a non trivial amount of oversight
and work. As such we do have to make sure to only commit to things we can
follow through on.

**Comment by gr2m** [comment]
> [Rails Girls SUmmer of Code] is not limited to Rails/Ruby projects, right? That might be a good fit!

no it’s not :) Between the 3, I’d try RGSoC. Outreachy requires us to sponsor, I think it was $6,000 last time I taked to them

**Comment by fhinkel** [comment]
AFAIK getting sponsor money from member companies is easier than finding projects and mentors ;)

**Comment by mcollina** [comment]
So, do we have project ideas?

Here is mine: improve the prebuild toolchain for Node binary addons, so that binary modules can be signed and verify after downloading, and we have first-class support for node-addon-api modules.

**Comment by Trott** [comment]
I know these things tend to focus on code, so maybe this sort of thing won't quite fit into some of these events/organizations, but maybe there's something @nodejs/build could suggest. I'm not sure _exactly_ what sort of code the Build WG could use right about now, and I don't know if having a person is exactly what they need now, but maybe?

**Comment by bnb** [comment]
Building on the suggestion of the Build WG, selecting one of our various automation tools and improving it (like the GitHub bot, for example) may be a good approach.

**Comment by jasnell** [comment]
What is the current status on this?

**Comment by TimothyGu** [comment]
The deadline for application has long passed, so this is definitely not happening.
