### ISSUE TITLE
Meeting next week - NI overlap

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#368]
I likely won't be able to make the meeting next week due to overlap with Node Interactive.

I'm guessing it might be the same for a number of other TSC members.

Should we cancel the meeting or schedule it anyway and find a volunteer to run it ?

**Comment by targos** [comment]
I will be at Node Interactive too.
At what time (in Vancouver) is the meeting supposed to be?

**Comment by mcollina** [comment]
I’m +1 on cancelling

**Comment by cjihrig** [comment]
Also +1 to canceling.

**Comment by Fishrock123** [comment]
The meeting would be at 3-4pm Pacific Time (@targos). I think we should skip.

**Comment by targos** [comment]
Thanks. +1 to skip.

**Comment by MylesBorins** [comment]
Could we do a proxy meeting during collaboration summit?

**Comment by mhdawson** [comment]
@MylesBorins there is a lot going on at NI so I'd prefer to skip instead of doing a proxy meeting.

**Comment by jasnell** [comment]
I would prefer to skip as well.

**Comment by Trott** [comment]
It will conflict with @joyeecheung's talk at Node Interactive. That's almost certainly where I'll be, so if anyone wants to have a micro-TSC meeting between her talk and the next one, see you then and there.

This is my longwinded way of saying +1 to either skipping next week or at least changing the time to something less in conflict with Node Interactive.

**Comment by joyeecheung** [comment]
Ah, didn't noticed the overlap. I will certainly skip this...because of my talk.

**Comment by mhdawson** [comment]
Unless there are objections by end of day today, I'll cancel.

**Comment by mhdawson** [comment]
Cancelled, removed from foundation calendar.
