### ISSUE TITLE
How to contribute to node as a beginner

### ISSUE THREAD

**Issue by Giovarco** [nodejs/TSC#373]
Hello!

As a beginner, I would like to contribute solving some issue, but I noticed that there is no "beginner" label or the like. Can you give me some tip?

**Comment by sam-github** [comment]
Check out `good first contribution`:

https://github.com/nodejs/node/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+contribution%22

**Comment by gibfahn** [comment]
In general https://github.com/nodejs/help/ is the right place for questions, if you have more you can also raise issues there.

Also check out http://nodetodo.org/

**Comment by mhdawson** [comment]
I'd also suggest looking at the different working groups to see if any of them interest you and then start following/helping out there.

**Comment by Giovarco** [comment]
@mhdawson with "different groups" do you mean "other repositories"?

**Comment by Trott** [comment]
Regarding "different working groups":  https://nodejs.org/en/about/working-groups/

In addition to some of the suggestions above for places to ask this sort of stuff, you can also try asking in the #node-dev channel on Freenode IRC.

If you happen to be attending Node Interactive in Vancouver this week, come to the Code + Learn session on Friday morning.

Thanks for asking about this and your interest.  I
