### ISSUE TITLE
This week's TSC meeting

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/TSC#376]
As I am now in Pacific time I will be unable to record/broadcast this meeting time. Perhaps someone else could. 

There are docs in https://github.com/nodejs/TSC/tree/master/Streaming if you need info how to. If you run macOS you need special drivers for audio though. Let me know if anyone needs any help with this.

**Comment by mcollina** [comment]
I can try to do it from my Windows machine as I am at home. I'll do a practice run on my personal account later today.

**Comment by mcollina** [comment]
I can confirm I can live-stream with OBS.

@Fishrock123 do you connect two accounts to UberConference or do you join from the windows box? What's best for audio quality?

**Comment by fhinkel** [comment]
Closing this, as the meeting is about to happen. Feel free to reopen if necessary.
