### ISSUE TITLE
Proposal for some Incremental TSC Governance Practices Changes

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#380]
At the 2017 Node Interactive in Vancouver, the Node.js Technical Steering Committee (TSC) gathered to discuss governance. We had Sarah Novotny there to talk to us about Kubernetes project governance. (She is now on the Node.js Foundation board of directors!)

At the end of the session, we went around the room to talk about the one big thing we hoped to discss the following day.

Here are some samples:

* Anna Henningsen listed absence (in a very general sense, not just at meetings) of TSC members as an issue that needed addressing.
* Michael Dawson suggested that we needed to figure out how to get to the point where everyone on the TSC is actively engaged.
* Rich Trott (that’s me!) wanted to get agreement from other TSC members that we will increase TSC membership turnover.

“Increasing membership turnover” might seem like an odd goal, so I’ll explain a bit more: Right now, an appointment to the TSC is indefinite. You can think of it as a lifetime appointnment. People only leave when they voluntarily step down, which can often happen years after the person’s last significant involvement in Node.js governance. We’re not good at getting disengaged members to leave the TSC. (It’s technically true that someone can be voted off the TSC but this has never happened.)

Because we are not good about removing members who should be removed, we consequently need to exercise extreme caution in bringing new members on. If we bring someone on and they’re not engaged or even disruptive, we’re likely to be stuck with them for years.

So, that’s a bit of a problem statement. I and others have proposed various (and not necessarily conflicting) solutions to this problem. However, I want to additionally consider some other things that people said during that end-of-meeting round-up of priorities:

* Sarah Novotny implored us to take an operations approach: Move slowly. Don’t change a lot at once. Make one change at a time. Pick the top problem and Try A Thing.

* Franziska Hinkelmann requested that we don’t make rash decisions.

* Matteo Collina said that before making any final decisions around governance, we should ask what the rest of the collaborators think.

In the spirit of making a single incremental change and requesting feedback from the larger community, here is my proposal.

* TSC member should identify relatively inactive members and ask them if they would consider stepping down. This should not be a one time or even once-a-year thing. For the foreseeable future, at least one person a month should be asked to consider if they wish to remain on the TSC.

* For the foreseeable future, TSC should pretty much always be onboarding a new member. We should have a one-a-month cadence on that too. In the past, we’ve been slow to onboard people and we onboard them in groups. This leads to a “OK, we’re done onboarding people for 18 months” mentality. Let’s do one-at-a-time and do it always. This way, the TSC is always moving slowly to be more representative of the concerns of the people who make Node.js what it is.

The desired end result is:

* People cycle on and off the TSC more frequently.

* The TSC is more representative of the active Node.js community.

* As a result of that, there is a more engaged and trusted TSC.

* There is no stigma to leaving the TSC. It is not a punishment. It is a thing that happens all the time and is not a big deal because…

* People can cycle back on to the TSC when they are ready to be more involved again.

One great thing about this proposal is that I can do most of it myself. There’s nothing stopping me from asking people to consider if they still want to be on the TSC. And in fact, I’ve started doing that.

And as for nominating new members, there’s also nothing stopping me from nominating a new member every month. There, however, I need more buy-in from other TSC members. They need to approve the nominee and we need to actually onboard them if they accept the nomination. I did, in fact, nominate someone, but there is concern from some on the TSC that we need to more clearly document expectations of TSC members first. Fortunately, there also seems to be agreement that there ought to be a deadline (probably a month) on how long we wait for that documentation before we begin onboarding.

So there’s my proposal for a first incremental change. If everyone agrees to it, it’s important to realize this is not a done process. We may decide this was a mistake, in which case we undo it and try something else. Or perhaps we will decide it’s a terrific improvement, in which case we iterate and try to further improve.

**Comment by mcollina** [comment]
I see this as a stop-gap solution, not as the end result. However, it has the side benefit of putting power on whom is doing the work: SGTM.

**Comment by jasnell** [comment]
Definitely a stop gap. There are larger changes that are necessary. On Friday I should finally have some time to put together the rather more ambitious proposal I've been stewing over since collab summit.

**Comment by mhdawson** [comment]
I agree this is a reasonable approach while we think about the overall changes.  I'd propose that we look to onboard the next TSC member Nov 13, to set the hard date.  Between now and then, lets see what we can agree on in terms of expectations for TSC members so that we can at least informally cover those with the new TSC member to be on-boarded.
