### ISSUE TITLE
Replace regular invited "observers" from call-in TSC meetings with topic-specific participants

### ISSUE THREAD

**Issue by rvagg** [nodejs/TSC#388]
Following on from the aborted discussion @ #384 I'd like to propose that we limit the regular invitees to TSC meetings to TSC members. Other individuals are invited on an advisory basis for specific meetings (not recurring unless the issues involved are recurring) and that these individuals are proposed prior to meetings by one or more TSC members for the purpose of informing the discussion of one or items on the agenda.

The two primary issues to be addressed by this IMO are:

* Inclusion of somewhat arbitrary individuals in the decision-making process (voting is a minor part of our meetings & their decision-making process). If we have not seen fit to raise these people to the TSC then their inclusion is arbitrary.
* Additional blurring of the lines between the technical group's activities and the Executive and Board by the inclusion and expansion of their presence at meetings. The separation and independence of the technical group is a key founding precept of the Foundation that we ought not do away with lightly. If you want to do away with that then open a PR to the TSC Charter and discuss it there.

As per the Charter:

> ... The Board may additionally make amendments to the TSC charter at any time, though the Board will not interfere with day-to-day discussions, votes or meetings of the TSC.

Additionally:

> The Board will set the overall TSC Policy. The policy will describe the overarching scope of the Node.js Foundation initiative, Node.js Foundation’s technical vision and direction and project release expectations in the form of expected cadence and intent. The Board will use the TSC as a delegate body for governing technical implementation, individual project scope and direction while they remain within the scope and direction of the policies as described in the TSC Policy document and approved by the Board.

The Board (and by extension its Executive) is pay-to-play, the TSC is contribute-to-play and erosion of the separation is to the detriment of the trust and integrity of our governance processes and the independence of our technical decision-making capabilities.

That said, I have no objection to pulling in Board or Executive individuals where their input on administrative, governance, marketing, community, education (etc.) matters makes sense, this is purely about the entrenchment of regular observers.

@Trott:

> Not objecting but getting this on the radar: I've been considering suggesting that we not have "regular observers" anymore but that observers get invited when it is relevant. I think having regular observers creates a club and implies some elitism TBH, whereas having to specifically think about who to invite each week is probably healthy. It is especially healthy if it causes us to cast our net a little wider on who we invite.
> Should we invite bmeck any time we are discussing anything that touches on ES Modules? Absolutely. Should they get invited to every single meeting? I'm not sure that makes sense. (And I suspect Bradley would agree with that assessment.)

...

>Looking at the list of five regularly invited observers, none of them attend regularly. Nor should they, IMO. I'm tempted to add an agenda item saying that we should get rid of regularly invited observers. I'm happy to submit the PR to the tooling that makes the meetings.

@rvagg:

> Removal of "regular observers" makes sense to me too @Trott. We've had a lot of difficulty in the past trying to figure out where to draw the arbitrary line on who gets to attend or not. Particularly when someone tries to invite themselves, it can create a very awkward situation.

> That awkwardness is compounded by it being done in public like this too. It's very unlikely that folks are going to want to be totally honest about what they think of such proposals when it involves the very public perception of judging an individual's worth. We've had a lot more candour when we've discussed the merit of adding observers privately than we're going to get by doing it here. Assuming that because nobody objects here to proposals to add specific individuals means that there are no objections is pretty naive IMO. I'm pretty sure you're all aware of the new costs that have been squarely placed on any perception of not being "nice" now; that's going to have a strong chilling effect on honest discussion on topics like this.

> We are pretty diligent with streaming meetings these days and trying to be responsive to people outside the meeting that want to participate with Q&A so I'm not seeing a case for including more people on the observers list, you can observe without being dialed in.

> I'm -1 on more Foundation representatives (Board or Executive) joining in as participants in these meetings. The toll from administrative work here is already pretty large and I'm hearing a lot of grumbling about how dense the non-technical portions of these meetings are now. Adding more non-technical participants is going to push that in the wrong direction. Plus, technical independence was a founding principle of the Foundation, let's not blur those lines even more than they are already.

**Comment by jasnell** [comment]
Ok, +1 on no regular observers.

I would say that we need to be more proactive about pulling in outside experts on governance issues. Those need not be regular observers tho.

**Comment by mcollina** [comment]
+1 on not having regular observers. But I think it would be good to invite someone expert if we are lacking expertise on one of the issue being discussed.

**Comment by mhdawson** [comment]
My 2 cents.

I'm still not sure where the community representatives fit in with this.  I think there might be a case for them being regular observers.  They are different in the sense that we are not just arbitrarily inviting them, they have been elected to a the position within the organization.

I also think there might also be a case for some Foundation representation.  Even if the board/TSC are independent that does not mean we should not be aware of what each other is doing.  I take the point that they can just watch the live stream so if may not be necessary, just don't think we necessarily need to exclude them.

To me the important thing is that we have a good relationship between the TSC, the community representatives and the foundation.  If having them be observers helps to build/maintain this relationship then I see it as a good thing.  

I do agree that outside of these, pulling people in to specific meetings as opposed to making them regular observers makes sense.

**Comment by sarahnovotny** [comment]
I have no opinion on whether or not the TSC should have regular observers (i.e. join the uberconf in order to be able to voice an opinion) vs simply watching the streaming session.  I believe it is quite clear that the project is self governing and any role I might play as an observer is purely advisory where i have experience. Observer or public stream, I want to attend as I am able as an introduction to the governance of the project.

That said, I'd like to make a counter point as I have also heard **community members expressing concern that the board and foundation are too disconnected from the project**.  I think this speaks to a larger lack of trust in the community which I was hoping to help by being more obviously present as a resource to the TSC.

**Comment by Trott** [comment]
Closing because this seems to be a thing that happened. :-D
