### ISSUE TITLE
Proposal to form an automation working group (or team?)

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/TSC#392]
I am proposing to form an automation working group that handles automation outside build (i.e. tools, bots and scripts that make our lives easier)

Related projects:

* [The Github bot](https://github.com/nodejs/github-bot)
* [node-review](https://github.com/evanlucas/node-review) (See [discussion](https://github.com/nodejs/admin/issues/23) on moving them into the foundation)
* [branch-diff](https://github.com/rvagg/branch-diff) and [changelog-maker](https://github.com/rvagg/changelog-maker) (See [discussion](https://github.com/nodejs/admin/issues/16) on moving them into the foundation)
* [core-validate-commit](https://github.com/evanlucas/core-validate-commit) if @evanlucas agrees to move it into the foundation

I am not exactly sure if we should have a charted working group to work on these tools (because that probably means more meetings!), but I think it is a good idea to have a team of people working on them. These projects are somewhat related (e.g. core-validate-commit and branch-diff usually consumes output of node-review) so we should have a place to discuss how to divide the work to address our needs.

Also if IIRC at the collaboration summit we have talked about needing more automation to ease our maintainers' burnout (hopefully doing dev on automation won't make it worse...but meetings definitely make it worse which is why a charted WG may not be a good idea)

**Comment by joyeecheung** [comment]
cc @nodejs/tsc 

I am willing to join this group, and @evanlucas has indicated the same [on twitter](https://twitter.com/evanhlucas/status/921755431630004224) as well.

**Comment by jasnell** [comment]
+1 to a team. I'd love to see work on these tools get more official attention.

**Comment by targos** [comment]
+1. I'd like to be in this team.

**Comment by phillipj** [comment]
Great initiative, +1 from me! The bot deserves more attention than it has gotten lately..

Although I'm not that active collaboratoring nowadays because of family life, I'd also like to join such a group if it existed.

**Comment by MylesBorins** [comment]
+1 on the team, and I'd be interested in getting involved.

Should it be spun out of build?

**Comment by maclover7** [comment]
Also interested in getting involved. Food for thought, I [mentioned on Twitter](https://twitter.com/JoyeeCheung/status/921775445300862976) the possibility of shipping some of these CLI tools under a single root executable to make discoverability/usability easier.

**Comment by gibfahn** [comment]
My first reaction was "This is totally what the Build WG is/should be all about"

But I think it's worth having this anyway.

>Should it be spun out of build?

👍, How about we make @nodejs/automation a team within @nodejs/build, that doesn't have any special privileges (so anyone can be invited and start working on stuff without having to worry about trust etc.). Like how `nodejs/backporting` is a subset of `nodejs/release`.

Fundamentally the Build WG is two things:
1. A bunch of passwords to things (machines, accounts etc).
2. A load of automation scripts to set up machines (Ansible), run jobs (Jenkins), or do other stuff.

The problem is that `1.` means there's a high barrier to entry, which means we get fewer people working on `2.`, even though that's 90% of the actual work. It'd be really great to separate out the two things and reduce that barrier.

**Comment by gibfahn** [comment]
>the possibility of shipping some of these CLI tools under a single root executable to make discoverability/usability easier.

Possible, although the different tools tend to have quite specific uses and audiences. I think having them all under one npm account, and all linked from one repo, would make them much more discoverable anyway.

For example:

- The Github bot => Is run on a server, not by individual people
- node-review => Is run by all collaborators as a browser extension (hopefully downloaded from browser app store)
- branch-diff and changelog-maker => Run by people doing backporting, not really useful for other 
- core-validate-commit => Run by all collaborators as a globally installed node app

But that's totally a discussion we could have if we had an automation team.

**Comment by cjihrig** [comment]
+1 to this team existing, and another +1 to having it as a subset of the Build WG.

**Comment by refack** [comment]
RE Build WG current structure: If we take responsibility for the meta-tooling, then not every member needs to have even test access. Plus we should probably have a staging Jenkins, and a @gibfahn suggested an ansible "tower".
I'm adding this to the WG agenda for discussion.

**Comment by ljharb** [comment]
(also separately, it'd be ideal if every tool that was needed to contribute to node could be `npm install`ed, rather than having to have anything globally installed)

**Comment by joyeecheung** [comment]
@gibfahn Yes I think making a team under build makes sense. My understanding was that the build is more about stuff we cannot "build" without, while technically we can build without these tools (just that'll be a lot more work if we don't have them).

**Comment by joyeecheung** [comment]
Also, does anyone object to the idea of having a separate repo for `nodejs/automation`? If we use the build repo there will be many unrelated issues (e.g. CI machine toolchain updates). Also it would be friendlier if we want to attract people who are not core collaborators (yet) but interested in helping to get the core be more effective (I am thinking about code-and-learn follow ups).

**Comment by gibfahn** [comment]
>(also separately, it'd be ideal if every tool that was needed to contribute to node could be npm installed, rather than having to have anything globally installed)

@ljharb You mean locally installed (`npm i`) rather than globally installed (`npm i -g`)? How would that work? `package.json` in the node repo?

Also, to be clear, none of these tools are required for non-collaborators.

**Comment by gibfahn** [comment]
>My understanding was that the build is more about stuff we cannot "build" without, while technically we can build without these tools (just that'll be a lot more manual work if we don't have them).

I think build is mostly automation to make managing things easier, so I don't really see the distinction. We could do all the builds by sshing into machines and running `make binary-upload`, we just automated a lot of the process.

>Also, does anyone object to the idea of having a separate repo for nodejs/automation? If we use the build repo there will be many unrelated issues (e.g. CI machine toolchain updates).

No objections, but to be clear, the "CI machine toolchain updates" are actually "updates to the automation scripts to install stuff on CI machines".

I think the real difference between an "automation" repo and the Build repo would be that the automation stuff is designed to be run on your own machine, whereas Build stuff mostly runs on other people's machines.

At the same time it'd be great to get more people involved with the Build automation as well.

**Comment by joyeecheung** [comment]
> @ljharb You mean locally installed (npm i) rather than globally installed (npm i -g)? How would that work? package.json in the node repo?

I think @ljharb probably means a npm package with multiple `bin` entries pointing to these tools?

> Also, to be clear, none of these tools are required for non-collaborators.

Yep, although I often find myself reinstalling tools after updating my global Node version.

**Comment by gibfahn** [comment]
>Yep, although I often find myself reinstalling tools after updating my global Node version.

Interesting, I've never yet had to do that, probably because I do a `make install` to update my global node version, and then run `nvm` when I want a specific version.

If you're using `nvm`, maybe [default packages](https://github.com/creationix/nvm#default-global-packages-from-file-while-installing) or [reinstall-from](https://github.com/ljharb/nvm#migrating-global-packages-while-installing) might be helpful?

**Comment by joyeecheung** [comment]
@gibfahn Not exactly nvm (something internal) but thanks for the tips!

**Comment by gdams** [comment]
+1 I'd be interested in helping out wherever possible

**Comment by ljharb** [comment]
@gibfahn @joyeecheung I definitely mean `package.json` in the node repo, with `devDependencies`, set to `private: true`, so that only collabs use the tools and so it can't be published by mistake.

**Comment by fhinkel** [comment]
+1 on such a team

**Comment by bnb** [comment]
+1. I'd also reallllly love to see more around the Docs (I talked about Danger.systems with several people at NINA) and enabling smoother onboarding for first time contributors (again, talked with several people at NINA about this).

Such a team would also be extremely helpful as a source of truth for questions around this. I have many about our processes and implementation, but there's not really a central place to ask 😅

**Comment by Tiriel** [comment]
I'd definitely love to see such a team and be part of it if I can, as a "wannabe contributor" too impressed yet to try core. 👍

**Comment by bkeepers** [comment]
Let me know if there's anything we can do to help at GitHub.

I work on the ecosystem team at GitHub which is responsible for the API and integrations with GitHub. I also built [Probot](https://probot.github.io/) which aims to solve a lot of the automation issues for large projects.

**Comment by mhdawson** [comment]
+1 to this team.

**Comment by gr2m** [comment]
Sign me up :)

**Comment by ev1stensberg** [comment]
Super Interested in joining this! +1

**Comment by rvagg** [comment]
I'm mostly concerned about having enough people to make this work but the feedback here is really promising!

> Should it be spun out of build?

My inclination is to say that I wouldn't want this new team to be blocked by anything from Build, we don't have the smoothest operation at the moment and I would hate to see that frustrate new contributors to this effort. If it's just a matter of it having a home and somewhere to report to then that's great.

Do we have a volunteer to kick this off and make it a _thing_? Sounds like there's more than enough enthusiasm to just make it happen now.

**Comment by maclover7** [comment]
Does it make sense to create a `nodejs/automation` repo, and then people can start logging issues for things they'd like to see done / track progress of moving over some tools to the foundation?

**Comment by joyeecheung** [comment]
@maclover7 I have created https://github.com/nodejs/automation the repo :D Also created the @nodejs/automation team, I have added people who have indicated their interest to join (@maclover7 @ev1stensberg are not members of the Node.js organization so they would need to confirm the invitation). I probably miss some folks that have not explicitly said "I am interested in join" so feel free to add yourself to the team or ping me to do that :)

**Comment by Tiriel** [comment]
@joyeecheung if possible, I'd like to be part of this !

**Comment by joyeecheung** [comment]
@Tiriel Done, please check your invitaions

**Comment by al-k21** [comment]
I would like to be a part of this team.

**Comment by joyeecheung** [comment]
Now that the team and the repo has been created, I think we can close this now.
