### ISSUE TITLE
Intent to ship HTTP2 without a flag in tomorrow's 8.8.0 release

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#393]
Hey All,

We are doing a security release on the 8.x release line tomorrow that will bee bundled with a normal Semver-Minor release.

I am currently intending to ship HTTP2 without a flag based on our conversation from last week.

As the PR for the release will not be public I wanted to open this issue to give members of the TSC one more opportunity to raise concerns.

FWIW; @jasnell tested npmjs.org/http2 and it is currently broken on 8.x. This makes the majority of concerns regarding landing it a moot point imho.

**Comment by ljharb** [comment]
I'm not on the TSC, but #389 is still a concern imo - I agree that the npm http2 module being broken on 8.x obviates many concerns, but it still doesn't obviate the complexity of needing to do node version detection in modules like `resolve` to determine if something is a core module or not.

**Comment by addaleax** [comment]
@ljharb Maybe a dumb question, but doesn’t `path.isAbsolute(require.resolve(modulename))` tell you basically exactly that?

**Comment by ljharb** [comment]
@addaleax that tells the consumer of the resolved path, yes! However, it doesn't tell the *implementation of require.resolve* that, since it only has `modulename`.

**Comment by rvagg** [comment]
👍 @MylesBorins, make it so

**Comment by MylesBorins** [comment]
@ljharb fwiw I think we have general interest in the TSC to explore #389... if the concept had been pitched sooner I think it would have potentially affected the result of this particular change. At this point though I think it is too close to the release of 9.x to make any changes to the namespace, so I'd rather move forward with shipping this and iterating towards something like #389 if we can reach consensus

**Comment by ljharb** [comment]
Too close because of decision-making issues, or because of technical issues? It seems like it would be a small change.

**Comment by MylesBorins** [comment]
@ljharb too close to reach consensus before the dates that we have been advertising for months.

**Comment by MylesBorins** [comment]
shipped
