### ISSUE TITLE
Request to remove obsolete Membership team

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#397]
I would like to remove the @nodejs/membership team.

The description is "Team that handles individual membership in the foundation." But this would seem to not be the case as the membership is mostly obsolete, suggesting that the team is not really used for anything. Ex-Foundation folks are on there, and current Foundation folks are not. 

The team has no repositories.

If removing it turns out to be the wrong move, reinstating it shouldn't be hard.

For posterity, current members are:

	 voodootikigod	Chris Williams  voodootikigod
	 mikeal	Mikeal Rogers  mikeal
	 dshaw	Dan Shaw  dshaw
	 Morgul	Christopher S. Case  Morgul
	 Danese	Danese Cooper  Danese
	 guyellis	Guy Ellis  guyellis Maintainer
	 Burstaholic	Travis Odom  Burstaholic

**Comment by Trott** [comment]
Ping @nodejs/tsc

**Comment by mhdawson** [comment]
@hackygolucky can you confirm the foundation is not using it.  

Unless @hackygolucky tells us otherwise +1

**Comment by cjihrig** [comment]
+1

**Comment by ofrobots** [comment]
+1 on removing if there is no purpose.

**Comment by dshaw** [comment]
@Trott This group was created to encourage individual membership when we created the foundation. I would make sure you get feedback from @hackygolucky and @williamkapke before removing this team. 

We have a meeting tomorrow to discuss [User Feedback](https://github.com/nodejs/community-committee/issues/112) where I will make sure we discuss whether this is still useful.

**Comment by dshaw** [comment]
Note that this team was associated with https://github.com/nodejs/membership, which has now been appropriated and become https://github.com/nodejs/board.

**Comment by williamkapke** [comment]
It isn't serving a purpose currently. It's also not hard to recreate if we needed. I'm OK with removing it.

**Comment by Fishrock123** [comment]
✅  sgtm

**Comment by Trott** [comment]
Done.
