### ISSUE TITLE
Reduce semver-major requirement if there is a code

### ISSUE THREAD

**Issue by mcollina** [nodejs/TSC#401]
After 9 is out, I think we should treat error message changes as semver-minor if such errors have a code.

I _changed_ my mind since the last time this was discussed, so maybe other did as well.

cc @nodejs/tsc

**Comment by jasnell** [comment]
+:100:

**Comment by ljharb** [comment]
As long as *every* error has a code, then I’d agree - iow, I think that the precondition for being able to do this is “in precisely zero situations do I need to depend on an error message from node core”

**Comment by mhdawson** [comment]
@ljharb I don't think every error has a code yet...

**Comment by joyeecheung** [comment]
@mhdawson @ljharb From a quick search there are still 227 `env->Throw*` in src and 27 `new Error` in lib (there will be more errors than that because of functions/macros)

**Comment by joyeecheung** [comment]
@jasnell Should we make some new `env->Throw` helpers with error codes? IIRC we don't have those yet, or are you working on one? If not I can try to help.

**Comment by jasnell** [comment]
Not yet. I'm going through first and moving as many of the errors into js as possible. Let's not add any new env->Throw utilities until we're sure we absolutely need them

**Comment by jasnell** [comment]
@mcollina ... as a next step for this, perhaps an update to the documentation in the main repo would be better. This issue likely can be closed.
