### ISSUE TITLE
Request for moving automation related projects into the foundation

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/TSC#406]
Right now we have pending requests of

* [branch-diff](https://github.com/rvagg/branch-diff) (https://github.com/nodejs/admin/issues/16)
* [changelog-maker](https://github.com/rvagg/changelog-maker) (https://github.com/nodejs/admin/issues/16)
* [node-review](https://github.com/evanlucas/node-review) (https://github.com/nodejs/admin/issues/23)
* [core-validate-commit](https://github.com/evanlucas/core-validate-commit) (http://logs.libuv.org/node-dev/2017-10-31#19:14:23.762)

From the TSC readme

> The TSC is responsible for a number of projects that are not strictly required to plan, test, build, document and ship Node.js releases. Projects that are adjacent are either created from within the technical organization managed by the TSC or are adopted into that organization from outside.
> In the case of adopting existing projects, once the TSC has decided that adoption appropriate, it should seek agreement from the Node.js Foundation Board for such adoption as it impacts on the scope of technical activities of the Foundation.
> If the Node.js Foundation Board wishes to adopt an existing project, it must seek agreement from the TSC that such adoption is appropriate and that any changes to scope that it entails are acceptable.

So I think the best way to move things forward is to open an issue here. I am proposing:

1. A vote in @nodejs/tsc, make sure we agree to adopt these projects
2. Seek agreement from @nodejs/board (now quite sure how?)
3. Move these repos to the organization, @rvagg @evanlucas can directly transfer those since they are also owners of the organization.
4. Forming subteams from the @nodejs/automation team for each repo, and give the subteams write access/npm publish access.
   * The initial subteams would be the union of existing contributors of these projects, and members of the automation team.
   * People who are only one of these can ask to join the subteam, so we don't get people swamped by unnecessary messages.
4. Give the Node.js foundation npm account permission to publish the modules
5. Sort out the CONTRIBUTING.md, GOVERNANCE.md and LICENSE files (these 4 projects are all MIT) for all of them, and update package.json entries.

After the repos have been moved into the foundation, @nodejs/automation can discuss about the next steps in the automation repo.

If there are any necessary steps missing in the list, please point them out, thanks!

Refs: https://github.com/nodejs/automation/issues/1

**Comment by phillipj** [comment]
Would [semantic-release](https://github.com/semantic-release/semantic-release) be something to consider instead of individuals pushing releases?

**Comment by rvagg** [comment]
> Seek agreement from @nodejs/board (now quite sure how?)

I believe this might be a typo:

> **as** it impacts on the scope of technical activities of the Foundation.

I'm pretty certain that it should be "**if**" and I believe I authored that section too. The idea here is that the Board needs to be able to contain the scope of our technical activities so we shouldn't have free rein in expanding scope. Bringing in express is an example of scope expansion. As these tools don't impact scope they shouldn't need Board permission but we can certainly notify them. In this case I'm more than comfortable just proceeding with each of them as they all exist to serve core and I doubt there many users of them outside of core.

We recently also adopted https://github.com/nodejs/make-node-meeting and https://github.com/nodejs/node-meeting-agenda

+1 to all of these. Thanks for consolidating the requests @joyeecheung

**Comment by mhdawson** [comment]
+1

**Comment by jasnell** [comment]
We really shouldn't need a vote or board approval for these. They are simple tools used to help manage core itself. They do not expand the scope of responsibility of the TSC and I'm seeing no objections (a vote is only necessary if there are objections). Let's keep the process simple here.

**Comment by joyeecheung** [comment]
> We really shouldn't need a vote or board approval for these. They are simple tools used to help manage core itself. They do not expand the scope of responsibility of the TSC and I'm seeing no objections (a vote is only necessary if there are objections). Let's keep the process simple here.

I agree, just want to make sure I don't skip any necessary steps because those are written down in the README. Maybe we should add an exception about "projects that do not expand the scope" there?

From the +1 in this thread and previous discussions, I think it's safe to just skip to step 3 and to ask @rvagg and @evanlucas to transfer the projects now. After that we can move the discussion to the automation repo.

**Comment by mhdawson** [comment]
@joyeecheung agreed, we need to at least have an issue (like this one) to give people a chance to object or suggest we do need board approval.

We might give people a bit more time (issue looks like it has only been open for 5 hours), but other than that if there are no objects after (say 48 hours) then I think we should be ok to move forward on this one.  I'd just suggest you ask Myles to give the board a heads up, but its not something we need to block on.

**Comment by cjihrig** [comment]
SGTM

**Comment by evanlucas** [comment]
https://github.com/nodejs/core-validate-commit and https://github.com/nodejs/node-review are now a thing. I haven't given ownership to any teams at this point because I wasn't sure how we wanted to do that. Who should I give publish access to on npm?

**Comment by MylesBorins** [comment]
Great work y'all, very happy to see this happening

In agreement that this doesn't need any major approval aside from the
maintainers of original modules

**Comment by mhdawson** [comment]
In addition to people who will do update you should also add the 'nodejs-foundation' user which we have in place for backup.

**Comment by rvagg** [comment]
https://github.com/nodejs/branch-diff
https://github.com/nodejs/changelog-maker

https://github.com/rvagg/commit-stream is integral to both of these and I'm going to move that one too assuming it's part of the same bundle, unless there objections (I'll wait a bit for objections)

**Comment by rvagg** [comment]
added @nodejs/automation and @nodejs/release to both of those repos btw

**Comment by joyeecheung** [comment]
Now that these project have been moved, I think we can close this now.
