### ISSUE TITLE
Volunteers to run TSC meeting Nov 8 and 15

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#409]
I'm going to be at NodeConfEU on the 8th and on holiday on the 15th.

Any volunteers to chair the meeting one or both or those dates ?

@nodejs/tsc

**Comment by Fishrock123** [comment]
I could chair the meetings if someone can create the issues / documents

(I could never get rod's issue tool thing to work properly..)

**Comment by joshgav** [comment]
@Fishrock123 I'll help with issues and docs if you run the stream and keep the meeting on track.

Glad neither of these is the early time :)

**Comment by mhdawson** [comment]
I can create the issue on Saturday for the first meeting if that helps, for the second I won't have access to the machine were my automation is.

@Fishrock123 thanks for volunteering to chair.

**Comment by Trott** [comment]
> I can create the issue on Saturday for the first meeting 

It looks like maybe this hasn't happened yet? (Perhaps because no one said "Yes, please do!")

We should see if a bot can open these for us.

**Comment by mhdawson** [comment]
I missed creating it before I left.  I just tried remoting into my home network but I can't get in right now for some reason. I'll try again later but if its not up by tomorrow then you'll probably have to create manually.

As for the bot/automation, that is what I'm working towards.  I have the scripts to do the generation automatically now creating the issues and github docs, but want to test it out a few more times before I set it up as a cron job as a first step.  At that point if the automation team can set up a bot to do it at a scheduled time that would be great.

**Comment by mhdawson** [comment]
Sorry looks like my vpn is down for some reason and I'm not going to be able to get in so you'll have to create the issue manually like we've being doing up until a week or two ago.  @Trott I'm hoping you are still setup to do that.

**Comment by mhdawson** [comment]
These are the issues currently tagged for the agenda:

### nodejs/node

* Support both OpenSSL 1.1.0 and 1.0.2 [#16130](https://github.com/nodejs/node/pull/16130)
* stream: move prefixed files into internal/streams. [#11957](https://github.com/nodejs/node/pull/11957)

### nodejs/TSC

* doc: initial version of strategic initiatives [#399](https://github.com/nodejs/TSC/pull/399)
* Proposal to form a Governance Working Group [#383](https://github.com/nodejs/TSC/issues/383)

### nodejs/admin

* meta: fix case of extensions on internal docs and move CoC to admin repo [#25](https://github.com/nodejs/admin/pull/25)

**Comment by Trott** [comment]
I've reassembled my old setup for the CTC meetings and will have an issue opened for the meeting shortly.

**Comment by Trott** [comment]
There are currently [13 (!!!) issues labeled `tsc-review`](https://github.com/search?utf8=%E2%9C%93&q=label%3Atsc-review+org%3Anodejs+is%3Aopen&type=Issues).

**Comment by MylesBorins** [comment]
Closing as it seems we have volunteers set up to do this
