### ISSUE TITLE
Transfer 'lts' npm module to the foundation

### ISSUE THREAD

**Issue by gibfahn** [nodejs/TSC#410]
NPM: https://www.npmjs.com/package/lts
Github: https://github.com/continuationlabs/lts
Owner: @cjihrig 
Use: Generating the [Release schedule image](https://github.com/nodejs/Release#release-schedule)

Proposal that we add this module to the foundation (and that it ends up in the automation monorepo, see https://github.com/nodejs/automation/pull/13#discussion_r148781325)

@cjihrig said he'd be happy for it to be transferred in https://github.com/nodejs/Release/issues/275#issuecomment-341251613

**Comment by cjihrig** [comment]
Yep, I'm happy to transfer it. What exactly needs to be done?

**Comment by gibfahn** [comment]
>Yep, I'm happy to transfer it. What exactly needs to be done?

I think it just needs the TSC to agree it's okay.

After that I guess adding other publishers to the module at some point, but that's still being worked out by nodejs/automation.

**Comment by mcollina** [comment]
LGTM

**Comment by joyeecheung** [comment]
LGTM

**Comment by joyeecheung** [comment]
> Yep, I'm happy to transfer it. What exactly needs to be done?

After we reach the consensus you can just transfer it into the Node.js organization and add [nodejs-foundation](https://www.npmjs.com/~nodejs-foundation) to the npm package collaborators. We can discuss the rest in the automation repo. (would want to make a uniformed CONTRIBUTING.md for all automation projects later, and there are more stuff to come).

**Comment by MylesBorins** [comment]
Lgtm

**Comment by jasnell** [comment]
SGTM

**Comment by mhdawson** [comment]
LGTM

**Comment by MylesBorins** [comment]
What are the next steps here?

**Comment by DiegoRBaquero** [comment]
@cjihrig Must transfer repository to nodejs org in github and transfer npm ownership of the module.

**Comment by cjihrig** [comment]
I've added the nodejs-foundation user as an owner on the npm module. The repo now lives at https://github.com/nodejs/lts, and the automation team has access. I'll leave it up to them what happens next.
