### ISSUE TITLE
Request moving node-core-utils into the foundation

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/TSC#412]
Fixes: https://github.com/joyeecheung/node-core-utils/issues/59

We think it's about time to move it into the foundation, under the management of [the automation team](https://github.com/nodejs/automation), so here is the request. Please approve or discuss in this thread.

* [Github Page](https://github.com/joyeecheung/node-core-utils)
* [NPM Page](https://www.npmjs.com/package/node-core-utils)

**Comment by mcollina** [comment]
SGTM

**Comment by mcollina** [comment]
Can you update the COLLABORATOR_GUIDE as well to use this new tool as well?

**Comment by targos** [comment]
SGTM. Thanks for all the work!

**Comment by addaleax** [comment]
+1!

**Comment by cjihrig** [comment]
SGTM

**Comment by mhdawson** [comment]
LGTM

**Comment by joyeecheung** [comment]
Given the LGTMs I think it's time to move it. [Github Page](https://github.com/nodejs/node-core-utils) [NPM page](https://www.npmjs.com/package/node-core-utils)
