### ISSUE TITLE
Archive the node-v0.x-archive repo?

### ISSUE THREAD

**Issue by cjihrig** [nodejs/TSC#414]
This is now supported in GitHub. Maybe we should do it.

**Comment by addaleax** [comment]
Yup. Maybe somebody just bring it up at the TSC meeting & ask for objections? I can’t see a reason why there would be any.

**Comment by Trott** [comment]
Might want to close all the issues and pull requests for. And update the README to remove stuff about "new issues and pull requests" since people won't be able to open those etc. Link to pre-convergence repo is obsolete now too.

**Comment by Trott** [comment]
Never mind. The link is not obsolete. Yeah, we should archive. We can always unarchive if it turns out to be a mistake. Definitely let's bring it up at the TSC meeting in 45 minutes as @addaleax suggests.

**Comment by targos** [comment]
+1

**Comment by mcollina** [comment]
+1 to archiving

**Comment by MylesBorins** [comment]
+1

can we archive CTC too

**Comment by evanlucas** [comment]
+1 to archiving

**Comment by Trott** [comment]
@MylesBorins Issue for archiving other repos (like inclusivity) is #415. :tada:

**Comment by ofrobots** [comment]
For posterity, here's the info on archiving (hot off the press): https://github.com/blog/2460-archiving-repositories

**Comment by ChALkeR** [comment]
+1 to archiving this and all other repos which is logically «archived»

**Comment by mhdawson** [comment]
+1

**Comment by Fishrock123** [comment]
+1 on archiving all of our our practically-already-frozen repos (not the language group ones though)

**Comment by Fishrock123** [comment]
We should add commits to the readmes before we archive though.

**Comment by targos** [comment]
node-v0.x-archive already has a special readme. I went ahead and archived it: https://github.com/nodejs/node-v0.x-archive

**Comment by gibfahn** [comment]
As I mentioned in https://github.com/nodejs/node/issues/13768#issuecomment-342989612, archiving the repo without closing the issues and PRs leaves them open forever, which is a bit odd.

If someone works out how to mass close issues, then we should unarchive, close everything, and rearchive.

**Comment by targos** [comment]
The repository is still watched by a lot of people and closing everything would generate more than 1 million notifications. Do we really need to do that?
