### ISSUE TITLE
archive repositories for realz

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#415]
GitHub now offers the ability to "archive" a repository to make it read-only.

https://github.com/blog/2460-archiving-repositories

Perhaps we want to do that for the node-v0.x-archive repo, the inclusivity repo, and maybe a few others. (Probably will want to close all open PRs and issues first, and update the README file explaining what happened and where people should go now.)

**Comment by Trott** [comment]
Update: @cjihrig opened #414 to archive node-v0.x-archive. Cool. This should probably stay open so gather other repos that might be archived. (Or close this and move it to that issue. Whatevs. I would prefer a "node-v0.x-archive" issue separate from a "everything else" archive, but I'm not going to spend any time advocating for it beyond this paragraph. Kthxbai.)

**Comment by Trott** [comment]
Starting to think closing issues and PRs is not necessary. Updating README is, though. I'll do that now. (It should be updated whether we archive or not.)

**Comment by Trott** [comment]
Never mind. The link is not obsolete. Yeah, we should archive. We can always unarchive if it turns out to be a mistake. Definitely let's bring it up at the TSC meeting in 45 minutes.

**Comment by mhdawson** [comment]
+1

**Comment by ChALkeR** [comment]
+1 to archiving all repos which is logically «archived» and not active

**Comment by Trott** [comment]
I archived CTC.

I closed all issues in Inclusivity, updated the README, and archived it too.
