### ISSUE TITLE
Node.js Foundation Technical Steering Committee (TSC) Meeting 2017-11-15

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#418]
@mhdawson is on vacation, and @Fishrock123 is running the meeting. I don't think anyone opened an issue for the meeting itself, so here y'all go...

## Time

**UTC Wed 15-Nov-2017 22:00 (10:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 15-Nov-2017 14:00 (02:00 PM) |
| US / Mountain | Wed 15-Nov-2017 15:00 (03:00 PM) |
| US / Central  | Wed 15-Nov-2017 16:00 (04:00 PM) |
| US / Eastern  | Wed 15-Nov-2017 17:00 (05:00 PM) |
| Amsterdam     | Wed 15-Nov-2017 23:00 (11:00 PM) |
| Moscow        | Thu 16-Nov-2017 01:00 (01:00 AM) |
| Chennai       | Thu 16-Nov-2017 03:30 (03:30 AM) |
| Hangzhou      | Thu 16-Nov-2017 06:00 (06:00 AM) |
| Tokyo         | Thu 16-Nov-2017 07:00 (07:00 AM) |
| Sydney        | Thu 16-Nov-2017 09:00 (09:00 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Technical%20Steering%20Committee%20(TSC)+Meeting+2017-11-15&iso=20171115T22
* or http://www.wolframalpha.com/input/?i=10pm+UTC%2C+Nov+15%2C+2017+in+local+time

## Links

* **Minutes Google Doc**: <https://docs.google.com/document/d/1ltTwM-z-BqrUGGdQYmFqrQ8OaaZ4ulI-qFqYYd0wNCk>
* _Previous Minutes Google Doc: <>_

### nodejs/node

* Enable explicit `.m.js` intent for ESM [#16170](https://github.com/nodejs/node/pull/16170)

### nodejs/TSC

* doc: initial version of strategic initiatives [#399](https://github.com/nodejs/TSC/pull/399)
* Proposal to form a Governance Working Group [#383](https://github.com/nodejs/TSC/issues/383)

### nodejs/admin

* meta: fix case of extensions on internal docs and move CoC to admin repo [#25](https://github.com/nodejs/admin/pull/25)

## Invited

* Anna Henningsen @addaleax
* Сковорода Никита Андреевич @ChALkeR
* Colin Ihrig @cjihrig
* Evan Lucas @evanlucas
* Franziska Hinkelmann @fhinkel
* Jeremiah Senkpiel @Fishrock123
* Fedor Indutny @indutny
* James M Snell @jasnell
* Josh Gavant @joshgav
* Joyee Cheung @joyeecheung
* Matteo Collina @mcollina
* Michael Dawson @mhdawson
* Brian White @mscdex
* Myles Borins @MylesBorins
* Ali Ijaz Sheikh @ofrobots
* Rod Vagg @rvagg
* Michaël Zasso @targos
* Sakthipriyan Vairamani @thefourtheye
* Trevor Norris @trevnorris
* Rich Trott @Trott

## Notes

The agenda comes from issues labelled with `tsc-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

Uberconference; participants should have the link & numbers, contact me if you don't.

## Public participation

We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at **https://www.youtube.com/c/nodejs+foundation/live** when we turn it on. There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and it should show up.

Many of us will be on IRC in #node-dev on Freenode if you'd like to interact, we have a Q/A session scheduled at the end of the meeting if you'd like us to discuss anything in particular. @nodejs/collaborators in particular if there's anything you need from the TSC that's not worth putting on as a separate agenda item, this is a good place for it.

**Comment by MylesBorins** [comment]
Can we please add https://github.com/nodejs/TSC/issues/371 to the agenda

Specifically we need to discuss the IANA/IESG asking us to change from vendor to standards track for any registration. This has resulted in a request to specify / verify a Standards Organization to use as a contact.

Brad was curious if we want to move the contact to the foundation instead of the TSC

**Comment by fhinkel** [comment]
@dshaw Are you joining us for this? Asking because https://github.com/nodejs/TSC/issues/383 is on the agenda.

**Comment by MylesBorins** [comment]
we should again drop #383 from agenda, as the meeting hasn't happened

That being said we should pick a date, I'm about to head to asia for two weeks, and sounds like matteo is out for a bit as well. We may need to make a new collection of dates

@jasnell I'm more than happy to pick this up if you don't have time

**Comment by evanlucas** [comment]
I may be a few minutes behind depending on traffic

**Comment by jasnell** [comment]
@MylesBorins ... be me guest on picking that up. My available time over the next couple of weeks has all but evaporated.

**Comment by Fishrock123** [comment]
Also discussing https://github.com/nodejs/TSC/issues/371

**Comment by dshaw** [comment]
@fhinkel Waiting for the green light to engage in whatever forum the TSC chooses. Thanks for the callout.

**Comment by Fishrock123** [comment]
Decent viewers, max 13:

![node_livestream_viewers-2017-11-15](https://user-images.githubusercontent.com/1093990/32864975-0a352130-ca16-11e7-870b-f019a5d2b1e5.png)

**Comment by Trott** [comment]
Minutes in https://github.com/nodejs/TSC/pull/420.
