### ISSUE TITLE
TSC Nomination: Daniel Bevenius

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#419]
It's my pleasure to nominate Daniel Bevenius (@danbev) to the Technical Steering Committee (TSC).

@danbev's first contribution was June 2016 and he became a Collaborator in August 2016. @danbev has offered a consistently clear, calm, and respectful communication style in his participation in the project.  @danbev is an employee of Red Hat, which fills a need for CentOS/RHEL and yum/rpm representation on the TSC. @danbev also rounds out our C++ and crypto expertise a bit.

* Issues and pull requests: https://github.com/nodejs/node/search?q=author%3Adanbev&type=Issues&utf8=%E2%9C%93

* Commits: https://github.com/nodejs/node/search?q=author%3Adanbev&type=Commits&utf8=%E2%9C%93  (Most of Dan's commits are in src, test, and build, but he gets into doc, deps, tools, etc. too.)

* Comments: https://github.com/nodejs/node/search?utf8=%E2%9C%93&q=commenter%3Adanbev&type=Issues

It's a crude metric, of course, but not entirely useless: @danbev is the most prolific non-TSC contributor (and 4th overall if you include TSC members) to Node.js at this time in terms of commits with 102 in the last six months and 163 in the last year.

**Comment by cjihrig** [comment]
+1

**Comment by targos** [comment]
+1

**Comment by jmernin** [comment]
+1

**Comment by lance** [comment]
+1.73591

**Comment by mhdawson** [comment]
+1

**Comment by MylesBorins** [comment]
+1

**Comment by fhinkel** [comment]
+1

**Comment by matzew** [comment]
+1

**Comment by evanlucas** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by Fishrock123** [comment]
+1

**Comment by mcollina** [comment]
+1

**Comment by trevnorris** [comment]
+1

**Comment by ChALkeR** [comment]
+1

**Comment by Trott** [comment]
Between votes here and in email, this passes with no opposition. Congratulations and welcome, @danbev!

**Comment by danbev** [comment]
I'm really excited about joining and looking forward to working with all of you. Thanks everyone!

**Comment by Trott** [comment]
PRs opened to add him to the TSC list in the main README and add him to the mailing list. Also added him to the TSC GitHub team.
