### ISSUE TITLE
Strategic Initiatives - Tracking Issue

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#423]
Tracking issue tagged with tsc-agenda so that we have entry to review status of the initiatives in the weekly TSC call.

https://github.com/nodejs/TSC/blob/master/Strategic-Initiatives.md

**Comment by Trott** [comment]
Should we consider paring down strategic initiatives that aren't really strategic? Collab onboarding is important, but I'm not sure it's strategic. I don't mind giving a weekly quick update on who was onboarded during the announcements section of the TSC meeting, but I wonder if we lose signal on truly strategic things by including everything here.

**Comment by MylesBorins** [comment]
+1 on pairing down. This was one of my original critiques

**Comment by mhdawson** [comment]
@Trott I'd agree that if the collab onboarding is going to be an update about who was onboarded as opposed to a specific effort to improve onboarding (as an example) we can remove it.

**Comment by mhdawson** [comment]
@Trott should I open a PR to remove collab onboarding  and Moderation ?

**Comment by Trott** [comment]
@mhdawson Moderation can probably stay until the team is fully spun up. We need to figure out how to give that team the necessary privileges across the various repositories. Onboarding of collaborators can definitely be removed, in my opinion. I'll open a pull request.

**Comment by Trott** [comment]
This isn't really a tracking issue. This is a permanently-opened issue to keep this in the agenda. Can we simply update the template for the meeting to include strategic initiative updates as a thing we always do (just like Announcements, Q&A, Upcoming Meetings, etc.)? Then we can close this issue.

**Comment by mhdawson** [comment]
Its more complicated than that since there is only a template for for the minutes, not for the issue.  Its on the todo list to add a template for the issue as well but its not there right now.    

If we change the underlying module used to generate the issue, then we'll get it for other meetings which we don't want, so we should wait until there is a template to generate the issue.

**Comment by Trott** [comment]
> If we change the underlying module used to generate the issue, then we'll get it for other meetings 

Isn't the underlying module `make-node-meeting`? If so, then you can edit `examples/tsc.sh` and/or `$HOME/.make-node-meeting/tsc.sh` and it will only affect the TSC meeting.
