### ISSUE TITLE
Proposal for making two-factor authentication optional 

### ISSUE THREAD

**Issue by mlosh** [nodejs/TSC#436]
Howdy, 

@Trott  posted in Website WG that all the members should have two-factor auth enabled, and that soon enough they'd be removed. 

Personally, I don't agree with this TSC decision, and I propose that it should be optional. Two-auth, as it is now, is difficult to be added, I requested a code to my device yesterday at 11pm, received it today at 7pm. Also when using CLI, members would need to use SSH and GPG keys, which may be difficult for new comers. About security, sure, it improves security, but I think a strong password is enough (try me if you think the opposite :)), and even on rare occasion, if something like that happens, It wouldn't be hard restore data.  I agree that administration should be obligated to set up two-factor authentication. Maybe in the future, when Github improves their auth system, this could be implemented, but right now I think it's too early for that.

**Comment by MylesBorins** [comment]
@mlosh why would people need a gpg key to use two factor?

There was discussion around getting collaborators Yubikeys to help with this

**Comment by ljharb** [comment]
2-factor auth doesn't apply to using SSH keys to access github.

**Comment by fhinkel** [comment]
Sorry that the first login was such a hassle with 2FA. 

Usually, you need the extra authentication only when you log on from an unknown device, not every time. You can use the [recovery codes](https://help.github.com/articles/downloading-your-two-factor-authentication-recovery-codes/) for future logins from new devices. Would that be an OK workflow for you?

**Comment by mhdawson** [comment]
For command line access you can create a personal access token

https://github.com/settings/tokens

It ends up being like a very long/hard to remember password, but otherwise the workflow is the same when using the git command line client

**Comment by MylesBorins** [comment]
If you are on OSX you can use this line to store the login credentials 

https://github.com/MylesBorins/dot-files/blob/master/.gitconfig#L31

Also if you use ssh there is no need to auth.

**Comment by mlosh** [comment]
Alright, as I am the only one who has problem with this, I'll close this issue

**Comment by fhinkel** [comment]
@mlosh I'm sure you're not the only one. Were you able to log on with 2FA enabled?

**Comment by mlosh** [comment]
I can't even set it up, as I said, I tried mobile verification, requested code and it came like after 12h

**Comment by MylesBorins** [comment]
Let me know if you want to pair on this. It seems like there might be a
better way to set this up and if we find the places you are having issues
we can document it to help others later

**Comment by joyeecheung** [comment]
> I can't even set it up, as I said, I tried mobile verification, requested code and it came like after 12h

@mlosh Are you using SMS messages to authenticate? You can try [using a TOTP app](https://help.github.com/articles/configuring-two-factor-authentication-via-a-totp-mobile-app/) instead. Github can't even send messages to me so I use the Google Authenticator to set up the 2FA.
