### ISSUE TITLE
Updating CTC references

### ISSUE THREAD

**Issue by maclover7** [nodejs/TSC#438]
A bunch of [Dependent projects](https://github.com/nodejs/TSC#dependent-projects) [Adjacent projects](https://github.com/nodejs/TSC#adjacent-projects) in the readme repeat the phrase "administration delegated to the Core Technical Committee". Since the CTC has been merged back into the TSC, what should this be updated to? Maybe just "managed by TSC" or something to that effect?

**Comment by mhdawson** [comment]
I would just replace "Core Technical Committee" with "Technical Steering Committee"

**Comment by Trott** [comment]
> I would just replace "Core Technical Committee" with "Technical Steering Committee"

Then the text would be "administration delegated to the Technical Steering Committee" which is kinda confusing because it says the TSC delegated to itself.

I propose removing the text entirely, along with text delegating other things to defunct groups. See https://github.com/nodejs/TSC/pull/439

**Comment by jasnell** [comment]
Is there a next step here or can this be closed?

**Comment by Trott** [comment]
Seems closable now that #439 landed.
