### ISSUE TITLE
Mentorship initiative ramping up.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#443]
FYI to make sure on radar for TSC.  

Progress on write has been made. See https://github.com/Bamieh/node-ment and was reviewed in last Community committee.

Issue will be opened in admin repo to move it over to Node.js foundation.

**Comment by rvagg** [comment]
fwiw this is a whole lot of awesome, thanks for putting in a heap of work into this @Bamieh!

**Comment by Bamieh** [comment]
thanks @rvagg 🎉

**Comment by jasnell** [comment]
Yes, quite happy to see this evolving. Should have some detailed feedback after the holiday.

**Comment by jasnell** [comment]
The repo has been moved to the nodejs github org. I believe we can close this now.
