### ISSUE TITLE
Proposal to delete https://github.com/nodejs/node/wiki/Node-Hosting 

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#448]
I think https://github.com/nodejs/node/wiki/Node-Hosting should be removed. It's absurdly outdated, will never be up-to-date, is content that is likely to have biases, and is more appropriate for other venues. Any objections?

@nodejs/tsc @nodejs/community-committee

**Comment by ryanmurakami** [comment]
I agree. I can see value in that type of information, but not in the Node.js wiki. Seems more fitting to live in an awesome list.

**Comment by bnb** [comment]
No objection as a part of the Moderation Team and the Community Committee. This topic may be a good subject for a post on the Node.js Collection, though, in addition to an awesome list as @ryanmurakami suggested 👍

Happy to review/edit a submission to the Node.js Collection if someone wants to take on that initiative (at present or in the future - standing offer).
