### ISSUE TITLE
Proposed New TSC Schedule (Take 2)

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#449]
Based on current data in the availability spreadsheet (up to and including Jeremiah's changes that were made about 9 hours ago), the proposal (based on the whole fairness algorithm thing that I'll be PR'ing into this repo soon) is:

Keep the schedule as it now stands with the exception of moving the 17:00 UTC meeting to 20:00 UTC.

This was discussed at today's TSC meeting. There were 11 TSC attendees. We had 8 votes in favor and 3 abstentions. That's not quite enough in-favor votes to pass it, but it's close.

At this time of year, 17:00 UTC looks like this:

| Location      | Time             |
|---------------|-----------------------|
| US / Pacific  |09:00 AM |
| US / Mountain | 10:00 AM |
| US / Central  | 11:00 AM |
| US / Eastern  | noon |
| London        | 5:00 PM |
| Amsterdam     | 6:00 PM |
| Moscow        | 8:00 PM |
| Chennai       | 10:30 PM |
| Hangzhou      |1:00 AM |
| Sydney        | 4:00 AM |

The proposal here is to change it to 20:00 UTC, which would be this:

| Location      | Time             |
|---------------|-----------------------|
| US / Pacific  |noon |
| US / Mountain | 1:00 PM |
| US / Central  | 2:00 PM |
| US / Eastern  | 3:00 PM |
| London        | 8:00 PM |
| Amsterdam     | 9:00 PM |
| Moscow        | 11:00 PM |
| Chennai       | 1:30 AM |
| Hangzhou      | 4:00 AM |
| Sydney        | 7:00 AM |

**Comment by Trott** [comment]
| Vote | Who | 
|---|---|
| Yes&nbsp;(8) | @ChALkeR @fhinkel @Fishrock123 @MylesBorins @ofrobots @targos @trevnorris @Trott |
| No&nbsp;(0) | | 
| Abstain&nbsp;(3) | @cjihrig @mcollina @thefourtheye  |
| Not Yet Voted (10) | @addaleax @danbev @evanlucas @indutny @jasnell @joshgav @joyeecheung @mhdawson @mscdex @rvagg |

**Comment by Trott** [comment]
(Technically, this doesn't need a vote, just consensus, so even if no one says anything at all, this can land after a reasonable amount of time. Still, it would be nice to have an iron-clad case, so please vote. :-D )

**Comment by Trott** [comment]
(I guess I'll also say that the vote isn't for "Oh, yes, this time works for me, sounds great", but rather "Yes, I understand that this makes things more fair, so it has my vote.")

**Comment by jasnell** [comment]
No objections to this new schedule

**Comment by MylesBorins** [comment]
I would personally like to see confirmation from individuals that the 12:00
utc meeting is meant to serve that it is indeed the best time

Either way no blocking this from moving forward

**Comment by danbev** [comment]
No objections from me

**Comment by fhinkel** [comment]
I realized that lots of our meetings go for 90 minutes (including the initial 10 minutes waiting), but the spreadsheet has 1-hour slots. Did everybody consider their availability of the next hour when filling out the form? I updated my times accordingly. Also, there's one person who sleeps 1 hour per day, is that correct? 😎 

I want to second what Myles said: We have low turnout at the 12 utc (1 pm Berlin, 4 am San Francisco, 7 am NYC) meeting. That's why we wanted to update the sheet in the first place. Now we're changing a different meeting. That seems off. Though that 12 utc meeting is the most convenient for me personally, it's not all that useful if we don't reach quorum. 

I guess the question is, do we want to keep the 12 utc, it's very convenient - for a small group. Would it make sense to move it back 1 or 2 hours, so it's more reasonable for the US folks to join it or does that exclude too many people who can only make it at 12 utc? 

Does anybody else have an option on that 12 utc meeting?

**Comment by mcollina** [comment]
I did some reasoning on my rough 6 months of membership. At that midday meeting I was sparingly able to join, even if it should have been my core timezone. My _preferred_ time slots for TSC meetings is at 17:00 and 18:00 UTC. I updated my availability another time (sorry @Trott).

**Comment by Trott** [comment]
> I updated my availability another time (sorry @Trott).

And...we're back to the three time slots we currently have. :-D 

Unless things change, I'll withdraw the proposal, but I do have some more things to say in another comment...

**Comment by Trott** [comment]
@fhinkel Right now, there's a provision in the code that it won't pick any times unless more than half the TSC has rated that time 2 or higher. This is designed to omit truly terrible times. (This is because a "fair" schedule could be three time slots where no one can attend at all. Fair! But also useless.) If we think 12:00 UTC isn't working out, people updating the spreadsheet is one possibility (and I never want to discourage that!). But we could also think about modifying that threshold to either move it to more than 50% or move the minimum score higher than 2. Small changes here can eliminate a large percentage of meeting times, so caution is warranted, but it's an option.

Some more information:
 
* Last time, there were 6 people, which is definitely light attendance. (We had 11 at the 17:00 meeting yesterday.) But that may have been a bit unusual.
* The previous 3 meetings at that time, we had 9 attendees. 9 is not great, but it is definitely workable.

If we're routinely getting 9 people, and we'd ideally like to at least have a quorum (currently 11 people), two things to consider:

* Maybe increase the "must be more than half people rating the time slot 2 or above) above to "must be at least half + 1".  With the current data, that will eliminate the 12:00 time. (Times proposed would be 13:00 15:00 22:00.) That will likely have the side effect of introducing more stability in the time choice algorithm because fewer options means fewer variations. It has the downside of making it harder on people who are in time zones that no one else is in, but this is all about striking that balance in the first place.
* The *other* thing to do, though, is to advocate more strongly for people who don't attend meetings and don't otherwise participate in TSC activities (like votes) to temporarily or permanently move themselves to Emeritus. There is one member who has missed 13 consecutive meetings, didn't vote in the most recent nodejs/node issue that TSC had a vote on, and currently has a "5" and a "4" for two of our three meeting slots in the spreadsheet. I'll contact them privately, but for everyone else.... (putting the next sentence in its own comment because it's kind of targeted at people who would only skim anyway)...

**Comment by Trott** [comment]
@nodejs/tsc Periodic reminder: If you've been relatively inactive on the TSC, please consider voluntarily moving yourself to Emeritus temporarily or permanently. Thanks!

**Comment by fhinkel** [comment]
@Trott thanks so much for trying to improve the schedule ❤️  I have absolutely no idea how to improve the criteria 🤷‍♀️

**Comment by Trott** [comment]
I'm going to close this (again) and make the criteria a bit more stringent as described above. Hopefully our various proposals won't be so wildly divergent or sensitive to small changes in the data.

Thanks for all your patience, everyone.
