### ISSUE TITLE
Foundation Hiring: Education Community Manager

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#46]
The Node.js Foundation is looking to hire an Education Community Manager. If you are interested in the position please email mikeal.rogers@linuxfoundation.org with your resume ASAP :)

The role is a contract position.

### Education Manager Hiring Doc
* Requirements
  * Available for part time contract employment (1099)
  * Familiarity with existing Node.js education communities.

### Responsibilities
 * Subject matter expert on Node.js development with familiarity w/ existing Node.js education.
  * Is the point of contact for the Node.js Foundation's e-learning, training and certification teams.
   * This means approving Marketing materials regarding our education efforts.
   * This means be a point of contact for questions and signoff for Public Relations related to education.
   * This means being present at certain events as the foundation’s education representative.
 * Collecting and exposing community resources.
 * Participates in the NodeSchool community.
 * Participates in the Documentation WGs.
 * Coordinating with for-profit Node.js education providers.
 * Leading a University Committee.

This issue is an announcement only and is now locked. If you have questions or want to apply please email mikeal.rogers@linuxfoundation.org

**Comment by chrisdickinson** [comment]
Should I point the Docs WG at this issue (or wait to do so?)

**Comment by mikeal** [comment]
@chrisdickinson sure :)

**Comment by williamkapke** [comment]
@mikeal I think I head this position was filled? Close this issue?

**Comment by jasnell** [comment]
Yep. Closing!
