### ISSUE TITLE
Nominating @gibfahn to the TSC

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#466]
@nodejs/tsc ... I would like to nominate @gibfahn to the TSC. Gibson has been doing amazing work in the build group, with CITGM, and more recently helping with LTS releases.

Following the normal procedure, the first step would be to invite @gibfahn as an observer in the regular TSC calls.

**Comment by targos** [comment]
+1

**Comment by jasnell** [comment]
+1

**Comment by cjihrig** [comment]
+1

**Comment by fhinkel** [comment]
+1

**Comment by danbev** [comment]
+1

**Comment by mcollina** [comment]
+1

**Comment by evanlucas** [comment]
+1

**Comment by addaleax** [comment]
+1

**Comment by Trott** [comment]
+1

**Comment by ofrobots** [comment]
+1

**Comment by Fishrock123** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by ChALkeR** [comment]
+1

**Comment by Trott** [comment]
@gibfahn As you attend TSC meetings as an observer, feel free to speak. Part of the point is to get folks on the TSC familiar with how you communicate in meetings. Don't say stuff just for the sake of saying stuff, of course. But if you have something to add or a question to ask, do it!  :-D

**Comment by gibfahn** [comment]
>As you attend TSC meetings as an observer, feel free to speak.

Oh, I assumed _observer_ was in contrast to _participant_, and thus implied not talking. So what is the aim of being an observer? Is it a trial period? Does it just mean you don't vote on things?

I also notice people seem to use the chat a fair amount, especially for asides when other people are talking. Seems like a good way to stop it devolving into the usual "start talking at the same time as someone, both stop and say you go first, then both start talking again" pattern.

**Comment by jasnell** [comment]
Generally observer means actively participate in everything except voting on the rare occasions we actually need to vote on things.

**Comment by TimothyGu** [comment]
Now that @gibfahn is officially a member, I think this could be closed.
