### ISSUE TITLE
Make team for Electron

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#467]
Hey All,

With our recent cleanup of members not in other teams it appears we have removed some members of the electron core team. I was thinking it might make sense to make a new team specifically for electron

Thoughts?

**Comment by ChALkeR** [comment]
What purpose would it serve, and what do those people think about that? (Perhaps mentioning them here would help).

**Comment by mhdawson** [comment]
I think we might name the team 'embedders' so that we can include any product/project that embeds Node.js.  I see that as a growing use case a tea might be a good way to have a communications channel.  An email alias might work just as well unless we want them to have access that only comes with being part of the org.

**Comment by mhdawson** [comment]
Thinking about it more being able to to an @ is easier than sending an separate email so maybe and email alias is not a good alternative.

**Comment by groundwater** [comment]
It would be great to have folks working on upgrading node in electron on a team here. This would also ensure folks were already added to the org if folks ever need to discuss things in a private repo. Org invite mails are notorious for getting lost, and having folks complete it beforehand would be useful.

👍 on being able to @-mention folks who want to subscribe to things going on in the node side, it's a convenient _/cc_ mechanism without needing to know the electron org team structure.

**Comment by rogerwang** [comment]
> I think we might name the team 'embedders' so that we can include any product/project that embeds Node.js.

I second this. NW.js is a large downstream project of Node.js.

**Comment by ChALkeR** [comment]
:+1:  for an «embedders» team, even just making it easy to @-mention them as a group looks like good reason to have it.

**Comment by mhdawson** [comment]
Marking as cc-review and tsc-review as an FYI as it would be adding a 'new' group to the org and additional people with access to the moderation repo.

**Comment by Trott** [comment]
> Marking as cc-review and tsc-review as an FYI as it would be adding a 'new' group to the org and additional people with access to the moderation repo.

This could be considered a team of external collaborators that are not under the `members` umbrella group and do not get access to the moderation repo. Not advocating either way. Just saying that it's an option. We don't have to grant *everybody* access to the moderation repo if that's not the right thing to do.

**Comment by cjihrig** [comment]
+1 to a team of external collaborators without moderation repo access. I prefer embedders over electron.

**Comment by mhdawson** [comment]
@Trott good point.  I agree +1 to what @cjihrig said.

**Comment by jasnell** [comment]
The discussion here appears to have stalled out. Is there reason to keep this open?

**Comment by mhdawson** [comment]
There is another issue where this is actively being discussed and my next step is to open a PR.  Once I have time to do that I'll link the 2 together and close this one.

**Comment by mhdawson** [comment]
This is the other issue: https://github.com/nodejs/admin/issues/59

**Comment by mhdawson** [comment]
PR to add new team https://github.com/nodejs/node/pull/19098

**Comment by mhdawson** [comment]
New team created under https://github.com/nodejs/admin/issues/59

@groundwater who all should be added? I've already sent you an invite.

**Comment by mhdawson** [comment]
@Trott I did not make this team a child of members, based on the earlier discussion in the issue.

**Comment by Trott** [comment]
> @Trott I did not make this team a child of members, based on the earlier discussion in the issue.

@mhdawson Sounds good to me.

**Comment by groundwater** [comment]
@mhdawson thanks, I've been re-added and accepted

Please add my team: @zcbenz @ckerr @zeke @codebytere @vanessayuenn @jkleinsc

Some non-GitHub Electron core committers include: @alexeykuzmin @MarshallOfSound @deepak1556 @nitsakh @felixrieseberg

**Comment by fhinkel** [comment]
🤔 This has the tsc-review label since January, but I've not seen it on the TSC agenda. Are we not discussing tsc-review items or is there a problem with the auto-generation of the agenda?

**Comment by Trott** [comment]
`tsc-review` is (was?) for stuff that is *not* on the agenda but requires attention.

When it was `ctc-review`, I'd put them in the agenda issues every week so people would see them. I can start doing that again, perhaps.

This can probably be closed because Electron and other embedders should be included in https://github.com/orgs/nodejs/teams/delivery-channels. I'll close but feel free to re-open if there's still an issue here.
