### ISSUE TITLE
Discussing Top Level Await at TC39

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#470]
Hey All,

I've recently added [a 30 minute agenda item](https://github.com/tc39/agendas/pull/296) to discuss Top Level Await at tc39 and attempt to get it accepted at Stage 0.

If anyone has specific questions or concerns please chime in.

**Comment by fhinkel** [comment]
Closing, I believe this was discussed [here](https://github.com/MylesBorins/proposal-top-level-await) (Please re-open if closed in error.
