### ISSUE TITLE
Joining core security team and core triage team

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/TSC#474]
Hello,

As of https://github.com/nodejs/security-wg/blob/master/processes/security_team_members.md I'd like to request membership to the security team and the core triage team. 

Right now, I am active in the security WG:
* I have set up the ecosystem triage team
* I am helping setting up the core triage team

I believe I could still be helpful on HackerOne usage and housekeeping for the core triage team.

Also, having a few people members of both triage teams could ensure an efficient management of security issues shich scopes are unclear.

cc @nodejs/security @nodejs/security-triage

**Comment by mhdawson** [comment]
This seems reasonable to me, and it would also let @vdeturckheim help transition the core triage team to using HackerOne.  @nodejs/security thoughts ?

**Comment by bnoordhuis** [comment]
No objections.

**Comment by jasnell** [comment]
No objections

**Comment by mcollina** [comment]
no objections

**Comment by jasnell** [comment]
Given that there have been no objections to this, we should consider it accepted.

**Comment by jasnell** [comment]
@vdeturckheim ... I have added you to the security-triage team and added you to the member list for the nodejs-security private repository. Please remember to be diligent about maintaining the confidentiality of issues and patches discussed in the private security repositories.

**Comment by vdeturckheim** [comment]
@jasnell thanks a lot!
