### ISSUE TITLE
Tracking issue for updating TSC on Board Meetings

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#476]
I figured it might make sense to keep a meta tracking issue for this similar to what we do for Strategic Initiative.

Thoughts?

**Comment by fhinkel** [comment]
IMHO too much overhead.

**Comment by mhdawson** [comment]
Don't think there would be much overhead.  If we have an open issue tagged tsc-agenda it will automatically show up in the list of issues when the issue/minutes are automatically generated.

**Comment by Fishrock123** [comment]
Couldn’t that just be a continuous agenda item rather than a separate issue?

**Comment by MylesBorins** [comment]
@Fishrock123 yup, could be worked into the tool. For example we didn't land this, and I forgot to update the committee yesterday 😓

**Comment by mhdawson** [comment]
A tracking issue is the easiest, as we simply label and then it shows up in the agenda

**Comment by mhdawson** [comment]
I'm going to close this and open a single tracking issue in the admin repo that we can put on both the CommComm and TSC agendas.

**Comment by mhdawson** [comment]
Replaced with https://github.com/nodejs/admin/issues/395, closing
