### ISSUE TITLE
Time to charter the security working group

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#486]
The security working group has been up and running for quite some time now.  I'm wondering if people think it might be time to formally charter it ?

**Comment by mcollina** [comment]
I am 👍 to chartering with the responsibilities defined in the README.

**Comment by jasnell** [comment]
+1 to chartering.

**Comment by Trott** [comment]
This hasn't happened yet? Oh, yes, let's do it if they have all the necessary docs in order.

**Comment by mhdawson** [comment]
I'll add it to my list of TODOs to get the docs in order and get it chartered

**Comment by evanlucas** [comment]
+1 to chartering

**Comment by mcollina** [comment]
+1 to chartering

**Comment by joyeecheung** [comment]
SGTM

**Comment by ChALkeR** [comment]
:+1: @mhdawson What should the next steps be?

**Comment by mhdawson** [comment]
We just need to write the charter with the scope etc. Its on my list I've just been travelling but have not quite gotten to it.

**Comment by Trott** [comment]
> We just need to write the charter with the scope etc. Its on my list I've just been travelling but have not quite gotten to it.

I could be wrong, but it seems like a draft charter could probably be written in less than 30 minutes if someone else on the WG wants to take it off your hands.

**Comment by mhdawson** [comment]
Still on my todo list, sorry for not getting to it yet.

**Comment by mhdawson** [comment]
PR has been submitted here: https://github.com/nodejs/TSC/pull/548

**Comment by mhdawson** [comment]
PR landed. closing.
