### ISSUE TITLE
A new onboarding team

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/TSC#489]
We have discussed in a recent TSC meeting about getting more people involved with the onboarding work. I propose that we create a new onboarding team and use the discussion page to coordinate work there.

I think the initial members will be me, @Trott @addaleax , and probably @mcollina . Does this SGTY?

**Comment by mhdawson** [comment]
STGM

**Comment by mcollina** [comment]
SGTM!

**Comment by joyeecheung** [comment]
I have already created @nodejs/onboarding . Closing..
