### ISSUE TITLE
CoC violation report review results(follow-up on #324)

### ISSUE THREAD

**Issue by de-tester** [nodejs/TSC#497]
Could anyone please provide followup on what was the results of CoC report review opened in #324. 

### Background

Code of Conduct violation report was received on Aug 28, 2017 it was closed on Aug 30, 2017 with comment.

> Closing the issue for now. 

On Sep 2, 2017 `tsc-review` label was removed.
No updated or changes were done to that ticket ever since.

**Comment by MylesBorins** [comment]
The TSC and CommComm both disclosed their decision regarding the report on the private collaborator moderation repo. As the reporter had communicated that they are a collaborator, this was considered a sufficient disclosure as per our [enforcement policy](https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md#enforcement).

There are no plans for the project to further discuss this publicly, and all future inquiries will be pointed towards this response.

I'm going to close this issue, and I'd like to request that @nodejs/moderation lock it.

**Comment by ryanmurakami** [comment]
Locking conversation
