### ISSUE TITLE
Node.js Foundation Technical Steering Committee (TSC) Meeting 2016-02-18 (HANGOUT NOT UBERCONFERENCE)

### ISSUE THREAD

**Issue by rvagg** [nodejs/TSC#50]
## Time

**UTC Thu 18-Feb-2016 20:00**:

* San Francisco: Thu 18-Feb-2016 12:00
* New York: Thu 18-Feb-2016 15:00
* Amsterdam: Thu 18-Feb-2016 21:00
* Moscow: Thu 18-Feb-2016 23:00
* Sydney: Fri 19-Feb-2016 07:00
* Tokyo: Fri 19-Feb-2016 05:00

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Technical%20Steering%20Committee%20(TSC)+Meeting+2016-02-18&iso=20160218T20
* or http://www.wolframalpha.com/input/?i=8pm+UTC%2C+Feb+18%2C+2016+in+local+time

## Links

* **Minutes Google Doc**: <https://docs.google.com/document/d/1S1hzSEB1-_b2cHhcCSXRIiH1irWiWfLS4KawKQMPwvI>
* _Previous Minutes Google Doc: <https://docs.google.com/document/d/1P63hrV4WRdaQ5dAf4or0gP8-mBnuSyIdqFlFsFM-MBM>_

## Agenda

Extracted from **tsc-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/TSC

* Preferred meeting tools [#48](https://github.com/nodejs/TSC/issues/48)
* Improve process and coordination w/ the Foundation PR team [#43](https://github.com/nodejs/TSC/issues/43)
* add initial TLP application for the Appium project [#34](https://github.com/nodejs/TSC/pull/34)
* Submitting NodeConf to the Foundation. [#28](https://github.com/nodejs/TSC/pull/28)

## Invited

* @bnoordhuis (TSC)
* @chrisdickinson (TSC)
* @cjihrig (TSC)
* @Fishrock123 (TSC)
* @indutny (TSC)
* @jasnell (TSC)
* @misterdjules (TSC)
* @mikeal (observer)
* @mscdex (TSC)
* @orangemocha (TSC)
* @piscisaureus (TSC)
* @rvagg (TSC)
* @shigeki (TSC)
* @trevnorris (TSC)

## Notes

The agenda comes from issues labelled with `tsc-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

We will be using Google Hangouts for this meeting and it will be live streamed via YouTube. Anyone is welcome to watch the stream but please only use the Hangout link below if you are one of the invited participants (due to Hangouts limits, we'd love to make room for everyone!).

If you are viewing the YouTube stream, the meeting is unlikely to start on time, you may have to wait while we organise ourselves and clear any business that we are unable to publicly broadcast (we try to do as little of this as possible but it does come up occasionally).

* **Hangouts On-air** (for participants): https://plus.google.com/hangouts/_/hoaevent/AP36tYfFeBs2lOTkYJvoUNhXQx9hKqhLWjydk_SmbwtlYPqnwGHYCw
* **YouTube** (for observing): http://www.youtube.com/watch?v=T6wFkZgnNEQ

**Comment by rvagg** [comment]
@bnoordhuis (TSC)
    @chrisdickinson (TSC)
    @cjihrig (TSC)
    @Fishrock123 (TSC)
    @indutny (TSC)
    @jasnell (TSC)
    @misterdjules (TSC)
    @mikeal (observer)
    @mscdex (TSC)
    @orangemocha (TSC)
    @piscisaureus (TSC)
    @rvagg (TSC)
    @shigeki (TSC)
    @trevnorris (TSC)

To make doubly clear, we are using a Hangout for this, not Uberconference, link above. If you have trouble with Hangouts then let me know your number and I'll try a dial-out to your phone.

**Comment by rvagg** [comment]
@bnoordhuis (TSC)
@chrisdickinson (TSC)
@cjihrig (TSC)
@Fishrock123 (TSC)
@indutny (TSC)
@jasnell (TSC)
@misterdjules (TSC)
@mikeal (observer)
@mscdex (TSC)
@orangemocha (TSC)
@piscisaureus (TSC)
@rvagg (TSC)
@shigeki (TSC)
@trevnorris (TSC)

To make doubly clear, we are using a Hangout for this, not Uberconference, link above. If you have trouble with Hangouts then let me know your number and I'll try a dial-out to your phone.

**Comment by thefourtheye** [comment]
The latest observers are not invited?

**Comment by jasnell** [comment]
@thefourtheye... This is TSC, not CTC. The latest observers are added to
the CTC calls on Wednesday. Those cover the technical issues. The TSC looks
at more foundation level stuff including the other top level projects,
interacting with foundation board, etc. Technically different things even
tho there's currently lots of overlap in membership.

**Comment by thefourtheye** [comment]
@jasnell So CTC is purely technical, TSC is technical + managerial?

**Comment by jasnell** [comment]
Essentially. More managerial than technical really.

**Comment by sam-github** [comment]
I think it would have been clearer when the committee split into two new ones to use new names, particularly if the T in TSC doesn't mean "technical", maybe "F(oundation)SC"? Even collaborators are confused!

**Comment by thefourtheye** [comment]
> Essentially. More managerial than technical really.

Thanks for clarifying @jasnell :-)

Also +1 to what @sam-github said. TSC and CTC mean almost the same to me.

**Comment by bnoordhuis** [comment]
I'll have to decline today.  No strong opinion on the issues on the agenda.

**Comment by rvagg** [comment]
@sam-github I think we all completely agree, however "TSC" is written into the Foundation bylaws as the governing body for everything that happens at this level so we had to use that name for this exercise. Easier than changing things at an official level.
