### ISSUE TITLE
Bug Bounty Program

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#506]
Today I gave the TSC a short presentation engaging with the IBB for an official bug bounty program for for the Node.js project. We had quorum in the meeting and no dissenters. We decided that we would open this issue and give individuals from the TSC who missed the meeting 48 hours to object. If there are no objections in 48 hours I'll close this issue and chime in on https://github.com/nodejs/security-wg/issues/49 that they can move forward with the program

Details below

IBB Program:

* The reports don’t go through IBB, they go to maintainers following normal process 
* After bug is fixed IBB assigns bounty based on severity, which they pay out
* IBB is run by panel made up of companies who have donated
* It runs on top of Hacker One platform

What does node need to do?

* No expectation for money for the foundation to pay for vulns that are discovered in core
* We could incentivize by adding money to the bounties
* If we wanted to have bounties for ecosystem modules we could help sponsor (currently not happening)
* No need to sign anything, they just want to make sure we are ok with this going on, opt-in

/cc @reedloden in case I missed anything

**Comment by reedloden** [comment]
Seems good to me. 👍 

Excited to have Node.js be a part of the IBB!

**Comment by mcollina** [comment]
SGTM
Il giorno mer 14 mar 2018 alle 19:46 Reed Loden <notifications@github.com>
ha scritto:

**Comment by bnb** [comment]
@MylesBorins it looks like there's no objections 💥

**Comment by mhdawson** [comment]
Chimed in on nodejs/security-wg#49 that there were no issues and we can move forward, closing.
