### ISSUE TITLE
Moving 12:00 UTC time to 14:00 UTC

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#510]
Current TSC meeting times are UTC 12:00 17:00 22:00.

@fhinkel has proposed moving to UTC 14:00 17:00 22:00.

TSC meeting (private segment because I forgot during public segment, sorry) consensus was to move forward with that.

I'll update the calendar.

@mhdawson Can you please update your tooling and then close this?

**Comment by fhinkel** [comment]
Thank you! This is a short term solution, we should revisit our schedules again and see if we can find better times.

**Comment by ChALkeR** [comment]
@Trott @fhinkel This completely excludes one TSC member that was otherwise included and _lowers_ the participation fairness. I suggest to just move to 16:00, 20:00, 22:00 instead.

```
times: [ 12, 17, 22 ], participation: 0.47011, participationFairness: 0.7145, interaction: 0.32129, interactionFairness: 0.4362
times: [ 14, 17, 22 ], participation: 0.63103, participationFairness: 0.69312, interaction: 0.4193, interactionFairness: 0.45352
times: [ 16, 20, 22 ], participation: 0.73014, participationFairness: 0.87383, interaction: 0.54327, interactionFairness: 0.59781
```

**Comment by Trott** [comment]
@ChALkeR Can we move that new suggestion to a new issue? I'd like to keep this discussion of the agreed-upon current schedule separate from your proposal (which I'm excited about, and thank you for doing all the number-crunching work).

**Comment by ChALkeR** [comment]
@Trott, yes. I currently can't open a new issue, could you do that, please? Otherwise. I'll do that tomorrow.

For this specific proposal - I am not in favor of it for the reason stated above, but I won't block this.

**Comment by fhinkel** [comment]
Thanks for finding a better time! I like your proposal much better.

**Comment by mhdawson** [comment]
Not sure who updated, but the schedule is already updated to show 12 UTC for the next "early" meeting.

I'll assume the additional changes suggested by @ChALkeR will be handled in a different issue.

**Comment by mhdawson** [comment]
Sorry yes.
