### ISSUE TITLE
Node.js Foundation Technical Steering Committee (TSC) Meeting 2016-02-25 - can we skip it?

### ISSUE THREAD

**Issue by rvagg** [nodejs/TSC#52]
I'm proposing we skip the TSC meeting, partly because I'm selfishly not wanting to do yet another early morning this week but also because we don't have anything fresh to discuss as far as I'm aware. The agenda comes out the same as last week:

* Preferred meeting tools [#48](https://github.com/nodejs/TSC/issues/48)
* Improve process and coordination w/ the Foundation PR team [#43](https://github.com/nodejs/TSC/issues/43)
* add initial TLP application for the Appium project [#34](https://github.com/nodejs/TSC/pull/34)
* Submitting NodeConf to the Foundation. [#28](https://github.com/nodejs/TSC/pull/28)

And the one big item that we were going to try and work on which is this thing about purpose, and how we can come up with a basis for making decisions about new incubator projects, doesn't appear to have moved along in this repo at all. I think we've all been a little too busy. I will say though that some board members appear to be in a similar place to us, wondering if we can more clearly define what we are trying to do, so it might be worth getting on a similar wavelength to them.

So, I'll set my alarm and if anyone thinks it's important enough that we have a meeting I'll try and set it up, if not then I'll go back to sleep for a tiny bit longer.

**Comment by orangemocha** [comment]
I probably won't be able to join today, so I am selfishly +1 for skipping.

**Comment by cjihrig** [comment]
I'm fine with skipping if there is nothing new to talk about. Do we still need the preferred meeting tools item after live streaming yesterday's CTC meeting?

**Comment by mikeal** [comment]
+1 to skipping, I don't have anything new.

**Comment by Fishrock123** [comment]
Nothing much to report here, express had an initial hangout last night, no official meeting or decisions yet, pushing to next week.

As for meeting tools, we'll have to see how this works out but it would be nice to be able to display who is talking, which isn't really possible with uberconference.

**Comment by mikeal** [comment]
@Fishrock123 I think GoToMeeting does this in their little participant list.

**Comment by Fishrock123** [comment]
@mikeal WHat were the reasons we moved from GoToMeeting? I forget, was it just the recordings?

**Comment by mikeal** [comment]
@Fishrock123 the foundation already has an account for the board meetings. we don't have to use it but it's an available option for no extra cost. the main reason we didn't like it was that we always forgot to do the recording, and hangouts auto-posted to youtube which saved a lot of manual work.
