### ISSUE TITLE
Update meeting times

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#539]
Current TSC meeting times (in UTC) are 14:00 17:00 22:00.

@ChALkeR has proposed changes based on his code that measures various characteristics of schedules.

* 14:00 -> 12:00
  * 7AM Pacific -> 5AM Pacific
  * 10AM Eastern -> 8AM Eastern
  * 4PM CET -> 2PM CET
  * This is a worse time for a lot of people, but it is a great improvement for Rod and Sakthi. This is worth sacrificing convenience for others in my opinion because right now Sakthi has two "impossible" times and one time that is "inconvenient". Meanwhile, Rod has two "impossible" times and one time that is "tolerable". This change removes one of the "impossible" times for each of them.
* 17:00
  * no change; we already use this time
* 22:00 -> 21:00
  * 3PM Pacific -> 2PM Pacific
  * 6PM Eastern -> 5PM Eastern 
  * midnight CET -> 11PM CET
  * This is an obvious change IMO. It is an improvement or neutral for everyone except Rod, for whom it changes a "tolerable" time to an "inconvenient" time. We want to be careful about making things even worse for Rod as he along with Sakthi seem to get the least accommodations in our schedule. However, I think combined with the other change above, it works out on balance. Currently, Rod has two "impossible" times and one "tolerable" time. If we change both of the meeting times proposed to be changed here, Rod ends up with one "impossible", one "inconvenient", and one "tolerable". That's not great, but it's at least a move in the right direction (and realistically, there are going to be people for whom the schedule is going to look like that no matter what we do).

It would be great to get this change implemented via consensus rather than a vote, but we'll see. If you are in favor of this change, please leave a :+1: reaction on this. If you are opposed to this change, please leave a detailed comment explaining what you would prefer instead (even if it is "no change to our current schedule" and, more importantly, why your proposal is better than this one). 

I would ask that people please refrain from questions like "Why don't we just move meeting A to time B instead of time C? It seems like that would be better." We all have access to the spreadsheet with people's availabilities. Please look at that information if you want to propose an alternative. Then make it a statement with a full accounting of impact along the lines of: "I think we should move meeting A to time B instead of time C because that improves attendance likelihood for Members X, Y, and Z for whom the current schedule is awful. I acknowledge that it makes things worse for Members V and W, but that reduces them from near-perfect schedules to mostly good schedules."

@nodejs/tsc

**Comment by Fishrock123** [comment]
> This is a worse time for a lot of people

Yeah. We did that before. Not enough people showed up and meetings were unproductive.

**Comment by TimothyGu** [comment]
I will be able to make it to none of the proposed meeting time. (Note: the spreadsheet entries for a lot of US-based TSC folks seem to have not been updated after the start of daylight saving time, including mine.)

**Comment by Trott** [comment]
> Yeah. We did that before. Not enough people showed up and meetings were unproductive.

The last time we had a meeting at 12:00, 7 people showed up. There are a few reasons to believe the meeting time would work slightly better now but none of them seem super-compelling to me:

* That was before daylight savings time started in North America, which pushes the meeting an hour later there. Instead of 7AM  Eastern, this time is now 8AM Eastern.
* Two people who had that time as "impossible" are no longer on the TSC.
* The TSC is slightly smaller now so quorum is 10 rather than 11 people.

I'm going to close this and focus on getting better data from folks in the spreadsheet first. (If @ChALkeR or someone else wants to re-open and try to make this happen, I'm OK with that.)

**Comment by ChALkeR** [comment]
@Trott Oh. I didn't notice this since it became closed before I looked at it, and opened #540 instead.
Sorry :-/.
