### ISSUE TITLE
Move meeting times to 17, 21 or to 12, 17, 21.

### ISSUE THREAD

**Issue by ChALkeR** [nodejs/TSC#540]
_All the data is according to Google Spreadsheets table that lists time options.
In case if the numbers in the table will get updated while the decision is not yet made, that might affect the numbers here. If that happens, I will update the numbers accordingly, and if that would cause a change in the selection, I will make a clear notice about that._

### The current meeting times are 14, 17, 22 (UTC).
The average expected participation probabilities for each person (anonymized, sorted):

<table><tr>
<td>0.8666</td><td>0.8575</td><td>0.8261</td><td>0.8197</td><td>0.7451</td><td>0.7248</td><td>0.6951</td><td>0.6641</td><td>0.6641</td>
</tr><tr>
<td>0.6144</td><td>0.6124</td><td>0.5792</td><td>0.5792</td><td>0.5540</td><td>0.4822</td><td>0.3248</td><td>0.2288</td><td>0.1782</td>
</tr></table>

Metrics row: `avg: .612, min: .1782, stdev: .1967, fair: .6724, n5: 14, u2: .9628`.
Average is 61%.

### For 12, 17, 21 (UTC):

<table><tr>
<td>0.7769</td><td>0.7769</td><td>0.7736</td><td>0.7506</td><td>0.7236</td><td>0.7229</td><td>0.7229</td><td>0.7196</td><td>0.6541</td>
</tr><tr>
<td>0.6365</td><td>0.6365</td><td>0.6331</td><td>0.5156</td><td>0.4907</td><td>0.4866</td><td>0.3443</td><td>0.3235</td><td>0.3172</td>
</tr></table>

Metrics row: `avg: .6114, min: .3172, stdev: .1552, fair: .7797, n5: 13, u2: .9782`.
Average is 61% — the same as now, just more fairly distributed.

### For 17, 21 (UTC):

<table><tr>
<td>0.9493</td><td>0.9493</td><td>0.9493</td><td>0.9493</td><td>0.9493</td><td>0.9493</td><td>0.9443</td><td>0.9443</td><td>0.9443</td>
</tr><tr>
<td>0.8694</td><td>0.8693</td><td>0.7246</td><td>0.7246</td><td>0.7194</td><td>0.4798</td><td>0.4795</td><td>0.2599</td><td>0.2597</td>
</tr></table>

Metrics row: `avg: .7731, min: .2597, stdev: .2356, fair: .7257, n5: 14, u2: .9783`.
Average is 77% — and looks much better than what we have now.

--- 
The numbers could be reproduced by copy-pasting the data from the table into https://chalker.github.io/Lliira/ (and/or with the source code behind that).

**Comment by mhdawson** [comment]
For me 2 of the times are good, but my +/= will depend more on how it works for other people.

**Comment by ChALkeR** [comment]
Perhaps, it would also make sense to collect the data about previous participations and throw that into the the model to compare against it — that could give some hints about if this predicition is valuable or not.

**Comment by ChALkeR** [comment]
Ok. Seems that people are still updating their data. Closing this for now, will file a new one in a day or two.
