### ISSUE TITLE
Updated JS MIMEs under 2 week review from IETF

### ISSUE THREAD

**Issue by bmeck** [nodejs/TSC#566]
https://datatracker.ietf.org/doc/draft-ietf-dispatch-javascript-mjs/ is under review and has a mailing list thread open about it at https://mailarchive.ietf.org/arch/msg/dispatch/X3aBzTbPFT8bJRAYcO7ldjJmAls

Please respond with any endorsements or concerns.

**Comment by jkrems** [comment]
As somebody who doesn't know the IETF processes very well: Are endorsements from random community members welcome or is this call tailored towards people who are both node- and IETF members..?

**Comment by bmeck** [comment]
@jkrems you do not need to be an IETF member to provide feedback

**Comment by mcollina** [comment]
This looks good from my end. Should I reply? Are you looking for an endorsment from the TSC.

**Comment by bmeck** [comment]
@mcollina it is just a comment period, if you endorse it personally or through the TSC it doesn't matter, the editors are mostly just looking for some signal of +/- from the parties involved.

**Comment by benjamingr** [comment]
I'm +1 on that draft (personally).

**Comment by bmeck** [comment]
please put feedback on the official IETF mailing list, the editors won't be reading stuff on this issue

**Comment by benjamingr** [comment]
@bmeck sure, gladly - who do I email? Do I just send an email saying I like it to draft-ietf-dispatch-javascript-mjs.all@ietf.org ?

**Comment by bmeck** [comment]
I think so (this is all new to me)

**Comment by Fishrock123** [comment]
@bmeck Any idea the status of this?

**Comment by sam-github** [comment]
@bmeck @jkrems You probably realized this by now, but the IETF is composed of those who participate, mostly in its working groups, mostly by email. Just sign up to the WG email list and join the discussion.

> The IETF has no formal membership, no membership fee, and nothing to sign. 

- https://www.ietf.org/about/participate/

**Comment by bmeck** [comment]
It got pushed back in part due to page length of the change, I'm taking hiatus from trying to push it through.

**Comment by mhdawson** [comment]
@MylesBorins just wondering if this is still something you plan to get to at some point?

**Comment by MylesBorins** [comment]
@mhdawson this is still ongoing. We have the latest draft sent for IETF review, likely to take another 6 - 12 months to see through

**Comment by mhdawson** [comment]
K, thanks was just doing a housecleaning pass of the issues.  Good to know it is still in flight.

**Comment by mhdawson** [comment]
@MylesBorins I'm wondering if this might makes sense to be in the OpenJS Foundation org, in the standards repo?

**Comment by MylesBorins** [comment]
I think transferring to standards could make sense, although this is somewhat node specific. The proposal is moving forward.

**Comment by Trott** [comment]
I'm going to guess that after 3+ years of inactivity, this issue can be closed. If I'm guessing wrong, please comment or re-open. Just doing some cleanup.
