### ISSUE TITLE
Move meetings times to 12,16,21

### ISSUE THREAD

**Issue by ChALkeR** [nodejs/TSC#570]
Current ones are `14,17,22` — those seem to be far from being optimal (according to the meeting time options spreadsheet), and for two people that brings estimated participation levels below 30% (one of which — below 20%).

Switching to `12,16,21` essentialy means to:
1) Revert https://github.com/nodejs/TSC/issues/510,
2) Move the remaining two by one hour (probably mostly caused by daylight saving adjustment?).

Data from [the tool](https://chalker.github.io/Lliira):
 * Expected participation levels for `14,17,22`: average: `69.0%`, stdev: `.201`, **[current]**
   row: `93% 93% 93% 88% 88% 79% 78% 74% 69% 69% 64% 64% 62% 62% 62% 62% 26% 18%`
 * Expected participation levels for `12,16,21`: average: `72.3%`, stdev: `.149`, **[proposed]**
   row: `91% 91% 87% 87% 87% 87% 78% 78% 78% 77% 66% 64% 64% 60% 59% 56% 49% 41%`
 * Expected participation levels for `12,16,22`: average: `65.3%`, stdev: `.122`,
   row: `89% 85% 81% 76% 76% 76% 71% 66% 62% 62% 58% 57% 57% 56% 56% 53% 50% 47%`
 * Expected participation levels for `12,21`: average: `68.7%`, stdev: `.163`,
   row: `90% 90% 90% 83% 83% 83% 83% 76% 70% 70% 70% 61% 52% 48% 48% 48% 48% 44%`
 * Expected participation levels for `16,21,21`: average: `80.7%`, stdev: `.219`,
   row: `95% 95% 95% 95% 95% 95% 95% 95% 94% 94% 90% 85% 80% 80% 63% 45% 34% 28%`

Each value in a «row» stands for expected participation level of one person, rows are anonymized and sorted from most included (high percentage) to most excluded (low percentage).

_Upd: exact predicted participation levels (non-anonymized) are available on the second sheet of the private document._

`12,16,22` works a bit better for minimizing the stdev and bringing everyone as close to 50% participation plank as possible, but that lowers the average expected participation by about 4% instead of increasing it (as `12,16,21` does), which means about 1¼ persons less on a random meeting in average.

/cc @Trott, @fhinkel, @nodejs/tsc 

_Note: data is based on the current values in the table, updated at 2018-07-18 06:30 UTC._\
_I will update this in case if anything changes in the data._

**Comment by mcollina** [comment]
I’m definitely +1 with the move. The 22 time slot is impossible for me with daylight savings.

Side note, I think we should always reassess the timeslots after daylight savings changes have settled.

**Comment by ChALkeR** [comment]
@mcollina I plan to ad TZ support to the tool that I use to select those before the next TZ shift, that should make things easier to track without everyone having to update the table in UTC all over after a TZ shift (which is where we were blocked last time).

**Comment by ChALkeR** [comment]
Exact predicted participation levels (non-anonymized) are available on the second sheet of the document.

**Comment by ChALkeR** [comment]
Data updated, recommendation switched to just `12,16,21` as 17 became not optimal.

**Comment by joyeecheung** [comment]
+1 to `12,16,21`

**Comment by mcollina** [comment]
Definitely +1 to 12, 16 and 21.

**Comment by targos** [comment]
+1 from me too but I'd like to have feedback from people for whom those times are the worse.

**Comment by ChALkeR** [comment]
About the `14` timeslot — it does not to be a part of any optimal set.

In fact, if the `12` timeslot should be moved somewhere — moving it to another `21` instead of `14` produces better results::
 * Expected participation levels for `16,21,21`: average: `80.7%`, stdev: `.219`,
   row: `95% 95% 95% 95% 95% 95% 95% 95% 94% 94% 90% 85% 80% 80% 63% 45% 34% 28%`
 * Expected participation levels for `14,16,21`: average: `77.2%`, stdev: `.235`,
   row: `95% 95% 95% 95% 95% 95% 94% 94% 90% 90% 80% 80% 70% 64% 64% 49% 28% 18%`

I would suggest to keep the 12 timeslot though, as it does a better job for some people.

**Comment by mhdawson** [comment]
I'm good with any of the new options.

**Comment by ofrobots** [comment]
I'm also good with any of the options. In practical terms, my ability to attend will not be affected.

**Comment by Trott** [comment]
+1 from me.

**Comment by Trott** [comment]
(Thanks for doing the analysis, @ChALkeR. This stuff can be mind-bending.)

**Comment by fhinkel** [comment]
+1 from me but somebody would need to chair the `12` timeslot.

**Comment by mhdawson** [comment]
@nodejs/tsc I think we should agree on this in the meeting this week, so please chime in if you have any objections or other suggestions.

**Comment by mhdawson** [comment]
Agreed in  TSC meeting to move.

Updated calendar, closing.
