### ISSUE TITLE
A new NodeJs execution model

### ISSUE THREAD

**Issue by bishwenduk029** [nodejs/TSC#589]
Hi,

I apologize before hand if I am posting this issue in a wrong forum. I have been working with Akka framework for a long time. I have been very fascinated by the idea of actors and how asynchronous behaviour is baked into their mode of operation allowing for an implicit non-blocking co-operative multitasking execution model.

Functions in JS are atomic units of work, which can be represented as actors. There could be two kinds of  messages being passed to them, first one being execution intent leading them to execute the function on their internal and closure state. Second one being suspend intent, although when an actor is not precessing it could be in suspend state but if it is not referenced by, it can be garbage collected or destroyed.

The biggest advantage this model has to offer is increase the accuracy of the timers in JavaScript and also allow for scaling on multi-core CPUs which now days are becoming a norm in modern computing engines. This is just a short summary of an imagination. 

In case this seems to be wrong or if my understanding of NodeJS/JavaScript is wrong please do ignore this and also I hope this was the right forum to post this, if not i am again sorry.

Thanks for reading,
Bishwendu.

**Comment by mhdawson** [comment]
I'm not sure what you are suggesting, new APIs or something else?

**Comment by bishwenduk029** [comment]
I am sorry I think I am wrong in my understanding somewhere, and posted this question. I will close this one. Sorry for the confusion caused.
