### ISSUE TITLE
Help in triaging node.js core security issues

### ISSUE THREAD

**Issue by mcollina** [nodejs/TSC#598]
I would like to candidate myself to help in triaging Node.js core security issues in H1.

**Comment by jasnell** [comment]
+1

**Comment by Trott** [comment]
Is there a documented process for this? Is this the right repo etc.? @nodejs/security-wg

**Comment by mcollina** [comment]
There isn't one. There is one for the 3rd-party vuln database (https://github.com/nodejs/security-wg/blob/master/processes/security_team_onboarding.md). 

I think this is governed by the TSC and not by the security-wg.

**Comment by jasnell** [comment]
The security triage team has nothing to do with the @nodejs/security-wg. It is the purvue of the TSC as part of the @nodejs/security team management. Generally speaking, all we need for this is no objections from @nodejs/tsc or @nodejs/security.

**Comment by bengl** [comment]
@mcollina 

> I think this is governed by the TSC and not by the security-wg.

@jasnell 

> The security triage team has nothing to do with the @nodejs/security-wg. It is the purvue of the TSC as part of the @nodejs/security team management. 

I just want to clarify this for those reading and thinking "Hey wait, isn't it Security WG's job to define this sort of policy?".

As it turns out, the charter for the group states among its responsibilities:

> Review and recommend processes for handling of security reports (but not the actual administration of security reports, which are reviewed by a group of people directly delegated to by the TSC).

While this is vague, it effectively states that the core triage team consists of folks who are approved by the TSC directly. So yes, by the Security WG's own charter (and likely other bits of policy spread around the org), this repo (TSC) is the correct place for this discussion, and the Security WG has no other policy for this (nor is it chartered to do so).

**Comment by mhdawson** [comment]
+1

**Comment by Trott** [comment]
> The security triage team has nothing to do with the @nodejs/security-wg. 

I pinged Security WG because they often document our policies around this stuff because we fail to do so, not because I thought they had authority.

To wit: https://github.com/nodejs/security-wg/blob/master/processes/security_team_members.md#nodejs-security-team

**Comment by mcollina** [comment]
@Trott there is absolutely no policy around that team, apart from it's a TSC responsibility.

**Comment by mcollina** [comment]
Cool! How do I get onboarded?

**Comment by vdeturckheim** [comment]
@mcollina If I get TSC approval, I can invite you on HackerOne org and we can schedule a call so I show you around :)

**Comment by cjihrig** [comment]
We talked about it in the private section of today's TSC meeting. @mcollina should be good to go I think.

**Comment by vdeturckheim** [comment]
@mcollina you should have received an email invite on the address from tje Node.js readme. Let me know if you want/need an onboarding, I'll be happy to schedule a call with you.

**Comment by mcollina** [comment]
A call will be good, how about tomorrow or Friday, maybe in the morning?

**Comment by vdeturckheim** [comment]
Following up by email :)

**Comment by mhdawson** [comment]
@mcollina I think this could be closed now.
