### ISSUE TITLE
Stepping back from security triage team

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#599]
@nodejs/security @nodejs/tsc ... just a quick heads up that while I will remain a member of the @nodejs/security team evaluating and working to resolve security issues, I will be stepping back from the initial triage team. This is due specifically to a lack of time to commit to the basic service level agreement required by initial triage.

**Comment by mhdawson** [comment]
@jasnell I think this could be closed now.

**Comment by jasnell** [comment]
yep, can be closed :-)
