### ISSUE TITLE
Meeting this Thursday

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#6]
I'd like to have our first full meeting prior to the board meeting on Monday so that we can get this travel program ready.

**Comment by jasnell** [comment]
Doodle for times?

**Comment by mikeal** [comment]
we should do it at the same time we've been doing the core meetings cause it's the only time we know work for everyone.

**Comment by jasnell** [comment]
Ok. Will this be weekly? If so, it would conflict with the HTTP WG times which are set for every other thursday at 1:00pm pacific. Next one is scheduled for Nov 5th.

**Comment by mikeal** [comment]
Not weekly, we should schedule them as-needed.

**Comment by jasnell** [comment]
+1 then :+1:

**Comment by Fishrock123** [comment]
Making sure @nodejs/tsc get the notice

**Comment by Fishrock123** [comment]
Is there a meeting today?

**Comment by mikeal** [comment]
Nothing scheduled, there's no pressing issues that I know of. If there is log an issue and we can get one on the schedule for next wee.
