### ISSUE TITLE
Q&A during meetings

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#60]
Some thoughts on the `Q&A` sections of meetings. These _could_ apply to ALL MEETINGS of ALL groups/committees.
## The scope & purpose

What can be asked? What is the purpose of this portion of the meeting? Why offer it? I think the scope of **what can be asked** should be defined. This would help to ensure that questions ranging from "What presidential candidate are each of you backing?" to "I'm getting a 404 error with express, what do I do?" can be avoided. If they do happen, then: "I'm sorry, that is out of the scope of this section"

From my experience, questions at the end of the meeting should be geared towards something that happened during the meeting. Examples:
- Burt, you cut out when you were talking about XYZ, could you repeat?
- Mikeal, you mentioned an Issue that was opened about XYZ, can you find where that is so I can check it out?

Suggestion: When meetings get to this portion of the agenda, offer a small statement of this and then open up the floor.
## The Name

Perhaps you want to allow people to feel welcome to make comments and provide feedback. So how about calling it `Audience Comments and Questions`. But this really depends on the `scope and purpose` topic above.
## The Timing

Because of the forum of the meetings, it really doesn't matter WHEN someone asks a question/comment. It can be posted at any time and the meeting moderator can go over them when the meeting advances to that stage. I suggest trying to encourage people to use YouTube comments instead of IRC since an IRC room member that doesn't know there is a meeting going on just sees things posted that look REALLY random.

Also, I have been involved in board meetings with community involvement before. It is very common to have a section at the beginning where the general public can have time to make a statement about _agenda items only_. This gives people a voice BEFORE votes happen and makes the community feel like they are heard & important. The current system kind of offers this via discussions in PRs and Issues... however when they topic comes up in a meeting, the community participation is not recognized. An example of giving this recognition could be having a meeting participant pull out & summarizing points brought up by community members. e.g.: _"silverwind suggested using Buffer.safe() and Buffer.unsafe()"_

**Comment by mikeal** [comment]
Each group has autonomy. The TSC can suggest and encourage open Q&A but it's each groups decision whether or not they do so. Also, not all groups have meetings (the website runs without regular meetings).

Unified calendar and best practices would be great though, I think most groups want to do this but are just lacking guidance.

**Comment by williamkapke** [comment]
> best practices would be great though, I think most groups want to do this but are just lacking guidance.

Doh- yes, I totally left that out on accident. Thanks for adding it.

Also: This hinges on "steering" in T**S**C being aimed at the overall eco system here.
...But then again, I guess this may not fall under the "technical" part of **T**SC 😕
So would that bubble it up to the Node.js Foundation Board? Seems too granular/process-oriented for that.

**Comment by williamkapke** [comment]
I'm going to close this one out. We haven't had any wild questions.

We can re-open if we ever need to address.
