### ISSUE TITLE
Shipping recursive fs.mkdir() in v10.x

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#604]
Based on conversation in https://github.com/nodejs/TSC/issues/601 and https://github.com/nodejs/node/issues/22585, I believe the following TSC members are in favor of shipping recursive `mkdir()` in v10.x as-is (that is, as something that can be turned on in the `options` object of `fs.mkdir()`):

1. @Trott 
1. @addaleax 
1. @joyeecheung 
1. @mhdawson 
1. @gabrielschulhof 
1. @MylesBorins 
1. @targos 
1. @mcollina 
1. @cjihrig 
1. @ofrobots 

And in the not-objecting/abstaining department:

1. @apapirovski 

Lastly, opposed to doing it at this time: 

1. @jasnell 
1. @danbev 
1. @thefourtheye 
1. @Fishrock123 

I don't believe further conversation is likely to move many people from one camp to the other. And I don't believe that taking more time to decide this is in the interest of the community. I therefore would like to call for a vote. (Anyone on the TSC can stop the vote by disagreeing that it's time for a vote and indicating that they believe more conversation would be useful. I implore you not to do that, but I can't stop you from doing it if it's what you believe.)

So, vote counting: If I have you categorized correctly above, please leave a comment to that effect or else a 👍 on this comment. If I have you categorized incorrectly, please leave a comment indicating how to correct. If I have not categorized you at all, please leave a comment as to where your vote should go. That last one would apply to @rvagg @fhinkel @ChALkeR @gibfahn @TimothyGu

**Comment by Trott** [comment]
And I'll make this comment for tallying things once people confirm their sentiments above:

YES:

1. @Trott 

NO:

1. ...

ABSTAIN:

1. ...

**Comment by jasnell** [comment]
As I've clarified a couple of times now, I'm not opposed to shipping recursive mkdir in 10.x. I'm opposed to shipping it *if* we're going to change it after we settle on the feature detection. I'm perfectly fine with shipping it now so long as it's understood that the feature detection discussion is a wholly separate issue.

**Comment by Trott** [comment]
> As I've clarified a couple of times now, I'm not opposed to shipping recursive mkdir in 10.x. I'm opposed to shipping it if we're going to change it after we settle on the feature detection. I'm perfectly fine with shipping it now so long as it's understood that the feature detection discussion is a wholly separate issue.

I think it's pretty clear that there is not consensus to avoid the alias, which is why you're listed as opposed.

**Comment by mhdawson** [comment]
+1 for shipping as is.

**Comment by fhinkel** [comment]
I abstain.

**Comment by mcollina** [comment]
+1 for shipping as is.

**Comment by Trott** [comment]
With 10 votes for and 1 abstention, that's enough to decide it for "ship it". :shipit:
