### ISSUE TITLE
Real names vs Github names

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#62]
While watching/listening to meetings, the participants use real names (usually?). However for most people, when someone says, for instance, "I want to add to what Brian said..." they have no idea that Brian is mscdex on Github which contains more context.

It looks like real names are used in agendas (or at least the agenda I peeked at)- but there isn't the cross reference to the Github name.
### Suggestions
- In meeting notifications- use both Real names and Github names.
- In the YouTube video description, also add the list of participants.
### Additional side note

When io.js had meetings, the google hangout would switch to the person that was talking. It wasn't perfect because it only would show their photo & not their name- but it really helped to see Bert's easily identifiable photo and we could tell who was talking ;P

Tip for anyone looking for a current solution: Follow along with the meeting notes Google doc to figure out who is talking.

<sub>*This applies to all meetings for all groups/committees.</sub>

**Comment by Fishrock123** [comment]
See also https://github.com/nodejs/TSC/issues/48#issuecomment-187828192 -- with our current meeting tools (because our meetings can often outsize google hangouts) there isn't really a good way to show who is speaking.

**Comment by nebrius** [comment]
A thought: one small thing we could do as a partial solution is to list people's display name on GitHub along with their GitHub handle in the `Invited` section of the meeting issue.

**Comment by nebrius** [comment]
Another thought: we could add an official "introductions" section to the agenda at the start of every meeting for each participant to say, e.g. "Hi my name is Bryan Hughes, nebrius on GitHub, and I work for Microsoft." We've do this for our inclusivity WG meetings, and it's pretty quick and effective.

**Comment by Fishrock123** [comment]
Added a participants list to today's youtube recording.

**Comment by Fishrock123** [comment]
@nebrius That becomes pretty impractical for the CTC meeting. We do, however, do a full standup there.

**Comment by nebrius** [comment]
Ah, that's a good point. For the TSC specifically, maybe intros could be rolled into standup, and we make sure to always do a standup, even if we say "Nothing new to report"?

**Comment by williamkapke** [comment]
If we ever get to the world where we have the meetings automated I feel confident we will work in the ability to display real names AND GitHub names in the best possible way. Probably iterating on a few different ideas.

For now, viewers can open the meeting issue and/or google doc where we have done a pretty good job keeping the list of participants using both names and @-mentions.
