### ISSUE TITLE
Discrepency between website and TSC charter

### ISSUE THREAD

**Issue by richardlau** [nodejs/TSC#620]
https://nodejs.org/en/about/governance/#tsc-membership (from https://github.com/nodejs/nodejs.org/blob/master/locale/en/about/governance.md) is inconsistent with https://github.com/nodejs/TSC/blob/master/TSC-Charter.md.

Inconsistencies:
1. Website describes an expected target size "between 6 and 12". The charter says, "The TSC must have at least three members."
1. Affiliation limits -- the website "No more than 1/3 of the TSC members may be affiliated with the same employer." vs the charter's "No more than one-fourth of the TSC members may be affiliated with the same employer."

I would presume the charter is the source of truth here, but am not sure so I'm raising the issue here instead of against the website repository.

Perhaps the inconsistency is somehow related to when the TSC and CTC were separate.

**Comment by targos** [comment]
1. Changed from "between 6 and 12" to "at least three" in https://github.com/nodejs/TSC/commit/e9e7baaa51af5dcdac7f45747a27879148b13eeb. The website is outdated. 
2. They differ from the beginning. I don't know which one was meant to be used.

**Comment by mhdawson** [comment]
I think we have to take the charter as the source of truth.

**Comment by Trott** [comment]
I'd be for removing nearly all information about the TSC from the website. Certainly information about the target size (or lack thereof) and company representation limits seem like minutiae.

**Comment by mcollina** [comment]
+1 on removing, it should link to this repo.

Il giorno ven 2 nov 2018 alle 19:22 Rich Trott <notifications@github.com>
ha scritto:

**Comment by refack** [comment]
A very heavy handed un-verbosing of the governance page - https://github.com/nodejs/nodejs.org/pull/1886 PTAL
