### ISSUE TITLE
Chair for 12pm gmt meeting -volunteer needed

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#625]
With the daylight savings time change the 12 GMT meeting is now too early for me.

Looking for a volunteer to chair on a regular basis.

**Comment by mcollina** [comment]
Considering daylight savings time maybe we should adjust our meeting times?

I'm happy to chair if I'm not traveling (but that happens often, including this week).

**Comment by Trott** [comment]
If it helps anyone figure out if they can volunteer for this....this is 4AM Pacific, 7AM Eastern, 1PM CET, 8PM CST....

I can usually attend these meetings, but cannot speak during them so I'm not a good candidate.

**Comment by mhdawson** [comment]
I was thinking we should re-evaluate the times.  I'll send out an email with the link to the doc.

**Comment by mhdawson** [comment]
Due to the last notice I was planning on getting up earlier this week.

@mcollina are you available Dec 5th?

**Comment by mhdawson** [comment]
@mcollina ok good, at least we have the next time covered while we sort out if anybody else can volunteer.

**Comment by mhdawson** [comment]
@nodejs/TSC can anybody volunteer to be a backup for @mcollina when he cannot make the  4AM Pacific, 7AM Eastern, 1PM CET, 8PM CST timeslot?

**Comment by mcollina** [comment]
@mhdawson let's consider that I chair that meeting going forward, and let's verify how many times there is an actual clash. All my travel is planned well in advance, and I can tell if I won't be able to chair.

**Comment by mhdawson** [comment]
k, sounds good. 

Do you have the zoom credentials and know the overall procedure to get the meeting started and stream?  If not maybe we can sync in advance of next meeting and have you start the streaming to make sure you can do it.

**Comment by Trott** [comment]
@mhdawson Can we remove `tsc-agenda` from this issue given this?

**Comment by ChALkeR** [comment]
12am is no longer part of any optimal set, given the recent updates to the spreadsheet.

The next 12am meeting is supposed to be in three weeks, and I assume that we'll revise our meeting times before than.

I propose we just close this for now =).

**Comment by mhdawson** [comment]
I'll assume that @mcollina is our volunteer and if we change we'll adjust after that, closing.
