### ISSUE TITLE
Proposal: Fewer TSC Meetings

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#626]
The @nodejs/tsc meeting agenda has been fairly light recently... which is a very good thing.
There have been few, if any, time sensitive issues on the public agenda and the current weekly rotating-time schedule generally ensures that only a third to a half of the TSC members can actually participate week to week.

I would like to propose that we move to a *monthly* meeting schedule.

Doing so would do a number of things for us:

1. It would free up time in all of our calendars each week. When a time sensitive issue does come up (private or public), then special interim calls can be scheduled as necessary.

2. It would encourage more consensus seeking in the GitHub issue tracker. Because there would be fewer TSC calls with more time between, collaborators would be incentivized to seek consensus rather than deferring quickly to the TSC for resolution.

Thoughts?

**Comment by mcollina** [comment]
We would need to select one or two timeslots that works for the majorjty of TSC members. The current rotating weekly meeting ensure thst everybody has a chance to join.

**Comment by Trott** [comment]
(More detailed Charter-ific problem with this in a subsequent comment, but for now...)

I'm -1 on this. I think instead:

* Have the meetings in the schedule and *cancel* them frequently. We don't cancel nearly enough meetings to justify having them once a month.

* Short meetings are great, if they're productive (like the last one was). 

* Having monthly meetings will greatly exacerbate people showing up to the meeting oblivious to what's on the agenda and waste time at the meeting getting up to speed on stuff that they should show up to the meeting already knowing

* Ad hoc meetings are time-consuming to schedule and always end up in times that are great for US and Europe and terrible for Asia and Australia.

If we end up canceling four meetings in a row or something, maybe consider switching to a biweekly schedule. But we don't do that (yet). 

> * It would encourage more consensus seeking in the GitHub issue tracker. 

I think the above point is very tempting but ultimately reverses cause and effect. If we use the GitHub tracker more and cancel meetings as a result, *then* reduce the frequency of scheduled meetings.

**Comment by Trott** [comment]
One more thing: Less frequent meetings is arguably a community-hostile thing to do. It gives the impression (and in my opinion, will probably result in the reality) that more happens in private conversations and less in the meetings.

**Comment by Trott** [comment]
(Also: OMG +100 on being serious about working hard during the week to get `tsc-agenda` items unstuck so we can cancel meetings more.)

Oh, there are probably things that need to happen at meetings according to our process, and we'll want to change that if we're going to less frequent meetings. For example, I believe Collaborator nominations are required to be announced at meetings. (I could be wrong about that and if I'm not, I'd be happy to see that change.)

**Comment by Trott** [comment]
> I believe Collaborator nominations are required to be announced at meetings.

This is actually enshrined in our Charter. 😱Opening a PR to change....

**Comment by joyeecheung** [comment]
@Trott The intention was to announce the nomination when there is a meeting - so, I believe we can just change that to something like  "announce it in the next TSC meeting after the nomination"

**Comment by jasnell** [comment]
> One more thing: Less frequent meetings is arguably a community-hostile thing to do. It gives the impression (and in my opinion, will probably result in the reality) that more happens in private conversations and less in the meetings.

I tend to disagree. The more we encourage discussions to happen within GitHub, the better.

If not a monthly schedule, then a meeting every other week sounds good to me.

**Comment by mhdawson** [comment]
I'm also -1 on moving to monthly.  We reduced/eliminated meetings in the release working group and In my opinion that did not benefit engagement and forward progress.  @Trott also makes a lot of good points that I agree.

I am more favorable on cancelling when there is not enough on the agenda, but I agree with @Trott that short meetings can also be effective.

**Comment by mhdawson** [comment]
@jasnell would you like to continue the discussion or are you ok with closing?

**Comment by jasnell** [comment]
I still think there is benefit to moving away from the weekly schedule but given that I appear to be in the minority on that, closing is fine.
