### ISSUE TITLE
Rotating TSC seats

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/TSC#629]
I noticed there are 2-4 seemingly inactive (or as good as) TSC members: they don't join meetings, don't participate on the bug trackers much or at all, etc. That's 10-20% of the TSC body.

Earlier this year (or was it last year?) a more proactive mindset was discussed. Is it an idea to ask them to reconsider their position and rotate in fresh blood?

**Comment by Trott** [comment]
> I noticed there are 2-4 seemingly inactive (or as good as) TSC members: they don't join meetings, don't participate on the bug trackers much or at all, etc. That's 10-20% of the TSC body.

@nodejs/tsc If you feel like maybe this describes you, consider moving yourself to Emeritus. It's always possible to ask to rejoin the TSC if your level of involvement/engagement changes.

**Comment by jasnell** [comment]
It's been a while since we've done an activity check on TSC members. Perhaps it's time?

**Comment by MylesBorins** [comment]
Regarding meeting participation I quickly tallied the attendance from Meetings since July

---

**Comment by MylesBorins** [comment]
I've done a quick tally of meeting attendance since July (last 14 meetings) and you can see it below. No one has dropped below the 25% threshhold as outlined [in our charter](https://github.com/nodejs/TSC/blob/master/TSC-Charter.md#section-4-establishment-of-the-tsc).

> In the case where an individual TSC member -- within any three month period -- attends fewer than 25% of the regularly scheduled meetings, does not participate in TSC discussions, and does not participate in TSC votes, the member shall be automatically removed from the TSC. The member may be invited to continue attending TSC meetings as an observer.

---

Michael Dawson, 13
Rich Trott, 10
Michaël Zasso, 9
Sakthipriyan Vairamani, 9
Сковорода НикитаАндреевич', 8
Matteo Collina, 8
Colin Ihrig, 7
Jeremiah Senkpiel, 7
Rod Vagg, 7
Gabriel Schulhof, 7
Ali IjazSheikh', 6
Joyee Cheung, 6
James MSnell', 6
Franziska Hinkelmann, 6
Anatoli Papirovski, 6
Anna Henningsen, 5
Myles Borins, 5
Timothy Gu, 5
Daniel Bevenius, 4

**Comment by Trott** [comment]
> I noticed there are 2-4 seemingly inactive (or as good as) TSC members: they don't join meetings, don't participate on the bug trackers much or at all, etc. That's 10-20% of the TSC body.

@bnoordhuis It's by no means your responsibility to do this, but perhaps email those 2-4 people privately and suggest that, at least by public appearances, they might do well to consider becoming Emeritus temporarily or indefinitely. Or at least do that if you have a good relationship with them?

> Earlier this year (or was it last year?) a more proactive mindset was discussed. Is it an idea to ask them to reconsider their position and rotate in fresh blood?

Indeed, I proposed something along these lines a little more than a year ago in https://medium.com/@Trott/an-incremental-node-js-governance-proposal-93410320fcff.

I'll step up my own work here, but honestly, it would really be great if it wasn't just me.

**Comment by mhdawson** [comment]
There was a discussion on the TSC emailing list with the result being that there was nobody specific we'd ask to consider stepping down.  I think this can be closed.  Any objections?

**Comment by bnoordhuis** [comment]
No, that sounds fine. I'll go ahead and close this out, then.
