### ISSUE TITLE
Meeting Calendar

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#63]
Somewhere I coming across a post saying that there doesn't see to be much interest in the community WRT community participation during live meetings (based on the lack of IRC activity). I just want to note that there was _some_ participation when io.js did them- I was probably the only one that tuned in for _all_ of them :)

I think the difference was notification/promotion of them. Once the io.js meetings stopped- it took me a long time to realize that these were started again. Perhaps the lack of activity is simply because no one knows about them [and what they offer to the community](https://github.com/nodejs/TSC/issues/60).

Also- where do we find if a group/committee has regular meetings and when they are? [I asked here](https://github.com/nodejs/TSC/issues/57#issuecomment-192174712) and it went unanswered.

Can we get a meeting calendar? (covering all groups/committees) It would be crazy awesome if it was published on the website under "[Get Involved](https://nodejs.org/en/get-involved/)"

**Comment by mikeal** [comment]
Can we please kill the old io.js calendar, i have double meetings for every meeting that is in it :(

**Comment by williamkapke** [comment]
While I wait to find out [the fate of my automation plans](https://github.com/nodejs/build/issues/404)...

I am hereby volunteering to...
1) Post the meeting schedule in the README and keep it up-to-date. (like say "Every other Thurs")
2) Create the meeting issues. @rvagg, I know you're crazy busy- _I'm here to help!_ 👍

**Comment by joshgav** [comment]
Perhaps all WG meetings could go on a shared calendar somehow? For example, the monthly Diag WG meeting will be first Wed. of month prior to CTC meeting (i.e. 12pm Pacific).

**Comment by williamkapke** [comment]
@joshgav That's my dream world! 😃 

I've been keeping [my own public calendar](https://calendar.google.com/calendar/embed?src=kap.co_i17i575te0aes6kaanfjr2e4hs%40group.calendar.google.com&ctz=America/Los_Angeles) for some time now- but I'm a bit behind.

Ideally, I'd automate a calendar (preferably hosted by the NF) using the bot so that when a meeting is added, changed, or even cancelled- it is syncd with a GH issue.

**Comment by nebrius** [comment]
It would also help if all WG meetings are listed on the Node.js Google+ page. We've made some progress on this, but IIRC most WG's still use individual accounts for meetings.

**Comment by mikeal** [comment]
@nebrius we should try to get them all on the G+ and youtube page. If people send me their G+ accounts I can add them to the page.

**Comment by joshgav** [comment]
A couple upcoming ones to add:

- Next Diag WG meeting: https://github.com/nodejs/diagnostics/issues/60
- Next post-mortem WG meeting: https://github.com/nodejs/post-mortem/issues/31

**Comment by williamkapke** [comment]
@joshgav I added those to [my public calendar](https://calendar.google.com/calendar/embed?src=kap.co_i17i575te0aes6kaanfjr2e4hs%40group.calendar.google.com&ctz=America/Los_Angeles) and tried to add you as someone that could change things if you wanted... but I'm not sure Google cared too much for your Microsoft email. heh. I'd love to have a Calendar that people contribute to... whether it's that one or another!

**Comment by joshgav** [comment]
thanks @williamkapke, i had subscribed to your calendar too. can you add `joshgavant AT gmail` instead of my microsoft account? .

i also started listing upcoming meetings at the end of CTC meeting notes, first attempt in https://github.com/nodejs/node/pull/7570

**Comment by williamkapke** [comment]
@joshgav Ok, your gmail account has been added and you should be able to edit events and even add more people!

Also, you may have noticed that I've added some of the bigger Node.js events to the calendar since these often cause absences and/or cancellations of meetings.

> i also started listing upcoming meetings at the end of CTC meeting notes, first attempt in nodejs/node#7570

...nice!

**Comment by joshgav** [comment]
Great, added one more already :)

**Comment by williamkapke** [comment]
Reference to the discussion in today's TSC meeting: https://youtu.be/UXlzfJ9zPIY?t=8m28s

Key Points:
- There is a desire to have an "official" calendar, but needs someone with permission within the Foundation to set it up.
- Automate ALL THE THINGS! :D
- @nebrius Asks to consider something that will work with the ecosystem of Calendar apps out there.

Additionally: Google calendar has the ability to display it to anyone as DHTML. (iframe embeddable). I like having the option to display it on a webpage.

**Comment by jasnell** [comment]
A calendar has been set up. Closing

**Comment by williamkapke** [comment]
Actually, as of yesterday, the Calendar is finally set up.

I will transfer over the current admins and events- then add a year long event that says my personal calendar is obsolete and include a link to the new one.

I will post the new link here once that has been completed.

Bonus task: Add a redirect from https://nodejs.org/calendar to the new calendar!

**Comment by williamkapke** [comment]
This is done. Please switch to the new calendar at your earliest convenience.

**Full URL:**
https://calendar.google.com/calendar/embed?src=nodejs.org_nr77ama8p7d7f9ajrpnu506c98%40group.calendar.google.com

**Shortened URL:**
https://goo.gl/t6jPwI
