### ISSUE TITLE
CANCELLED - Node.js Foundation Technical Steering Committee (TSC) Meeting 2018-11-14

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#630]
# Cancelled based on limited agenda and agreement in issue
* See discussion in comments for details

## Time

**UTC Wed 14-Nov-2018 12:00 (12:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 14-Nov-2018 04:00 (04:00 AM) |
| US / Mountain | Wed 14-Nov-2018 05:00 (05:00 AM) |
| US / Central  | Wed 14-Nov-2018 06:00 (06:00 AM) |
| US / Eastern  | Wed 14-Nov-2018 07:00 (07:00 AM) |
| London        | Wed 14-Nov-2018 12:00 (12:00 PM) |
| Amsterdam     | Wed 14-Nov-2018 13:00 (01:00 PM) |
| Moscow        | Wed 14-Nov-2018 15:00 (03:00 PM) |
| Chennai       | Wed 14-Nov-2018 17:30 (05:30 PM) |
| Hangzhou      | Wed 14-Nov-2018 20:00 (08:00 PM) |
| Tokyo         | Wed 14-Nov-2018 21:00 (09:00 PM) |
| Sydney        | Wed 14-Nov-2018 23:00 (11:00 PM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Technical%20Steering%20Committee%20(TSC)+Meeting+2018-11-14&iso=20181114T12
* or http://www.wolframalpha.com/input/?i=12PM+UTC%2C+Nov+14%2C+2018+in+local+time

## Links

* Minutes Google Doc: <https://docs.google.com/document/d/1u-h3xlUlBsdOfUQX33qPlYe1ZFJ7nTYvSBcbPzKxU7E/edit>

## Agenda

Extracted from **tsc-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/node

* doc: add link to VSCode config in testing [#24012](https://github.com/nodejs/node/pull/24012)
* fs: behaviour of readFile and writeFile with file descriptors [#23433](https://github.com/nodejs/node/issues/23433)

### nodejs/TSC

* Chair for 12pm gmt meeting -volunteer needed [#625](https://github.com/nodejs/TSC/issues/625)
* Tracking issue for updating TSC on Board Meetings [#476](https://github.com/nodejs/TSC/issues/476)
* Strategic Initiatives - Tracking Issue [#423](https://github.com/nodejs/TSC/issues/423)

## Invited

* Anna Henningsen @addaleax (TSC)
* Anatoli Papirovski @apapirovski (TSC)
* Сковорода Никита Андреевич @ChALkeR (TSC)
* Colin Ihrig @cjihrig (TSC)
* Daniel Bevenius @danbev (TSC)
* Franziska Hinkelmann @fhinkel (TSC)
* Gabriel Schulhof @gabrielschulhof (TSC)
* Jeremiah Senkpiel @Fishrock123 (TSC)
* James M Snell @jasnell (TSC)
* Joyee Cheung @joyeecheung (TSC)
* Matteo Collina @mcollina (TSC)
* Michael Dawson @mhdawson (TSC)
* Myles Borins @MylesBorins (TSC)
* Ali Ijaz Sheikh @ofrobots (TSC)
* Rod Vagg @rvagg (TSC)
* Michaël Zasso @targos (TSC)
* Sakthipriyan Vairamani @thefourtheye (TSC)
* Timothy Gu @TimothyGu (TSC)
* Rich Trott @Trott (TSC)

## Notes

The agenda comes from issues labelled with `tsc-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

Zoom link: https://zoom.us/j/611357642
Regular password

## Public participation

We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at **https://www.youtube.com/c/nodejs+foundation/live** when we turn it on. There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and it should show up.

Many of us will be on IRC in #node-dev on Freenode if you'd like to interact, we have a Q/A session scheduled at the end of the meeting if you'd like us to discuss anything in particular. @nodejs/collaborators in particular if there's anything you need from the TSC that's not worth putting on as a separate agenda item, this is a good place for that.

---

**Invitees**

Please use the following emoji reactions in this post to indicate your
availability.

* :+1: - Attending
* :-1: - Not attending
* :confused: - Not sure yet

**Comment by trivikr** [comment]
4am PST is too early for me, but I accept any decision on https://github.com/nodejs/node/pull/24012 as long as developers have a way to find out about editor configs from Node.js core.

**Comment by Trott** [comment]
@trivikr If there's no rush and if you'd rather be able to take part in the conversation, I don't think there'd be any objection to pushing https://github.com/nodejs/node/pull/24012 to the next meeting's agenda. Would you prefer that?

**Comment by Trott** [comment]
@thefourtheye Is https://github.com/nodejs/node/issues/23433 pretty much resolved at this point, and just waiting for the implementation to land? Or is there something for the TSC to decide there?

**Comment by Trott** [comment]
@nodejs/tsc It would seem silly to have to talk about https://github.com/nodejs/TSC/issues/625 at the meeting rather than getting it resolved in GitHub. @mcollina has offered to chair the meetings in that time slot when he is able to. It seems like all that is needed to close that issue is someone else to volunteer to be the back-up chair when @mcollina can't do it. Any volunteers?

As someone who has chaired a fair amount, I can tell you that it is not difficult or time-consuming. YOU CAN DO THIS!!!

**Comment by Trott** [comment]
While we're at it, I'd like to prod strategic initiative and board updates to be something that get done in advance. Leave a comment here and it can be read at the meeting and copy/pasted into the minutes. And then the update happens even if you don't make it to the meeting. HOW COOL IS THAT??!!

**Comment by trivikr** [comment]
@Trott There's no rush, and https://github.com/nodejs/node/pull/24012 can be pushed to next week.

**Comment by mhdawson** [comment]
We can push out #625 if its the only thing left on the agenda.

**Comment by mhdawson** [comment]
+1 for pushing out  nodejs/node#24012, unless anybody objects I'll remove from this weeks agenda tomorrow.

**Comment by Trott** [comment]
Looks like we can cancel this meeting. Would still be useful/good IMO if standing issue updates could be placed here.

**Comment by mhdawson** [comment]
Ok, I'm good to cancel :).  Going to close but if people could update the minutes with the updates for the board update/strategic initiatives update I'll capture the minutes and add into the repo along with an indication that the actual meeting was canceled.

I'm going to leave the issue open until we do that, but will update to show as cancelled.

**Comment by mhdawson** [comment]
What do people think about removing the calendar entry? I can't quite decide if it is better to leave it in or remove it.

**Comment by mcollina** [comment]
Better remove it I presume.

Il giorno mar 13 nov 2018 alle ore 22:52 Michael Dawson <
notifications@github.com> ha scritto:

**Comment by mhdawson** [comment]
ok removed for now.

**Comment by mcollina** [comment]
+1 to cancel

Il giorno mar 13 nov 2018 alle 22:44 Michael Dawson <
notifications@github.com> ha scritto:

**Comment by mhdawson** [comment]
I don't see any updates beyond N-API in the minutes so I'm not sure it's worth capturing them.  Will leave for another day or so and if there are no updates just close.

**Comment by targos** [comment]
I added my update:

* V8 currency
    * Ongoing work to improve node-core-utils command for V8 backports.
    * Onboarded @ryzokuken to help to keep the canary branch up-to-date

**Comment by thefourtheye** [comment]
Moderation Team Update:

1. A comment was hidden (https://github.com/nodejs/moderation/issues/247)

@nodejs/tsc @nodejs/community-committee @nodejs/moderation
