### ISSUE TITLE
Node.js Foundation Node.js Foundation Technical Steering Committee (TSC) Meeting 2018-12-12

### ISSUE THREAD

**Issue by mcollina** [nodejs/TSC#639]
## Time

**UTC Mer 12-Dic-2018 16:00 (04:00 pm)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 12-Dic-2018 08:00 (08:00 am) |
| US / Mountain | Wed 12-Dic-2018 09:00 (09:00 am) |
| US / Central  | Wed 12-Dic-2018 10:00 (10:00 am) |
| US / Eastern  | Wed 12-Dic-2018 11:00 (11:00 am) |
| London        | Wed 12-Dic-2018 16:00 (04:00 pm) |
| Amsterdam     | Wed 12-Dic-2018 17:00 (05:00 pm) |
| Moscow        | Wed 12-Dic-2018 19:00 (07:00 pm) |
| Chennai       | Wed 12-Dic-2018 21:30 (09:30 pm) |
| Hangzhou      | Thu 13-Dic-2018 00:00 (12:00 am) |
| Tokyo         | Thu 13-Dic-2018 01:00 (01:00 am) |
| Sydney        | Thu 13-Dic-2018 03:00 (03:00 am) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Node.js%20Foundation%20Technical%20Steering%20Committee%20(TSC)+Meeting+2018-12-12&iso=20181212T16
* or http://www.wolframalpha.com/input/?i=04pm+UTC%2C+Dic+12%2C+2018+in+local+time

## Links

* **Minutes Google Doc**: <https://docs.google.com/document/d/1_oV7J1F6VbNtBbKDzJfD3JuiA_MkQWBzGbWiSYioHBY/edit?usp=sharing>
* _Previous Minutes Google Doc: <https://docs.google.com/document/d/1zllgnvztB0FarZXFOmn3AnfTOZxpcS-lcLlmE2QDnXg/edit>_

## Agenda

Extracted from **tsc-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/node

* cli: add --max-http-header-size flag [#24811](https://github.com/nodejs/node/pull/24811)
* Fixing child_process module to check values passed strictly to the options object [#24267](https://github.com/nodejs/node/pull/24267)

### nodejs/nodejs.org

* Re-enstate link to NiM in debug documentation. [#1923](https://github.com/nodejs/nodejs.org/issues/1923)

### nodejs/TSC

* Tracking issue for updating TSC on Board Meetings [#476](https://github.com/nodejs/TSC/issues/476)
* Strategic Initiatives - Tracking Issue [#423](https://github.com/nodejs/TSC/issues/423)

### nodejs/community-committee

* Travel Fund Updates [#426](https://github.com/nodejs/community-committee/issues/426)
* Node Store Launch [#425](https://github.com/nodejs/community-committee/issues/425)

## Invited

* Anna Henningsen @addaleax (TSC)
* Anatoli Papirovski @apapirovski (TSC)
* Сковорода Никита Андреевич @ChALkeR (TSC)
* Colin Ihrig @cjihrig (TSC)
* Daniel Bevenius @danbev (TSC)
* Franziska Hinkelmann @fhinkel (TSC)
* Gabriel Schulhof @gabrielschulhof (TSC)
* Jeremiah Senkpiel @Fishrock123 (TSC)
* James M Snell @jasnell (TSC)
* Joyee Cheung @joyeecheung (TSC)
* Matteo Collina @mcollina (TSC)
* Michael Dawson @mhdawson (TSC)
* Myles Borins @MylesBorins (TSC)
* Ali Ijaz Sheikh @ofrobots (TSC)
* Rod Vagg @rvagg (TSC)
* Michaël Zasso @targos (TSC)
* Sakthipriyan Vairamani @thefourtheye (TSC)
* Tracy Lee @ladyleet (Node.js Foundation)

## Notes

The agenda comes from issues labelled with `tsc-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

Zoom link: https://zoom.us/j/611357642
Regular password

## Public participation

We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at **https://www.youtube.com/c/nodejs+foundation/live** when we turn it on. There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and it should show up.

Many of us will be on IRC in #node-dev on Freenode if you'd like to interact, we have a Q/A session scheduled at the end of the meeting if you'd like us to discuss anything in particular. @nodejs/collaborators in particular if there's anything you need from the TSC that's not worth putting on as a separate agenda item, this is a good place for that.

---

**Invitees**

Please use the following emoji reactions in this post to indicate your
availability.

* :+1: - Attending
* :-1: - Not attending
* :confused: - Not sure yet

**Comment by mcollina** [comment]
@thefourtheye fixed! Seems that make-node-meeting generates times in whatever locale is set!

**Comment by mhdawson** [comment]
Not sure why the meeting was not auto generated. Good to see Matteo created it. Back home but its late so I'll check tomorrow.

**Comment by mhdawson** [comment]
I'll be at the meeting but @mcollina happy to have you chair anyway.

**Comment by MylesBorins** [comment]
I may not be able to make it tomorrow as I'll be in ECMA meetings

https://github.com/nodejs/node/pull/24811 I'm +1 on landing and added comments in thread
https://github.com/nodejs/node/pull/24267 I have no opinion at this time

https://github.com/nodejs/TSC/issues/476 Board meeting is on Thursday, will have a full update afterwards.

## strategic initiatives update
> https://github.com/nodejs/TSC/issues/423

### Modules

Quite a bit of discussion happening right now in two break out proposals

https://github.com/GeoffreyBooth/node-import-file-specifier-resolution-proposal

A proposal to utilize metadata to determine the module type of a package allowing for us to support importing both esm and cjs modules.

https://github.com/jkrems/proposal-pkg-exports/

An alternative approach to the current Node.js resolution algorithm. Meta Data in package.json would be used to identify exports. Compatible with [import-map proposal](https://github.com/domenic/import-maps/)

### Governance

We started a project board to track responsibilities of various stakeholders within the proposed foundation. We will be using this artifact to help determine how many Top-Level committees there will be and what they will be responsible for.

https://github.com/nodejs/bootstrap/projects/1

### Open Web Standards

https://github.com/nodejs/node/pull/21551

Introducing a namespace to node. This has implications to other runtimes.

https://github.com/nodejs/node/issues/24894

Dynamic Modules proposal. This proposal would allow spec compliant named imports from CJS modules. TC39 and V8 want to ensure we have consensus within node before changes can land upstream. If you have concerns please raise them before next Wednesday (next modules team meeting)

**Comment by Fishrock123** [comment]
Feeling a bit unwell, gona try to get some extra sleep. Sorry folks.

**Comment by gabrielschulhof** [comment]
Bit of a rough night 😕 ... I've repeated my [comment](https://github.com/nodejs/node/pull/24267#pullrequestreview-184159754) from last week re https://github.com/nodejs/node/pull/24267 on the issue as well.

**Comment by addaleax** [comment]
(Sorry, I got kicked out repeatedly because of connection issues :/)

**Comment by mhdawson** [comment]
PR for minutes: https://github.com/nodejs/TSC/pull/640

**Comment by thefourtheye** [comment]
Moderation Team Updates:

No significant events this week.

@nodejs/tsc @nodejs/community-committee @nodejs/moderation
