### ISSUE TITLE
Delay in the live meeting stream leaves participants in prev meeting 

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#64]
Example:
- View arrives at 10AM sees title of whatever was the previous live stream.
- After "private business" is done, they start the live stream.
- The title, comments, description of the live stream remains as the previous event.

User can refresh to get it to update. If they do not, comments will go to old video.

**Comment by Fishrock123** [comment]
Noted, I'll need to test if I can update that without going live briefly or not.

**Comment by williamkapke** [comment]
@Fishrock123 , I'm sure you did test this. What did you find out? Maybe you already documented it someone. 

I think I've noticed the stream title change at the top of the hour. Can we close this?

**Comment by Fishrock123** [comment]
If you edit it beforehand it seems to save it. Youtube streaming is still in Beta so I'd say it was probably a Beta bug.
