### ISSUE TITLE
Override objection in https://github.com/nodejs/node/pull/24938

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#646]
We discussed https://github.com/nodejs/node/pull/24938 in the last meeting with no objections from the TSC to landing as is.    

Before allowing it to land we agreed to ask Brian if there was additional comments/info he wanted to add or if he wanted to come to a TSC meeting to discuss further.  He commented in the issue that he did not have more to add.

We discussed in the TSC meeting today, again there were no objections to it landing as is, but we did not have TSC members to confirm consensus had been reached.  @nodejs/tsc please comment if you object (confirmation that you agree it can land is also good) otherwise I'll comment in the issue that the TSC has agreed it can land despite the objection.

**Comment by mcollina** [comment]
+1 to land.

**Comment by ofrobots** [comment]
+1 to land.

**Comment by ChALkeR** [comment]
+1 to land.

**Comment by targos** [comment]
+1 to land

**Comment by danbev** [comment]
+1 to land

ons 2 jan. 2019 kl. 19:43 skrev Michaël Zasso <notifications@github.com>:

**Comment by awardrop** [comment]
+1 land as-is

**Comment by gabrielschulhof** [comment]
+1 to land.

**Comment by MylesBorins** [comment]
+1 to land
