### ISSUE TITLE
Nominating @trott to rejoin the TSC.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#650]
@Trott has indicated he's ready to rejoin the TSC and I'd like to nominate him to rejoin the TSC after his short break.

As always he's been active in keeping our CI green as well as submitting a large number of PRs to core and participating in Working Groups.

**Comment by mcollina** [comment]
+1!

**Comment by cjihrig** [comment]
+1

**Comment by danbev** [comment]
+1

**Comment by targos** [comment]
+1

**Comment by fhinkel** [comment]
+1

**Comment by apapirovski** [comment]
+1

**Comment by addaleax** [comment]
+1

**Comment by ChALkeR** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by thefourtheye** [comment]
+1

**Comment by mhdawson** [comment]
Looks like we have more than 50% already in agreement and no objections so I suggest Rich attends the next meeting and we conclude this motion/vote at that point.

**Comment by mhdawson** [comment]
If I count correctly I think we have 13/17 members who have voted yes and 0 objections so I think we can consider this closed unless there are objections up until or in the TSC meeting tomorrow.

**Comment by mhdawson** [comment]
There were no objections in the meeting today so the vote is concluded.  Welcome back @Trott.  I've opened https://github.com/nodejs/node/pull/25535 to add you back to the TSC list.

**Comment by mhdawson** [comment]
I've added you back to the TSC team.

**Comment by mhdawson** [comment]
PR to add back to email aliases: https://github.com/nodejs/email/pull/130

**Comment by Trott** [comment]
Can someone please add me back to the relevant GitHub teams here and in the private repo? For here, I'm pretty sure it's `@nodejs/TSC` and `@nodejs/security-tsc`. In the private repo, it's `security-tsc` and I think that's it.

**Comment by mcollina** [comment]
Done.
