### ISSUE TITLE
Code of Conduct requirements under Merged Foundation

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#663]
The requirements for a Code of Conduct on projects under a merged Foundation are being discussed in this issue: https://github.com/nodejs/bootstrap/pull/80.

In it's current form it would require that the Node.js project delegate the escalation process to the Foundation level and use a common Code of Conduct.  I believe the proposed common Code  of Conduct is in alignment with what we already do (or close enough not to be a concern).

A number of TSC members have already chimed into the discussion. Based on discussion in the private section of the last TSC meeting we agreed that wewe want to make sure we have TSC consensus that the proposed approach will be acceptable to use as a group.

I'd ask the following:

* Review https://github.com/nodejs/bootstrap/pull/80 and add any comments/suggestion/concerns that you have

* Respond on this issue with
  *  +1 if you think it is an acceptable approach for the project to accept,=
  * an indication that you would like to abstain
  * an objection (with details would be great, ideally a link to comments on https://github.com/nodejs/bootstrap/pull/80)

Based on the results we'll flow that feedback into the discussion on https://github.com/nodejs/bootstrap/pull/80

@nodejs/tsc

**Comment by mhdawson** [comment]
+1

**Comment by MylesBorins** [comment]
+1

**Comment by mcollina** [comment]
I don't think the wording on this issue is 100% clear.  As that proposal is spelled out, the TSC will still be responsible for the code of conduct within the project itself. However, there will be a higher, shared group to handle situations that could not be resolved within a project.

I'm +1 for that proposal.

**Comment by cjihrig** [comment]
+1

**Comment by Trott** [comment]
+1

**Comment by ofrobots** [comment]
+1

**Comment by apapirovski** [comment]
+1

**Comment by danbev** [comment]
+1

**Comment by thefourtheye** [comment]
+1

**Comment by jasnell** [comment]
+1

**Comment by targos** [comment]
Abstain

**Comment by gabrielschulhof** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by fhinkel** [comment]
+1

**Comment by addaleax** [comment]
+1

**Comment by mhdawson** [comment]
Summary of the input so far based on current TSC membersip:

+1                  13
Abstain         1 
-1                   0
No answer:   3

**Comment by MylesBorins** [comment]
+1

**Comment by mhdawson** [comment]
@Myles you had already chimed in:), Github may have just hidden it.

In any case going to close.  We had many +1s, no objections and the PR has now landed.
