### ISSUE TITLE
V8 - TSC meeting

### ISSUE THREAD

**Issue by hashseed** [nodejs/TSC#667]
We've had a meeting between the TSC and select members of the V8 teams twice before, with good results. We haven't done this in the recency since I had the feeling that there was quite some communication through conferences.

Nevertheless I want to bring up the idea of another such meeting. Before I set up any Doodle though, I'd like to gauge interest.

Topics I currently have in mind:

* JITless V8
* Pointer compression
* Requiring Clang in the long term?
* Build system of the future
* WebAssembly and Node.js
* Future of Node.js infrastructure
* Post-mortem debugging ideas
* Tracing and Perfetto
* Source map support?
* Performance bottlenecks?
* Signals V8 should expose.

I'm open to suggestions!

[Doodle](https://doodle.com/poll/y4627ybqs5isizit) for finding a date.

**Comment by mcollina** [comment]
Definitely +1.

I think we should keep Tracing, Perfetto and post-mortem to the diagnostics wg, and maybe talk about them in person at the summit?

I would focus on build system, performance, webassembly, and infra.

**Comment by mhdawson** [comment]
+1 from me.  A heads up on Tracing, Perfetto and post-mortem might still make sense but that they still need to be covered in the Diagnostics WG.

**Comment by cjihrig** [comment]
Sounds like a good idea to me. +1

**Comment by joyeecheung** [comment]
+1. I agree that we can talk about the diagnostics-related items in the diagnostics summit, in case we go over time too much with the topics in one meeting.

**Comment by apapirovski** [comment]
+1 from me.

**Comment by targos** [comment]
+1

**Comment by thefourtheye** [comment]
+1

**Comment by hashseed** [comment]
I'll try to set up a Doodle soon. Expect the meeting to be before March 22, because that's when I go on vacation for five weeks :)

**Comment by indutny** [comment]
+1 (I'd love to join)

**Comment by devsnek** [comment]
if non-tsc can join i'm also +1

**Comment by hashseed** [comment]
I have no opinion on whether non-TSC should join tbh.

**Comment by rvagg** [comment]
I think this should be open to collaborators to get as many people who are interested in this intersection as possible engaged. Sounds like @nodejs/build has a couple of items in there too.

**Comment by mhdawson** [comment]
+1 to what @rvagg mentioned. Worth getting as broad as input as possible.

**Comment by hashseed** [comment]
I set up a [Doodle](https://doodle.com/poll/y4627ybqs5isizit) for the next week. Sorry that I haven't taken care of this earlier.

**Comment by mcollina** [comment]
Unfortunately I have no availability for next week (I'm traveling).

**Comment by apapirovski** [comment]
Giving a little more notice would probably be good so more people can attend.

**Comment by hashseed** [comment]
In that case we'll have to wait until after April 26th... I'll be on vacation from March 22nd until then. Unless someone else organizes it?

I'd be fine with end of April or early May too.

**Comment by hashseed** [comment]
I'm going to wait till Friday evening to see which date works best. For those who are interested but cannot attend, I will record the meeting, and show up in Berlin for the next Collaborator Summit. I hope that works for everyone.

**Comment by hashseed** [comment]
Unless there are strong objections, I'd like to set the meeting to 2019-03-21, 8pm CET, or US/Pacific noon. The attendance is a bit less than I had hoped, but for the topics I proposed we probably have a good set of people for discussion. Anyone is welcome to join.

VC link: https://meet.google.com/bsc-uyie-xdz

**Comment by hashseed** [comment]
Reminder that this will happen in about 9 hours from now.

**Comment by apapirovski** [comment]
@hashseed any chance we have a recording or notes from this meeting?

**Comment by hashseed** [comment]
Yes. Sorry. I took some notes, and there are recordings.

@MylesBorins asked me to not release the recordings yet due to some things that will be announced today? Once Myles gives me his OK, I'll paste the link :)

**Comment by hashseed** [comment]
This is the announcement I was waiting for: https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/

Here are recordings and notes: https://drive.google.com/folderview?id=1hkvFJhYqP9DCIKEDFx9CT9xyMsOPwCuf

**Comment by mhdawson** [comment]
@hashseed can this issue be closed now that the meeting took place?

**Comment by apapirovski** [comment]
Thanks @hashseed!
