### ISSUE TITLE
30 Day Reports (Sample)

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#67]
I've been working on some code to pull out all the relevant information about the activity in repo. The idea is that we can run this org wide and get a good high level view of what has been going on.

I've run the code over this TSC repo, it's activity is relatively low compared to some other repos so it's a good test dataset. I'd like to know what people of the numbers and anything else we'd like to see.

In the last 30 days there were:
- **14** issues were created. **10 (%250)** over previous 30 days (4 total).
  - **8** were created by commiters, **6** by contributors.
  - **2 / 2 (%50)** commiter to contrib ratio, compared to **0 / 3 (%0)** over previous 30 days.
- **3** issues/pulls were closed. **2 (%200)** over previous 30 days (1 total).
  - **2** were created by commiters, **1** by contributors.
  - **1 / 2 (%33)** commiter to contrib ratio, compared to **0 / 1 (%0)** over previous 30 days.
- **5** pulls were created. **-1 (%-17)** over previous 30 days (6 total).
  - **3** were created by commiters, **2** by contributors.
  - **2 / 1 (%67)** commiter to contrib ratio, compared to **1 / 3 (%25)** over previous 30 days.
- **96** issue comments were created. **-167 (%-63)** over previous 30 days (263 total).
  - **73** were created by commiters, **23** by contributors.
  - **8 / 7 (%53)** commiter to contrib ratio, compared to **27 / 9 (%75)** over previous 30 days.

**Comment by Fishrock123** [comment]
@mikeal WHy not just use https://github.com/nodejs/TSC/pulse/monthly ?

**Comment by Fishrock123** [comment]
Oh I guess you want Contributor / Committer stats

**Comment by mikeal** [comment]
@Fishrock123 Pulse doesn't have a lot of this. It doesn't show issue comments nor does it give any information about whether or not the people involved are committers. There's also a lot of data I'm not showing yet that we could show: assignments, issues labels, referenced issues, issue locks, mentions, subscriptions, etc.

**Comment by mikeal** [comment]
Eventually I plan on bringing in more of the code data as well. We can show who is writing code and merging code and we could potentially show that across the org rather than just a single repo.

**Comment by mikeal** [comment]
Here's a new sample. I ran this one the Node.js Core repo so there's significantly more data. I also added in some more metrics.

* **468** issues were created. **290 (%163)** over previous 30 days (178 total).
 * **110** were created by commiters, **358** by contributors.
 * **233 / 26 (%90)** active contributors to committer ratio, compared to **138 / 10 (%93)** over previous 30 days.
 * Commiters: rvagg, TheAlphaNerd, fansworld-claudio, phillipj, vkurchatkin, indutny, benjamingr, cjihrig, mscdex, ChALkeR, targos, mhdawson, JungMinu, matthewloring, Trott, evanlucas, shigeki, mikeal, AndreasMadsen, orangemocha, calvinmetcalf, geek, Fishrock123, bnoordhuis, silverwind, whitlockjc
 * Contributors: feross, tflanagan, danielsan, littledan, MichaelTheriot, estliberitas, eljefedelrodeodeljefe, JacksonTian, heroboy, richardlau, drjokepu, kunalspathak, santigimeno, Nibbler999, sgentle, rluba, wKich, kevinoid, garrows, mattoshry, Nicholasny, felixfbecker, dcposch, obastemur, drewfish, Jimbly, TimothyGu, jgeewax, jiripospisil, Cangit, Corey600, orgkhnargh, agl, weinand, strrchr, lumberj, kthelgason, dj-hedgehog, jackzzjack, entertainyou, mindruptive, focusaurus, piepmatz, infusion, pra85, Necromos, gibm, sdayan, raineroviir, ncopa, SetTrend, SudershanReddy, ojss, imyller, Hanul, braydonf, juliepagano, BridgeAR, bennosom, SukharevAndrey, sidorares, samrm111, princejwesley, BrighTide, NoahRoseLedesma, TriAnMan, iliakan, acrazing, bleachisback, Avinash-Raj, stefanmb, cjthompson, dirceu, uy0101, QianJin2013, mrs2, leaves4j, T94T, quaidn, thomasthiebaud, erandakaanupama, igorklopov, akoskm, nmellempudi, dimhotepus, 3y3, zoubin, praveen-sambu, terinjokes, MrOutput, djErock, tristanls, d3x0r, ORESoftware, chinedufn, taylorhakes, tallskog, mikemaccana, t0lkman, irbull, egasimus, yjhjstz, emps, udaysurendra, mpyw, zxqfox, istr, mjcuva, jelmd, jacobp100, danielmurray, mpotra, sudhanshudahiya, andrewmash, ikon225, jhamhader, saeidalidadi, hgwood, ralt, crh3675, kaero, tomaspinho, silentroach, jray319, Kosti1, waynedpj, franz-josef-kaiser, KiYugadgeter, simone-sanfratello, jmm, Tobias-Zwick, glenholmes, pinggod, modao, nettofarah, fhemberger, 4kochi, egoroof, greg-js, tunnckoCore, tombell, mafintosh, ronkorving, Shambhavi, pranaydutta89, Delagen, riskfaktor, mrstrong184, Sequoia, STRML, simran66, calidion, Hsinky, SeekTheError, roman-io, jefftham, ganna-shmatova, qhduan, frickt, chrisdew, franky-continu, abdulrashid9, dnalborczyk, Zarel, cyberphone, julienw, NikosEfthias, zbinlin, nuintun, fanatid, c-f-h, omsmith, abenhamdine, surdu, kirked, billautomata, DungarMT, truunk, zhe13, firedfox, zdebyman, callumlocke, julianusti, cdai2, strawbrary, lance, Dzenly, varunavashia, robertchiras, arnav-gudibande, coolaj86, martinkuba, mike182uk, msmosso, nowis-st, Mizanurrahman2010, WebReflection, pmuellr, FreakinaBox, ccorcos, raiha7, piranna, figliohulio, polybuildr, artynet, schmelter-sap, AceMood, be-dcodeit, tarun-batra, Ravoltz, BrightLamp, RWOverdijk, sbdchd, vsemozhetbyt, mysticatea, axvm, therewillbecode, WhyEvenTry, pavelzaruba, dannymarsland, nevir, OmarHallab, stevemao, tdecaluwe, fpmalard, dmitryame, bmeck, rurigk, erg0dic, antipath, gnash48, luoziyong, pabigot
* **388** closed were created. **-67 (%-15)** over previous 30 days (455 total).
 * **350** were created by commiters, **38** by contributors.
 * **35 / 34 (%51)** active contributors to committer ratio, compared to **39 / 34 (%53)** over previous 30 days.
 * Commiters: chrisdickinson, indutny, TheAlphaNerd, bnoordhuis, Trott, mscdex, jasnell, vkurchatkin, silverwind, ChALkeR, evanlucas, srl295, cjihrig, trevnorris, mhdawson, rvagg, romankl, Fishrock123, targos, orangemocha, zkat, ofrobots, mcollina, micnic, brendanashworth, geek, phillipj, shigeki, AndreasMadsen, calvinmetcalf, matthewloring, whitlockjc, benjamingr, fansworld-claudio
 * Contributors: T94T, heroboy, MrOutput, d3x0r, tomgco, domosapien, yjhjstz, mpyw, strrchr, irbull, Kosti1, tomaspinho, pinggod, modao, tunnckoCore, ganna-shmatova, sambthompson, NikosEfthias, mnkhouri, billautomata, julianusti, eljefedelrodeodeljefe, arnav-gudibande, dcposch, nowis-st, richardlau, ccorcos, raiha7, figliohulio, vsemozhetbyt, therewillbecode, WebReflection, rurigk, ch-acctg, iliakan
* **10** assignments were created. **-17 (%-63)** over previous 30 days (27 total).
 * **10** were created by commiters, **0** by contributors.
 * **0 / 5 (%0)** active contributors to committer ratio, compared to **0 / 10 (%0)** over previous 30 days.
 * Commiters: srl295, trevnorris, mcollina, mhdawson, Trott
* **1144** labels were created. **-32 (%-3)** over previous 30 days (1176 total).
 * **1144** were created by commiters, **0** by contributors.
 * **0 / 33 (%0)** active contributors to committer ratio, compared to **0 / 33 (%0)** over previous 30 days.
 * Commiters: silverwind, mscdex, TheAlphaNerd, rvagg, jasnell, ChALkeR, ofrobots, trevnorris, bnoordhuis, Trott, zkat, romankl, thefourtheye, indutny, orangemocha, mhdawson, srl295, Fishrock123, targos, vkurchatkin, evanlucas, mcollina, micnic, sam-github, saghul, cjihrig, othiym23, jbergstroem, joaocgreis, brendanashworth, thekemkid, AndreasMadsen, fansworld-claudio
* **218** subscriptions were created. **4 (%2)** over previous 30 days (214 total).
 * **208** were created by commiters, **10** by contributors.
 * **9 / 30 (%23)** active contributors to committer ratio, compared to **15 / 28 (%35)** over previous 30 days.
 * Commiters: trevnorris, chrisdickinson, jasnell, misterdjules, thlorenz, zkat, rvagg, Fishrock123, seishun, tunniclm, indutny, cjihrig, mscdex, othiym23, geek, srl295, ofrobots, orangemocha, targos, TheAlphaNerd, mikeal, thefourtheye, bnoordhuis, rmg, joaocgreis, silverwind, shigeki, benjamingr, evanlucas, jbergstroem
 * Contributors: rdodev, tomgco, kthelgason, snostorm, DavidTPate, bnb, ryansobol, eljefedelrodeodeljefe, stevemao
* **1743** mentions were created. **-754 (%-30)** over previous 30 days (2497 total).
 * **1379** were created by commiters, **364** by contributors.
 * **179 / 50 (%78)** active contributors to committer ratio, compared to **302 / 53 (%85)** over previous 30 days.
 * Commiters: chrisdickinson, seishun, zkat, bnoordhuis, ChALkeR, jasnell, vkurchatkin, TheAlphaNerd, targos, jbergstroem, rvagg, petkaantonov, indutny, Trott, cjihrig, benjamingr, srl295, orangemocha, mscdex, saghul, AndreasMadsen, domenic, trevnorris, shigeki, thefourtheye, sam-github, silverwind, isaacs, mikeal, Fishrock123, evanlucas, joaocgreis, tellnes, mcollina, micnic, ofrobots, piscisaureus, mhdawson, Qard, phillipj, misterdjules, geek, calvinmetcalf, julianduque, matthewloring, othiym23, iarna, brendanashworth, fansworld-claudio, thekemkid
 * Contributors: jelmd, drjokepu, dcposch, ronkorving, dave, dherman, leaves4j, ncopa, thomasthiebaud, fbender, tflanagan, chrisdopuch, kikijhu, piranna, santigimeno, leonaves, staltz, jadbox, kittens, geppy, phpnode, bjouhier, ojss, dimhotepus, jiripospisil, jfhbrook, pesho, igorklopov, MrOutput, djErock, flow, fl0w, silentroach, Zarel, mikemorris, drewfish, feross, d3x0r, lordjabez, Zirak, sdayan, kthelgason, mikemaccana, SetTrend, PIC-27, czb, dotnetCarpenter, gireeshpunathil, LinusU, mafintosh, t0lkman, mtbrandy, mathiask88, tallskog, ORESoftware, algesten, rainabba, stefanmb, GregWoods, taylorhakes, cdai2, braydonf, STRML, princejwesley, JacksonTian, alvinlin123, eljefedelrodeodeljefe, Jameskmonger, emazzu, mpotra, littledan, felixonmars, ericmdantas, estliberitas, jhamhader, jsha, danielsan, jacobp100, ralt, franz-josef-kaiser, hsablonniere, bricss, dnakamura, BridgeAR, hg, nebrius, fhemberger, remixz, hashseed, raszi, gibm, tunnckoCore, egoroof, kahwee, s3ththompson, webertlima, tomgco, jrit, davepacheco, Sequoia, sudhanshudahiya, techjeffharris, tlivings, Hsinky, pranaydutta89, eggggger, designfrontier, jefftham, qhduan, Slayer95, a0viedo, repenaxa, dougwilson, jkrems, omsmith, ch-acctg, mnkhouri, jorangreef, waynedpj, abenhamdine, dnalborczyk, aayn, kirked, nettofarah, Skywalker13, DungarMT, piccoloaiutante, truunk, Rantanen, zdebyman, nyaaao, obastemur, surdu, lekkas, richardlau, dman777, skilledDeveloper, msmosso, mike182uk, YuriSolovyov, yoavaa, mgol, rafaelcastrocouto, XadillaX, trendsetter37, Ravoltz, alexjeffburke, simonkcleung, Amunu, Corey600, waynebloss, zeusdeux, pmuellr, NikosEfthias, italoag, tberthe, vsemozhetbyt, WhyEvenTry, sbdchd, williamkapke, yjhjstz, jfromaniello, joshgav, AceMood, pavelzaruba, bpasero, fengmk2, stevemao, fpmalard, WebReflection, dmitryame, bmeck, jmm, therewillbecode, entertainyou, Somebi, reqshark, dannymarsland, coolaj86
* **37** merged were created. **10 (%37)** over previous 30 days (27 total).
 * **37** were created by commiters, **0** by contributors.
 * **0 / 12 (%0)** active contributors to committer ratio, compared to **0 / 8 (%0)** over previous 30 days.
 * Commiters: trevnorris, bnoordhuis, evanlucas, TheAlphaNerd, cjihrig, rvagg, Fishrock123, sam-github, ofrobots, jbergstroem, joaocgreis, thekemkid
* **16** milestoned were created. **14 (%700)** over previous 30 days (2 total).
 * **16** were created by commiters, **0** by contributors.
 * **0 / 6 (%0)** active contributors to committer ratio, compared to **0 / 2 (%0)** over previous 30 days.
 * Commiters: targos, silverwind, Fishrock123, mcollina, rvagg, mscdex

**Comment by mikeal** [comment]
I'm pretty sure the issue create count is both issues and pull requests. I'll have to find a good way to differentiate later.

**Comment by mikeal** [comment]
Here's the processed JSON I use for the report, in case anyone wants to build on it. https://github.com/mikeal/contribution-reports/blob/master/samples/core.json

All the code is here https://github.com/mikeal/contribution-reports

**Comment by Fishrock123** [comment]
> 16 milestoned were created.

Should that be "commits with milestones", or "commits assigned to a milestone"? We've only created 2 milestones recently.

**Comment by mikeal** [comment]
it's actually the number of times a milestone was added to something.

**Comment by mikeal** [comment]
Here's the first view I've taken of the top people being active org wide.

I'm still figuring out exactly what a "pull" is as an event type.

* Top total:
 * TheAlphaNerd (**993**)
 * rvagg (**818**)
 * jasnell (**767**)
 * bnoordhuis (**744**)
 * Trott (**721**)
 * mscdex (**700**)
 * Fishrock123 (**619**)
 * chrisdickinson (**457**)
 * trevnorris (**456**)
 * indutny (**433**)
* Top issues:
 * Trott (**134**)
 * TheAlphaNerd (**60**)
 * rvagg (**51**)
 * mhdawson (**32**)
 * mscdex (**27**)
 * estliberitas (**22**)
 * outsideris (**22**)
 * jasnell (**22**)
 * benjamingr (**20**)
 * bnoordhuis (**19**)
* Top closed:
 * bnoordhuis (**69**)
 * Trott (**56**)
 * TheAlphaNerd (**50**)
 * silverwind (**48**)
 * rvagg (**48**)
 * jasnell (**42**)
 * mhdawson (**25**)
 * evanlucas (**24**)
 * cjihrig (**23**)
 * taggon (**21**)
* Top pulls:
 * TheAlphaNerd (**6**)
 * fhemberger (**5**)
 * chrisdickinson (**3**)
 * mikeal (**3**)
 * jianchun (**2**)
 * kunalspathak (**2**)
 * Trott (**2**)
 * mhdawson (**2**)
 * jlipps (**1**)
 * dherman (**1**)
* Top locks:
 *
* Top assignments:
 * taggon (**11**)
 * napiera (**5**)
 * mhdawson (**5**)
 * chrisdickinson (**3**)
 * chorrell (**3**)
 * mcollina (**2**)
 * trevnorris (**2**)
 * Fishrock123 (**2**)
 * jianchun (**2**)
 * yous (**2**)
* Top labels:
 * mscdex (**337**)
 * TheAlphaNerd (**329**)
 * Trott (**178**)
 * jasnell (**154**)
 * ChALkeR (**123**)
 * Fishrock123 (**78**)
 * bnoordhuis (**53**)
 * silverwind (**37**)
 * taggon (**27**)
 * rvagg (**26**)
* Top subscriptions:
 * rvagg (**399**)
 * bnoordhuis (**362**)
 * jasnell (**360**)
 * TheAlphaNerd (**297**)
 * Fishrock123 (**297**)
 * trevnorris (**273**)
 * indutny (**244**)
 * Trott (**215**)
 * chrisdickinson (**210**)
 * mscdex (**209**)
* Top mentions:
 * rvagg (**194**)
 * bnoordhuis (**186**)
 * jasnell (**164**)
 * TheAlphaNerd (**158**)
 * Fishrock123 (**147**)
 * trevnorris (**128**)
 * mscdex (**115**)
 * Trott (**115**)
 * indutny (**110**)
 * mikeal (**84**)
* Top merged:
 * TheAlphaNerd (**14**)
 * bnoordhuis (**11**)
 * rvagg (**11**)
 * taggon (**10**)
 * chorrell (**10**)
 * mikeal (**10**)
 * stevemao (**8**)
 * hg (**8**)
 * cjihrig (**5**)
 * JungMinu (**5**)
* Top milestoned:
 * Fishrock123 (**13**)
 * silverwind (**5**)
 * targos (**2**)
 * mscdex (**1**)
 * rvagg (**1**)
 * mcollina (**1**)
* Top issue_comments:
 * benjamingr (**95**)
 * rvagg (**75**)
 * chrisdickinson (**72**)
 * TheAlphaNerd (**71**)
 * bmeck (**69**)
 * mikeal (**67**)
 * petkaantonov (**65**)
 * mhdawson (**63**)
 * orangemocha (**52**)
 * Fishrock123 (**48**)
* Top pull_comments:
 * yous (**66**)
 * chrisdickinson (**52**)
 * benjamingr (**51**)
 * thefourtheye (**24**)
 * outsideris (**19**)
 * bnoordhuis (**15**)
 * taggon (**12**)
 * rvagg (**12**)
 * indutny (**9**)
 * TheAlphaNerd (**8**)

**Comment by nebrius** [comment]
Are you planning on open sourcing this code? I think it could be interesting to see what we can do with it in the inclusivity WG around diversity of the people involved

**Comment by mikeal** [comment]
@nebrius still working on the code, it's pretty gross right now :) https://github.com/mikeal/contribution-reports

**Comment by Fishrock123** [comment]
@mikeal What exactly do you plan on using this for? That context may be helpful for us commenting on it.

**Comment by mikeal** [comment]
@Fishrock123 it gives us some visibility into what is going on organization wide, which we don't quite have right now. We have good data on a per-repo basis but we're missing org wide data.

BTW, this whole way of getting the data, by pulling it out of the GitHub API at multiple endpoints, I'm scrapping because it's actually easier and faster to just filter out our org in the full github archive data. This is a lot more robust tho, and I can post a gzip of *all* our orgs data from as far back as September once it finishes.

**Comment by jasnell** [comment]
I believe it's ok to close this one now
