### ISSUE TITLE
can we make it so anyone with perms to close an issue can also move it to nodejs/help?

### ISSUE THREAD

**Issue by sam-github** [nodejs/TSC#671]
I've done [this](https://github.com/nodejs/help/issues/1801#issuecomment-468165075) myself.

It seems odd that collaborators who are trusted with ability to close (and reopen) issues aren't also allowed to move them to nodejs/help. Is that a policy decision, an oversight, or a technical limitation of github's permission system?

Sorry if I'm posting on the wrong repo. I wasn't sure exactly where the right place is, but I think all TSC members have rights to change github perms, so I used this repo to open the discussion.

**Comment by mcollina** [comment]
+1 for me. I don't know which settings we should change to achieve this.

**Comment by ljharb** [comment]
I believe you’d have to have write (or admin) access on both repos in the same org to be able to transfer an issue between them.

**Comment by richardlau** [comment]
GitHub docs say you need admin permissions: https://help.github.com/en/articles/transferring-an-issue-to-another-repository

**Comment by sam-github** [comment]
OK, technical limitation then, I guess we don't want to give nodejs/collaborators admin perms. 

I made a feature request to github for more fine-grained permissions, but it looks like this isn't configurable right now.
