### ISSUE TITLE
Meeting videos not under Node.js Youtube account

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#68]
As I tuned-in to the Build WG's meeting today- I found it wasn't at https://www.youtube.com/nodejs+foundation/live as I expected. Instead it was on [@orangemocha personal YouTube account](https://www.youtube.com/channel/UCOrZRx7OaT0MCryc70FsCBA)'s and then I found the past Build WG video's & a ChakraCore WG video there too.

This isn't a complaint- rather to just point out how this disconnected placement kept these from being as discoverable.
- Are there other WG/Committee/team meeting video's under other accounts?
- Can these be moved to [Node.js Foundation's Channel](https://www.youtube.com/nodejs+foundation/live)?

**Comment by mikeal** [comment]
@orangemocha can you send me the email you use for Google+ so that I can add you to the Node.js page. Then you'll be able to post them in the same account.

**Comment by mikeal** [comment]
@williamkapke there's not way to "move" a video except for exporting and re-uploading it. Nor can a video be in two YouTube channels :(

**Comment by orangemocha** [comment]
Sorry, I'll definitely fix it going forward.

**Comment by orangemocha** [comment]
Thanks @mikeal , I got the permission to manage the Node.js channel. I did some searching and I might be able to transfer the videos by changing the license to 'creative commons', and creating a remix from the Node.js page. Do you see any problems with changing the license?

**Comment by mikeal** [comment]
@orangemocha sounds fine, there's a CC license in our approved license list already :)

**Comment by nebrius** [comment]
@mikeal sounds like we should be using the node.js channel for the inclusivity WG meetings too, right? If so, can you add me as well?

**Comment by mikeal** [comment]
@nebrius yup, send me the email address you use for GooglePlus :)

**Comment by williamkapke** [comment]
@nebrius Where are they currently, if any?

**Comment by nebrius** [comment]
@williamkapke scattered across different people's accounts, mostly mine and @ashleygwilliams I think. They're linked to in each meeting issue in the repo.

**Comment by mhdawson** [comment]
@mikeal is there a doc that covers what I need to do differently when setting up a google hangout ?  Or if I just setup as before but then move the steps for how to move ?

**Comment by mikeal** [comment]
@mhdawson there is, but first i need to add you to the channel, what is your G+ email?

**Comment by mhdawson** [comment]
I think it should just be michael_dawson@ca.ibm.com

**Comment by mhdawson** [comment]
I think I saw requests etc to add me to the channel.  What is the procedure for moving a video into the channel and is there also a way I can use the nodejs channel to start when creating a hangout on air ?

**Comment by williamkapke** [comment]
Here are all of the Working Group videos (and some unofficial WGs) that are not on the official YouTube channel that I could find. Some are not listed in any GitHub issue or meeting notes.

## Bryan Hughes @nebrialis

**Node.js Inclusivity WG 2016-Mar-3**
https://www.youtube.com/watch?v=j_zlOIdDqyE

**Node.js Inclusivity WG 2016-Jan-20 (dates to not match)**
https://www.youtube.com/watch?v=PONibium-Gk

**Node.js Inclusivity 11/17 meeting**
https://www.youtube.com/watch?v=oBkMYONPYp8

**September Node.js Hardware Working Group meeting**
https://www.youtube.com/watch?v=0JtLl1EZ1v4

**Node.js Hardware WG 7/10 meeting**
https://www.youtube.com/watch?v=ksNmqTN5LTU

**Node.js Hardware WG meeting 5/28, JSConf edition**
https://www.youtube.com/watch?v=kGvogHbndlw

## Rich Trott @Trott

**Node.js Inclusivity 18-Dec-2015**
https://www.youtube.com/watch?v=KdV69lFQrnU

**Node.js Inclusivity WG 2016-Jan-08**
https://www.youtube.com/watch?v=PSF0oBQ4Gwg

**Node.js Testing WG 2016-Jan-15**
https://www.youtube.com/watch?v=UCH1crFZogY

**Node.js Testing WG 05-Feb-2015**
https://www.youtube.com/watch?v=6wnWsUN8Usw

**Node.js Testing WG 18-Mar-2016**
https://www.youtube.com/watch?v=Z4vU2e1LPnI

## Alexis Campailla @orangemocha 

**Node.js Foundation Build WG Meeting 2016-03-15**
https://www.youtube.com/watch?v=5cuOabjxEUY

**Node.js on ChakraCore WG meeting 2016-02-26**
https://www.youtube.com/watch?v=9SdBbUrmWeM

**Node.js Foundation Build WG meeting 2016-02-02**
https://www.youtube.com/watch?v=1zOSmnGytLo

**Node.js Foundation Build WG meeting 2015-12-22**
https://www.youtube.com/watch?v=PKFUFWGHF48

**Node.js Foundtation Build WG Meeting 2015-12-01**
https://www.youtube.com/watch?v=9aVNXVazrVw

**Node.js Build WG meeting 2015-11-10**
https://www.youtube.com/watch?v=jOHgYCt0N1E

## Howard Hellyer @hhellyer

**Node.js post-mortem diagnostics meeting (video posted on Jul 23, 2015)**
https://www.youtube.com/watch?v=8baN-X60H6M

## Michael Dawson @mhdawson 

**Node.js Benchmarking meeting 30 March 2016 2PM EST**
https://www.youtube.com/watch?v=vdo8Z_T8LyU&feature=youtu.be

**Node.js Benchmarking meeting - Feb 25 2PM EST**
https://www.youtube.com/watch?v=aGjxShr1Tw8

**Node.js TLS meeting 22 FEb 2016 (correction: LTS)**
https://www.youtube.com/watch?v=Bv-ynSxaozA

**25-01-2016 Node LTS WG Meeting**
https://www.youtube.com/watch?v=C9yz0yevpB0

**Node.js Benchmarking meeting (posted Jan 7, 2016)**
https://www.youtube.com/watch?v=GxIj2OZD6yA

**Node Benchmarking meeting - Nov 19**
https://www.youtube.com/watch?v=gSC82-VqeqE

**Node Build workgroup meeting 29 Sep 2015**
https://www.youtube.com/watch?v=Qo05XA9LxOc

**Node Benchmarking Meeting - Tuesday Aug 11 - 2PM EST**
https://www.youtube.com/watch?v=yi4pvTKj634

**Benchmarking Workgroup July 9**
https://www.youtube.com/watch?v=0D9Ea2FNStE

**nodejs benchmarking working group (posted Jun 16, 2015)**
https://www.youtube.com/watch?v=NKNFGgruNfs

## James Snell @jasnell 

**LTS Meeting, 2016-03-21**
https://www.youtube.com/watch?v=WcRp9T4xFRg

**Node VM Summit (posted Apr 5, 2016)**
https://www.youtube.com/watch?v=UOrU4d8cbtg

**Node VM Summit, Day 2 (posted Apr 6, 2016)**
https://www.youtube.com/watch?v=Al1qz6HGR3w

**LTS Meeting, 2016-03-21**
https://www.youtube.com/watch?v=WcRp9T4xFRg

**Node.js LTS WG Meeting (posted Mar 7, 2016)**
https://www.youtube.com/watch?v=400J6slKKVE

**Node.js LTS Meeting (posted Dec 14, 2015)**
https://www.youtube.com/watch?v=Bn00ZLyD2js

## Bryan English @bengl

**Node.js Docs WG Meeting 2016-01-20**
https://www.youtube.com/watch?v=bSX6OWoCsn8

**Node.js Docs WG Meeting 2015-09-18**
https://www.youtube.com/watch?v=Z-nYI5Q5myM

## Patrick Mueller @pmuellr

**Node.js Tracing WG Meeting 2016-01-26**
https://www.youtube.com/watch?v=DvQ7QSyEe64

**Node.js API WG Meeting - 2015-11-19**
https://www.youtube.com/watch?v=3rszjGYpbyM

**Node.js Tracing WG Meeting 2015-11-19**
https://www.youtube.com/watch?v=vxY_OLHF66A

**Node.js API WG Meeting 2015-10-23**
https://www.youtube.com/watch?v=fHU4L6Cl90M

**Node.js Tracing WG Meeting 2015-09-25 (PRIVATE VIDEO)**
https://www.youtube.com/watch?v=yM6q92V1IDk

**Node.js Tracing WG Meeting 2015-10-07**
https://www.youtube.com/watch?v=LsO8eLGN7XA

**Comment by nebrius** [comment]
Ugh right, I forgot I had to use my alternate username on YouTube 😅

**Comment by pmuellr** [comment]
I need to be added to the channel - pmuellr@nodesource.com

Happy to try downloading, then uploading, the videos I are on my account.

**Comment by williamkapke** [comment]
Super awesome to see the individual WGs dive in and get on the Foundation's YouTube channel!

I would LIKE to see the ones listed above moved to the Foundation's YouTube... but that's just *MY* desire and I don't have a way to help with that.

So, for a deliverable on this one- it seems there are 2 choices:
1) Decide to leave them where they're at.
2) Commit to moving them... someday when someone with access & time can do it.

LMK.

**Comment by jkrems** [comment]
I think it's possible to create playlists of those videos under the Foundation's YouTube account. Not fixing all the problems but it might be a quick way to make them easier to discover.

**Comment by jasnell** [comment]
@williamkapke ... is this still an issue? does this need to stay open?

**Comment by williamkapke** [comment]
@jkrems A playlist would be an improvement, but it doesn't help with searching within the Foundation's videos unfortunately.

@jasnell This is still the status:

> So, for a deliverable on this one- it seems there are 2 choices:
> 1) Decide to leave them where they're at.
> 2) Commit to moving them... someday when someone with access & time can do it.

... except that since posting this, I am now able to upload them. The @nodejs/tsc just needs to decide which they want (although option 2 also needs the OK of the other account owners).

**Comment by jasnell** [comment]
@williamkapke ... can I bother you to reframe the choices as specifically actionable proposals? I'd like to raise the issue on the TSC call and get a decision made. As is, however, these are a bit abstract and unspecific.

**Comment by williamkapke** [comment]
@nebrius, @Trott, @orangemocha, @hhellyer, @mhdawson, @jasnell, @bengl:

Can we republish the videos you have under your personal account to the Foundation's account?

Feel free to just use a 👍 (go ahead) or 👎 (I object) reaction below.

**Comment by nebrius** [comment]
@williamkapke I'm looking through the YouTube documentation, and my reading seems to suggest the only way is to download the original video from the original account and then reupload it under the Node.js account. This does mean we loose things like view counts, which is unfortunate.

Has anyone else found a better way to transfer videos?

**Comment by williamkapke** [comment]
It is the only way. Yes, view counts are lost 😞

**Comment by nebrius** [comment]
All of my videos have been uploaded to the Node.js account now!
