### ISSUE TITLE
Nominating Sam Roberts (@sam-github) to the TSC

### ISSUE THREAD

**Issue by rvagg** [nodejs/TSC#687]
No objections from the TSC so far and Sam has given a 👍 so I'm nominating him for the TSC. The case for Sam on the TSC is that (a) he has a long history with Node core and that kind of perspective aids in continuity and stability and (b) he's essentially taking over leadership of crypto, or OpenSSL at least, an area where the TSC could do with more representation (I've been phasing out of that area and Sam has been picking up the reigns and I think he's a much better fit than me anyway!). I also expect that Sam is the most likely person to be handling many of the security releases in the near future and having an additional level of authority to get all of the awkward things done and being able to take responsibility for difficult decisions is helpful for that.

**Comment by mhdawson** [comment]
I'll open a PR tomorrow to add @sam-github to the observer list for the next TSC meetings.

**Comment by rvagg** [comment]
I can't remember what the procedure with this is, is it 3 weeks observer then 4th week vote? @sam-github how many weeks has it been since you got to be an observer?

**Comment by Trott** [comment]
> I can't remember what the procedure with this is, is it 3 weeks observer then 4th week vote? @sam-github how many weeks has it been since you got to be an observer?

It's been the 3 the last few times. It used to be 4 but that seemed a bit longer than necessary to me.

**Comment by sam-github** [comment]
@rvagg  There have been 3 TSC meetings since I was added as an observer, I was present at the last 2 (the first was too early in my TZ).

**Comment by rvagg** [comment]
Adding on agenda for whenever the next meeting happens, votes can be collected in here if you're not attending. A +1 from me obviously (next week's meeting is 2am for me and this week looks like it's being cancelled and is not a great time anyway).

**Comment by Trott** [comment]
+1

**Comment by gireeshpunathil** [comment]
+1

**Comment by danbev** [comment]
+1

**Comment by targos** [comment]
+1

**Comment by cjihrig** [comment]
+1

**Comment by ChALkeR** [comment]
+1

**Comment by jasnell** [comment]
+1

**Comment by mcollina** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by rvagg** [comment]
12 of 18 have either provided a +1 or a :thumbsup:, no negatives (that I'm aware of). This week's meeting might be cancelled, #700, so I'm going call this successful and welcome @sam-github on board.

I'll open a PR to the README in nodejs/node, when that's merged we can do the other permissiony things that need to be done.

Before that lands, there is still time  **if there are any remaining concerns among TSC members. Please voice them now or contact me, or someone else on the TSC that you trust that can make it actionable**.

**Comment by rvagg** [comment]
https://github.com/nodejs/node/pull/27606

**Comment by gabrielschulhof** [comment]
+1
