### ISSUE TITLE
Onboarding @cclauss

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/TSC#692]
Hey, it seems like a lot of people are fine with the nomination of @cclauss (https://github.com/nodejs/node/issues/27115). Would someone please go ahead and onboard him? That would be great :)

**Comment by Trott** [comment]
I literally have a calendar invite that just popped up moments before opening this issue which says "Schedule onboarding for @cclauss."

I'll send them an email. If I don't have a compatible schedule, I'll loop things back here to find someone else.

**Comment by BridgeAR** [comment]
@Trott thanks a lot.

**Comment by Trott** [comment]
I'm having trouble scheduling this so I've looped in the rest of the TSC in email. We'll get it done....

**Comment by cclauss** [comment]
Michael Dawson and I are that the same conference in Orlando, FL this week…  Can we do this face-to-face?

**Comment by mhdawson** [comment]
I don't think we are at the same conference as I'm not at one :).  I'm off on holiday next week but its not Orlando...

**Comment by cclauss** [comment]
LoL OK.  My mistake... Enjoy the time off.

**Comment by Trott** [comment]
Hi, @cclauss! I've emailed you a couple times in the last week, but haven't heard anything back. Is there a better way to contact you? Or maybe I just need to be patient because you're traveling right now or some other reason?

**Comment by Trott** [comment]
Deleting the above comment in case it is perceived as public shaming (which it is absolutely not intended to be, but just in case....)

**Comment by Trott** [comment]
https://github.com/nodejs/node/pull/27554
