### ISSUE TITLE
Nominating @jasnell to rejoin TSC

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#694]
@jasnell has indicated he would like to rejoin the TSC in May after his time away.

As part of our standard process for adding TSC members, I'm nominating him to be added back to the TSC.

@nodejs/TSC please +1 to confirm your vote to have @jasnell rejoin.

**Comment by mcollina** [comment]
+1

Il giorno mer 17 apr 2019 alle 20:29 Michael Dawson <
notifications@github.com> ha scritto:

**Comment by danbev** [comment]
+1

**Comment by targos** [comment]
+1

**Comment by addaleax** [comment]
+1

**Comment by Trott** [comment]
+1

**Comment by gireeshpunathil** [comment]
+1

**Comment by cjihrig** [comment]
+1

**Comment by ChALkeR** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by MylesBorins** [comment]
+1

**Comment by gabrielschulhof** [comment]
+1

**Comment by Fishrock123** [comment]
+1

**Comment by mhdawson** [comment]
From Nikita Skovoroda to Everyone:  05:35 PM
+1
From Jeremiah Senkpiel to Everyone:  05:35 PM
+1
From Anatoli to Everyone:  05:36 PM
+1
From Sam Roberts to All Panelists:  05:36 PM
+1 (if I vote )
From Gabriel Schulhof to All Panelists:  05:36 PM
+1

**Comment by mhdawson** [comment]
Looks like we have 14/17 with +1s and no objections so I'll open a PR adding James back tomorrow.

**Comment by Trott** [comment]
> Looks like we have 14/17 with +1s and no objections so I'll open a PR adding James back tomorrow.

Note the full list of onboarding tasks at https://github.com/nodejs/TSC/blob/master/ONBOARDING.md#onboarding.

**Comment by mhdawson** [comment]
PR to add James to README.md https://github.com/nodejs/node/pull/27411
PR to add to meeting invite templates: https://github.com/nodejs/create-node-meeting-artifacts/pull/59
PR to add to mailing lists: https://github.com/nodejs/email/pull/140

Believe I have completed the rest of the items in https://github.com/nodejs/TSC/blob/master/ONBOARDING.md#onboarding. as well.
