### ISSUE TITLE
Org Wide Activity and Commit Graphs

### ISSUE THREAD

**Issue by mikeal** [nodejs/TSC#70]
Been working on more org wide data. To my surprise, some of our assumption about growth aren't holding. We're relatively stable in terms of contributions and individual contributors since September of last year, which was a high point historically.

![slide08](https://cloud.githubusercontent.com/assets/579/13894950/d2aabab4-ed2a-11e5-88ef-da1cce415ed5.jpg)
![slide09](https://cloud.githubusercontent.com/assets/579/13894951/d2b360ba-ed2a-11e5-97f7-f498feff974c.jpg)
![slide10](https://cloud.githubusercontent.com/assets/579/13894952/d2b47d60-ed2a-11e5-92d7-dc561131bd5d.jpg)
![slide11](https://cloud.githubusercontent.com/assets/579/13894955/d2b71e76-ed2a-11e5-8895-3a9f16e44e78.jpg)
![slide12](https://cloud.githubusercontent.com/assets/579/13894953/d2b4b32a-ed2a-11e5-844f-ec81d61c1294.jpg)
![slide13](https://cloud.githubusercontent.com/assets/579/13894954/d2b53f98-ed2a-11e5-8ff7-2388b431bd0e.jpg)
![slide14](https://cloud.githubusercontent.com/assets/579/13894956/d2bad9e4-ed2a-11e5-8168-d0e936d59430.jpg)

**Comment by mikeal** [comment]
Here's the raw data, extracted from the GitHub Archive https://drive.google.com/a/linuxfoundation.org/file/d/0B2Hy63SlAcGKemZuWk8wRE80VHM/view?usp=sharing

All the code i used to create and process the data is here https://github.com/mikeal/contribution-reports

**Comment by jasnell** [comment]
I'm not too concerned about the actual growth. The project is maintaining a health volume and things seem to be progressing. The trend for commits org wide is quite promising although the trend on unique people is a bit concerning.

**Comment by mikeal** [comment]
@jasnell keep in mind that this is activity of any kind, including issue comments, so when we have controversial issues watches and comments go way up in terms of unique people.

**Comment by nebrius** [comment]
It could also be that people tend to be busier during the late fall/early winter months (at least in the US) with non-work/holiday activities, combined with companies trying to get things out the door before the holiday break making people more focused on the short term. I don't think that fully explains it, but maybe partly?

**Comment by williamkapke** [comment]
@mikeal that google doc is not public... if that's what you intended.

**Comment by mikeal** [comment]
@williamkapke my bad, missunderstood the Google Drive share settings, here we go https://drive.google.com/file/d/0B2Hy63SlAcGKemZuWk8wRE80VHM/view?usp=sharing

**Comment by mikeal** [comment]
@nebrius Oh, there is a definitely a big drop in activity across the board in open source and software in general in December. Everyone who has metrics sees a drop there.

Our drop is a little compounded by the fact that September was a really strong month, we have v4 LTS and a lot of activity, the fact that we're now basically back to that level of activity as a norm is pretty encouraging.

**Comment by mikeal** [comment]
Two more nice graphs, this time regarding contributions to Core branches.

![slide15](https://cloud.githubusercontent.com/assets/579/13899800/30729aca-edb4-11e5-8ca5-86e503d05607.jpg)
![slide16](https://cloud.githubusercontent.com/assets/579/13899801/3072ae3e-edb4-11e5-9502-f9d91594f74a.jpg)

**Comment by jasnell** [comment]
Closing... tho it would be good to get some updated graphs :-)
