### ISSUE TITLE
GitHub Package Manager

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#703]
Hey all,

As you've likely heard, GitHub has launched a new Package Manager service that is fully integrated with GitHub. It launched as a beta on Friday. I asked for it to be enabled for the nodejs organization. This means that the `@nodejs` scope for the `npm.pkg.github.com` registry has been enabled, and anyone with write permissions to a repo in this organization can publish modules to it. Note that the registry also supports docker, NuGet, and others. 

We likely need to come up with some policies around it's use. First, however, if anyone has any questions or concerns about the new service, post them here and I'll try to get answers.

**Comment by devsnek** [comment]
I'm looking forward to `@nodejs/left-pad`

more seriously, I'm curious how this ties into the scoped builtins issue

**Comment by jasnell** [comment]
They'll be restricting the mutability of the registry in an update. ;) ... I'm not sure it does tie into the scoped builtins stuff

**Comment by ljharb** [comment]
Since we’d  have the same ownership over packages in the public registry, i don’t see how github’s announcement would change that.

**Comment by mhdawson** [comment]
I agree that we should define/document policies before we start using it within the project.

**Comment by mcollina** [comment]
Who wants to take a stab at that? Specifically, what should we document?

@jasnell I would kindly ask Github if they plan to provide some different level of ACL for the registry. We are very liberal in getting people commit access to repos, but we have very few releasers. I'd love to be able to create a team that can do releases, and not give permission to all collabs.

**Comment by jasnell** [comment]
Currently, anyone with write permissions to any repo in the GitHub org would be able to public packages, as far as I understand it. We certainly could request additional granularity here.

**Comment by mhdawson** [comment]
@jasnell are you planning to work on a fist cut on policies for using this?

**Comment by jasnell** [comment]
I certainly can. It'll be a couple weeks before I can

**Comment by mhdawson** [comment]
@jasnell thanks!

**Comment by mhdawson** [comment]
@jasnell is this still relevant given the passage of time and that npm was acquired by GitHub?

**Comment by mhdawson** [comment]
Given that its been a few months without a response I'm going to close it out. @jasnell please re-open if that was not the right thing to do.
