### ISSUE TITLE
Reevaluate meeting times

### ISSUE THREAD

**Issue by cjihrig** [nodejs/TSC#707]
We've recently had people step down from the TSC, and new members have joined. Let's revisit our meeting schedule to see if the current times are still best for the collective group.

**Comment by sam-github** [comment]
I'm in North America, west coast, so the 5am meeting doesn't work well for me, the other two work well.

**Comment by ChALkeR** [comment]
Based on current data, the difference would not be significant -- two timeslots would be shifted by one hour (in different directions), one would remain the same.

I'll post more info prior to the meeting next week or once the data gets updated.

**Comment by mcollina** [comment]
Maybe we can move to two timeslots instead?

**Comment by ChALkeR** [comment]
@mcollina That will be possible (e.g. 15, 20 seems viable atm), but it would be slightly less ideal.

What would be the reason for preferring two instead of three? Is it more convenient for everyone?

**Comment by mcollina** [comment]
Let’s keep the three slots then!

**Comment by ChALkeR** [comment]
Status update: after the recent changes in data, the optimal seems to now be 15, 16, 19.
Let's wait a bit more =).

**Comment by ChALkeR** [comment]
Unless the data changes, the proposal would be 15, 16, 19.
ping @nodejs/tsc @gabrielschulhof @Fishrock123 once again about the data =).

**Comment by ChALkeR** [comment]
No data updates over the week.

**Comment by ChALkeR** [comment]
No data updates since May 20.
Let's go with 15, 16, 19 =).

**Comment by ChALkeR** [comment]
@Trott @mhdawson Do we still need to confirm those via vote, or can we start using those starting with the next meeting? Ref: https://github.com/nodejs/TSC/issues/713#issuecomment-496251042

**Comment by Trott** [comment]
> @Trott @mhdawson @nodejs/tsc Do we still need to confirm those via vote, or can we start using those starting with the next meeting? Ref: [#713 (comment)](https://github.com/nodejs/TSC/issues/713#issuecomment-496251042)

5 upvotes and no other participation wouldn't be enough for a vote, but since there's no one opposed, it's enough for consensus. I say we call it done!

**Comment by targos** [comment]
+1. Do we start with 15 this week?

**Comment by mhdawson** [comment]
To avoid confusion I'd suggest we use the current scheduled time (9PM UTC) and I'll update for all future meetings.

**Comment by mhdawson** [comment]
Calendar updated for meetings started next week, closing issue.

**Comment by Fishrock123** [comment]
Updated mine but it did not change significantly.

**Comment by ChALkeR** [comment]
@Fishrock123 Thanks! It looks like that didn't change the optimum.

**Comment by ChALkeR** [comment]
The data was updated once more just now :-). 

Two alternatives now:
```
times: [ 15, 16, 19 ]
  participation: { avg: .756, min: .39, stdev: .1584, fair: .9536, n5: 17 }
  percentages: 95,95,95,94,94,80,80,80,80,80,80,70,64,60,59,59,59,39
  interaction: { avg: .568, min: .0658, stdev: .1761, fair: .657, n5: 102 }
  meetings: { probs: [ .998, .996, 1 ], avg: [ 13.56, 13.12, 14.22 ] }
times: [ 15, 18 ]
  participation: { avg: .753, min: .484, stdev: .1736, fair: .9635, n5: 14 }
  percentages: 95,95,95,94,94,94,87,80,72,72,72,72,72,65,48,48,48,48
  interaction: { avg: .562, min: .019, stdev: .1975, fair: .533, n5: 82 }
  meetings: { probs: [ .998, .998 ], avg: [ 13.56, 13.58 ] }
```

**Comment by mhdawson** [comment]
+1 to sticking with 15/16/19. That is what the calendar now reflects.
