### ISSUE TITLE
Berlin Collaborator's Summit

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#711]
Just wanted to take a quick poll of @nodejs/tsc members... Who is planning to be at the Collaborator Summit next week in Berlin? If we have enough TSC members there, we should plan a TSC (and @nodejs/community-committee) dinner...

please use a :+1: to indicate if you'll be there, :-1: to indicate that you won't

**Comment by sam-github** [comment]
I'll be there, as will @mhdawson

**Comment by targos** [comment]
I'm not able to come to Berlin next week as I'll be moving into a new apartment.

**Comment by addaleax** [comment]
I will be there, but am heading back on Friday in the evening.

**Comment by ChALkeR** [comment]
I won't be present due to a time conflict, unfortunately. Sorry all.

**Comment by danbev** [comment]
I’ll be there.

tors 23 maj 2019 kl. 18:20 skrev Сковорода Никита Андреевич <
notifications@github.com>:

**Comment by MylesBorins** [comment]
I’ll be there

**Comment by ChALkeR** [comment]
I think this ended? Closing, as the only intention as I see was a poll to predict attendance and plan things in advance.

Feel free to reopen if I'm mistaken. 😸

**Comment by keywordnew** [comment]
👉 If you were there feel free to drop your thoughts in the [retrospective issue](https://github.com/nodejs/summit/issues/177). Taking all suggestions, critiques, and perspectives :)
👉 You're also welcome to join the retrospective discussion that will happen on the 11th at 13.00 EST.
