### ISSUE TITLE
Having trouble with zoom/youtube setup for WG meetings

### ISSUE THREAD

**Issue by sam-github** [nodejs/TSC#719]
I couldn't get the zoom meeting started for the last sec-wg meeting, @mhdawson had to do it for me, so I'm trying to work through https://github.com/nodejs/TSC/blob/master/Streaming/Streaming-To-Youtube.md to make sure I'm setup for the next one, assuming those directions are for all WG, not just the TSC.

I'll update the instructions once I've got them working, here is what I'm finding.

> You need the Foundation login credentials for Zoom in order to host the meeting

- Where do I get them? I thought they might be shared with me via lastpass, but my lastpass Vault is completely empty.

- Where do I use them? I generally sign-in to zoom.us with google OAuth, and it starts my local client. Should I be logging in with Node foundation credentials instead?

> In addition, your YouTube Account must be a manager of the Node.js YouTube account.

- How do I verify this? I do have the ability to from youtube.com "switch my account" from my personal one to the "node.js" user. Do I have to do this before attempting to open the Zoom meeting and go live?

**Comment by mhdawson** [comment]
I had shared the credentials with you. I can see that the invite is still pending:


![image](https://user-images.githubusercontent.com/9373002/59714220-25d59680-91df-11e9-8a93-94973e57db33.png)

You need to log into zoom using the Node foundation credentials instead.

**Comment by mhdawson** [comment]
You don't need to switch your youtube account in advance.  When you select the live stream on Youtube you can choose the Node.js user instead of your own.

The issue you reported the last time sounded like problems I has having. I had to paste the link that was auto opened in firefox into a chrome browser instance and then it seemed to work ok.  Otherwise I got the same "you cannot stream from this account".  Might be an issue with using firefox instead of chrome as opposed to anything to do with your account.

**Comment by TimothyGu** [comment]
@mhdawson, @sam-github’s GitHub account has “vieuxtech” as the email rather than “viewtech”… could that possibly be a factor?

**Comment by mhdawson** [comment]
ok that would explain it.  Canceled the share that had not been accepted.  Seems that now Lastpass has changed to you need a paid account to share with more than one person so I can't re-share :(

I'll share the info directly with Sam, but if/when the password changes it would still be good if it was shared properly.  @brianwarner, @hackygolucky  are you able to share the Node.js one more broadly with the lastpass accounts that you have?

**Comment by mhdawson** [comment]
@sam-github were you able to check out that you now have access with the info I sent you directly?

**Comment by mhdawson** [comment]
@brianwarner, @hackygolucky ping

**Comment by sam-github** [comment]
I don't think I can be confident its working until I host a meeting, or is there a way I can do a dry run.

I opened https://github.com/nodejs/TSC/pull/723, moved discussion there.
