### ISSUE TITLE
Proposal: Node.js openembedded layer technical stewardship

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [nodejs/TSC#721]
(Please point me to the correct repo if incorrect)

Leaving a quick proposal:
Node.js on embedded devices is a veritable runtime. One of the most common toolchains for this is Yocto / Openembedded, a layer based Linux environment.

For the sake of market and security, the org could consider having a repo and some stewardship, similar to the docker stack, for such a layer.

There is an outdated repo of a collaborator and a newer fork here https://github.com/aaronovz1/meta-nodejs/tree/pyro

Kind regards

**Comment by sam-github** [comment]
This kind of work tends to be driven by people willing to put the effort in, there isn't a lot of capacity for taking on new projects like this. See https://github.com/nodejs/Release/issues/341#issuecomment-504263551 for discussion of this on a different but somewhat similar topic.

I'm not saying I'm opposed, maybe you can get involved with @rvagg and unofficial-builds.nodejs.org, or perhaps put together a description of what you would like to see happen, and how you could do it? If you just need  repo to work in, that would probably be easy.

Maybe this issue will attract attention of other people interested in Yocto, and they will step up to help you.

**Comment by rvagg** [comment]
👍 the barrier to this kind of work is *leadership*, it really just requires someone with motivation and time and a willingness to own something. Resources, like a repo, could be provided, but anything that smells like it might become a dumping ground is probably not going to be greeted with much enthusiasm.

I don't think anyone around here knows much about Yocto and Openembedded although we see a [steady (but not rapid) stream of issues](https://github.com/nodejs/node/issues?utf8=%E2%9C%93&q=yocto) discussing it and asking compatibility questions. There was an [issue](https://github.com/nodejs/node/issues/28284) just 2 days ago trying to get a newer recipe working, but none of us have much of a clue about how that works. There's not going to be anyone here right now who could or might want to own such work. Are you putting up your hand to own this @eljefedelrodeodeljefe? Or are you in touch with a community that is interested? We'd need some names to own a repo / working group / initiative and probably come up with some kind of minimum-viable state rules like I did for unofficial-builds @ https://github.com/nodejs/unofficial-builds/issues/1 -- I'm not sure that criteria is going to be successfully met but at least a possible discontinuation is foreshadowed.

**Comment by eljefedelrodeodeljefe** [comment]
Yes, I have personal interest and time and also we as a company a commercial interest and time in something like that. I wouldn't need anything except for the repo really and some mental buy-in, like "this kinda belongs here" as well as awareness to send people there to resolve issues and maybe attract co-maintainers.

Going forward I'd fork out those repos put some OSS CI on it and see how it goes.

If no-one opposes this, I'd start a new nodejs/* repo after returning with the results. I believe I have the necessary permissions, otherwise would kindly ask for help.

LMK what you think. I return on this matter in 2 weeks time, as I am gonna be afk until then and would proceed as mentioned.

**Comment by rvagg** [comment]
Sounds good to me then, for what it's worth! Best of luck.

**Comment by mhdawson** [comment]
The process to request a new repo under nodejs/* is here: https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md#repositories

You will need to open an issue in nodejs/admin to make the request.

**Comment by mhdawson** [comment]
@eljefedelrodeodeljefe can this be closed at this point?

**Comment by mhdawson** [comment]
I'm going to close @eljefedelrodeodeljefe let me know if that is not the right thing to do and reopen.
