### ISSUE TITLE
Move "Items to discuss with the board" to admin repo

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#729]
I think now that we have a single Board representative it would make sense to move the "Items to discuss with the board" project in the TSC repo over to the admin repo.

This is the link to the existing project in the TSC repo:

https://github.com/nodejs/TSC/projects/1

@nodejs/TSC any concerns with doing this?

**Comment by Trott** [comment]
No concerns here.

@nodejs/tsc

**Comment by mhdawson** [comment]
Moving since there were no concerns expressed.

**Comment by mhdawson** [comment]
New board https://github.com/nodejs/admin/projects/1
