### ISSUE TITLE
Broken links in Project-Lifecycle.md

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#73]
There is a broken "Proposal" under the Lifecycle section:
https://github.com/nodejs/TSC/blob/master/Project-Lifecycle.md#lifecycle

**Comment by williamkapke** [comment]
Also the "mentors" link under "Incubation" points to:
https://github.com/nodejs/TSC/blob/master/README.md#mentors

...which doesn't exist

**Comment by mikeal** [comment]
We should remove "apply to join" while the TSC isn't accepting applications.

**Comment by jasnell** [comment]
@williamkapke ... if this is still an issue, please reopen
