### ISSUE TITLE
Nominating @tniessen for the TSC

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#746]
Tobias is an absolute pleasure to work with in the issue tracker. He is invaluable for certain subsystems (e.g., `crypto`), and has involved in certain important non-core initiatives (e.g., webcrypto). I would like to nominate him for the TSC at this time.

@nodejs/tsc

**Comment by cjihrig** [comment]
+1

**Comment by Trott** [comment]
Guess I should @-mention @tniessen here too. 😀

**Comment by addaleax** [comment]
+1

**Comment by targos** [comment]
+1

**Comment by danbev** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by sam-github** [comment]
+1

**Comment by gireeshpunathil** [comment]
+1

**Comment by mcollina** [comment]
+1

Il giorno gio 15 ago 2019 alle 16:39 Gireesh Punathil <
notifications@github.com> ha scritto:

**Comment by MylesBorins** [comment]
+1

**Comment by gabrielschulhof** [comment]
+1

**Comment by fhinkel** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by jasnell** [comment]
+1

**Comment by apapirovski** [comment]
+1

**Comment by ChALkeR** [comment]
+1

**Comment by Fishrock123** [comment]
+1

**Comment by mhdawson** [comment]
We discussed in the TSC meeting today and agreed nomination can progress.

As per TSC charter we need a vote.  @nodejs/tsc, we'll consider +1s in this issue to be a yes vote unless an objection is raised in this issue before the end of this week.

The following people were in attendance in the meeting and are considered yes votes as well:
* Beth Griggs @BethGriggs (guest participant)
* James Snell @jasnell (TSC)
* Jeremiah Senkpiel @Fishrock123 (TSC)
* Joyee Cheung @joyeecheung (TSC)
* Gireesh Punathil @gireeshpunathil (TSC)
* Matteo Collina @mcollina (TSC)
* Michael Dawson @mhdawson (TSC)
* Tobias Nießen @tniessen (guest participant)
* Rich Trott @Trott (TSC)
* Sam Roberts @sam-github (TSC)

@nodejs/tsc, if you have not commented in this issue before or would like to change your vote please comment in the issue before the end of the week.  Michael will plan to tally votes and open PR's to add to TSC if appropriate on Monday next week.

**Comment by danbev** [comment]
+1

**Comment by mhdawson** [comment]
We have 17/18 +1s and no objections so considering vote complete and acceptance onto the TSC complete.  Will PR addition.

**Comment by mhdawson** [comment]
PR to add to mailing list: https://github.com/nodejs/email/pull/144

**Comment by mhdawson** [comment]
PR to add to invitee list for TSC meetings: https://github.com/nodejs/create-node-meeting-artifacts/pull/76

**Comment by mhdawson** [comment]
PR to add to TSC list in nodejs/node: https://github.com/nodejs/node/pull/29545

**Comment by mhdawson** [comment]
checklist once PR in nodejs/node lands:

- [ ] Add the new member to the @nodejs/tsc and @nodejs/security-tsc teams.
- [ ] Change the new member's role in the GitHub nodejs organization to Owner.
- [ ] Add them to the @nodejs-private org and with an Owner role.
- [ ] Add them to the @nodejs-private/security-tsc team.

**Comment by mhdawson** [comment]
Checklist complete. @tniessen welcome to the TSC!

**Comment by tniessen** [comment]
Thank you, everyone!
