### ISSUE TITLE
Next weeks meeting conflicts with Modules Team

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#748]
Can we change the TSC meeting time? This is now the second time we've had the conflict... is it worthwhile for us to consider permanently changing that time?

**Comment by Trott** [comment]
> Can we change the TSC meeting time? This is now the second time we've had the conflict... is it worthwhile for us to consider permanently changing that time?

It's OK and better to swap the meeting on an _ad hoc_/as needed  basis. We should endeavor to cancel most of our meetings anyway. Taking that time out of rotation entirely will simply make attendance even worse than it is and result in less fair scheduling.

**Comment by Trott** [comment]
If Modules WG is every other week, and Meeting Time C is the one that conflicts with it, we could probably permanently switch our schedule from:

Week 1 Meeting Time A
Week 2 Meeting Time B
Week 3 Meeting Time C (will conflict with Modules once every six weeks)

...to this:

Week 1 Meeting Time A
Week 2 Meeting Time B
Week 3 Meeting Time C
Week 4 Meeting Time A
Week 5 Meeting Time C
Week 6 Meeting Time B

The downside there is that it makes it more complicated to have a recurring calendar event.

Another possibility is to see if switching to rotating through four times works. (That could include one time appearing twice, although @ChALkeR may have to fix up the script to take that possibility into account.)

**Comment by Trott** [comment]
@MylesBorins If you haven't updated the spreadsheet to change your availability for that time to 50% or whatever, it might be interesting to see if doing that alters the results of the scheduling algorithm. Probably not, but I'd be curious anyway.

Also, once we bring on the next two currently-nominated folks (assuming that happens, which I assume it will, so assuming), we'll may need to re-think the schedule again anyway.

**Comment by MylesBorins** [comment]
@Trott it would appear that my times were not accurate for Daylight savings... I've fixed that. the current timezone converter is off by one (not including daylight savings) and that confused me

/cc @ChALkeR

**Comment by ChALkeR** [comment]
> Another possibility is to see if switching to rotating through four times works. 

The script is mostly agnostic to that, so if it would require fixes that would be a one number that defines the max number of timeslots. I will increase that and reiterate

@MylesBorins As for three-timeslot variant, the main premise was that they are all distributed evenly ie have the same share, and having them rotating specifically in A-B-C-A-B-C is not required. We could rotate them as `A-B-C-B-A-C`, for example, and `A` would never happen on even timeslots (and `B` would never happen on odd timeslots).

Would that solve the issue?

**Comment by ChALkeR** [comment]
Perhaps we should wait for the new members to fill in their data before reiterating.
Also, I checked how 4-slot meeting look like with the dataset -- those are definitely a possibility if everyone is ok with that.

**Comment by mhdawson** [comment]
For next week should we just swap the TSC meeting time between next week and the week after?

**Comment by ChALkeR** [comment]
@mhdawson SGTM.
@MylesBorins What do you think?

**Comment by Trott** [comment]
> For next week should we just swap the TSC meeting time between next week and the week after?

I think yes. Make it so!

**Comment by MylesBorins** [comment]
@mhdawson That would mean the TSC meeting would move to 11am ET?

+1 on whatever time that is as long as it doesn't conflict

**Comment by mhdawson** [comment]
Calendar updated.  Nexte week is now 11 ET, and the following week 3ET, no conflicts.

**Comment by mhdawson** [comment]
My current plan would be to worry about this once the new members have been confirmed, we can get their availability data and then take another look at the meeting times.

**Comment by sam-github** [comment]
```
Week 1 Meeting Time A
Week 2 Meeting Time B
Week 3 Meeting Time C
Week 4 Meeting Time A
Week 5 Meeting Time C
Week 6 Meeting Time B

The downside there is that it makes it more complicated to have a recurring calendar event.

```

Would making it ACBACB fix that complication?

I'm all for schedules that require as little discussion and maintenance as possible, and while moving the occaisonal meeting isn't a huge time sync, its one more administrative drag. If the conflicts are predictable and recurring, it would be good to rearrange schedules to avoid them.

**Comment by ChALkeR** [comment]
The current spreadsheet shows that we should just update to 15,16,20.
Even if that didn't block the modules meeting.

@MylesBorins would that resolve the issue?

**Comment by mhdawson** [comment]
Discussed in TSC meeting today. No objections to moving the meeting time out 1 our as suggested by @nodejs/version-management 

Calendar updated, closing.
