### ISSUE TITLE
TSC representation on Moderation Team

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#757]
From https://github.com/nodejs/admin/issues/408#issuecomment-533161189:

> I am concerned that this means there is no TSC representation in the moderation team which I think is important for establishing trust between the moderation team and various bodies.
> 
> Would it be possible to ask for volunteers in the next TSC meeting?

**Comment by sam-github** [comment]
Based on what I see in moderation, their actions are reasonable and helpful, and I trust them to continue like that. That all members (I think) need recertification from _both_ TSC and commcomm should be enough to demonstrate trust, IMO. That said, I have no problems with asking for more volunteers from the TSC (even though I don't think its necessary).

**Comment by mcollina** [comment]
I don’t really think it’s necessary, they are doing a good job! It would be
good to get a regular update at the tsc meetings

Il giorno gio 19 set 2019 alle 20:09 Sam Roberts <notifications@github.com>
ha scritto:

**Comment by mhdawson** [comment]
We discussed in the TSC meeting, of the 9 TSC members present there was no concern.  Removing tsc-agenda label.
