### ISSUE TITLE
Node core security team nomination: Thomas Watson

### ISSUE THREAD

**Issue by mcollina** [nodejs/TSC#779]
I would like to nominate @watson to the Node core security team. Thomas has volunteered to help in preparing the next release.

Any objections/question?

**Comment by sam-github** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by Trott** [comment]
You may or may not already know all of this, but just in case:

Note that the security team has no members itself and instead is comprised of four subteams. Those teams are:

security-tsc
security-release
security-external
security-triage

The first two should mirror nodejs/tsc and nodejs/releasers exactly so they should be added to one of the other two. If the plan is for them to do triage of bug reports on HackerOne, add them to security-triage. If the idea is that they're being added to generally help out but won't be doing triage of initial reports on HackerOne, add them to security-external.

Whichever one you add them to, also add them to the corresponding team in the nodejs-private org.

**Comment by Trott** [comment]
> You may or may not already know all of this, but just in case:
> 
> Note that the security team has no members itself and instead is comprised of four subteams. Those teams are:
> 
> security-tsc
> security-release
> security-external
> security-triage
> 
> The first two should mirror nodejs/tsc and nodejs/releasers exactly so they should not be added to those teams (unless they are going to be added to to the general releasers team? but that would be up to the Release WG and not TSC). If the plan is for them to do triage of bug reports on HackerOne, add them to security-triage. If the idea is that they're being added to generally help out but won't be doing triage of initial reports on HackerOne, add them to security-external.
> 
> Whichever one you add them to, also add them to the corresponding team in the nodejs-private org.

Or, alternatively, just tell me to add them and I'll make sure it happens in the right places. :-D

**Comment by mcollina** [comment]
I will onboard @watson on Monday.

**Comment by mcollina** [comment]
@Trott if you don't mind to add him everywhere in the meantime, that would be great!

**Comment by Trott** [comment]
> @Trott if you don't mind to add him everywhere in the meantime, that would be great!

I added him to security-external for both nodejs and nodejs-private, so he should have access to everything GitHub-wise. Not sure what needs to be done on the HackerOne side of things, if anything.

**Comment by mhdawson** [comment]
I think at this point this can be closed. Please re-open if that is not the case.

**Comment by Trott** [comment]
@watson Do you have login access to our HackerOne instance?
