### ISSUE TITLE
Tracking issues for strategic initiatives?

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/TSC#782]
At the TSC meeting today we discussed about writing down the weekly progress report of strategic initiatives and read them in meetings, instead of having champions (who need to be TSC at the moment) present coming up with reports at each meeting. We also discussed about creating teams to ping for the strategic initiatives, and PR'ing the progress report reminder into the meeting template.

On a second thought, I think it would also help if we have tracking issues for the strategic initiatives, and ask people working on them to try always referencing these issues when they land PRs related to the initiatives. I always find tracking issues like these in the v8 issue tracker immensely helpful. It may also help whoever writes the weekly summary in the TSC meeting issue to have an idea about the progress. These issues can serve as a map for the related issues/PRs so we should try avoiding technical discussions in these tracking issues but defer those to separate spin-off issues in order to reduce the noise. 

WDYT?

**Comment by mhdawson** [comment]
+1, we already have a link in the strategic initiatives table and ideally it would point to a tracking issue like you suggest.  https://github.com/nodejs/TSC/blob/master/Strategic-Initiatives.md#current-initiatives

**Comment by mcollina** [comment]
+1
Il 27 nov 2019, 22:40 +0100, Michael Dawson <notifications@github.com>, ha scritto:

**Comment by tniessen** [comment]
What is with the "Mentoring" and "Error Messages" initiatives? The former seems to be managed by the CommComm, and the latter seems to have been solved for the most part. Can we remove them from the "Need volunteers for" initiatives, or are we still looking for champions?

**Comment by mhdawson** [comment]
@joyeecheung is there a next step on this one or can we close it out?

**Comment by mhdawson** [comment]
@joyeecheung I'm going to close this, please re-open if you think there is a next step and it should still be open.
