### ISSUE TITLE
Meetings over the holiday Weeks

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#784]
I'm out the weeks of Dec  18 and 25th and Jan 1, wIth Dec 25th and Jan 1 being a holiday for many people.  

I'm wondering how many people will be around those dates and if I should try to find a volunteer to chair the TSC meeting of if we should cancel ?

**Comment by mhdawson** [comment]
@nodejs/tsc

**Comment by mcollina** [comment]
+1 to cancel
Il 28 nov 2019, 18:55 +0100, Michael Dawson <notifications@github.com>, ha scritto:

**Comment by tniessen** [comment]
I could make Dec 18, but I won't be able to join Dec 25 and Jan 1.

**Comment by sam-github** [comment]
The meetings are literally on the 25th and 1st? I won't make those dates, either. +1 to cancel.

**Comment by BethGriggs** [comment]
I could also make Dec 18, but +1 to cancelling Dec 25th and Jan 1st

**Comment by cjihrig** [comment]
+1 to cancelling.

**Comment by danbev** [comment]
+1 to cancelling.

**Comment by mhdawson** [comment]
Based on email and this issue we are going to cancel the meeting for next week and the meetings on 
 Dec 25th and Jan 1,

**Comment by mhdawson** [comment]
Updated the calendar, closing.
