### ISSUE TITLE
Unpin CitGM repo

### ISSUE THREAD

**Issue by tniessen** [nodejs/TSC#788]
The main reasons for pinning repositories have been outlined in https://github.com/nodejs/TSC/issues/189:
1. To attract attention to important repositories, or to repositories that currently lack attention.
2. As a way of saying: You might be looking for this!

It was suggested to unpin the [citgm repository](https://github.com/nodejs/citgm) in https://github.com/nodejs/TSC/issues/189#issuecomment-284020381. I would like to follow up on that suggestion and to instead pin a repository that is a better fit for the above criteria.

From my perspective, [node-addon-api](https://github.com/nodejs/node-addon-api) might be a good choice. It is something that we want to encourage people to use, and something that both organization members and non-members are more likely to be looking for.

Are there any objections to unpinning citgm? Which other repositories should we consider pinning instead?

**Comment by cjihrig** [comment]
+1 to replacing CITGM with node-addon-api.

**Comment by mcollina** [comment]
+1
Il 4 dic 2019, 22:54 +0100, Colin Ihrig <notifications@github.com>, ha scritto:

**Comment by Trott** [comment]
/ping @nodejs/community-committee (since GitHub management is shared with them, as I understand it--I don't expect anyone on CommComm to oppose this or anything).

**Comment by keywordnew** [comment]
+1 I'm onboard with @tniessen's reasoning and support this thread's choice of replacement in line with the same reasoning.

**Comment by bnb** [comment]
If we’d like people to use node-addon-api perhaps it’s worth knocking off node-gyp and having an additional space to add something?

**Comment by ahmadawais** [comment]
+1 on swapping the two repos in the pinned section.

**Comment by tniessen** [comment]
> If we’d like people to use node-addon-api perhaps it’s worth knocking off node-gyp and having an additional space to add something?

I think everyone is open to suggestions. Note that, unlike citgm, node-gyp is still getting reasonably much traffic from GitHub and search engines (about 30,000 unique visitors in the last two weeks).

**Comment by tniessen** [comment]
I have replaced citgm with node-addon-api. (We can still change it back or pin something else.)

## Before:
![pins-before](https://user-images.githubusercontent.com/3109072/70249038-327c8580-1752-11ea-9ac9-95be900a47f9.png)
## After:
![pins-after](https://user-images.githubusercontent.com/3109072/70249046-35777600-1752-11ea-9622-123d1578d2d1.png)
