### ISSUE TITLE
HackerOne monthly status meeting

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/TSC#791]
Followig up on H1 proposal to hold a monthly meeting to follow the state of the bug bounty program.

We have this in place for ecosystem and it helps synchronize the H1 and the working group team. Do we want to setup the same meeting for Node.js core?

**Comment by Trott** [comment]
> Do we want to setup the same meeting for Node.js core?

Yes! Great idea.

**Comment by mhdawson** [comment]
How much time is needed for the review?  Just wondering if we need a separate meeting or if its something we can handle as part of the TSC meetings?

**Comment by sam-github** [comment]
The TSC meetings are under agendaed at the moment (#792), so perhaps we can use the timeslot, have one agenda item, and talk to H1/review the vulnerabilities? But I guess it would all have to happen in the private part of the meeting. I wouldn't want to ask the H1 folks to wait around while we go through public agenda items to get to the private part.

**Comment by mhdawson** [comment]
@sam-github we could try to plan to have the review in the second 1/2 hour and then make sure we end the public section by then. Do you think that would be workable?

**Comment by sam-github** [comment]
As long as we can invite people for a specific time. But we don't even know their availability, we're assuming we can pick any time that works for us. It might be better to move this to email with H1.

@vdeturckheim what are contact emails for the H1 people we'd want to talk to? Or is there a slack channel we can move that into? I don't think the H1 people are on github here.

**Comment by mralekzandr** [comment]
Hey everyone! We can keep the chat here if it's easier for y'all; I created a github account specifically for node.js ecosystem team communications, so I'm happy to be here for you all, too.

I'm definitely open and available to any style of meeting -whatever works best for you. Everyone here does node.js core stuff on a volunteer basis with their own time; HackerOne is my primary job. So I can be flexible!

Keep in mind that I'm in the U.S., Central Time Zone (1 hour behind Eastern, 2 hours ahead of Pacific). My workday starts at 8am CT, but I'm very happy to jump on a call earlier than that once a month, if necessary.

Feel free to tag me here directly!

**Comment by mralekzandr** [comment]
(BTW - This is Alek, H1 Program Manager :D )

**Comment by sam-github** [comment]
@mhdawson can you make space in a TSC meeting for @mralekzandr to join?

We should do this in the next week or so, I have open questions about the issue lifecycle in H1, I'd like to close and possibly publish some of the existing issues, but will need some guidance.

**Comment by sam-github** [comment]
Related: https://github.com/nodejs/TSC/pull/799

**Comment by mhdawson** [comment]
@mralekzandr are you available for the next meeting which is 11-12 EST. If so maybe we can keep the regular agenda to 30 mins and make the second half of the call (11:30-12:00) be used for H1 status meting.

**Comment by mralekzandr** [comment]
@mhdawson which day? (sorry if it's posted somewhere, I'm not yet super familiar with the UI of GitHub)

**Comment by mhdawson** [comment]
Sorry should have added that Wed Jan 15.  For future instances calendar is available at nodejs.org/calendar

**Comment by mralekzandr** [comment]
Perfect, I just synced that with my own calendar. I can definitely join for the latter half of the meeting! I didn't see a link to join the call, though?

**Comment by mhdawson** [comment]
The link will be https://zoom.us/j/611357642 (will also be in the issue created in the repo for the meeting on Monday).

I'll need to get you the password.  Can you send me an email to the address associated with my Github account and then I can get you the password.

**Comment by mhdawson** [comment]
@mralekzandr ^^^

**Comment by sam-github** [comment]
IMed you the email @mhdawson

**Comment by mralekzandr** [comment]
thank you @sam-github and @mhdawson

**Comment by sam-github** [comment]
We'll do this periodically, but issue doesn't need to remain open.
