### ISSUE TITLE
Request For Docs: Starting a team or non-top level WG

### ISSUE THREAD

**Issue by wesleytodd** [nodejs/TSC#795]
At the collab summit we discussed starting up a "web frameworks wg" with the goal of bringing together the authors of the primary web frameworks in the ecosystem to a shared place to discuss both how node core could better support them as well as how we can collaborate more.

I was looking around here and found docs on starting a chartered wg, but I could not find anything on how to start something more like the [tooling team](https://github.com/nodejs/tooling) or the [package maintenance wg](https://github.com/nodejs/package-maintenance).  If I understand correctly both of these are non-chartered groups, which seems like a reasonable place to start for us.

Is there something I am missing?  Can we piggyback off the existing docs for this use case? Do we need to draft a PR with a new guide?

**Comment by Trott** [comment]
If you have an idea of initial membership, you can request the GitHub team with an issue in the nodejs/admin repo.  Similarly, if you want the group to have a repository, you can request it there too. If you have a TSC and/or CommComm person who can help you champion the idea, that can help smooth things a bit too.

**Comment by wesleytodd** [comment]
Maybe @mcollina, @MylesBorins or @jasnell can chime in, they were involved in the discussion?  I will open the admin issue and yes we will want a repo.

Before we make that we will probably want to finalize the name (which we had not yet done), so adding a few other interested parties:

@ghermeto @dougwilson @Ethan-Arrowood @retrohacker

**Comment by dougwilson** [comment]
I'd be interested in participating.

**Comment by gireeshpunathil** [comment]
@wesleytodd - can you elaborate on what would be the goal and scope of the wg that is not covered in the package maintenance wg? I am just trying to confirm there are no overlaps.

**Comment by wesleytodd** [comment]
It would be a very different scope.  This would be focused around how the core http(1/2/3) and other related apis fit the needs of the web frameworks (express, fastify, restify, etc).  It would also give the maintainers a forum to discuss issues which span the different projects.  The package maintenance working group is generally about maintaining packages and the only reason Express is discussed so much there is because it is a pilot project for the work.  Does that help clear it up?

**Comment by jasnell** [comment]
I'm definitely interested in participating tho because of time activity may be a bit limited. My key interest is in what we can do in core to better support framework implementations, particularly around http2 and http3.

**Comment by retrohacker** [comment]
restify team here. We would be interested in participating.

**Comment by wesleytodd** [comment]
Ok, I will close this issue in favor of the admin one, as it has turned into more orginization of the WG.  But my original question still stands, are there docs we should write so that others who want to start WGs or teams know where to get started without asking?

**Comment by wesleytodd** [comment]
Thanks @MylesBorins, I just missed it!  For future reference: https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md#teams
