### ISSUE TITLE
TSC consensus on Async storage API in core

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#803]
This PR was a result of discussions at the last Diagnostic Summit where the participants agreed having an async storage API in core would be useful.

There is currently an objection in the PR to bringing such an API into core. See - introduce async-storage API [#26540](https://github.com/nodejs/node/pull/26540) for more details.

This issue is to see if we have consensus on the specific question:

> Should an async storage API API be in core versus user land.  

The specifics of what that API will lock like and when the PR itself is ready to land will continue to be discussed in the PR itself.

In the TSC meeting this week the consensus of the people in the meeting was that that the TSC should reach consensus and community that in the PR sooner than later.

Please add your +1, 0, -1 to this issue along with any questions/comments/discussion and ideally some info as to why you lean one direction or the other.

@nodejs/tsc

**Comment by jasnell** [comment]
I'm +1 on landing an async storage impl in core. Whether or not the current option is the right implementation, I do not yet have an opinion.

**Comment by targos** [comment]
+1, same as @jasnell

**Comment by addaleax** [comment]
I’m neutral on this. My personal preference would be vendoring in an npm module, that can also be new and based off the current PR and maintained inside the nodejs org, but I don’t feel too strongly about that either.

**Comment by cjihrig** [comment]
I'm +1 to having an implementation. I'd be OK with vendoring in a module as long as steps are taken to make it behave like other core modules for a more consistent developer experience.

**Comment by danbev** [comment]
+1 on having such an implementation. I've taken a look at the suggested API in the pull request but don't have any experience with npm modules that provide such functionality,  so I don't really have anything to compare with at this stage regarding if this is the implementation that we should go with or not.

**Comment by Trott** [comment]
I'm +0 on having something in core for this, with no opinion on the implementation. I guess that should count as neutral/abstain but that I'm willing to move to a +1 if I'm the tie-breaking vote or something.

**Comment by mcollina** [comment]
I'm +1 on adding an implementation

**Comment by BethGriggs** [comment]
+1 to adding an implementation

**Comment by apapirovski** [comment]
+1, same as @jasnell

**Comment by gabrielschulhof** [comment]
I'm of the same opinion as @Trott.

**Comment by mhdawson** [comment]
+1 for adding an implementation

**Comment by gireeshpunathil** [comment]
I have approved the PR, but making my vote explicit here, +1. My rational:
 - functional: this feature can be leveraged by many workloads such as web, ml, etc.
 - performance / footprint: my theory is that this feature can eliminate a good amount of closure functions
 - diagnostics: my theory is that this feature can eliminate monkey-patching

being in core can help evolve, optimize and adopt fast IMO.

**Comment by Trott** [comment]
With 9 TSC +1s and 3 abstentions, agreement to clear the objection to having the feature in core seems secure if this comes to a vote. That said, we're seeking consensus here so if any TSC members who object, they should definitely say something.

Again, this is about whether the feature should be in core, not whether any particular implementation is the right one or that particular PR should land.

**Comment by MylesBorins** [comment]
I abstain

**Comment by mhdawson** [comment]
@nodejs/tsc we'll touch on briefly in the meeting this week and unless we have objections before then or in the meeting assume that consensus has been reached.

**Comment by mhdawson** [comment]
No objections in the TSC meeting today.  We have consensus that we want an Async storage API in core. Will comment on issue then close.

**Comment by mhdawson** [comment]
Commented: https://github.com/nodejs/node/pull/26540#issuecomment-577396606
