### ISSUE TITLE
Updated GitHub repo description

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#806]
It had said "Node.js Foundation Technical Steering Committee". I changed it to "Node.js Technical Steering Committee". Anyone have a better idea for a description?

**Comment by Trott** [comment]
The @nodejs/community-committee repo  description could use a similar edit.

**Comment by Trott** [comment]
> The @nodejs/community-committee repo description could use a similar edit.

Ah, I see you already opened https://github.com/nodejs/community-committee/issues/575 for that.

**Comment by mhdawson** [comment]
I think this was for an FYI, since its been over a month I think we can close it. @MylesBorins let me know if that was not the right thing to do.
