### ISSUE TITLE
Review meeting date times ?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#809]
May be time to review the day/times for the TSC meetings.  https://github.com/nodejs/TSC/issues/808#issuecomment-579754507

@targos sounds like Wednesday is not good for you at all. @nodejs/tsc are people open to looking to move to another day? From past conversations I think we'd tried to keep all instances on the same day is that still the case or should we consider different days in addition to different times?

**Comment by ChALkeR** [comment]
Please also update the `valid at` column _even if your timeslots were not updated_ so that we can tell how actual the data is =).

**Comment by mhdawson** [comment]
I wonder if we should also discuss a different day based on the comment by @targos.  Possibly a timeslot on Thursday?

**Comment by gabrielschulhof** [comment]
Thursdays would work better for me as well.

**Comment by mcollina** [comment]
I'm good on both Wednesdays and Thursdays.
I would prefer to avoid Mondays, Tuesdays and Fridays.

**Comment by targos** [comment]
Thursdays work for me. If we do multiple days we'll need multiple spreadsheets

**Comment by Trott** [comment]
FWIW, Wednesdays are much better than Tuesdays or Thursdays for me.

**Comment by mhdawson** [comment]
I've added another sheet for Thursday.  I have a feeling we are going to need to use 2 days.

**Comment by ChALkeR** [comment]
Given the current data, it's likely that we will have either 2 or 3 (out of 3) timeslots on Thursdays.
We don't have about half of the data confirmed yet. @nodejs/tsc ping =).

**Comment by mhdawson** [comment]
@ChALkeR at this point we probably have the data we are going to get.  Can you pull generate a recommendation from the data?

**Comment by ChALkeR** [comment]
@mhdawson data updated (on the third page of the sheet).

Seems like two main alternatives (times not mentioned on a purpose -- those are present in the table, but I don't want the specific timeslots to affect the generic decision we make here):

### Option 1. Three timeslots (different days)
```
  participation: { avg: .731, min: .389, stdev: .1754, fair: .9529, n5: 15 }
  percentages: 95,95,94,94,89,89,85,80,80,65,64,64,64,64,58,49,49,39
  interaction: { avg: .529, min: .0729, stdev: .194, fair: .598, n5: 86 }
  meetings: { probs: [ .997, .999, .996 ], avg: [ 13.25, 13.26, 13.07 ] }
```
One person at ~40%, two at ~50%, 6 at or above ~60%, 3 at or above ~80%, 6 at or above ~90%.
Average ~73%.
Interaction at ~60%.

The downside here is that it brings one person significantly below 50% (to 40%) participation.

### Option 2. Two timeslots (different days)
```
  participation: { avg: .78, min: .48, stdev: .215, fair: .9766, n5: 12 }
  percentages: 95,95,95,95,95,95,94,94,94,94,94,72,48,48,48,48,48,48
  interaction: { avg: .601, min: .0189, stdev: .253, fair: .457, n5: 66 }
  meetings: { probs: [ 1, 1 ], avg: [ 13.83, 14.25 ] }
```
6 persons at ~50%, one at ~70%, everyone else (11) at above 90%.
Average ~78%.
Interaction at ~46%.

The downside here is interaction -- this decreases interaction between people. In particular, there are going to be more pairs of people who are very unlikely to ever be present on the same call.

**Comment by ChALkeR** [comment]
@mhdawson One more note: it seems that not everybody confirmed Thursdays yet, and I see at least one person whose data has the potential of shifting the optimal timeslots there.

**Comment by Trott** [comment]
We should probably add availability data for @codebytere and @mmarchini and see if anything changes. (The other two current nominees, Ruben and Gireesh, are already in the spreadsheet. And the recent emeritus, Sakthipriyan, has been removed from the spreadsheet. So the spreadsheet is up-to-date otherwise.)

**Comment by Trott** [comment]
> We should probably add availability data for @codebytere and @mmarchini and see if anything changes.

I'll email them the link along with the "please do not share this information" caveat.

**Comment by Trott** [comment]
Also, daylight savings time change happens in the U.S. this weekend, so everyone here will probably have to update their data again. Whee!

**Comment by mhdawson** [comment]
Ok given the daylight savings time can we ask that everybody @nodejs/tsc updates their entries and we'll look at the results in a week. Hopefully, we'll have data from @codebytere and @mmarchini as well as updates from the rest of the TSC by then.

**Comment by mhdawson** [comment]
@nodejs/tsc I  think we'll all have shifted (if a shift was going to occur next week). Please make sure to have updated your entries by end of this week.

@ChALkeR can you do another pass at good times next monday?

**Comment by mhdawson** [comment]
@ChALkeR ping?

**Comment by ChALkeR** [comment]
@mhdawson sorry for the delay -- recent events stir everything.

Two main variants now:
### Two timeslots (two days)
Five people at about ~50%, 4 at ~60%, all rest above 70%.
Average 72%.

The downside is that there are at lest two (and probably several pairs of) people who are likely to be never present on the same meeting.
```
  participation: { avg: .72, min: .484, stdev: .1987, fair: .9772, n5: 14 }
  percentages: 95,95,95,95,95,95,94,87,72,72,57,57,57,57,48,48,48,48,48
  interaction: { avg: .512, min: .019, stdev: .224, fair: .462, n5: 77 }
  meetings: { probs: [ .998, 1 ], avg: [ 13.16, 14.21 ] }
```
### Two timeslots (one day)
Six people at about ~50%, all rest above 70%.
Average 76%.

Very similar to the previous one, one person drops from~60% to ~50%, some others go up, average is increased, somewhat higher interaction. Same downside.
```
times: [ 38, 44 ]
  participation: { avg: .762, min: .48, stdev: .204, fair: .9769, n5: 13 }
  percentages: 95,95,95,95,95,95,94,94,94,87,72,72,72,48,48,48,48,48,48
  interaction: { avg: .574, min: .0189, stdev: .236, fair: .479, n5: 78 }
  meetings: { probs: [ 1, 1 ], avg: [ 14.67, 14.28 ] }
```
### Three timeslots (two days)
One person at ~40%, one at ~50%, all rest above 60%.
Average 75% -- similar to the previous one.

The positive side is that minimum interaction is higher -- each two people _can_ have some possibility of meeting at a same timeslot.
```
  participation: { avg: .749, min: .39, stdev: .172, fair: .9564, n5: 17 }
  percentages: 95,95,95,95,94,94,90,90,70,69,65,64,64,64,64,64,64,49,39
  interaction: { avg: .555, min: .076, stdev: .1964, fair: .599, n5: 108 }
  meetings: { probs: [ 1, 1, 1 ], avg: [ 14.22, 14.21, 14.28 ] }
```

**Comment by ChALkeR** [comment]
Please disregard the previous comment, I missed one row.
Recalculating...

**Comment by ChALkeR** [comment]
@mhdawson sorry for the delay -- recent events stir everything.

Two main variants now:
### Option 1. Two timeslots (one day)
6 people at about ~50%, 3 at ~60%, 1 at ~70%, all rest above 90% (10).
Average 74%.

The downside is that there are at lest two (and probably several pairs of) people who are likely to be never present on the same meeting.

The positive side is that everyone is at almost 50% or above.
```
  participation: { avg: .74, min: .484, stdev: .212, fair: .9771, n5: 14 }
  percentages: 95,95,95,95,95,95,94,94,94,94,72,57,57,57,48,48,48,48,48,48
  interaction: { avg: .542, min: .019, stdev: .243, fair: .451, n5: 87 }
  meetings: { probs: [ .999, 1 ], avg: [ 14.41, 15.23 ] }
```

### Option 2. Three timeslots (two days)
Two persons at ~40%, one at ~50%, all rest above 60% (8 above 90%).
Average 73% -- similar to the previous one.

The positive side is that minimum interaction is higher -- each two people _can_ have some possibility of meeting at a same timeslot.
Also, this brings 3 people from ~50% to ~65% (and lowers stdev).

On the downside, this makes things harder for two people, bringing them from ~50% down to ~40%.

```
  participation: { avg: .73, min: .39, stdev: .1847, fair: .9511, n5: 17 }
  percentages: 95,95,95,95,94,94,90,90,70,69,65,64,64,64,64,64,64,49,39,39
  interaction: { avg: .528, min: .0759, stdev: .205, fair: .557, n5: 108 }
  meetings: { probs: [ .997, .999, 1 ], avg: [ 14.24, 14.41, 15.23 ] }
```
---
Times not included on a purpose to avoid unintended bias, but one can look them up in the table on the third page (by searching for matching blocks).

**Comment by mhdawson** [comment]
My opinion is that taking people down from 50% to 40% is not worth the benefit of having greater possibility of interaction in meetings. If it was 90% to 80% that might be different but those at 50% are already challenged in terms of the meeting times and going down even further I don't think would be the right choice.

**Comment by ChALkeR** [comment]
@mhdawson To clarify: the difference is not just in bringing two people from 50% to 40% vs increasing interaction, there is a bunch of differences between the two options, e.g. the second one also brings three people from 50% to 65%.

But yes, that might be not worthwhile.

Let's have a quick reaction-based poll here:
* :+1: – option 1
* :tada: – option 2

I personally abstain, mostly because I prepared the poll.

**Comment by mcollina** [comment]
It's not exactly clear what are the timeslots. I think that'd be helpful.

**Comment by ChALkeR** [comment]
@mcollina I did not mention the timeslots on a purpose, to not unintentionally bias people towards their personally convenient timeslots as opposed to what option seems more appropriate.

One could look them up the spreadsheet as I mentioned above, but I'm not sure if this a good idea. I'm not personally because I might be biased.

**Comment by Trott** [comment]
@ChALkeR Is it safe to assume you explored a 4-timeslot option but that it didn't have any reasonably superior options?

**Comment by ChALkeR** [comment]
@Trott No, that didn't happen because I used the web version that has that disabled.
I will recheck with 4-timeslot option today.

**Comment by ChALkeR** [comment]
@Trott, actually, there is a number of 4-timeslot variants which seem better than both of those.

**Comment by ChALkeR** [comment]
E.g. this one:
```
times: [ 14, 39, 44, 45 ]
  participation: { avg: .723, min: .484, stdev: .1665, fair: .9787, n5: 17 }
  percentages: 95,95,94,94,91,91,84,75,72,72,72,72,68,60,60,53,53,48,48,48
  interaction: { avg: .517, min: .0616, stdev: .1895, fair: .556, n5: 92 }
  meetings: { probs: [ .997, .999, 1, .996 ], avg: [ 14.24, 14.41, 15.23, 14.05 ] }
```
One meeting at 14 UTC on Wednesday, the remaining ones on Thursday at 15, 20, 21 UTC.

WDYT?

**Comment by ChALkeR** [comment]
Ok, given that a lot of people weighted in on the 1/2 option and there is almost a draw, also we have a 4-slot option now, let me reveal the times involved.

### Timeslots:
1. 2 timeslots: `39, 44` (15, 20 UTC Thu), **74%** avg.
2. 3 timeslots: `14, 39, 44` (14 UTC on Wed + 15, 20 UTC Thu), **73%** avg.
3. 4 timeslots: `14, 39, 44, 45` (14 UTC on Wed + 15, 20, 21 UTC Thu), **72.3%** avg.
    Would make sense to make it in the order of `14, 45, 39, 44`, for example.

### Meeting averages
* **14 UTC on Wed** -- 99.7% chance, 14.24 people avg,
* **15 UTC on Thu** -- 99.9% chance, 14.41 people avg,
* **20 UTC on Thu** -- >99.9% chance, 15.23 people avg,
* **21 UTC on Thu** -- 99.6% chance, 14.05 people avg.

### Participation percentages:
```
1: 95,95,95,95,95,95,94,94,94,94,72,57,57,57,48,48,48,48,48,48
2: 95,95,95,95,94,94,90,90,70,69,65,64,64,64,64,64,64,49,39,39
3: 95,95,94,94,91,91,84,75,72,72,72,72,68,60,60,53,53,48,48,48
```

### Interaction percentages:
```
1: 90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,88,88,88,69,69,69,69,69,69,68,68,68,68,55,55,55,55,55,55,55,55,55,55,55,55,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,50,50,50,47,47,47,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,45,45,45,45,45,45,45,45,45,45,45,45,45,25,25,25,25,10,10,10,10,10,10,10,10,10,10,10,10,2,2,2,2,2,2,2,2
2: 90,90,90,90,90,90,89,89,89,89,89,89,89,89,88,85,85,85,85,85,85,85,85,84,84,84,84,81,66,66,66,66,66,66,66,66,65,65,65,65,65,64,62,62,62,62,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,59,59,56,56,56,56,56,56,56,56,56,56,49,49,46,46,46,46,46,46,46,46,46,46,44,44,42,39,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,36,36,36,36,34,34,34,32,32,32,32,32,32,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,17,17,17,17,8,8,8,8,8,8,8,8
3: 90,89,89,89,89,88,86,86,86,86,86,86,85,85,83,79,79,79,79,76,75,72,72,71,71,71,70,69,69,68,68,68,68,68,68,68,68,68,68,68,68,67,67,67,67,66,65,64,64,64,64,64,64,64,64,64,64,64,64,63,61,60,59,58,57,57,57,57,57,57,57,57,57,57,57,56,56,55,55,54,54,54,53,52,52,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,49,49,48,48,48,47,47,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,45,45,45,45,45,45,45,45,45,45,45,45,45,45,43,43,43,42,42,42,42,42,42,42,42,40,40,39,38,36,35,35,33,28,28,28,28,28,28,28,28,25,25,25,25,24,24,24,24,24,24,18,18,13,13,13,6,6,6,6,6,6
```

**Comment by ChALkeR** [comment]
It looks like the 4-slot variant is better in general, so I'm going to propose that as the main variant.
Please let me know if anyone thinks that's too complex.

**Comment by mcollina** [comment]
I'm good with everything, however if the 4 variants is chosen it's better we alternate the times like so:

14 UTC on Wed
20 UTC on Thu
15 UTC on Thu
21 UTC on Thu

So that the people that can meet earlier in the day have a chance to meet every other week anyway.

**Comment by Trott** [comment]
Sounds good to me.

**Comment by targos** [comment]
SGTM

**Comment by ChALkeR** [comment]
@mcollina In the post above, I mentioned this order: `14, 45, 39, 44`, which is:
1. 14 UTC on Wednesday
2. 21 UTC on Thursday
3. 15 UTC on Thursday
4. 20 UTC on Thursday

I don't see much difference between the two of those, anything of those two should work I think :-).
14-20-15-21 is also fine.

**Comment by mcollina** [comment]
I did not understand what 45 and 44 where at all.

**Comment by ChALkeR** [comment]
@mcollina Ah. Time in hours minus 00:00 UTC on Wednesday, that's how the timeslots are numbered in the spreadsheet.

**Comment by apapirovski** [comment]
The 4 time slots + thu are way better for me. Too many standing mtgs on Wed that I can't move :(

**Comment by mhdawson** [comment]
Calender updated, closing.

**Comment by targos** [comment]
Next meeting: 

Thursday, 16 April 2020, 15:00:00 UTC
