### ISSUE TITLE
Nominating Ruben Bridgewater (BridgeAR) to the TSC

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#811]
No objections from the TSC so far and @BridgeAR has given a 👍 so I'm nominating him for the TSC. Ruben has consistently shown a passion for driving Node.js forward and has an affinity for all the deepest darkest parts of the Node.js JavaScript codebase where few brave to venture.

**Comment by BridgeAR** [comment]
I am honored to be nominated to the TSC! I will do what I can to further improve Node.js.

**Comment by mhdawson** [comment]
Those in  todays TSC meeting considered +1: in addition to comments in this issue:
* Anna Henningsen @addaleax (TSC)
* Anatoli Papirovski @apapirovski (TSC)
* Beth Griggs @BethGriggs (TSC)
* Сковорода Никита Андреевич @ChALkeR (TSC)
* Franziska Hinkelmann @fhinkel (TSC)
* Joyee Cheung @joyeecheung (TSC)
* Matteo Collina @mcollina (TSC)
* Michael Dawson @mhdawson (TSC)
* Rich Trott @Trott (TSC)
* Sam Roberts @sam-github (TSC)
* Tobias Nießen @tniessen (TSC)
* Myles Borins @MylesBorins (TSC)
* Sam Roberts @sam-github (TSC)

**Comment by mhdawson** [comment]
My count is 15 based on those in the meeting today and positive comments on this issue which makes it official. @BridgeAR welcome.

**Comment by mhdawson** [comment]
Starting onboarding checklist

**Comment by mhdawson** [comment]
- [ ] Confirm that the new member has read, understands, and agrees to uphold the
  [Code of Conduct](https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md).
- [ ]  Add the new member to the `@nodejs/tsc` and `@nodejs/security-tsc` teams.
- [ ] Change the new member's role in the GitHub `nodejs` organization to `Owner`.
- [ ] Add them to the `@nodejs-private` org and with an `Owner` role.
* Add them to the `@nodejs-private/security-tsc` team.
* Invite them to the HackerOne [Node.js team](https://hackerone.com/nodejs/team_members).
* Add them to the `tsc` and `crypto-export` mailing lists.
* Update the `@nodejs/node` repository README to reflect membership in the TSC.
* Update https://github.com/nodejs/create-node-meeting-artifacts/blob/master/templates/invited_tsc and https://github.com/nodejs/create-node-meeting-artifacts/blob/master/templates/observers_tsc to reflect membership in the TSC.

**Comment by mhdawson** [comment]
PR to add to meeting invites: https://github.com/nodejs/create-node-meeting-artifacts/pull/88

**Comment by mhdawson** [comment]
PR add to add to Node.js README.md https://github.com/nodejs/node/pull/32213

**Comment by mhdawson** [comment]
PR to add to mailing lists: https://github.com/nodejs/email/pull/153

**Comment by mhdawson** [comment]
Mostly waiting on PR approvals now.
