### ISSUE TITLE
Sorting out Intl vs I18n labels, teams, and repos

### ISSUE THREAD

**Issue by sam-github** [nodejs/TSC#813]
I think something is out of sync with naming, we seem to have both `i18n` and `intl`, but they mean different things in different contexts, and sometimes seem to switch meaning.

Repos:
- https://github.com/nodejs/i18n
- https://github.com/nodejs/Intl  Described as the "new i18n", but its archived and the (old?) i18n above is not.

> ?!?!

Teams:
- https://github.com/orgs/nodejs/teams/i18n
- https://github.com/orgs/nodejs/teams/intl

> These team's descriptions point to their corresponding github repos above, but that means that there isn't a team that refers to the node core i18n support. Does such a  team exist, or is it just @srloomis all the time?

- https://github.com/orgs/nodejs/teams/core/teams

> No team for ICU and related i18n APIs?

Labels:
- https://github.com/nodejs/node/labels/intl "Issues and PRs related to the i18n implementation"

> The `intl` label is for `i18n`? That's not confusing at all... :-) can I rename the label to `i18n`?

I'm not sure what should be done with the teams and repos.... perhaps
- nodejs/intl should, in fact, be the new (and only) repo?
- And nodejs/i18n should be archived?
- And at-nodejs/intl should be the nodejs/intl team (as it is)?
- And at-nodejs/i18n should be the nodejs/node/core i18n team, associated with the `i18n` label?

cc: @srloomis @nodejs/intl @nodejs/i18n

**Comment by srl295** [comment]
For reference: https://github.com/nodejs/TSC/issues/353

**Comment by srl295** [comment]
- Could the `Intl` team be renamed `@nodejs/i18n/api` or some such?

> can I rename the label to i18n
Yes, good idea.

**Comment by srl295** [comment]
> https://github.com/nodejs/i18n 

this _is_ the new i18n

> https://github.com/nodejs/Intl Described as the "new i18n", but its archived and the (old?) i18n above is not.

I was trying to use the description of `nodejs/Intl` there as a redirection: `Node.js Intl Team (see new i18n WG)` with URL `https://github.com/nodejs/TSC/issues/353`.  We could unarchive, reword, and rearchive the dechartered `nodejs/Intl`.  @sam-github do you have suggested better wording?

**Comment by sam-github** [comment]
`see new` --> `replaced by the` ?

**Comment by srl295** [comment]
> replaced by the

https://github.com/nodejs/Intl - better?

**Comment by srl295** [comment]
@obensource @nodejs/i18n — I have requested to move the `Intl` team (now called `i18n-api`) under `i18n` — says it's pending approval.

**Comment by srl295** [comment]
I renamed the `Intl` label to `i18n-api`.

So now, `i18n-api` consistently refers to API related stuff.

**Comment by obensource** [comment]
@srl295 approved! 🚀

**Comment by srl295** [comment]
> These team's descriptions point to their corresponding github repos above, but that means that there isn't a team that refers to the node core i18n support. Does such a team exist, or is it just @srloomis all the time? 

Actually there are a couple of others in @nodejs/i18n-api 

@sam-github I think all issues are resolved here, close this? On the i18n-WG side there are issues such as https://github.com/nodejs/i18n/issues/210 to improve the WG's docs and such, but I don't think that should keep this #813 open.
