### ISSUE TITLE
Ability for website team to transfer issues to nodejs/help

### ISSUE THREAD

**Issue by nschonni** [nodejs/TSC#818]
Looks like only Write permissions are required now to allow members to transfer issues between repositories https://github.blog/changelog/2019-05-29-improvements-to-issue-transfer-permissions/ 
This would allow the occasional support issue that lands on nodejs/nodejs.org repo to transfer the issues to a better place rather than just closing them and asking them to open a new issue.

The TSC README indicates that that repo is delegated to Evangelism Working Group, but that repo is closed, so I'm opening the issue here.

**Comment by addaleax** [comment]
So, what you need is write permissions to nodejs/help for @​nodejs/website? Sounds good to me :+1:

**Comment by nschonni** [comment]
Yup, I figure that would be a good landing zone, and folks in that repo could transfer things to nodejs/node if appropriate afterwards.

**Comment by mhdawson** [comment]
As an FYI to TSC members there are 158 members of the website team https://github.com/orgs/nodejs/teams/website

**Comment by mcollina** [comment]
How many of those are active?
Il 17 feb 2020, 14:39 +0000, Michael Dawson <notifications@github.com>, ha scritto:

**Comment by Trott** [comment]
> How many of those are active?

Of the 158, I'd guess that fewer than 20 are active more than sporadically.  But I'm not sure that's much worse than the ratio for the Collaborators team, and I'm not sure that giving more people access to the help repo would be a bad thing.

**Comment by ChALkeR** [comment]
We could either create a sub-team which could move issues, or just give write access to the help repo to the website team. Both sounds good to me, and the latter would probably be easier.

**Comment by bnb** [comment]
>but I'm not sure that's much worse than the ratio for the Collaborators team, and I'm not sure that giving more people access to the help repo would be a bad thing.


I would generally agree with this for the express purpose of moving issues, which I've seen the need for in quite a few repos - not just one or two.

**Comment by nschonni** [comment]
Maybe we can test this out with the website team, then extend it to the Collaborators if it works out

**Comment by targos** [comment]
Collaborators already have write access to the help repo. I'm +1 on adding the website team.

**Comment by Trott** [comment]
Website team added to the help repo. (Sorry if that messes with anyone's notifications....)
