### ISSUE TITLE
Archival of the node-chakracore repo

### ISSUE THREAD

**Issue by cjihrig** [nodejs/TSC#821]
TL;DR - Microsoft doesn't plan to maintain the repo anymore.

See https://github.com/nodejs/node-chakracore/issues/628 for all of the details.

I'd like to archive this repo. Is anyone opposed to doing so?

**Comment by jasnell** [comment]
I had a brief chat with @aruneshchandra a week or so ago. They are working on a deprecation strategy for node-chakracore with the folks they know were making use of it. It would likely be best to avoid archiving until after confirmation from msft that the deprecation process has been defined.

**Comment by jasnell** [comment]
That said, I'm +1 on archiving as soon as we get a go-ahead from the msft folks

**Comment by mhdawson** [comment]
+1 to archive once we have confirmation from the msft folks

**Comment by ChALkeR** [comment]
+1 to archive as soon as there is confirmation, but let's wait for a while until that happens

**Comment by divmain** [comment]
Hey everybody - thanks for being patient as we work things out on our end.  We have no objection to archiving `node-chakracore` at this time.

**Comment by cjihrig** [comment]
Thank you @divmain. I've gone ahead and archived it.

**Comment by chicoxyzzy** [comment]
Hello everyone. ChakraCore will be owned by community soon https://github.com/microsoft/ChakraCore/issues/6384. There are some discussions on making Node ChakraCore active again. Would it be possible to unarchieve the repo in future if work on Node ChakraCore will be resumed?

**Comment by cjihrig** [comment]
I'd personally be fine with unarchiving the repo if people plan to actively work on it. A revived effort could also live outside of the nodejs org.
