### ISSUE TITLE
Re-nominate @gireeshpunathil to TSC

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#829]
@gireeshpunathil  stepped down from the TSC as IBM was over the maximum numbers after one of the TSC members resigned.  As part of that discussion it was suggested we should re-nominate him as soon as the numbers were expanded. I'm formalizing that suggestion in this issue,

Once we confirm @BridgeAR (see https://github.com/nodejs/TSC/issues/811). I'd like to nominate @gireeshpunathil to rejoin the TSC.

I'd also suggest we can waive the usual 3 weeks of attending the TSC meetings as an observer due to his recent participation in the TSC over the last year.

**Comment by Trott** [comment]
> I'd also suggest we can waive the usual 3 weeks of attending the TSC meetings as an observer due to his recent participation in the TSC over the last year.

Yes, absolutely. That's an informal guideline. I don't think it's documented anywhere. So we can absolutely waive it at our discretion.

**Comment by Trott** [comment]
I do have a concern that may block this for a few weeks that I will email you (@mhdawson) and @gireeshpunathil about privately.

**Comment by cjihrig** [comment]
+1 to re-adding Gireesh as soon as possible.

**Comment by mhdawson** [comment]
@Trott thanks for the heads up,  even if it is blocked for a bit wanted to get the suggestion formalized and ready to go when it is appropriate.

**Comment by tniessen** [comment]
+1, as soon as the other issue is resolved

**Comment by sam-github** [comment]
+1 from me, and thanks again to @gireeshpunathil for graciously stepping down.

**Comment by jasnell** [comment]
+1

**Comment by danbev** [comment]
+1

**Comment by mcollina** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by danbev** [comment]
+1

lör 7 mars 2020 kl. 17:12 skrev Joyee Cheung <notifications@github.com>:

**Comment by mhdawson** [comment]
By my count we have >1/2 TSC as +1s and no objections. Considering approved will start on onboarding checklist. With the addition of the other 2 members we will also no longer be over the corporate limit for IBM.


- [ ] Confirm that the new member has read, understands, and agrees to uphold the
  [Code of Conduct](https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md).
  @gireeshpunathil can you comment in this issue confirming this.
- [ ] Add the new member to the `@nodejs/tsc` and `@nodejs/security-tsc` teams.
- [ ] Change the new member's role in the GitHub `nodejs` organization to `Owner`.
- [ ] Add them to the `@nodejs-private` org and with an `Owner` role.
- [ ] Add them to the `@nodejs-private/security-tsc` team.
- [ ] Invite them to the HackerOne [Node.js team](https://hackerone.com/nodejs/team_members).
- [ ] Add them to the `tsc` and `crypto-export` mailing lists.
- [ ] Update the `@nodejs/node` repository README to reflect membership in the TSC.
- [ ] Update https://github.com/nodejs/create-node-meeting-artifacts/blob/master/templates/invited_tsc and https://github.com/nodejs/create-node-meeting-artifacts/blob/master/templates/observers_tsc to reflect membership in the TSC.

**Comment by mhdawson** [comment]
PR to add to meeting issue generator: https://github.com/nodejs/create-node-meeting-artifacts/pull/89

**Comment by gireeshpunathil** [comment]
I confirm that I (re-)read and understood the said code of conduct. I pledge to uphold its values and maintain its standards

**Comment by mhdawson** [comment]
Checklist complete, closing.
