### ISSUE TITLE
Nominating Matheus Marchini (mmarchini) to the TSC

### ISSUE THREAD

**Issue by cjihrig** [nodejs/TSC#831]
I would like to nominate @mmarchini to the TSC. Matheus is a long time contributor to the Node project, particularly in the areas of diagnostics and post-mortem debugging.

There have been no objections from the private TSC discussion, and I have contacted Matheus privately to verify their interest.

**Comment by mhdawson** [comment]
+1

**Comment by danbev** [comment]
+1

**Comment by mcollina** [comment]
+1!

**Comment by jasnell** [comment]
+1

**Comment by mmarchini** [comment]
Thank you for the nomination! I'm honored and looking forward to help.

**Comment by joyeecheung** [comment]
+1

**Comment by fhinkel** [comment]
+1

**Comment by apapirovski** [comment]
+1

**Comment by gabrielschulhof** [comment]
+1

**Comment by MylesBorins** [comment]
+1

**Comment by addaleax** [comment]
+1

**Comment by mhdawson** [comment]
By my count we have >1/2 TSC as +1s and no objections. Considering approved will start on onboarding checklist.


- [ ] Confirm that the new member has read, understands, and agrees to uphold the
  [Code of Conduct](https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md).
  @mmarchini  can you comment in this issue confirming this.
- [ ] Add the new member to the `@nodejs/tsc` and `@nodejs/security-tsc` teams.
- [ ] Change the new member's role in the GitHub `nodejs` organization to `Owner`.
- [ ] Add them to the `@nodejs-private` org and with an `Owner` role.
- [ ] Add them to the `@nodejs-private/security-tsc` team.
- [ ] Invite them to the HackerOne [Node.js team](https://hackerone.com/nodejs/team_members).
- [ ] Add them to the `tsc` and `crypto-export` mailing lists.
- [ ] Update the `@nodejs/node` repository README to reflect membership in the TSC.
- [ ] Update https://github.com/nodejs/create-node-meeting-artifacts/blob/master/templates/invited_tsc and https://github.com/nodejs/create-node-meeting-artifacts/blob/master/templates/observers_tsc to reflect membership in the TSC.

**Comment by mmarchini** [comment]
I read and agree to uphold the [Code of Conduct](https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md)

**Comment by mhdawson** [comment]
@mmarchini thanks!

**Comment by mhdawson** [comment]
PR to add to meeting issue generator: https://github.com/nodejs/create-node-meeting-artifacts/pull/89

**Comment by mhdawson** [comment]
Checklist complete, closing.
