### ISSUE TITLE
Election for the Voting Representative for the OpenJS Cross-Project-Council (TSC rep)

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#835]
It’s time to elect the Cross-Project-Council voting representatives for next term which starts on April 1st 2020. The current one is @mcollina.

See https://github.com/nodejs/admin/issues/472 for more detail.

Timeline is:
* March 9th Call for nominations for both CPC representatives
* March 16th Close nominations and open balloting for CPC representative
* March 23rd Close balloting and announce CPC representative
* March 23rd- Handover
* April 1st Transition complete

Please note the expectations of the voting CPC representative:
https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#voting-members

Also note: any member of the Node.js org can participate in the Cross Project Council as a regular member.
https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#regular-members
Similar to the practices in Node.js, the CPC follows the consensus seeking model and there is little difference between a voting rep of a project and a regular member. Becoming a regular member could be a good way to get involved if one is unsure of running for a voting member.

**Comment by mhdawson** [comment]
@nodejs/tsc please self-nominate in this issue if you are interested to run to be the Node.js TSC voting CPC representative.

**Comment by mcollina** [comment]
I'm happy to continue as the Voting Representative for Node.js.

**Comment by mhdawson** [comment]
Nominations are now closed. With a single volunteer I think we can confirm @mcollina. Lets discussion in the TSC meeting tomorrow.

@nodejs/tsc if there are any objections to confirming @mcollina please chime into this issue.  If we don't hear any by the end of the week (March 20) and we agree in the TSC meeting we'll confirm @mcollina for another year and close the issue.

**Comment by mhdawson** [comment]
Ok, no objections so @mcollina is officially our rep for the next year. @mcollina can you let the CPC know and then close this issue?
