### ISSUE TITLE
Logistics of organizing a TSC summit to discuss the future direction of Node.js

### ISSUE THREAD

**Issue by apapirovski** [nodejs/TSC#836]
Tying into https://github.com/nodejs/TSC/issues/797 and the discussion in today's TSC meeting, I'm opening up this issue as a discussion venue for how we can effectively organize a distributed event like this while allowing everyone from the TSC (and other interested parties) to participate.

**Comment by apapirovski** [comment]
I'm wondering if it makes sense to make this a more long-running event — 1-2 weeks with shorter time slots and perhaps incorporating @ChALkeR's idea of having multiple sessions on each topic to allow people from different timezones to contribute.

**Comment by jasnell** [comment]
> I'm wondering if it makes sense to make this a more long-running event — 1-2 weeks with shorter time slots each day and perhaps incorporating @ChALkeR's idea of having multiple sessions on each topic to allow people from different timezones to contribute.

I'm good with that approach

**Comment by mhdawson** [comment]
When you say shorter time slots each day, what did you have in mind?

**Comment by mhdawson** [comment]
We'd probably also want multiple time slots which are better/worse depending on the timezone. I'm thinking 2 different ones and possibly 2 hours at a time?

**Comment by mhdawson** [comment]
Been thinking about it to see what might make sense. It's really hard to cover all of the timezones.  The best I've come up with so far is the following:

* Assume sessions are 2 hours
* Assume starting at 9AM and ending by 6 is `Good`
* Assume starting at 8AM and ending by 8PM is `Tolerable`

Then we could look at these slots:

![image](https://user-images.githubusercontent.com/9373002/77793212-0efe8300-7040-11ea-8209-7319ed67b88c.png)

The result is at least one slot which is `Good` for each timezone, and at least one more that is `Tolerable`. There is also 1 more slot which is not `Impossible` for most of the timezones except for Pacific.

**Comment by mhdawson** [comment]
With the suggestion that we have 2 slots per topic to get broad coverage I'd then suggest we go in this order:

Topic 1 - Slot1, Slot3
Topic 2 - Slot2, Slot4
etc..

**Comment by mhdawson** [comment]
I'd also suggest we have people pre-register for topics/slots so that people don't go out of their way to get to a session that ends up not having enough attendees.

**Comment by gireeshpunathil** [comment]
assuming `bangalore === me` in this context, `starting at 8AM and ending by 8PM is Tolerable`  can be widened more towards right for that column alone (like ending by 11 PM is still tolerable for me), if it improves the schedule in any manner. (please ignore if it messes up an otherwise settled schedule)

**Comment by apapirovski** [comment]
Thanks for thinking this through @mhdawson — that seems a solid approach. Given the current lockdown, are we thinking we'll run this only during work days (Mon-Fri) or extend to weekends as well? I imagine there's obvious downsides to using the weekends but at the same time, we are far more likely to get good participation and engagement from everyone due to fewer conflicts. And since most people are sheltering in place, I imagine there aren't a ton of much better activities to do on the weekend...

**Comment by mhdawson** [comment]
Since next-10 effort (https://github.com/nodejs/next-10) is up and running believe we can close this
