### ISSUE TITLE
TSC Chair Election 2020 - proposed schedule

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#849]
May is the month for TSC Elections. The proposed schedule is:

April 16 - Call for nominations
April 30 - Close nominations
May 1 - Open balloting
May 15 - Announce Results
May 16-29- Handover
May 30 (or earlier if handover complete) Transition complete

This issue is to open the call for nominations.

Depending on the number of nominations we'll figure out if we need to have people write up something about why they would be a good fit for the position.

**Comment by mcollina** [comment]
+1

**Comment by mhdawson** [comment]
There was only one self-nomination (@mhdawson) in #851.

**Comment by mhdawson** [comment]
I think we still need either a vote or public consensus with no objections from the TSC for me to continue as the Chair.

@nodejs/tsc please chime in on this issue whether you'd like a private vote or an public issue for consensus.

**Comment by jasnell** [comment]
No objections here on not needing a vote. @nodejs/tsc ...?

![image](https://user-images.githubusercontent.com/439929/81019243-1cffaa80-8e1b-11ea-9419-49a27bc23037.png)

**Comment by gireeshpunathil** [comment]
@mhdawson continuing as chair: +1
not needing a voting: +1

**Comment by danbev** [comment]
+1 on not needing to vote

**Comment by joyeecheung** [comment]
+1 on not needing to vote

**Comment by mcollina** [comment]
+1 not needing a vote!

**Comment by targos** [comment]
+1 on not needing to vote

**Comment by sam-github** [comment]
+1 on not needing to vote

**Comment by BridgeAR** [comment]
+1 on not needing to vote

**Comment by addaleax** [comment]
+1 on not needing to vote

**Comment by MylesBorins** [comment]
+1 on not needing to vote

**Comment by tniessen** [comment]
+1 on not needing to vote

**Comment by mhdawson** [comment]
We agreed in the meeting yesterday that unless there were objections by today we'd consider this closed and I'd continue for the next year.
