### ISSUE TITLE
Collaboration and Contribution Process Review

### ISSUE THREAD

**Issue by bnb** [nodejs/TSC#864]
I briefly reached out to @mcollina about this who suggested I open an issue on the TSC repo:

I'm not sure if we've ever done a full review/reflective pass on our collaboration and contribution documents within the project (for example, the [TSC Charter](https://github.com/nodejs/TSC/blob/master/TSC-Charter.md) and [Working Groups](https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md) doc,).

It may perhaps be beneficial to collectively take a look at these processes (and any others!) and see both which parts may or may not be reflective of how we currently operate and which parts could be improved to allow us both as a project to work better *and* for the community to contribute effectively and meaningfully.

**Comment by Trott** [comment]
I think we're overdue to move whatever is of value in `Applications` elsewhere and then remove the directory in this repository. We don't have projects applying for membership anymore. They should go to the OpenJS Foundation instead, I would think.

**Comment by jasnell** [comment]
It's going to be easiest to start with a list of issues that may need to be addressed, otherwise it's going to be way too open ended.

**Comment by mcollina** [comment]
@bnb would you like to faciltiate this? I think having an approach from _outside_ the folks with Node.js commit access would be very interesting.

**Comment by boneskull** [comment]
(also collaborators who _would_ contribute more often, if not for the process. 🙂)

**Comment by bnb** [comment]
@mcollina sure. Is this something you'd want me to do inside of the TSC repo, inside of the Admin repo, or somewhere else?

**Comment by mcollina** [comment]
I think opening issues here is ok.

Having a fresh perspective on https://github.com/nodejs/node/blob/master/CONTRIBUTING.md and how we could simplify things.

**Comment by Trott** [comment]
> Having a fresh perspective on https://github.com/nodejs/node/blob/master/CONTRIBUTING.md and how we could simplify things.

Since most of us who are frequent contributors to the project also never look at that file, it's possible there's some pretty low-hanging fruit in there.  My immediate suggestions:

* Simplify language everywhere. Be brief, informative, and friendly.
* For issues:
  * Remove "How to Contribute in Issues".
  * Remove "Resolving a Bug Report". 
* For pull requests:
  * Remove the preamble that is before the table of contents.
  * Remove the lengthy section on "Reviewing pull requests". It's not that it isn't important; it's just irrelevant to someone wanting to *open* a pull request, which is who is most likely to be reading this. If we want to keep it, link to it in the contributors guide rather than having it all laid out here.

**Comment by mhdawson** [comment]
@bnb are you still planning to move this forward ?

**Comment by bnb** [comment]
@mhdawson good timing on this question 😅

I'd completely not remembers that I created it nor that I committed to it. After next week I'm planning on pretty aggressively focusing on open-source work for a bit, and I can prioritize this in that time.

**Comment by mmarchini** [comment]
That's something I've been thinking a lot about lately (especially in the context of https://github.com/nodejs/node/blob/master/CONTRIBUTING.md), and I'm eager to bounce off ideas with anyone who's also interested in this conversation :D

**Comment by mhdawson** [comment]
@bnb @mmarchini great to hear :)

**Comment by mhdawson** [comment]
@bnb, @mmarchini anything to report on this front?

**Comment by mmarchini** [comment]
Haven't done anything on this front lately.

**Comment by bnb** [comment]
I've not gotten a chance to work on this. Perhaps taking a slightly different approach - would anyone be interested in sitting down and pairing on it? If not, that's fine ❤️

**Comment by mhdawson** [comment]
I wonder if it might fit into - https://github.com/nodejs/next-10/issues/16.  We could target one of the upcoming Next-10 meetings to discuss? That would be a slightly larger pairing :)

**Comment by mhdawson** [comment]
The last comment on this was more than a year ago, while it would be great to make progress that's not happened for quite some time.  @bnb any objections to be closing this issue?
