### ISSUE TITLE
Self Nomination Larson Carter - YouTube

### ISSUE THREAD

**Issue by larson-carter** [nodejs/TSC#867]
I'm at it again.

I'm trying to involve myself as much as possible.

I do a bunch of renderings (After Effects, Premiere Pro) that I think would be perfect for releases. I do a lot of 3D animations that I could make for showcases.

I'd be happy to show some of my work. I also wouldn't mind helping upload YouTube videos after meetings or anything else.

Thank You!

**Comment by jasnell** [comment]
@larson-carter ... it's not clear what you're nominating yourself for here.

**Comment by larson-carter** [comment]
> @larson-carter ... it's not clear what you're nominating yourself for here.

I'm nominating myself to help out in any area where my skills for graphic rendering can be used. Hence the issue name YouTube area

**Comment by jasnell** [comment]
There's really nothing to self-nominate for at this point. There are many ways of getting involved with the Node.js project and nominations to become a collaborator must come after a history of making contributions. We do not have a "YouTube area".

Closing this as inactionable right now.
