### ISSUE TITLE
Nominating ronag to the security team

### ISSUE THREAD

**Issue by mcollina** [nodejs/TSC#875]
I would like to nominate @ronag to the security team as depicted in https://github.com/nodejs/TSC/blob/master/Security-Team.md.

@ronag contributions to http and http2 would help significantly the project as it's a critical part of our attack surface.

**Comment by jasnell** [comment]
If @ronag is interested, then +1

**Comment by Trott** [comment]
Assuming @ronag is interested, I strongly endorse this.

**Comment by ronag** [comment]
I'm interested.

**Comment by danbev** [comment]
+1

**Comment by addaleax** [comment]
+1

**Comment by cjihrig** [comment]
+1

**Comment by mhdawson** [comment]
@mcollina if you have not already I'm guessing you can do so and then close this issue.

**Comment by mcollina** [comment]
I have invited @ronag to all the relevant teams.

@ronag would you mind PR yourself to https://github.com/nodejs/TSC/blob/master/Security-Team.md#team-with-access-to-private-security-reports-against-nodejs?

**Comment by mhdawson** [comment]
@mcollina anything more to do on this or can it be closed?

**Comment by mcollina** [comment]
closed
