### ISSUE TITLE
TSC meeting on 02-Jul-2020

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#887]
Looks like the automated thing @mhdawson runs to create meeting issues didn't run this week? (Or else I am really bad at finding issues in the TSC repo for some reason today?) Maybe it was cron'ed out until the end of June 2020 only?

Anyway, my calendar says we have a meeting tomorrow (02-Jul-2020) at 8PM UTC, which is 1PM Pacific Time, 4PM Eastern Time, and... well, let's just leave this here until we get the more detailed usual issue and then we can close this.

/ping @nodejs/tsc for awareness

**Comment by richardlau** [comment]
> 
> 
> Looks like the automated thing @mhdawson runs to create meeting issues didn't run this week? 

It would involve someone figuring out permissions/secrets so that the issues can be created but maybe it's something that could be moved to a GitHub action on, say, the admin repo?

**Comment by gireeshpunathil** [comment]
the diag wg meeting that was supposed to be scheduled for 12.30 ET (10 mins from now) is also not showed up, so looks like an issue with the script

**Comment by BethGriggs** [comment]
> It would involve someone figuring out permissions/secrets so that the issues can be created but maybe it's something that could be moved to a GitHub action on, say, the admin repo?

It might be worth exploring migrating to https://github.com/pkgjs/meet

**Comment by mhdawson** [comment]
Sorry checking now

**Comment by mhdawson** [comment]
Ok here is there link for the meeting: https://github.com/nodejs/TSC/issues/888

**Comment by mhdawson** [comment]
For some reason the machine I've been running the generation scripts has been a bit flaky recently.
