### ISSUE TITLE
Resigning from CPC Voting Member

### ISSUE THREAD

**Issue by mcollina** [nodejs/TSC#898]
Hi Everyone!

I'm resigning as the CPC Voting Member for personal reasons that will require me scaling down my OSS time starting from November. 
I'm happy to continue on my role until a new member is elected as well as keep joining the CPC calls to guarantee a smooth transition.

(If you do not know about those personal reasons and you are curious, feel free to contact me privately. I'm happy and everything is good!)

**Comment by mcollina** [comment]
We need to decide who will take my place. Are there any volunteers from the @nodejs/tsc?

As per the meeting of the https://github.com/nodejs/TSC/issues/900, please self-nominate in two weeks: the deadline is on the 20th of August.

**Comment by mmarchini** [comment]
I would like to volunteer

**Comment by joesepi** [comment]
Please consider me a resource for any questions or any assistance in this transition. Thanks

**Comment by mcollina** [comment]
No objections :), opening the PR to the cpc repo now.
