### ISSUE TITLE
Node.js TSC Survey: Unhandled Promises

### ISSUE THREAD

**Issue by joesepi** [nodejs/TSC#902]
Hey friends. I'm here to close the loop on spinning up this survey. Sorry for the delay.

Everything should be in place. See survey link below and respond in this issue if it needs updates/fixes.

_Note: Survey Monkey doesn't allow markdown or code formatting in answers, so we decided to use bold to denote actual code in answers. Not ideal but is what it is._

The foundation suggested (and I think its a great idea) to do a blog post about the survey and follow up with results. I'm working with @mmarchini to quickly put that together, but it doesn't need to hold up the survey if we aren't fast enough, although it would be best to put it all out there at once.

Survey: https://www.surveymonkey.com/r/FTJM7YD
(Let's be sure its reviewed before blasting it out to the world)

References:
- [survey in TSC repo](https://github.com/nodejs/TSC/blob/master/surveys/promise-rejections/survey.md)
- [feedback request to foundation](https://github.com/openjs-foundation/user-feedback/issues/2)
- [doc: add unhandled promise rejection survey CLOSED PR](https://github.com/nodejs/TSC/pull/857)
- [process: Change default --unhandled-rejections=throw OPEN PR](https://github.com/nodejs/node/pull/33021)
- [Add a new `process.unhandledRejections` runtime flag OPEN PR](https://github.com/nodejs/node/issues/33577)

Below is what the foundation provided back to me. As we flesh out User Feedback Surveys at the foundation, the copy below will be abstracted into the [user feedback repo](https://github.com/openjs-foundation/user-feedback) as how the foundation can support requests like these. If anyone has any feedback on executing this survey or surveys in general, please let me know. I'm always wanting to make things better. And the more we have this formalized, the speedier they can be turned around. Thanks!

## Node.js TSC Survey: Unhandled Promises 
OpenJS Foundation Support Plan

### Objective
To provide the Node.js TSC insights and feedback via survey data for decisions pertaining to Unhandled Promises. 

### Foundation Support to include:
- Uploading survey questions into the survey tool (Survey Monkey)
- Promoting the survey via OpenJS Foundation Social Channels and collaborating with other applicable audiences and projects to promote. 
- Providing survey links for individual promotion of the survey to drive respondents
- Supplying data to the TSC
- Working with TSC to create content based on the survey and its results

### Additional Requirements
The Foundation would like to include an optional question requesting name and email. This is to provide survey results back to the respondent as well as collect contact information regarding people interested in the technical direction of Node.js. 

_Note: this copy currently reads as such_
>Please provide your name and email in order for us to deliver the results of this survey and if you'd like to be included in future communications regarding Node.js.

Personally, I think that copy should make it more clear that it is optional and I will work to get that updated to:
>Please optionally provide your name and email in order for us to deliver the results of this survey and if you'd like to be included in future communications regarding Node.js.

**Comment by devsnek** [comment]
all the code blocks are missing indentation and the one at the top is cut off:

![](https://gc.gy/64391534.png)

**Comment by RRomoff** [comment]
Thanks for this, @devsnek 
1. I've gone through and fixed formatting on the code blocks, however, the character limit is 4000, and it's cutting off the summary. I'm exploring adding screenshots to save character count, however, we can also use the first paragraph and link to an issue or blog post for additional context.
2. For question number 1. **Are you currently using Promises, async functions, a mix, or neither?**,  and 2.**How are you handling rejections today?** do we want to provide the option for more than one selection? I can change that to a check all that apply.
3. I've updated question 4 with the right copy.

**Comment by devsnek** [comment]
@RRomoff 

Thanks. For the header, the only thing i would say there is that screenshots would not be ideal for people who use screenreaders, unless it provides the option for alt text. For question one, I think check all that apply is the best.

**Comment by mmarchini** [comment]
@devsnek agreed. We're exploring turning the summary/header into a blog post we can link in the summary (alongside a shorter summary).

**Comment by mmarchini** [comment]
Found some formatting issues and inconsistencies with the [original proposed survey](https://github.com/nodejs/TSC/blob/master/surveys/promise-rejections/survey.md). @RRomoff let me know if you have any questions.

---

[Question 2](https://github.com/nodejs/TSC/blob/master/surveys/promise-rejections/survey.md#how-are-you-handling-rejections-today) is missing the summary after the title. Summary should be:

> When consuming Promises, async functions or thenables, which of the options below do you use to handle rejections?

SurveyMonkey:

![image](https://user-images.githubusercontent.com/4048656/89723800-cc669300-d9af-11ea-937d-ea3f40ddcff1.png)

Proposed question:

![image](https://user-images.githubusercontent.com/4048656/89723804-d4263780-d9af-11ea-8a2c-27ec5fe4df9c.png)

---

Options to question 3 are incorrect:

![image](https://user-images.githubusercontent.com/4048656/89723773-5d893a00-d9af-11ea-9c7e-0911ca0df0b5.png)

Should be:

  - [ ] I use `process.on('unhandledRejection')`
  - [ ] I don't use `process.on('unhandledRejection')`
  - [ ] I didn't know `process.on('unhandledRejection')` existed

See: https://github.com/nodejs/TSC/blob/master/surveys/promise-rejections/survey.md#do-you-know-that-nodejs-has-a-global-handler-for-unhandled-rejections-processonunhandledrejection-if-so-do-you-use-it

---

Question 5 in our proposed questions is missing: https://github.com/nodejs/TSC/blob/master/surveys/promise-rejections/survey.md#do-you-know-that-nodejs-has-a-global-handler-for-uncaught-exception-processonuncaughtexception-if-so-do-you-use-it

![image](https://user-images.githubusercontent.com/4048656/89723819-16e80f80-d9b0-11ea-9375-9f2c9b8c9407.png)

---

Question 7(`When a rejected promise doesn't have a catch handler, what is the behavior of your application today?`): 
* should be a radio button to select only one option
* Match formatting after the code block with formatting before the code block.

![image](https://user-images.githubusercontent.com/4048656/89723845-5b73ab00-d9b0-11ea-909d-71f4382c39c5.png)

---

Question 8:

Extra `a` after `databaseConnection.release` in one of the options

```diff
+  - [ ] I make sure (...) `databaseConnection.release`a throws(...)
-  - [ ] I make sure (...) `databaseConnection.release` throws(...)
```

---

Question 9: 

- `Consider the following modes:` missing
- Not sure if it's possible, but `Other (please elaborate)` is clearer for this question than `Other (please specify)` (as we expect users to describe the mode they want if they select Other).

**Comment by mmarchini** [comment]
The survey is available at: https://www.surveymonkey.com/r/FTJM7YD

We also wrote an accompanying blog post for extra context: https://medium.com/@nodejs/node-js-promise-reject-use-case-survey-98e3328340c9

The survey will run for at least two weeks, at which point we'll evaluate if the number of replies is enough for us to move forward, otherwise we might extend it for a week or two. Please fill out the survey as it will help us decide the future of unhandled promise rejections on Node.js!

**Comment by mmarchini** [comment]
Linking here for TSC visibility: https://github.com/nodejs/TSC/pull/857#issuecomment-675223537

**Comment by mmarchini** [comment]
we reached our target number of responses (with 5 days left! 🎉). The survey will continue until Monday as planned, once it closes we'll share the results.

**Comment by mmarchini** [comment]
Results are available at https://www.surveymonkey.com/results/SM-82X6PX3B7/, we'll be sharing the free-form results (Other field) as well soon too. I'll open a PR to add the results to this repo later.

**Comment by mhdawson** [comment]
@joesepi, @mmarchini I think this can be close now ?
