### ISSUE TITLE
Package manager manager ... discussion

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#904]
@nodejs/tsc ... Maël Nison (@arcanis) has been working on a new project tentatively called "pmm" (package manager manager) that implements an approach that can allow us to continue to support npm as well as including support for yarn and pnpm. Rather than butcher the details myself, I'd like to invite @acanis to provide some details here, and I'd like to invite @arcanis to a future TSC call (or special dedicated call) to demo the work that they've done thus far and start a conversation about it. It's compelling work that I strongly believe should be given a fair review.

**Comment by mhdawson** [comment]
Can you add the link to the repo for the project?

**Comment by jasnell** [comment]
Repo is here: https://github.com/arcanis/pmm

**Comment by jasnell** [comment]
Labeling this tsc-agenda to escalate it and ensure there's discussion.

**Comment by mmarchini** [comment]
Should we move pmm to the Node.js org as a next step?

**Comment by mhdawson** [comment]
@mmarchini I'm wondering if we need some level of consensus on the direction of bringing it into Node.js before asking for that.  Maybe the issue asking for it to be moved in would be the place for that discussion, but I'm not sure that is visible enough based on the number of people who have commented on past requests.

**Comment by ljharb** [comment]
This also seems like it would signal a pretty major direction decision made in the relative solitude of a TSC meeting, without inviting wider comment. I don't think any official encouragement or endorsement is necessary for exploration, and I think official encouragement or endorsement may be premature if the current stage is "exploration".

**Comment by jasnell** [comment]
@mhdawson ...actually, I think those are two different questions. `pmm` can exist as a separate project under Node.js without us actually bundling it with the distribution. We ought to be able to move forward with that discussion in parallel if @arcanis is willing. I can open an issue in nodejs/admin to start that process.

The separate (and more difficult question) about whether we'd want to bundle `pmm` with the Node.js distribution is going to take much more time to consider.

@ljharb:
> This also seems like it would signal a pretty major direction decision made in the relative solitude of a TSC meeting, without inviting wider comment.

I really don't get what you're saying here. No decisions have been made about anything.

**Comment by ljharb** [comment]
@jasnell glad to hear that :-) what i meant was, bringing it into the node org may signal that a decision *has* been made.

**Comment by mmarchini** [comment]
> `pmm` can exist as a separate project under Node.js without us actually bundling it with the distribution

That's why I suggested it, collaboration should be easier if the project is under the Node.js org, and that doesn't imply that `pmm` is going to be bundled (but if we decide to bundle, being under the org is a requirement IMO) :)

**Comment by arcanis** [comment]
I'm fine with whatever you decide regarding where this project should live, I'll be happy to keep maintaining it in both orgs.

> The separate (and more difficult question) about whether we'd want to bundle `pmm` with the Node.js distribution is going to take much more time to consider.

Something I wanted to ask - from my understanding, Node 15 is scheduled for October. I believe pmm is reaching a state where it would benefit from being evaluated in real-life conditions, and an odd release would sound the perfect fit for this. Do you think there is any chance we could schedule those discussions to happen before then, so that pmm could be part of Node 15?

Of note, since it would be an odd release, if it turns out this model doesn't work with the ecosystem after all, it would be perfectly fine to pull it out before the next even release.

**Comment by jasnell** [comment]
I don't think we should rush anything in to 15.0.0. This can be introduced as an experimental feature anytime during the 15.x lifetime. What I'd personally like to see is:

1. Moving the project into the nodejs github organization soon. 

2. Distributing pmm with the main distro as experimental sometime before 16.0.0 is out the door.

**Comment by arcanis** [comment]
I've made the changes we mentioned (about the offline workflow, and the `engines.pm` -> `packageManager` renaming). What would be the next step? There are a few things I plan to land this week, and after that it should be in a good state for a first review.

**Comment by arcanis** [comment]
I've opened a PR against Node to formally keep track of the changes that would be entailed: https://github.com/nodejs/node/pull/35398

**Comment by mhdawson** [comment]
@jasnell given the vote/decision on corepack can this be closed ?
