### ISSUE TITLE
Provide a point of contact for non-code security vulnerabilities

### ISSUE THREAD

**Issue by mcollina** [nodejs/TSC#912]
Currently our Node.js HackerOne program only covers vulnerabilities of Node.js core. In case there are security issues with other part of the project, including our infra, our website, and all the other assets we use, we do not have a clear reporting line.

@nodejs/build @nodejs/tsc what do you think? Should we expand the scope of our HackerOne program or provide some other form of communication? Expanding the HackerOne program might require a few folks from build to join.

One thing that would remain outside is npm, and it should clearly stated as such.

**Comment by MylesBorins** [comment]
Looking at the copy of https://nodejs.org/en/security/ it seems like we send all reports through that channel. There is language about eligibility, specifically `Only vulnerabilities in Node.js core will be considered for eligibility. Submissions related to nodejs.org and other project websites are explicitly NOT eligible.`, but my read on that is more related to Bug Bounties, not about the program itself.

Huge +1 on making this clearer in the copy on the security landing page + hackerone

**Comment by mmarchini** [comment]
Seems like a good idea to have a separate program since folks triaging Node.js core vulnerabilities are not the same as folks who can triage or act on infra vulnerabilities.

Does Hacker One have any features to forward a vulnerability to another program?

**Comment by MylesBorins** [comment]
@mmarchini my understanding in seeing things moved between the node.js core + node.js ecosystem program was that things definitely can be transferred. Are you imagining that every report would still come in from a single point of entry or that we would have distinct programs to manage all of them? I have to admit that I am a little concerned about n programs at n pages would make it much harder to manage, we already only have limited resources to keep up to date on this.

Maybe we could talk to hackerone about their initial triage and see if there is a way to streamline this. Might be good to do a call with them and talk about the problem space and get their suggestion on best solution with their platform?

**Comment by mmarchini** [comment]
Ah, first time I read @mcollina suggestion I thought the idea was to provide a different program, re-reading it I see I misread the first time :). I don't see a problem keeping infra-related issues under the same program we have today. I guess we can always split into two programs in the future if we deem necessary.

**Comment by mcollina** [comment]
I'm happy to have a single program. I propose to also include it in the bounty program.

Does anybody object?

**Comment by MylesBorins** [comment]
Our current bounty program is paid for by the IBB which has strict requirements for what qualifies for a bounty, and I think is scoped to core. I can follow up and find out what the limitations are. If the current program cannot cover things like the website we could ask cpc about a foundation provided bounty program.

**Comment by mcollina** [comment]
Then we need some better text for the page that esplicitly says that non-core vulns are not covered by the program.

**Comment by mhdawson** [comment]
@mcollina, @MylesBorins 

I think it's only the bounty can can't be covered and using a single program to report all types of security issues (which is probably easier for reporters is ok).

The only question I think is if this text is clear enough that only vulnerabilities in core are eligible for the bounty. It seems pretty clear to me.

> Only vulnerabilities in Node.js core will be considered for eligibility. Submissions related to nodejs.org and other project websites are explicitly NOT eligible.

**Comment by mcollina** [comment]
It's clear!

**Comment by mhdawson** [comment]
@mcollina I think we can close this issue then.  I'll do that, please let me know if that was not the right thing to do.
