### ISSUE TITLE
Developer's Certificate of Origin version

### ISSUE THREAD

**Issue by williamkapke** [nodejs/TSC#92]
Several Working Groups have a reference to `Developer's Certificate of Origin 1.0` however  https://github.com/nodejs/node/pull/5170 makes me think maybe these should be updated to v 1.1.

Since WGs are autonomous I guess they're not forced to use v1.1, but I bet many just don't know of the newer version- or that the older one is used in their documentation. I can do PRs for all of these, but before I do- I'm wondering if this is one of those rare things that the lawyers insist WGs adopt. If so, should these just have a URL pointing to a "Master" Developer's Certificate of Origin that applies to all things under the Node.js Foundation?

## Using DCO v1.1
https://github.com/nodejs/node/blob/master/CONTRIBUTING.md
https://github.com/nodejs/node-chakracore/blob/master/CONTRIBUTING.md
https://github.com/nodejs/docs/blob/master/CONTRIBUTING.md

## Using DCO v1.0
https://github.com/nodejs/Intl/blob/master/CONTRIBUTING-draft.md
https://github.com/nodejs/TSC/blob/master/Applications/Express.md
https://github.com/nodejs/TSC/blob/master/BasePolicies/Governance.md
https://github.com/nodejs/TSC/blob/master/Project-Lifecycle.md
https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md
https://github.com/nodejs/benchmarking/blob/master/CONTRIBUTING.md
https://github.com/nodejs/dev-policy/blob/master/README.md
https://github.com/nodejs/docker-iojs/blob/master/GOVERNANCE.md
https://github.com/nodejs/docker-node/blob/master/GOVERNANCE.md
https://github.com/nodejs/evangelism/blob/master/CONTRIBUTING.md
https://github.com/nodejs/hardware/blob/master/CONTRIBUTING.md
https://github.com/nodejs/iojs.org/blob/master/CONTRIBUTING.md
https://github.com/nodejs/nan/blob/master/README.md
https://github.com/nodejs/node-chakracore/blob/master/WORKING_GROUPS.md
https://github.com/nodejs/node/blob/master/WORKING_GROUPS.md
https://github.com/nodejs/nodejs-hu/blob/master/content/en/working-groups.md
https://github.com/nodejs/nodejs-uk/blob/master/CONTRIBUTING.md
https://github.com/nodejs/nodejs.org/blob/master/COLLABORATOR_GUIDE.md
https://github.com/nodejs/post-mortem/blob/master/CONTRIBUTING.md
https://github.com/nodejs/testing/blob/master/Governance.md
<del>https://github.com/nodejs/inclusivity-slack-inviter/blob/master/CONTRIBUTING.md</del>
<del>https://github.com/nodejs/inclusivity/blob/master/CONTRIBUTING.md</del>

### legacy repos...
https://github.com/nodejs/iojs.org/blob/master/content/en/working-groups.md
https://github.com/nodejs/iojs.org/blob/master/content/tr/working-groups.md
https://github.com/nodejs/node-convergence-archive/blob/master/CONTRIBUTING.md
https://github.com/nodejs/node-convergence-archive/blob/master/WORKING_GROUPS.md

**Comment by mikeal** [comment]
We should update across the board to 1.1

**Comment by mhdawson** [comment]
In the case of the benchmarking WG it's simply a case of did not know.  What's there was derived from what was in place when the WG formed.  The only questions I have are :

* if we change do we need to actively alert WG members  
* do we need to know what was contributed under one versus the other or is simply knowing the change over date/timestamps commits enough ?

**Comment by williamkapke** [comment]
> it's simply a case of did not know. What's there was derived from what was in place when the WG formed.

@mhdawson I'm certain that is the case for all of them and I think you raise some good questions. Hopefully the TSC give some guidance.

**Comment by williamkapke** [comment]
@mhdawson Did you get answers to your questions above from any @nodejs/tsc reps?
(Looking to help move https://github.com/nodejs/benchmarking/issues/46 forward)

**Comment by williamkapke** [comment]
Ok, so there is only 1 of these left in the entire org: https://github.com/nodejs/dev-policy/issues/78. @jasnell - you have 99% of the commits on that repo, are you the only person with access to the Merge button? Can I get you to merge it so I can close out this issue?

**Comment by Fishrock123** [comment]
@williamkapke merged

**Comment by williamkapke** [comment]
🎉  thanks @Fishrock123 !
