### ISSUE TITLE
ES Module interop named exports agenda item

### ISSUE THREAD

**Issue by guybedford** [nodejs/TSC#923]
Hi all, I'd like to post an item to the agenda for this week for the TSC to discuss the named exports PR at https://github.com/nodejs/node/pull/33416, which is the closest we've come to enabling named exports for CJS modules yet, based on an initial parse phase to detect exports before execution.

**If we are to be able to even consider shipping named exports to Node.js 12 we need to make a decision this week. Shipping in 15 only risks problematic backwards compatibility issues for published packages.**

I hope members of the TSC can take some time to lend their decisive thoughts towards this further to help us conclude this saga and if we want to:

A) Drop this entirely, and just keep `import cjs from 'cjs'`
B) Ship this feature for `__esModule` packages only (it works 99% comprehensively for Babel / TypeScript emitted code with __esModule interop, the 5% issues are mostly for custom entry point cases).
C) Ship this feature for all CommonJS modules.

I don't want to dig up the history on this problem too deeply other than to say that this type of fast source lexing approach to determine named exports is working very well and is the closest we have come to consensus - we almost have group consensus to land this feature but for the single block from @devsnek.

In discussion with Gus, we came to following compromises so far:

1. Restrict the detection to `__esModule` CommonJS modules (effectively transpiled modules). This is to ensure predictability of when the parse-based exports detection will apply and work soundly (since it is a lexer and not execution based there is always a chance it gets things wrong either over or under classifying exports).
2. In further discussion we determined that a criteria to land would be 95% of packages with __esModule statistically detecting all their named exports correctly.

A number of us have now done various analyses of the data. Just this evening I spent a few hours completing a new analysis against 4000 packages and got 158/4000 exporting __esModule and a 92% pass rate for exports detection of those __esModule cases in my recent testing. Methodology differences mean that these numbers have varied from 92% to 96% depending on the exact data (eg including binary builds or not).

It seems like @devsnek is still unconvinced to remove the block in discussion and is currently shifting the debate to these methodology questions hence I would like to invoke a TSC opinion at this point to consider overriding Gus's block. This is a decision that should be made for Node.js as a whole, and I think focusing too much on a single blocker risks distracting from the primary concerns at hand which are ecosystem compatibility for everyone in the Node.js ecosystem.

We have been trying to gain wider feedback through discussion on Twitter as well as publishing the binaries in the PR for further testing. I have also tested and used this exports detection approach on over a million packages on jspm and it has worked well there. One way to test this code is to test named exports support on jspm.dev! Although I do not include the __esModule restriction we added for Gus there as I find it more useful to extend it to more packages.

**Comment by devsnek** [comment]
You should've waited more than 12 hours cuz I was about to comment that I'm removing my block.

**Comment by GeoffreyBooth** [comment]
> You should've waited more than 12 hours cuz I was about to comment that I'm removing my block.

Thanks @devsnek. I think this is still worth the TSC discussing, because I still think this detection feature is very valuable and shouldn't be limited to transpiled packages. Or would you be willing to drop that restriction as well?

**Comment by devsnek** [comment]
I must've said this a good 10 times by now, but I don't care about the `__esModule` thing, or really any specifics of this feature. I care about it behaving consistently and us being able to communicate what that behaviour is.

**Comment by guybedford** [comment]
> You should've waited more than 12 hours cuz I was about to comment that I'm removing my block.

@devsnek this is still a little ambiguous - can you clarify if you are removing your block with this comment, or if you are still retaining your block, and if so the reasons?
