### ISSUE TITLE
Show all participants on zoom streaming in meetings

### ISSUE THREAD

**Issue by sxa** [nodejs/TSC#924]
At the moment the live streaming of the TSC calls only shows the participants who have video enabled and not the full list of TSC attendees, so when someone who does not have video enabled speaks, it's impossible for viewers to know who is speaking and making certain points (No green highlight around a name). If the zoom client can be modified to ensure that all participants are visible on the screen (as I've done in some of my own meetings) it would make it easier for the non-TSC members to follow the discussions.

![image](https://user-images.githubusercontent.com/6487691/93352139-6c76ce00-f832-11ea-85ad-30c1766bc868.png)

**Comment by mmarchini** [comment]
> as I've done in some of my own meetings

Can you share the steps? TSC is not the only one who would benefit from that, WGs would too

**Comment by sxa** [comment]
Ensuring that `Video Settings -> Hide Non-Video Participants` is NOT checked does it for me when using zoom locally (I haven't livestreamed to youtube with it so I don't know for sure if it makes a difference to that although I'd hope so!). You would probably also want to make sure "!Always display participant names on their video" is enabled

**Comment by mmarchini** [comment]
Thanks! I'll definitely try that out on the next Diag meeting :)
Do you know if we can save those settings? Having to remember on every meeting will definitely lead to it being forgotten sometimes.

@mhdawson can you try it on the TSC meeting as well?

**Comment by mhdawson** [comment]
I don't see any way to set it in the webinar, but can try to remember for the next TSC meeting

**Comment by mhdawson** [comment]
@sxa it was already enabled (ie show non-video participants) and I don't think it makes a difference in the recording as I think it was already the default behavior.

**Comment by mhdawson** [comment]
@sxa if you know how to fix this it would be great but otherwise not sure what we can do and this issue could be closed.

**Comment by mmarchini** [comment]
I suggest closing it after the next meeting and trying to test settings to see how much better we can get in the recording.

**Comment by mhdawson** [comment]
@mmarchini, sure I just need suggestions on what to set. I looked in the N-API team meeting but could not find something that looked like it would help.

**Comment by sxa** [comment]
> @sxa if you know how to fix this it would be great but otherwise not sure what we can do and this issue could be closed.

I don't have a paid zoom account (which I think is requred to livestream elsewhere) so it's not something I can investigate unfortunately.

**Comment by Trott** [comment]
I tried everything during the last TSC meeting and could not get the stream to show panelists who didn't have video turned on. I also went combing through Zoom docs. I literally think this is not possible currently, and our choices are to either ask everyone to turn on their cameras (even if they block their cameras so all we get is a black square) or live with the current situation.

**Comment by sxa** [comment]
That's a shame. I think it might be worth "recommending" but not mandating that people turn on camera (even if blocked) purely so that's easy to tell who's speaking. It might not be obvious to many people that it's not clear at present.

**Comment by mhdawson** [comment]
Going to close, please re-open/open a new issue if things change with zoom and we can improve
