### ISSUE TITLE
Code of conduct link out of date

### ISSUE THREAD

**Issue by sxa** [nodejs/TSC#925]
When raising a new issue at https://github.com/nodejs/TSC/issues/new the "Code of conduct" goes to the old location https://github.com/nodejs/TSC/blob/master/CODE_OF_CONDUCT.md and while it has a link to the new one it would make sense for it to point directly to the updates location at https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md

(I don't think that link is something I can PR into this repository - not sure where the links are stored)

**Comment by MylesBorins** [comment]
I think, but could be wrong, that the link you are referring to is generated by GitHub itself. You can for example see the exact same text at the bottom of this issue

> Remember, contributions to this repository should follow its code of conduct.

**Comment by mmarchini** [comment]
I don't think GitHub let's us point a link to a COC on a separate repository, but I might be wrong. Let me do some digging.

**Comment by mmarchini** [comment]
Considering [the API is GET-only](https://developer.github.com/v3/codes_of_conduct/) and [the documentation doesn't provide any guidance on custom location](https://docs.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project), I think it's unlikely we can point to the nodejs/admin COC through GitHub links. You can raise an issue to GitHub for cross-repository COCs, but that's not something we can fix.

**Comment by mmarchini** [comment]
At most we could have an Action that syncs this COC with the one in admin, but that's seems overkill.

**Comment by targos** [comment]
Can we use this?

https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

**Comment by mmarchini** [comment]
We can try, although I'm not sure if we can have both one in the repository and one in the org, and I think there's value having the one in the repository (I rarely notice the GitHub links, whereas I always notice a file named CODE_OF_CONDUCT in the repository)

**Comment by mhdawson** [comment]
There has been discussion in the context of the pkgjs org and we decided that it was important to have a file in the repo as otherwise if you do a checkout there is no way to find it from the local copy.

I'd suggest that what we have while not prefect is reasonable.  @sxa any objections to closing the issue?

**Comment by mhdawson** [comment]
Going to close as no response for a while. Please let me know if you think this is not the right thing to do.
