### ISSUE TITLE
Objection Override -> [#33879](https://github.com/nodejs/node/pull/33879)

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#928]
We discussed this in the TSC meeting this week.

Proposal is to override the objection after the PR having been updated to reflect this suggested compromise:

* Reduce the current time limits to 24 hours with two sign offs, at least one of which is from relevant CODEOWNERS team, or 72 hours with one sign off.

Along with a planned audit of the current members of the CODEOWNERS for each area.

@nodejs/tsc unless there are objections by Wed Sep 23rd, the assumption will be that TSC consensus on this as the direction has been reached.

**Comment by mmarchini** [comment]
If there are more than one codeowner for a PR, will one approval from each team be require, or only from one of the teams?

**Comment by MylesBorins** [comment]
I was under the impression it was one member from one of the teams, although I think this does beg the question of in what circumstance there will be more than one codeowner, and how those specific teams feel about it

**Comment by mmarchini** [comment]
A PR touching two subsystems would be one case where more than one team is pinged. Another question: the approval still has to be from a collaborator (since codeowners can be working group teams and not all members will be collaborators), right?

**Comment by mmarchini** [comment]
As for audit, how far do we want to go with the strictness of it? I think we could have an Action in this repository that runs periodically and dumps membership of all teams in the org into files, and opens a PR if anything changes. This way we get notified of any membership changes. It's not super robust since the Action would need to run periodically instead of on an event (there are no Actions for Org events yet), but better than nothing I guess? Or is this more than necessary, and just a sweep of teams every once in a while is enough?

**Comment by mmarchini** [comment]
Plus, should we aim for 100% codeownership on nodejs/node?

**Comment by mmarchini** [comment]
(I'm plus one on this proposal, just want to make sure we remove some ambiguity or unclarity from it)

**Comment by ljharb** [comment]
Linking to https://github.com/nodejs/node/pull/33879

**Comment by mhdawson** [comment]
Also related discussion in https://github.com/nodejs/TSC/issues/921

**Comment by mhdawson** [comment]
@mmarchini I was looking to see if we have consensus as the target we set for objections has passed.  I'm not sure if you think we should change the proposal to be put into https://github.com/nodejs/node/pull/33879 or if the details of the audit can be finalised agreed afterwards?

**Comment by mmarchini** [comment]
Audit can be done afterwards IMO

**Comment by mmarchini** [comment]
There were no objections, so I'll assume this is approved. I'll leave a comment in the PR and remove from the agenda.
