### ISSUE TITLE
Stream Summit

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/TSC#93]
During a discussion in https://github.com/nodejs/node/issues/6178#issuecomment-212434138 I proposed the idea of a `Stream Summit` as a way to expand and share the stream knowledge base. I would personally be up for taking on the responsibility of planning / organizing the event, although I will need some support from the streams working group to make sure that the agenda is aligned with what they view as useful. I would also need support from the Foundation and potentially a member of the TSC in order to handle the fun financial bits.

What would be the appropriate next steps to get the ball rolling?

/cc @mikeal @jasnell @rvagg @nodejs/streams

**Comment by jasnell** [comment]
Duplicate: https://github.com/nodejs/readable-stream/issues/203 ;-)

**Comment by TheAlphaNerd** [comment]
@jasnell is that the more appropriate place for this issue? If so please feel free to close this as a dupe

**Comment by jasnell** [comment]
I would think so. :-)

**Comment by mikeal** [comment]
We could do this alongside Node.js Interactive, we have some budget for Collaborator Summits and are talking about getting them going again for those events.

**Comment by jasnell** [comment]
+1
