### ISSUE TITLE
Avoid ping @nodejs/collaborator in weekly meeting

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/TSC#939]
I personally find it pretty annoying like this in https://github.com/nodejs/TSC/issues/938.

**Comment by Trott** [comment]
Those are from templates. I'm not sure which one is the right one, but if you want to stamp it out for sure, I think if you open a pull request to get rid of it [here](https://github.com/nodejs/create-node-meeting-artifacts/blob/2379ca0a1541a9d0a2279e53a2c606a2daa39bde/templates/meeting_base_michael), [here](https://github.com/nodejs/create-node-meeting-artifacts/blob/f0ad6b5c584208365c33688178642d04e8d5279e/templates/meeting_base_tsc), and [here](https://github.com/nodejs/make-node-meeting/blob/756ecd246f87eccad97d3681adbb42043d68ddbd/examples/tsc.sh), that should hopefully do it.
