### ISSUE TITLE
PSA: Linux Foundation Insights Dashboard (beta)

### ISSUE THREAD

**Issue by mmarchini** [nodejs/TSC#952]
The Linux Foundation is working on an [Insights Dashboard](http://lfx.dev/) for projects. It has insights from GitHub Activity, chat (for projects with it), issue trackers, CI/CD, security, etc. [Node.js Insights](https://insights.lfx.linuxfoundation.org/projects/ojsf%2Fojsf-nodejs/dashboard?filter=%23%2Fdashboard%2FGitHub-Issues%3Fembed%3Dtrue%26_g%3D(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:%27now-90d%27,to:%27now%27))&time=%7B%22from%22:%22now-90d%22,%22type%22:%22datemath%22,%22to%22:%22now%22%7D) are mostly git and GitHub statistics now (we can setup Jenkins statistics as well, and maybe chat statistics if we want to). Thought it would be interesting to share since sometimes questions about velocity come up, which we might be able to use the dashboard to answer.

**Comment by mhdawson** [comment]
@mmarchini I think we could probably close this now?
