### ISSUE TITLE
Update meeting times

### ISSUE THREAD

**Issue by ChALkeR** [nodejs/TSC#958]
About time we should do a regular update (actually, I should have opened this a while ago).

Looks like Wednesday is no longer present in the optimal set.

A combination of 14, 16, 21 UTC on Thursday looks good.

Raw data:
```
times: [ 38, 40, 45 ]
  participation: { avg: .701, min: .49, stdev: .1244, fair: .9696, n5: 18 }
  percentages: 94,89,89,80,79,79,79,79,64,64,64,64,63,63,58,58,58,58,49
  interaction: { avg: .491, min: .1458, stdev: .1462, fair: .714, n5: 87 }
  meetings: { probs: [ 1, .975, .999 ], avg: [ 14.19, 12.03, 14.04 ] }
```

Doesn't look like any other option is near that.
Unless the data in the spreadsheet gets updated :-).

---

For comparison, best two-slot option:
```
times: [ 38, 44 ]
  participation: { avg: .746, min: .48, stdev: .211, fair: .9763, n5: 12 }
  percentages: 95,95,95,95,95,95,94,94,87,87,72,72,48,48,48,48,48,48,48
  interaction: { avg: .549, min: .0189, stdev: .242, fair: .437, n5: 66 }
  meetings: { probs: [ 1, 1 ], avg: [ 14.19, 14.16 ] }
```
The negative side of a two-slot option is that there are some pairs of people who will almost never be present on a meeting together.
Also, brings some people from 58-63% to 48%.

**Comment by Trott** [comment]
I very much suspect some folks updated the Wednesday sheet and not the Thursday sheet....

**Comment by Trott** [comment]
Since we only have a few months before daylight savings messes with our meeting schedule again, I'm all for a speedy adoption of 14, 16, 21 UTC on Thursday. If this causes problems for people, they can fill out the spreadsheet and we can adjust based on the data. But I'd rather not have many weeks of conversation about this.

**Comment by mhdawson** [comment]
I'm +1 to moving to these, unless there are objections by the end of the next meeting.

**Comment by mhdawson** [comment]
Ok no objections. I'm going to leave this week at the previous time and change all future meetings to the new times.

**Comment by mcollina** [comment]
+1

**Comment by mhdawson** [comment]
Times updated, closing.
