### ISSUE TITLE
Update on Mentoring initiative and looking for interested teams

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#994]
The Mentoring team would like to do a quick update and brainstorm if there are teams that would be good candidates/interested in mentees.

**Comment by mhdawson** [comment]
@davidguttman

Upcoming meetings include: 

March 25 - 4 ET
April 1 - 9 ET
April 8 - 11 ET

which would be best for you?

**Comment by davidguttman** [comment]
> @davidguttman
> 
> Upcoming meetings include:
> 
> March 25 - 4 ET
> April 1 - 9 ET
> April 8 - 11 ET
> 
> which would be best for you?

3/25 at 4pm ET works for me.

**Comment by mhdawson** [comment]
Ok good, it will be on the agenda, I'll send you the info you need to join separately

**Comment by mhdawson** [comment]
Session held, closing
