### ISSUE TITLE
Election for CPC representative for 2021

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#996]
Based on the timing of the last election in: https://github.com/nodejs/TSC/issues/835

It’s time to elect the Cross-Project-Council voting representatives for next term which starts on April 1st 2021. The current one is @mmarchini.

See nodejs/admin#472 for more detail.

Timeline is:

March 18th Call for nominations for both CPC representatives (since that is now :))
March 25th Close nominations and open balloting for CPC representative
April 1st Close balloting and announce CPC representative
Please note the expectations of the voting CPC representative:
https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#voting-members

Also note: any member of the Node.js org can participate in the Cross Project Council as a regular member.
https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#regular-members
Similar to the practices in Node.js, the CPC follows the consensus seeking model and there is little difference between a voting rep of a project and a regular member. Becoming a regular member could be a good way to get involved if one is unsure of running for a voting member.

@nodejs/tsc please self-nominate in this issue if you are interested to run to be the Node.js TSC voting CPC representative.

**Comment by mmarchini** [comment]
I'd be happy to continue as representative, but also happy to step down if someone else is interested.

**Comment by mhdawson** [comment]
@nodejs/tsc fyi so every body is aware of the March 25th deadline for nominations.

**Comment by jasnell** [comment]
Very happy for @mmarchini to continue!

**Comment by mhdawson** [comment]
The deadline has passed and we only have 1 nominee.  In the past I think we did not require a formal vote in this case so @mmarchini congratulations and thank you for being our representative for the next year. Closing.

**Comment by mcollina** [comment]
Congrats @mmarchini !!!
